### ISSUE TITLE
[Feature Suggestion] CRUD Revisions

### ISSUE THREAD

**Issue by se1exin** [Laravel-Backpack/CRUD#100]
This is just a feature suggestion, but I have been thinking it would be handy (especially for non-tech-savy clients) if the CRUD system also (optionally) kept track of every historical change to a CRUD Model. This would allow someone to revert a change if they made a mistake.

Additionally, I imagine this would require quiet a bit of work, which I am offering to do myself (I need this on an upcoming project anyway), however I want to run it by the community before doing so in case there are other/better ideas out there or potential improvements on my proposed method below.

Heres what I'm thinking from a top level:
* Developer adds an additional migration for each target CRUD table, with the table name suffixed with a convention (e.g. `_revisions`). This table would be identical to the target CRUD table, but with an additional foreign key column (such as `parent_id`) that relates to the target table's Primary Key (more on this below)
* When a CRUD Model is saved, the contents are then also inserted into the corresponding `_revisions` table, with the `target_id` set to the original record's Primary Key in the target table
* Over time, for each single record in the target CRUD table, there will be many records in the corresponding `_revisions` table, hence providing history of the target record's changes
* At the bottom of the edit form for a CRUD instance, a each revision record for the current CRUD instance is listed as a datetime in descending chronological order, with a link to 'View' or 'Restore' the revision. It might also be a good idea to also provide a 'Delete' link for a revision.
* 'Viewing' the revision re-uses the CRUD form for the original Model, filling the fields with that revision's values, so that the user can see what the Model contained at the point in time
* 'Restoring' the revision writes the revision's values back to the original record in the target table - essentially reverting the CRUD instance to that point in time. This action would also be written to the `_revisions` table as a new revision as it is technically a new change to the Model at the current point in time.

I'll leave the explanation at that for now (there are a few edge cases to be considered), but I am keen to hear other people's opinions on the above.

[edit] A lot of the above could potentially be avoided by integrating https://github.com/VentureCraft/revisionable instead

**Comment by tabacitu** [comment]
Woooow. Yes, of course I'd like that, it would be great. I don't trust admins either - they mess up sometimes.

Looking at both your explanation and the link, I think using the package's new, trait-based approach, would benefit us. The package would help us with a lot of legwork. I especially like that it stores all revisions in a single table, no matter the model, so making one ore more models revisionable is easier - even as an update. But using it does imply some changes to the interface and how a user can use the revisions, since it stores each change column's change on a different row. But I don't think that is bad, we can achieve something very useful and pretty with it. For example, instead of showing the revision history in the EDIT form, we can show it as a separate page and give the user the option to "restore that attribute" with a click.

Let me explain how I see it, hope I use the right words to be understood:
- developer wants revisions for a Model;
- developer implements the Revisionable trait on the model;
- developer calls in his CrudController something like ```$this->crud->allowAccess('revisions');```;
- we have a new button that is loaded into the list view all the time, something like:
```php
@if ($crud->hasAccess('revisions'))
	<a href="{{ url($crud->route.'/'.$entry->getKey().'/revisions') }}" class="btn btn-xs btn-default"><i class="fa fa-clone"></i> {{ trans('backpack::crud.revisions') or 'Revisions' }}</a>
@endif
```
- we have a new route (```entity/{id}/revisions```), which shows that row's revisions on a timeline. We can use the AdminLTE timeline and it will look pretty:
![screen shot 2016-09-08 at 13 18 51](https://cloud.githubusercontent.com/assets/1032474/18346021/e267b64e-75c6-11e6-9486-43be7c5701da.png)
- this implies a new view (revisions.php) and a new method: CrudController::revisions();

Extra thoughts about this implementation, if you like it:
- maybe the buttons should work with AJAX so the user can go through multiple values and restore them without page refresh?
- I don't know it showing a "delete revision" button is a good idea - users might do that and lose all revision benefits...

What do you think? It sounds to me like we're getting somewhere :-)

**Comment by se1exin** [comment]
That sounds awesome, I really like your proposed method - especially having a seperate revisions page and using the AdminLTE timeline, and I agree that using the revisionable package would save a lot of legwork.

It's currently Friday morning where I am, so realistically I won't be able to get a good run on this until next week, but I'll get started today on a new branch in my fork and keep you updated on how it's going? If theres an different way you'd rather me go about implementation just let me know.

**Comment by tabacitu** [comment]
Of course, I understand, it's Friday here too.

Fork and Pull Request is perfect! Let me know how I can help.

Cheers!

**Comment by tabacitu** [comment]
PS. Let's leave this issue open until the final merge, so we have the entire conversation and specs easy for orhers to see.

**Comment by se1exin** [comment]
@tabacitu - I'm about to start on the functionality to actually revert specific revisions, and really like your suggestion of doing so with AJAX, but just want to run it by you before jumping into it.

In an effort to match code style and implementation technique I've had a bit of probe around the codebase for both CRUD and base but can't find any other AJAX related model manipulation. Is there a specific method you had in mind, or you happy for me to just go ahead and do it my own way?

**Comment by tabacitu** [comment]
Hi @se1exin ,

Thank you for asking that. [CrudController::search()](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php#L266-L302) and [CrudController::destroy()](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php#L189-L194) are ajax methods, you can take a look at them - but I can't say they follow a certain pattern, so I guess any way you find fit will do. I usually return a JSON but I now see destroy() does not...

What I think is important (because it would be a breaking change afterwards) is the naming of the routes and methods. I propose something like:
- GET post/1/revisions -> lists the revisions
- POST post/1/revisions/25/restore -> restores that revision
- DELETE post/1/revisions/25 -> deletes that revision

And for the CrudController I would use a trait (something like ViewsAndRestoresRevisions), with the following methods:
- listRevisions()
- restoreRevision()
- destroyRevision()

---

Another thing that popped into my head is the possibility of [using soft deletes](https://laravel.com/docs/5.3/eloquent#soft-deleting) on the revisions table. That way, we can allow the Admin to delete revisions... but the developer will be able to see it directly in the DB. What do you think about this?

**Comment by tabacitu** [comment]
PS. Of course, the names above are open for debate. If you find better ones, so be it.

**Comment by se1exin** [comment]
Thanks @tabacitu, I'll stick to your route names as they are now documented here (as well as the readme when I update it).

As for soft deletes on the revisions table, I know was the one that suggested deleting revisions, but after thinking about it more I'm inclined to not implement revision deletion at all for the following reasons:
* The primary reason for enabling revisions is to empower users to undo their mistakes. It seems really contradictory to then enable them to destroy the data that empowers them (thoughts?).
* If the main concern is simply cleaning up extra data, the upstream package [provides `$historyLimit` and `$historyCleanup`](https://github.com/VentureCraft/revisionable#implementation-notes) for exactly this.

Now the first point is obviously just my opinion and that shouldn't be the sole reason for a feature not being implemented, but I think for now I'm going to put it in the nice-to-have/future bucket. I'm keen to hear your opinion though.

**Comment by tabacitu** [comment]
Hi @se1exin , 

Ok. Totally agree with you - no deleting revisions, it defeats the purpose. 

Cheers!

**Comment by tabacitu** [comment]
Added starting with ```Backpack\CRUD v3.1.13```. Its [documentation is here](https://laravel-backpack.readme.io/v3.0/docs/crud#revisions).

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
