### ISSUE TITLE
Relationship not saving

### ISSUE THREAD

**Issue by kev-ian** [Laravel-Backpack/CRUD#104]
Hi,

I have two model, Article and Image. An article can have many images. I am storing only the url of the images. For some reason, the image url and article_id is not being recorded in the images table. here's my code

Article model
`public function images()
    {
        return $this->hasMany('App\Models\Image');
    }`

Image model : 
`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    public $fillable = [
        'name',
        'article_id',
    ];
    
    public function article()
    {
        return $this->belongsTo('App\Models\Article');
    }    
}`

In the controller, i'm using the code below to add a text field to capture the image url
`
$this->crud->addField([
            'name' => 'images',
            'label' => 'Image',
            'type' => 'text',
            'entity'    => 'images',
            'attribute' => 'name',
            'model'     => 'App\Models\Image',
        ], 'update/create/both');
`

The article is being saved, but not the record for the image.

What's wrong?

**Comment by kev-ian** [comment]
Anybody experienced this problem before? :)

**Comment by tabacitu** [comment]
Hi @kev-ian,

The CRUD only stores the information for one Eloquent model. If you want to do something else too (add images from the same form), you can use ArticleCrudController::updateCrud() to do some extra processign before the "return" (save any image files in the db / store on disk);

The relationship fields (select, select2, select2_multiple, select_multiple) are there to help the hser define relationships between existing entries.

Hope I've explained it clearly... Please let me know if I haven't.

Cheers!

**Comment by kev-ian** [comment]
Thanks @tabacitu .. I thought it handles the saving automatically. Do you have any quick example of what I'm try to achieve? I'm kind of new to laravel. 

Now regarding many to many, I believe I have to proceed in the same manner, right?

**Comment by tabacitu** [comment]
It does handle the saving automatically, but only for the main Eloquent model. 

Sure, see:
- [Eloquent documentation](https://laravel.com/docs/5.3/eloquent#inserts)
- how to [save eloquent relationships](https://laravel.com/docs/5.3/eloquent-relationships#the-save-method)
- how the [CrudController you're extending](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php) looks

So if in your ArticleCrudController you have an input called "image", you'll need to do something like this in your ArticleCrudController:
```php
	public function store(StoreRequest $request)
	{
        $response = parent::storeCrud();

        $image = new \App\Models\Image;
        $image->name = $request->image;
        $image->save();

        return $response;
	}
```
you'll also need to think what happens on the "edit" screen - do you rename the existing Image or do you delete it and add another one? That needs to be done in the ArticleCrudController::update() method, instead of:
```php
public function update(UpdateRequest $request)
	{
		return parent::updateCrud();
	}
```

Hope it helps. Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by kev-ian** [comment]
Thanks for the help ! :)
