### ISSUE TITLE
Attributtes on field is missing

### ISSUE THREAD

**Issue by seedgabo** [Laravel-Backpack/CRUD#105]
When a field has a name with  "snake_case" , the attributes  in the array are ignored 

 `$this->crud->addField(['name' => 'fecha_ingreso','label'=>'Fecha de Ingreso A la Empresa','attributes' => ['required' => 'required']]);` 

the attribute required is not loading because the name is fecha_ingreso.

 Sorry for the bad english

**Comment by tabacitu** [comment]
Hi @seedgabo ,

That's very weird. I just tried on the latest version and it worked for me. 

1) Could you please tell me the Backpack\Base and Backpack\CRUD versions you are using? You can find that out by looking at the last version in the changelog in ```vendor/backpack/crud/CHANGELOG.md``` and ```vendor/backpack/base/CHANGELOG.md```.

2) Does it work with the input type specified?
```php
$this->crud->addField([ // Text
    'name' => 'fecha_ingreso',
    'label' => "Fecha de Ingreso A la Empresa",
    'type' => 'text,
    'attributes' => ['required' => 'required']
]);
```

3) If the field is show in the form, but not stored in the database, it might be because ```fecha_ingreso``` isn't in the ```$fillable``` array on the model. Was this it?

Cheers!

**Comment by seedgabo** [comment]
fixed on update, maybe its a bug from previous version
