### ISSUE TITLE
dev-upgrade issues?

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/CRUD#1059]
Hi,
im trying to get hold of crud 3.3 but it wont let me install it as im also using dev-upgrade branch of base. ideally base 0.8 should go along with crud 3.3? 

can anyone suggest how do i get all the latest versions so i dont have to go thru updating breaking changes later?

or any eta on official release so i can see if its possible to wait for it to be released?

**Comment by lloy0076** [comment]
This one's best answered by @tabacitu.

**Comment by tabacitu** [comment]
Hi @mpixelz ,

You can require ```dev-upgrade``` in your composer.json file, for both Base and CRUD. That will do it. It's a good idea for new projects, but not for upgrading old ones, as the "upgrade guide" is not yet written. 

The plan is to have this major release ready by the end of the month, so that's when it will be officially released, along with the upgrade guide.

Cheers!
