### ISSUE TITLE
Bug on enum field

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#1069]
Hello, there's a bug when i create a migration like this:

```
$table->enum('status', ['In attesa', 'Aperto', 'Chiuso'])->default('In attesa');
```

and in my CRUD controller there's
```
$this->crud->addField([
    'name' => 'status',
    'label' => 'Stato del ticket:*',
    'type' => 'enum'
], 'both');
```
On my DOM I see something like this that seems fine.
![](https://i.gyazo.com/1a1745bf0393832e44d5b4f56eacab53.png)

But when I save, it seems that the indexes are broken (they should be +1), example:

If I save selecting "In attesa", then it saves "In attesa" (correct behaviour).
If I save selecting "Aperto", then it saves "In attesa" (wrong behaviour).
If I save selecting "Chiuso", then it saves "Aperto" (wrong behaviour).

**Comment by tabacitu** [comment]
Hi @EmanueleCoppola ,

It's very weird how your HTML looks. As far as I know, the "value" should be exactly like in the DB, not 0, 1, 2. I've just tested it and that's how it works for me:
<img width="857" alt="screen shot 2017-10-25 at 17 11 31" src="https://user-images.githubusercontent.com/1032474/32003414-9bcb98e2-b9a7-11e7-8801-b25d738a717d.png">

What version of MySQL & PHP are you on? What version of Backpack\CRUD?

**Comment by EmanueleCoppola** [comment]
My PHP version is 7.1.5 and my MySQL 5.6.34-log - MySQL Community Server (GPL). And my backpack version is "backpack/crud": "^3.2".

**Comment by lloy0076** [comment]
@tabacitu Have you considered that the values in the DB are __actually__ `0, 1, 2` etc?

My guess is `getPossibleEnumValues` is returning something weird:

https://github.com/Laravel-Backpack/CRUD/blob/0250f8dd23a4572c2cffa19e209e009b8c903943/src/CrudTrait.php#L17

**Comment by tabacitu** [comment]
@lloy0076 well from his migration I see they're not 0, 1, 2:
```
$table->enum('status', ['In attesa', 'Aperto', 'Chiuso'])->default('In attesa');
```

Which is what makes it weird :-)

@EmanueleCoppola I'm afraid I'm out of ideas here. Have you been able to debug this by now? I guess there's nothing else to do but to go through the enum blade file, up the functions, until you discover why it outputs 0 1 2 instead of the actual values... Sorry I can't be of more help...

Feel free to reopen this if you think it's Backpack issue - just tested it again and ENUMs work fine for me...
