### ISSUE TITLE
Updating policy

### ISSUE THREAD

**Issue by dennisc1** [Laravel-Backpack/CRUD#107]
With the current composer settings, if you want to update this package to 3.1.* it is required to have Laravel 5.3.* installed
This is because this package requires Backpack/Base 0.7 
`"backpack/base": "^0.7.0",`
which in turn requires Laravel 5.3
`"laravel/framework": "5.3.*",`

Is this intentional? Because this results not being able to get newest updates on Backpack\CRUD without upgrading to Laravel 5.3. I think it would be good to keep supporting Laravel 5.2 as well.

**Comment by tabacitu** [comment]
Hi @dennisc1,

Thanks for the detailed explanation. 

Yes, it was intentional. There are a few major changes in Laravel 5.3 that we needed to implement in Backpack to support it:
1) array_first has a different parameter order
2) authentication uses different controllers
3) authentication uses different logout method (post instead of get)
4) password reset functionality requires a change in the User model in Laravel 5.3

These are the big ones. We can fix #1-3 by checking in the code for the laravel version and #4 with a documentation notice, but I'm not sure it's a good idea... As a result, the package will contain both code for 5.3 and code for 5.2 with if/else/switch statements. Entire controllers that go unused. It won't look that bad now, but what about when 5.4 comes along? 

I'm not very firm against supporting it, but I'm wondering if there isn't a better way to achieve this, that I don't know about. I've seen other projects have the old laravel version on a different branch, but they rarely do any updates on them. And new features don't get pushed there. So it's the same - update laravel or be forced to stick with that version for ever. It's annoyed me in the past, but I have come to understand them now: supporting the old version seems to require:
- the developer to make some architecture and code standard compromises;
- the maintainer to answer questions and fix bugs for both versions;
That's more work than it looks. So I now understand why most open-source developers have said "_duck it, we only support 5.3 now_" - it passes the blame from the developer to the user ("_you spend 1-2h to update your applications instead of me spending countless hours providing support for the old version_"). I can't say I'm a big fan of that logic, but it _does_ make sense to me now. And it somehow made it ok for me to do the same, this time.

Sorry for the long reply - as you can see I'm not quite happy with the issue (dropping 5.2 support), but neither am I happy with the solution (if 5.2 do that; else...).

Do you (or anybody else) have a better solution to this? Or a strong opinion to guide me one way or another?

Thanks, cheers!

**Comment by dennisc1** [comment]
No, thanks for the long reply. It's clear, and I get your point. 
However, I do not have any experience or knowledge to think of a better solution. So this indeed seems like the best way to go.

Any other opinions?

**Comment by tabacitu** [comment]
It seems to me like there's no solution to this right now. Maybe we'll be able to do this in a few months, if the community grows and there will be more manpower available.

Until then, I'll close this issue. Feel free to reply here if you have anything to say.

Cheers!

**Comment by dennisc1** [comment]
@tabacitu I'm preparing a separate branch for laravel 5.2. This way people who still use L5.2 can use al the great new field types that have been added recently. Do you agree on making a separate branch for 5.2? I agree with your comment that a separate branch will probably be updated a lot less compared to the master branch. However, any small update will still benefit the users I think?

So I prepared a pull-request, but I don't know what the best way would be to submit it. As far as I know I cannot make a pull request to a non-existing branch. If you agree with making a L5.2 branch, maybe you should make one so I could push the update?
Besides making a branch, it would be great if the tag `3.0.19` could be added as well. I'm not sure if this is possible. But if it is, all L5.2 users with update policy `3.0.*` could benefit from it

**Comment by tabacitu** [comment]
Hi @dennisc1 , sorry to be late to reply. Sounds great! 

I've just created a "laravel-5.2" branch. Feel free to submit a PR when ready. 

But we really _really_ need to make sure we don't introduce any breaking changes - keeping the ```3.0.*``` tag means when users run ```composer update``` on Laravel 5.2, that's what they'll get. I think. Hey might need to specify ```backpack\crud: 3.0.*@laravel-5.2``` in their composer.json. But I guess we'll figure that out together :-)

@Ghitu , @cristiantone - you guys still have projects on Laravel 5.2 and would also benefit from this. When @dennisc1 submits the PR could you please find time to test if no breaking changes are introduced in your projects?

**Comment by dennisc1** [comment]
@tabacitu sounds like a good plan.
I've been busy past week. But the coming week I'll find some time to make a PR.
