### ISSUE TITLE
revisions access

### ISSUE THREAD

**Issue by rzaglinskij** [Laravel-Backpack/CRUD#1080]
while I am not logined to the admin panel, when I opened this URL
https://iwaspoisoned.local/admin/complaints/76597/revisions
I have access to the view.
how can I prevent this ?

**Comment by lloy0076** [comment]
This may be better asked on [Stack Overflow](https://stackoverflow.com/search?q=laravel+backpack),

That said, put that in a route protected by any relevant guard, see [Protecting Routes](https://laravel.com/docs/5.5/authentication#protecting-routes).

**Comment by tabacitu** [comment]
Hi @rzaglinskij - I just tested the revisions again and it doesn't seem like it's a general problem, but specific to your project.

Check out my video here - https://cl.ly/1O3D271U223i

The revision routes are created by ```CRUD::resource();```, so they're behind the same middleware as the rest of your admin panel. Please make sure they're behind a secure middleware, like ```admin``` otherwise anybody will have access to modify your entries.

Hope it helps. Cheers!
