### ISSUE TITLE
Menu Ordering: can't move parent menus

### ISSUE THREAD

**Issue by scottgrayson** [Laravel-Backpack/CRUD#1085]
the hierarchy of my menu items goes

- navbar (no parent)
  - navbar children
  - `availabilities` (parent: navbar)  *trying to move this one
     - has children *and these
  - more navbar children

I can move all of the `navbar` children except for `availabilities` and children of `availabilities`

![image](https://user-images.githubusercontent.com/7796074/32137004-09d05ca2-bbe6-11e7-93a8-21f06f491af9.png)

**Comment by scottgrayson** [comment]
http://recordit.co/RarLknM2tc

**Comment by scottgrayson** [comment]
https://github.com/Laravel-Backpack/MenuCRUD/issues/38

I realized i should have put this issue here. closing

**Comment by scottgrayson** [comment]
reopening this because i realized the frontend for ordering is on this repo

**Comment by tabacitu** [comment]
Hi @scottgrayson - huh, I guess the pale red area isn't a very informative error... who would have thought? :-))

I bet your problem is that you only have one level of hierarchy activated in your MenuCRUD. In the [reorder docs](https://laravel-backpack.readme.io/docs/advanced-features#section-reordering-and-nesting-items) it specifies the code to enable the reordering of an entity:
```
$this->crud->enableReorder('label_name', MAX_TREE_LEVEL);
$this->crud->allowAccess('reorder');
```

You see, that MAX_TREE_LEVEL parameter lets CRUD know how many levels deep you would like to let your users nest items. I bet yours is set at ```1```, and that would be the normal behaviour, what I see in your video - letting the user nest 1 level deep, but no deeper. If you set it at ```0``` then it will be infinite. If you set it at ```2``` it will let him go 3 levels deep. Etc.

Was this it? Does changing that second parameter fix it for you?

Cheers!

**Comment by tabacitu** [comment]
PS. Closing this as I\m pretty sure this will do it for you. Please reopen it if it doesn't.
