### ISSUE TITLE
Problem with NewsCRUD

### ISSUE THREAD

**Issue by binhduck1990** [Laravel-Backpack/CRUD#1090]
I have an issue with "Tag". 

When I add a new Tag with Name and Slug, it's ok.  For example: Name Tag: One piece and
Slug: One piece. 

I edit the Slug become to anything but nothing happen, the tag Slug still is Onepiece.

Finally I change the name Tag and don't fill the Slug but nothing happen to the slug

**Comment by tabacitu** [comment]
Hi @binhduck1990 ,

This is intentional. It is **not recommended to change the slug after the insert**, IMHO. Slugs are used as URLs, so once they're public they're indexed by search engines and used as links on forums, social networks, etc. If you automatically change the slugs by changing the title, all those links break. You'll get 404s and be downgraded by search engines. And for what? Most of the time nobody even notices the slug, except for the admin.

Tricky stuff this slug thing. But if you want to change the behaviour, you can of course change all that in the Tag model.

Hope it clears thing up.
Cheers!
