### ISSUE TITLE
[Question] Block access to other entries than those assigned to us

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#1124]
Hello,

Before using for the first time backpack for a client (and buying my first license, hura!), I try to set up a security system. For the moment, I am stuck.

I have items that I add with the administration interface. By saving the item, it fills the "user_id" column with the ID of the user who is doing the manipulation.

Thanks to the command `$this->crud->addClause('where', 'user_id', '==', Auth::id())` users only see their items.

But I noticed that by changing the ID in the URL, they can access other users' items. I tried several techniques to prevent this, but I never did. 

I tried to use `$this->crud->allowAccess(['edit']);` but it does not work.

In setup() :
```
if ( Auth::id() != $item->user_id){
          $this->crud->allowAccess(['edit'])
        }
```
But it does not work and I feel that it will never work because I do it wrong. Already, I can not access the data of an item precisely (because here, it does not find user_id which is a given item). I tried to give several value to $item but each time, I collect a collection.

I'm really lost! Please, help me or make me understand!

**Comment by lloy0076** [comment]
You've run into the perennial permissions problem; the solution is multi-pronged and it depends on how paranoid (and/or thorough) you want to be; at a minimum you'd want to:

* add a global "something" appropriate for whoever is logged in
* intercept the calls to **store** and **update** and **destroy** (delete?) methods in the CRUD controller(s) to make sure people cannot do unexpected stores, updates or deletes

You could also add:

* extra decision making code in the authentication guard (probably the "admin" guard but it can be any guard or middleware auth)
* Eloquent observers that double check what the controllers, and/or anything else can do

For something "global" I tend to add a pile of `where` clauses in the `setup` but these fairly much only stop people who aren't trying to break the system from breaking the system. You might be able to achieve the same thing using global (or non-global) scopes but be aware that to not apply a global scope in Backpack involves reaching through to the underlying model itself; not difficult but a pain.

Also be aware that Backpack does use `sync` when handling relationships so that can -- actually it does -- avoid model observers. There is a PR or a suggestion to make it easier to handle permissions here but I'm not sure of its status (actually it's stalled but that's because the suggester hasn't pushed the matter).

**Comment by OliverZiegler** [comment]
What you describe sounds like laravels [global scopes](https://laravel.com/docs/5.5/eloquent#global-scopes). Please have a look at them.

**Comment by tabacitu** [comment]
I personally prefer to use [Eloquent observers](https://laravel.com/docs/5.5/eloquent#events), one for each entity I need to protect (since it uses typecasting in the methods). That way, you can easily test if the user has permission upon ```updating``` and ```deleting``` events. If he doesn't, you can ```abort(403)```. If he does, no harm no foul. This basically adds a single layer, when the entry tries to get saved or deleted by Eloquent. Just like validation, I like to do it only one, where it actually counts, at the last possible layer.

This DOES leave a window for a malicious user to see the edit page of an entry he isn't supposed to, but that can easily be solved in the controller:

```php
public function edit($id)
{
   if ( Auth::id() != $this->crud->entry->user_id) {
          abort(403);
   }

   return parent::edit($id);
}
```

This way, all holes are covered, in my opinion:
- user can't edit the URL of an edit page and see a forbidden item;
- user can't edit the id in the HTML form to overwrite a forbidden item;
- user can't even edit/delete an item from the front-end, if you have forms there (the benefit of doing things in the Model as opposed to Controller);

Hope it helps.
Cheers!

**Comment by lloy0076** [comment]
If one has a relationship based field, the Backpack code uses `sync` which fairly much *ignores* Eloquent observers.

See [create uses sync](https://github.com/Laravel-Backpack/CRUD/blob/54fb667a1cf64f4c53f8a90a3752d1f964fdec6f/src/PanelTraits/Create.php#L95) and [update users sync](https://github.com/Laravel-Backpack/CRUD/blob/78197595e1d8a00352e839bc0667b5af662606e3/src/PanelTraits/Update.php#L28).

**Comment by tabacitu** [comment]
Hmmm... what do you mean @lloy0076 ? As far as I know, ```sync``` doesn't trigger the observers on the connected entry (child), but it _does_ trigger observers on the main entry (parent). Does it not?

**Comment by lloy0076** [comment]
Sync doesn't trigger observers at all, parent or otherwise:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php

There's no `fireModelEvent()` - which is the method used by the Laravel framework to fire model events.

Personally I think there **should** be but I'm not a maintainer for the upstream Laravel framework :)

**Comment by Athuli7** [comment]
I'm not sure if this is the right way to do it, but this is what I do. It is specific to my use case. So do consider this a very incomplete representation.

```
<?php

namespace App\Http\Middleware;

use Closure;
use Auth;
use App\Models\Judgment;
use App\Models\Notification;

class publishedCaseFaliure
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if(ends_with($request->url(),'/edit')){
            if( !Auth::user()->hasEditRights( $request->route()->parameters['judgment'] ) ){
                Notification::newEntry(Auth::user()->name . ' trying to edit non-editable case ' . Judgment::find($request->route()->parameters['judgment'])->getICONumber());
                \Alert::error('No edit rights !')->flash();
                return redirect('admin/judgment?iconumber=' . $request->route()->parameters['judgment']);
            }
        }
        return $next($request);
    }
}
```

I use middlewares. At the moment, it works by defining a middleware for every model. The middleware is applied on the crud routing entry and executes on the edit call. It does the calculation and redirects back to the list page if the validations fail with an Alert.

![screen shot 2018-06-30 at 08 33 27 am](https://user-images.githubusercontent.com/4718029/42120880-b3baa91e-7c40-11e8-8511-b49a214f6b66.png)

@tabacitu, Would you be open to extending the CrudController to having a overidable permission check function that could be used to do this in a much more cleaner manner ?

Notes:-
abort(403); is not a great idea, especially if you have something like Sentry running. It was meant to a stop unauthorised requests not for user regulation.
Notifications is a queue of sorts to dump these mishaps to Telegram.
My validation rules are entered in the User model. And there it is specific to the entity's (Judgment) current status.
Visibility of edit button was a waste of time as validation on each line make everthing slower. Some ajax based implementation could work, but its not needed in most cases.

**Comment by Athuli7** [comment]
Oh, I do use the assigned concept in conjuction with this, but it is under the assumption that, If the user clicks on the assignments link, the list of cases shown are the ones that are accessible. And as far as my site is concerned, there is no need for hiding other records.

**Comment by tabacitu** [comment]
@Athuli7 I think it's an inventive way to do it, yes. And if it works, it works :-)

I personally would probably do it in the model's boot() method, with [Eloquent Events](https://laravel.com/docs/5.6/eloquent#observers). Would not only solve the problem for Backpack interfaces, but anywhere else inside the app.
