### ISSUE TITLE
select 2 css and js are included multiple times when different select2 field types are used.

### ISSUE THREAD

**Issue by kevinab** [Laravel-Backpack/CRUD#1148]
# Bug report

### What I did:
Added a multiple select2 fields, a select2_multiple field, a select2_from_ajax field and the css and js files get added multiple times.

### What I expected to happen:
Those assets should only load once

### What happened:
Assets were loaded 3 times.

### What I've already tried to fix it:
In the 3 field blade templates.  I switched to

```
     $first_field = array_first($fields, function ($value, $key) {
        return substr($value['type'], 0, 7) === 'select2';
    });


{{--@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))--}}
@if ($field['name'] == $first_field['name'])
    Then include the assets
@endif 
@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))
    Then do the jquery stuff.

### Backpack, Laravel, PHP, DB version:
latest version of backpack and laravel 5.5.

**Comment by lloy0076** [comment]
Does this break anything?

**Comment by tabacitu** [comment]
Hi @kevinab - I'm afraid this is a know issue with Backpack. It's pretty harmless as it is, since all browsers will not even make a new HTTP request for the same file twice, they'll just pull it from cache. So it shouldn't affect pageload at all. Nor should it affect your JS/CSS functionality.

It is, however, messing with my OCD :-) And I'm not the only one. So this is something we're working on fixing right now, but it involves a much more general solution. A solution to  enqueue JS and CSS assets, so that they're not loaded twice, and get updated easily. Not only for select2 fields, but for all CSS and JS across the admin panel. Other fields, column, functionality, etc. We'll probably end up using webpack and mix. So we're thinking about a solution, but we're far from adopting something in the near future, I'm afraid.

Will keep you posted. But do know this shouldn't affect performance.

Cheers!
