### ISSUE TITLE
Autodiscover - CRUD Alias Missing?

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/CRUD#1152]
# Bug report

### What I did:

Looked into [Permission Manager's Issue 134](https://github.com/Laravel-Backpack/PermissionManager/issues/134).

### What I expected to happen:

CRUD to work in the resources file.

### What happened:

It didn't work?

### Backpack, Laravel, PHP, DB version:

Latest.

**Comment by lloy0076** [comment]
```
"extra": {
    "laravel": {
        "providers": [
            "Barryvdh\\Debugbar\\ServiceProvider"
        ],
        "aliases": {
            "Debugbar": "Barryvdh\\Debugbar\\Facade"
        }
    }
},
```

It only has a link to the service provider - we may need the alias as well.

File:

https://github.com/Laravel-Backpack/CRUD/blob/master/composer.json

**Comment by tabacitu** [comment]
Hmm... not sure that's needed, since we do register the alias manually in CrudServiceProvider:87 - https://github.com/Laravel-Backpack/CRUD/blob/master/src/CrudServiceProvider.php#L87

Different way, same result I think. The only difference is that this old way also works on Laravel 5.4... But since we've dropped support for L5.4 in the latest version I guess we could do that, yes.
