### ISSUE TITLE
Dimsav Translatable compatibility

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#1157]
# New feature

My need is using Dimsav Translatable package with backpack, i saw that this is compatible with spatie, so i made a new fork and branch of this project to implement this.
My fork is taken from master about 2 days ago.
I finished my work and it is working fine (for the test i made).

I added also two new features that can be added also for spatie package.
Sort by translated field and search into translated field.
This is working now for dimsav but not on spatie where i return query as is without modification.
@tabacitu maybe, can you work on this?

i need to take some other test and after that i will do a new pull request.

Hope this is useful also for other people, this modification were not "light".

Let me know what you think.

**Comment by lloy0076** [comment]
From what you've said, it would appear that the translation package and the CRUD package are somewhat intertwined or closely coupled - if Dimsave were entirely 100% compatible, I'm not sure you'd indicate that the modifications were not "light [sic]".

The issue that the Backpack team has is that the *more* that is supported, the *more* bugs are discovered or uncovered and those who are able to (and have the time to) support the packages may not have the time - or patience - to support another integration.

I'm wondering if it would be possible to step back a bit and answer the following:

* What does [Dimsav/Larave-Translatable](https://github.com/dimsav/laravel-translatable) offer me over what is currently available?
* What does [Dimsav/Larave-Translatable](https://github.com/dimsav/laravel-translatable) offer others over what is currently available?

I'm not trying to be discouraging - I got all sixes when my creator rolled my "ability to be discouraging feat" - but I'm interested in seeing things from your point of view.

**Comment by bedoz** [comment]
Yeah you're right i can understand your point of view.
The real differences are a comparison of dimsav vs spatie.
The first one use a send table for translation, the second one use a json field.
The first one work on every mysql version, the second one is great after mysql 5.7
The first one can be sorted and filtered, the second one i don't know.

I repeat i added two new feature (sort and search on translated fields) that i cannot see before, maybe i'm wrong.

The reason for this is that i need to upgrade a website from laravel 5.1 to laravel 5.5 and i use your backpack for admin.
So i want to develop this not to lose all translation i have with dimsav (thousand of content on 4 languages).

I thought other people could be on my situation and can be helped with this, for this reasons i thought to create a new pull request for these changes.

Feel free to accept or decline my modification. You can find this on https://github.com/bedoz/CRUD/tree/dimsav-translatable

**Comment by Spodnet** [comment]
I use dimsav with backpack, needed separate table for translations for audit purposes, users have access to translations but not the main table for editing for instance. Dates on translations so you can see which translations are out of date, change control on a field level vs a single object.

Single field works great for convenience but not for anything more complicated

**Comment by tabacitu** [comment]
I completely agree with @lloy0076 on the difficulty of supporting things. Every new features comes with a huge overhead in terms of time spent:
- fixing bugs
- covering niche use cases
- answering real issues people have
- answering non-issues people have
- actually improving the feature

So at this point, we're pretty skeptical to adding new features to the Backpack core, especially one as complicated as translations. And it's natural for @lloy0076 to be particularly skeptical, since he's been the hero holding up our _entire_ first line of defence.

That being said...

**@bedoz I WOULD LOVE to have dimsav/laravel-translatable support on Backpack!** THANK YOU SO MUCH for your work!! Support for dimsav's package has been planned from day 1, that's why we've implemented spatie/translatable as an "adaptor". I even announced the future support for dimsav in the newsletter at the time. But having one translation option, it's just never been a priority to code the second adapter. I'm glad you needed that and are able to provide a solution. Please create a PR when you think it's ready and let's move the conversation there. Happy to help in any way.

@lloy0076 - translations are something very tricky indeed. And spatie's package has proven to be a headache. By the end of the month I expect to be able to dedicate enough time to it to make translations rock-solid. It's the one feature in Backpack where I've never been 100% sure it will work no matter what, since it's like a freaking octopus - it spreads so many ways. But we'll be ending 2017 with rock-solid translations, both for spatie and dimsav's package. And I expect that we will be recommending people to use dimsav's as option numbero uno, since it's a lot cleaner. JSON in the db always felt a bit icky to me...

Cheers guys! Thanks a lot for being part of this!

**Comment by theduke** [comment]
@tabacitu is there any place to track your work on Dismav support?

I'd really like to buy a license for a project I'm working on, but this depends on support for dimsav.

@Spodnet could you share some details on how you are currently using dimsav?

**Comment by tabacitu** [comment]
@theduke I've just made PR https://github.com/Laravel-Backpack/CRUD/pull/1247 from @bedoz 's work. The work hasn't advanced at all, I'm afraid, and we have no timeline for implementing this feature. I hope we get to it in the next month, but no promises.

**Comment by theduke** [comment]
@tabacitu I just implemented it as a custom input type, which was pretty easy to do.

**Comment by tabacitu** [comment]
A custom field type? Wow. How? Could you copy-paste your custom field type please?
