### ISSUE TITLE
ajax-loader.gif not found

### ISSUE THREAD

**Issue by cerelli** [Laravel-Backpack/CRUD#1175]
# Bug report
vendor/backpack/crud/img/ajax-loader.gif not found

### What I've already tried to fix it:
I copied the folder ```vendor/backpack/crud/src/public/crud/img``` in to ```public/vendor/backpack/crud/img```

### Backpack, Laravel, PHP, DB version:
3.3.4, 5.5.28, 7.2

**Comment by tabacitu** [comment]
Hi @cerelli ,

Thanks for the bug report. Yes, the ajax-loader image has been introduced in a relatively new Backpack\CRUD version, as a backwards-compatible update. So you shouldn't get an error - if the file is missing you should see the "Loading..." text, just like before, instead of the new, cooler spinner:
![screen shot 2018-01-09 at 10 05 00](https://user-images.githubusercontent.com/1032474/34710588-9d3173e2-f524-11e7-9088-c138b2c2d1d1.png)


If you have this error I recommend you re-publish the assets with ```php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="public"```.

Another solution would be to copy the file manually, like you said.

Thanks, cheers!
