### ISSUE TITLE
Date input in Table field

### ISSUE THREAD

**Issue by anand-a6** [Laravel-Backpack/CRUD#1177]
I was trying to create date field Inside Table but it isn't working out

it shows this angular date format exception 

![capture12345](https://user-images.githubusercontent.com/15985328/34621773-e8437ab0-f263-11e7-85fd-7b4ac42c6a6e.PNG)

![error](https://user-images.githubusercontent.com/15985328/34621772-e816ecac-f263-11e7-87a1-fa2d55bef3ec.PNG)

**Comment by tabacitu** [comment]
Hi @anand-a6 ,

The table field currently only supports text inputs, unfortunately. Supporting more field types is planned (we call it "the matrix field"), but it's far from being done. I'm afraid the only way to include a date field in the table field would be [a custom field type](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types), starting from the table field.

Sorry. Cheers!

**Comment by luukScheur** [comment]
Hi @anand-a6,
Have you managed to get this working? I'm stuck on the same issue now.
As the Angular error is saying, it requires a javascript `Date` format as input. Instead of a regular PHP `date` (like it is implemented right now). So before initalizing the date inside the items need to be converted (with Angular?).

FYI, 'the matrix field' status can be found here #771
