### ISSUE TITLE
Can't override validation roles

### ISSUE THREAD

**Issue by abdelrahmanahmed** [Laravel-Backpack/CRUD#1179]
# Bug report
### What I did:
I am trying to override backpack form validation roles (update request).
**UserUpdateCrudRequest.php**  

```
use App\Http\Requests\Backpack\PermissionManager\UserUpdateCrudRequest as UpdateRequest;

class UserUpdateCrudRequest extends \Backpack\PermissionManager\app\Http\Requests\UserUpdateCrudRequest 
{
	
	function __construct()
	{
		parent::__construct();
	}
	
	public function authorize()
    {
        // only allow updates if the user is logged in
        return \Auth::check();
    }
	
	public function rules()
	{
		$rules = [
			'name'     => 'required',
			'password' => 'confirmed',
		];
	
		return $rules;
	}
} 

```
**app/Http/Controllers/Admin/Backpack/PermissionManager/UserCrudController.php**
```
   public function update(UpdateRequest $request)
    {
        //code
    }
```

### What I expected to happen:
The email field is mandatory on create , and not mandatory on update.
### What happened:
```
ErrorException in UserCrudController.php line 18:
Declaration of App\Http\Controllers\Admin\Backpack\PermissionManager\UserCrudController::update() should be compatible with Backpack\PermissionManager\app\Http\Controllers\UserCrudController::update(Backpack\PermissionManager\app\Http\Requests\UserUpdateCrudRequest $request)
```

### Backpack, Laravel, PHP, DB version:
3.2, 5.3 ,5.6

**Comment by OliverZiegler** [comment]
In my opinion what you are trying is currently not supported due to PHP type hint restrictions.

PHP doesn't allow changing the methods type hints in subclasses. (and that's what your are doing)

you could change the update-route to point to another function where you type-hint your new UpdateRequest and do the logic (as the UpdateRequest is a subclass of the original request you can call `parent::update()` if needed).

Closing this issue as this is more of a Stackoverflow question.

We try having only bugs and features on the issue section. 
If you feel this should be addressed in some way feel free to reopen.

Cheers
