### ISSUE TITLE
$this->crud->orderBy disables ajaxTable reordering

### ISSUE THREAD

**Issue by tquensen** [Laravel-Backpack/CRUD#1181]
# Bug report
Adding `$this->crud->orderBy('...');` in the CRUD controller prevents any reordering by clicking the column titles.

### What I did:
Add `$this->crud->orderBy('position');` inside the setup() method

### What I expected to happen:
That the tables use the "position" column for default ordering, but clicking a column headline to reorder the table should still have priority

### What happened:
Reordering doesn't work anymore. The search method in the Backpack\CRUD\app\Http\Controllers\CrudFeatures\AjaxTable trait also calls `$this->crud->orderBy` 

`$this->crud->orderBy` calls `$this->query->orderBy` which just **adds** the order to the query builder instead of replacing it. The setup method of the CRUD controller is executed before the ajaxTable trait's search method, so the orderBy called in the setup method always gets higher priority.

### What I've already tried to fix it:
There is no method to remove or replace the orderBy in the laravel QueryBuilder, So thats not an option. 

A working workaround is to only set the default order in the setup method when no order is passed for the ajaxTable:
```
if (!$this->request->input('order')) {
            $this->crud->orderBy('position');
}
```

But it would be much cleaner to have a `$this->crud->defaultOrderBy`method that does this check for you, as it is probably the desired behaviour to not disable the ajaxTable sorting

### Backpack, Laravel, PHP, DB version:
"backpack/base": "^0.8.3"
"backpack/crud": "^3.3"
"laravel/framework": "5.5.*"

**Comment by lloy0076** [comment]
I'm fairly certain this is mentioned either in another PR or issue but I cannot for the life of me find it.

If the `orderBy` is added during setup then it's never updated for the AJAX ordering (i.e. column ordering by the little triangle [usually] thingomejiggybobwhatchamecallsits).

**Comment by lloy0076** [comment]
@tabacitu If this is urgent is there a PR?

**Comment by tabacitu** [comment]
Thank you @tquensen .

You're right, I can confirm that's a problem. I think a better solution would be to change the ```search()``` method instead, to clear any ```orderBy```s if another order is specified. Otherwise, if we modify the ```orderBy()``` method, we'd be making it impossible to call ```orderBy()``` multiple times. Plus, I see this as a search-specific problem, not a general-query problem, so the logic shouldn't live in the general class.

I've made the necessary change in PR #1246 , so it'll get fixed in the next patch update. Let's close this issue. Please reopen if you're not satisfied with the result.

Thank you, cheers!
