### ISSUE TITLE
Storing Value not ID

### ISSUE THREAD

**Issue by anand-a6** [Laravel-Backpack/CRUD#1184]
In my application while using the select2 field I want to save the value that shows to the database not the id

**Comment by lloy0076** [comment]
Off the top of my head:

* https://laravel-backpack.readme.io/docs/crud-fields#section-select2_from_ajax

Could do what you want.

**Comment by b8ne** [comment]
You could get it done by switching the values in `store()` and `update()` in your CrudController before the parent methods.
However you'd need to roll custom relationship methods in order to get the edit/update form to work?

Why do you want to do this though? Why not just save the id and use an eloquent relationship as normal whenever you want to render the stored value?
i.e. `$model->relationship->value`.
