### ISSUE TITLE
Simplification: Don't generate custom requests

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/CRUD#1273]
Custom requests are generated when using `backpack:crud modelname`

I've found **much** simpler using $request->validate in controller.

Example: 
![imagen](https://user-images.githubusercontent.com/4065733/37166522-db3436ca-22c4-11e8-85d2-758eabbb52be.png)

In this example, I've implemented different "unique field validation" for store and update methods. 
In less than 10 lines. 

If I were using custom requests, I would need two separate files, which feels like too much. 

My suggestion is removing requests generation in 
 `backpack:crud modelname`

and simply leaving a template like this:
![imagen](https://user-images.githubusercontent.com/4065733/37166814-bebad174-22c5-11e8-9dc4-b22b22594525.png)

**Comment by tabacitu** [comment]
@eduardoarandah I think the CONs heavily outweigh the PROs here.

PROs:
- one less file

CONs:
- I feel like this would be against the Laravel best practice. Laravel _used_ to do validation like that, but has created FormRequests for the specific purpose of your validation logic being separate. 
- Using FormRequests, the validation is done _before_ it even reaches the controller; validation in controllers, however, will happen after the request goes through ```__construct()``` and ```setup()```; so less secure and more difficult to debug;
- it's not DRY - most EntityCrudControllers would then have the same validation rules, written twice;
- You wouldn't be able to [reuse the same validation rules in JS](https://github.com/proengsoft/laravel-jsvalidation);
- EntityCrudControllers are bulky enough as they are, IMHO; this would make them even bulkier;
- This would promote everyone modifying their ```store()``` and ```update()``` methods; which in most cases is _not_ necessary;
- In the not-too-distant future, we plan for FormRequests to be generated with sensible rules already written, based on the DB columns; so that, in most cases, developers won't _need_ to modify it at all; for eg:
  - ```NOT NULL``` columns will have ```required```;
  - integer columns will have ```integer```;
  - float columns will have ```float```;
  - varchar columns will have a max as per the db column;
  - columns with standard names like ```email``` could have ```email``` validation;

I think generating Requests should still be done by default. However, I am not against creating a config file for [Backpack/Generators](https://github.com/Laravel-Backpack/Generators) to specify which files _you_ would like to be generated when you run a ```php artisan backpack:crud entity``` command. So that, if some developers prefer

I'll close the issue for now, anyone can reply here if they don't agree with me. As I always say - I make mistakes all the time.

Cheers!
