### ISSUE TITLE
Getting Symfony\Component\Process\Exception\ProcessFailedException  : The command "mkdir -p public/uploads" failed. error

### ISSUE THREAD

**Issue by harishdurga** [Laravel-Backpack/CRUD#1299]
# Bug report

### What I did:
i ran the following command on windows 10.
 php artisan backpack:crud:install

### What happened:
 Exception trace:

  1   Backpack\Base\app\Console\Commands\Install::executeProcess("mkdir -p public/uploads")
      C:\xampp7.2.1\htdocs\decentblocks-site\vendor\backpack\crud\src\app\Console\Commands\Install.php : 51

  2   Backpack\CRUD\app\Console\Commands\Install::handle()
      C:\xampp7.2.1\htdocs\decentblocks-site\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  Please use the argument -v to see more details.

### Backpack, Laravel, PHP, DB version:
1.1, 5.6, 7.2.2, mysql 5.7

**Comment by tabacitu** [comment]
Hi @harishdurga ,

Backpack assumes you're running a UNIX command line - just mentioning it because it looks like you're on Windows. Hope you're running this through Vagrant/Homestead/something.

You can increase the timeout with the following ```php artisan backpack:crud:install --timeout=600```. It's worth trying, but I don't think it will fix the issue for you. It seems like installation is failing at ```mkdir -p public/uploads``` which is a very simple command, it shouldn't take much time at all. 

**What I recommend you do is [manually install CRUD](https://laravel-backpack.readme.io/v3.4/docs/faq#section-how-do-i-manually-install-backpackcrud)**. So that when that command fails, you can manually create that folder in Explorer, then run the next commands yourself.

Hope it helps. Please let me know if you discover why the mkdir command failed for you - it's an odd one.

Cheers!

**Comment by mycroftsk** [comment]
mkdir in windows has different syntax. I tried to change line 50 in file `vendor/backpack/crud/src/app/Console/Commands/Install.php`

from this:
```php
$this->line(' Creating uploads directory');
$this->executeProcess('mkdir -p public/uploads');
```

to: 
```php
if (DIRECTORY_SEPARATOR == '/') {
    // linux or unix like OS
    $this->executeProcess('mkdir -p public/uploads');
}

if (DIRECTORY_SEPARATOR == '\\') {
   // windows
   if(!file_exists('public\uploads')) {
       $this->executeProcess('mkdir public\uploads');
   }
}
```

and it works.

**Comment by indra1** [comment]
Try using gitbash if you're on windows. It acts like a unix console. Since most laravel installations live on a linux based os in the cloud this is not really an issue.

**Comment by pxpm** [comment]
@indra1 i tried using gitbash but the problem still persists on my machine.

Running WIN 7 PRO x64

**Comment by promatik** [comment]
Besides the `mkdir` command, the 5th command, `php artisan backpack:base:add-sidebar-content ...` is also creating an issue in windows.

I solved both with the code bellow, @tabacitu, @indra1, do you think this is handful for backpack? To support both unix like and windows OS? I can create a PR with this changes.

```php
switch (DIRECTORY_SEPARATOR) {
    case '/': // unix
        $this->executeProcess('mkdir -p public/uploads');
        break;
    case '\\': // windows
        if(!file_exists('public\uploads')) {
            $this->executeProcess('mkdir public\uploads');
        }
        break;
}
```

and 

```php
switch (DIRECTORY_SEPARATOR) {
    case '/': // unix
        $this->executeProcess("php artisan backpack:base:add-sidebar-content '<li><a href=\"{{ backpack_url(\"elfinder\") }}\"><i class=\"fa fa-files-o\"></i> <span>File manager</span></a></li>'");
        break;
    case '\\': // windows
        $this->executeProcess('php artisan backpack:base:add-sidebar-content "<li><a href=""{{ backpack_url(\'elfinder\') }}""><i class=""fa fa-files-o""></i> <span>File manager</span></a></li>"');
        break;
}
```

**Comment by tabacitu** [comment]
Thanks a lot @promatik - I just applied your corrections and tagged it, a ```composer update``` should fix it for everyone.

Cheers!
