### ISSUE TITLE
Backpack 3.3 for Laravel 5.5 not publishing /views/vendor/

### ISSUE THREAD

**Issue by neromaki** [Laravel-Backpack/CRUD#1331]
# Bug report

### What I did:
Follow the 3.3 installation procedure for Laravel 5.5:
https://laravel-backpack.readme.io/v3.3/docs/install-on-laravel-55

### What I expected to happen:
Backpack vendor views to be published to `resources/views/vendor/backpack/*`

### What happened:
Nothing was published

### What I've already tried to fix it:
Roll back and attempt to reinstall from the beginning

### Backpack, Laravel, PHP, DB version:
Backpack 3.3
Laravel 5.5
PHP 7.1.3
MySQL 5.7.17

All `vendor:publish` commands reported success, so I'm not sure what is going on:
```
vagrant@homestead:~/Code/pressstart$ php artisan elfinder:publish                                                                                                       
Published assets to: barryvdh/elfinder                                                                                                                                  
vagrant@homestead:~/Code/pressstart$ php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="public" #publish CRUD assets                      
Copied Directory [/vendor/backpack/crud/src/public] To [/public/vendor/backpack]                                                                                        
Publishing complete.                                                                                                                                                    
vagrant@homestead:~/Code/pressstart$ php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="lang" #publish CRUD lang files                    
Copied Directory [/vendor/backpack/crud/src/resources/lang] To [/resources/lang/vendor/backpack]                                                                        
Publishing complete.                                                                                                                                                    
vagrant@homestead:~/Code/pressstart$ php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="config" #publish CRUD and custom elfinder config f
iles                                                                                                                                                                    
Copied Directory [/vendor/backpack/crud/src/config] To [/config]                                                                                                        
Publishing complete.                                                                                                                                                    
vagrant@homestead:~/Code/pressstart$ php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="elfinder" #publish custom elFinder views          
Copied Directory [/vendor/backpack/crud/src/resources/views-elfinder] To [/resources/views/vendor/elfinder]                                                             
Publishing complete.      
```

**Comment by indra1** [comment]
Hi,

It seams like you did this directly in Vagrant. Does the same happen if you do it on git bash? Are you on windows/ mac or linux?

**Comment by tabacitu** [comment]
Hi @neromaki ,

We no longer publish the views by default, nor recommend doing so in the installation process. I _belive_ this started since CRUD 3.3, so that might be the source of your confusion. It looks to me like you've published everything that's necessary for CRUD to run, but NOT the views (since the installation doesn't ask you to do that). In order to publish the views use the ```views``` tag:

```bash
php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="views"
```

However. Before you do that, please consider NOT doing it :-) Because:
1. You don't _need_ all the views published in your /views/ folder. If a view isn't there, Backpack will just pick it up from the package.
2. If you _do_ publish all views, after a ```composer update``` you won't be getting any updates to the view files, since you won't be using the views from the package, but your own views (the ones you published).
3. Since CRUD has _a lot_ of views, updates are bound to happen.

So I really recommend NOT publishing all the CRUD views. I recommend you manually create files for the views you need to customize, with the same name as the ones in the package. I know, it's a bit uncomfortable, but this way, you get the best of both worlds - you customize whatever you want, but you'll also receive any updates to all other files.

Just my 2 cents.
Cheers!
