### ISSUE TITLE
[4.0][Performance Improvement] Columns, filters and fields should be loaded when needed

### ISSUE THREAD

**Issue by turkeryildirim** [Laravel-Backpack/CRUD#1375]
# Bug report
Not a bug, improvement. If you have several relations in relatively big table, page loading takes too much time.

### What I did:
Defult CRUD controller created.

### What I expected to happen:
addFilters, addFields and addColumns should be populated when needed.

### What happened:
On every request addFilters, addFields and addColumns are populated.

### What I've already tried to fix it:
```
        $currentScreen = $this->getCurrentScreen();
        if (in_array($currentScreen, ['index', 'show', 'search'])) {
            $this->addColumns();
            $this->addFilters();
        }
        elseif (in_array($currentScreen, ['create', 'edit'])) {
            $this->addFields();
        }
```

### Backpack, Laravel, PHP, DB version:
BP: 3.4.6., L:5.6.18, PHP: 7.2.4, Mysql: 5.7.x

**Comment by tabacitu** [comment]
Hi @turkeryildirim ,

Thank you for the improvement suggestion. I do agree it's suboptimal to have everything loaded on every request. **This is mainly due to how we define a CrudPanel - we define everything inside the ```setup()``` method.**

Adding fields/filters/columns with relationships _does_ get the relations, so that might have the biggest impact on performance, and where we can make major improvements.  I'll need to run some tests first, to see the impact. **A backwards-compatible way to improve performance _could be_ to fetch the relationships and everything else on ```getFields()``` instead of ```addField()```**. That should:
- keep the syntax as is (in the ```setup()``` method);
- restrict  ```addField()```, ```addFilter()```, ```addColumn() ``` to just writing stuff in an array or collection, which would have minimal performance impact;
- move the "heavy lifting" to ```getFields()```, ```getColumns()```, ```getFilters()```, which are only called in their respective methods/requests;

I'll be back.
![giphy-downsized](https://user-images.githubusercontent.com/1032474/39686004-f64ce504-51ce-11e8-80be-20294a1d1f10.gif)

**Comment by lloy0076** [comment]
If there are relations, does splicing in a `with` somewhere appropriate help here?

**Comment by tabacitu** [comment]
@lloy0076  we can already do ```$this->crud->with('categories');```. It definitely improves performance, but... could always do better...

**Comment by tabacitu** [comment]
**Update:** In v4 there are two places you can move your ```$this->crud``` calls so that they're only loaded when that operation is happening:

```php
public function setup()
{
    $this->crud->operation('list', function() {
        $this->crud->addColumn('text');
    })
}

public function setupListConfiguration()
{
    $this->crud->addColumn('text');
}
```

They both do the same thing, developers can use which one they prefer. 
Details in this long PR here - https://github.com/Laravel-Backpack/CRUD/pull/2000
Closing this, as v4 fixes it :-)

Thanks again for the suggestion @turkeryildirim , you were right!
Cheers!
