### ISSUE TITLE
Concatenate layout CSS + JS to reduce HTTP Requests

### ISSUE THREAD

**Issue by paperscissors** [Laravel-Backpack/CRUD#1394]
Hello!

I'm wondering the feasibility of potentially setting up concatenation of CSS and JS requirements that layout.blade.php uses in order to reduce HTTP requests--- whether it's some sort of vendor:publish bit that adds to the `webpack.mix.js` file or what have you.

I suppose it's relatively overkill since the admin sides of sites tend to not have the sort of traffic volume front ends have, but in my mind any sort of reduction in server load and asset optimization can't hurt, yeah?

**Comment by tabacitu** [comment]
Hi @paperscissors ,

**Backpack doesn't provide a solution for this "out of the box", but you can use any solution you use on your front-end.** 

However, I would agree with your sentiment - I think it's overkill in admin panels. Personally, I prefer to:
- serve as much custom CSS/JS as possible from CDNs
- always ALWAYS use HTTP/2 requests
- cache CSS/JS

Using a free [CloudFlare](http://cloudflare.com/) account takes care of all three, and in my experience is faster than minifying and concatenating files. HTTP/2 loads the assets independently, from multiple locations (so instead of downloading one concatenated file weighing 300kb, we download 5 files, each weighing 100kb, but they're downloaded in parallel so they reach the end user faster).

There are talks about using different solutions for this, and we might do it in the future, but... not at the moment, no :-) My 2 cents - use Cloudflare, or nothing. Minimizing and concatenating for admin panels _should be_ be overkill, especially considering that you can't possible concatenate all the JS your admin panel uses. A lot of _field types_ have their own JS, that is only loaded if that field type is used. If you concatenate all JS from all field types, it would be a HUGE file, even minified. Again - I might be wrong and proven otherwise :-) It happens.

Cheers!

**Comment by paperscissors** [comment]
That is a good point--- between HTTP/2 and Cloudflare that should more or less cover bases here!
