### ISSUE TITLE
Datetime picker field is broken

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/CRUD#1396]
# Bug report
**datetime_picker** field just stopped working, because path to JS libraries in blade template was changed.
### What I did:
As described in documentation I added field in the next way
```
        $this->crud->addField([
            'name'        => 'start_at',
            'type'        => 'datetime_picker',
            'label'       => 'Starts at',
            'allows_null' => true,
        ]);
```
And I found that actually path to the library JS was not found: [See image](https://monosnap.com/file/MJM2dygPdtFV5OSAQGnWOm2fXkrORP)
That was made in this commit: https://github.com/Laravel-Backpack/CRUD/commit/a3ea937be7410b2c943e8dc05cf802bce710a68c#diff-ea82d17c7d5493e182dcf3df3880059eR40

But there was nothing about hot should this path be fixed. And also this path mean that we should start using bower or another package managers, but according to the main BackPack idea, there should not be any such JS package managers. For example as described here: https://github.com/Laravel-Backpack/CRUD/issues/736 

I could fix that by putting library manually to that folder, but is there another proper way to fix that? 

I use the last available version:
* backpack/base - 0.9.5
* backpack/crud - 3.4.9

**Comment by tabacitu** [comment]
Hi @mialex ,

Don't worry, we're not using bower (at least not yet). My position on this is still the same - I think it would bring an extra layer of difficulty, that some Backpack users will find annoying. That folder is named that way because _that's what the developers of this js plugin named it_. It's not generated by us or anything, it's just copy-paste from their Github repository. I find using the repository as-is, without changing any names, is the cleanest method available.

Indeed, the paths to the CSS\JS files have changed from Backpack\CRUD 3.3 to 3.4. If you're upgrading your project to CRUD 3.4, this shouldn't be a problem, because **[the upgrade guide](https://laravel-backpack.readme.io/docs/upgrading-crud-33-to-34) specifically states that you should delete your published assets, and republish them. You must have missed that.** If you do that, you shouldn't get any console errors in JS, because the files are there. 

I'm 99% sure this is what happened for you - missed this step when upgrading, so I'm going to go ahead and close this. Let me know if this wasn't the case.

Cheers!

PS. Very clear bug report. Thanks a lot for taking the time to dive deep and see what the problem was - and even when it was introduced. Very helpful.

**Comment by mialex** [comment]
Hello @tabacitu , you were right. My fault, as i didn't followed update instructions. As far as I hadn't made any major changed an the moment I updated the project, I just decided to open the project first and everything was working fine, so I didn't not follow the update instruction :)
Not it works. Thank for update

**Comment by tabacitu** [comment]
No problem ;-) You're not the first person to cut corners when upgrading - been guilty of this a number of times :-)

Cheers!
