### ISSUE TITLE
defaultDate in datetime_picker does not post value unless changed

### ISSUE THREAD

**Issue by patrickreck** [Laravel-Backpack/CRUD#1412]
# Bug report
When adding the `defaultDate` option to a `datetime_picker` field type, it does not actually post it in the request unless you change the date.

### What I did:
Add the field to the crud:

```
$this->crud->addField([
    'name' => 'start_at',
    'label' => 'Start date',
    'type' => 'datetime_picker',
    'allows_null' => false,
    'datetime_picker_options' => [
        'defaultDate' => (new Date())->toDateString()
    ],
]);
```

### What I expected to happen:
To get the `defaultDate` value in the request if the user does not touch it.

### What happened:
If the user does not change the date, it will be `null`

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4.8
Laravel: 5.6.20
PHP: 7.2.4
Mysql: 5.7.22

**Comment by tabacitu** [comment]
Hi @patrickreck ,

Thanks for reporting this. Never used ```defaultDate``` myself, I always use Backpack's ```default``` attribute, since it works across all fields - just easier to remember imho.

```
        $this->crud->addField([   // DateTime
            'name'  => 'datetime_picker',
            'label' => 'Datetime picker (jQuery plugin)',
            'type'  => 'datetime_picker',
            'allows_null' => true,
            'default' => '2017-05-12 11:59:59',
            // optional:
            'datetime_picker_options' => [
                'format'   => 'DD/MM/YYYY HH:mm',
                'language' => 'en',
            ],
        ]);
```

It should work for you with ```default``` - just checked. Also, I've just updated the docs to show this (even if commented) so that people understand this is the preferred way to specify a default date. Let me know if it doesn't work for you and we'll reopen the issue.

Thanks, cheers!
