### ISSUE TITLE
Customize integrity error message (question)

### ISSUE THREAD

**Issue by androidedev** [Laravel-Backpack/CRUD#1429]
# Question 

Hello, I would like to know what is the correct way to do the following in backpack.

I have a  :

Section Model -> has many products
Product Model -> belongs to a Section

I have integrity and relations defined in db and models.

When I try to delete a Section with products the database throws a "Integrity constraint violation", thats fine is working as expected.

What I want to do is customize the error that is show in backpack "_NOT deleted, There's been an error. Your item might not have been deleted_.", with (for example) "_Hey mate are you crazy, there will be a lot of crying products if you let them orphaned_"

I understand that the best way to do that is asking first for the existence of Products in that Section before delete and show a message and abort if they exists, and not capture the message for database (I'm was used to that in .net for example), so I tried to do it with :

- laravel events
- laravel observers
- overwrite destroy() in my controller
 
  
No matter what I do the problem is always the same the Alert::error(...)->flash(); only shows after a I exit the current url and load another (and after the message from backpack has showed), there is no way that I can overwrite the message of backpack and stay gracefully in the grid, even if I do a redirect to the current url.

I have wasted many hours with this, and I'm sure that I'm missing something obvious because is a very common use case and can't be so cumbersome.

**Comment by tabacitu** [comment]
Hi @androidedev ,

You should be able to customize the message by **overwriting the ```destroy()``` method** in your controller AND **customizing the delete button**. If you create a blade file in your ```resources/views/vendor/backpack/crud/buttons/delete.blade.php```, Backpack will pick up that one instead of the one in the package. [That's where the message logic is right now](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/buttons/delete.blade.php), unfortunately. So to sum up:
- overwrite ```destroy()``` to check that relationships do not exist before deleting; return a custom message as an AJAX response instead of the standard one;
- overwrite ```buttons.delete``` view to show the message passed by the ```destroy()``` method, instead of the standard one;

Hope it helps.
Cheers!

P.S. Alternatively, you could overwrite the message with a generic one, by just publishing the CRUD lang files. But you'd still have to overwrite the ```destroy()``` method. I think the method above provides better UX.

**Comment by androidedev** [comment]
Thank you @tabacitu I will try the second path, I don't like to overwrite the backpack views if I can avoid it.
