### ISSUE TITLE
[Feature Request] Better Custom Button Placement

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1438]
Currently we can only define a custom button to be at the 'start' or 'end' of the button stack. I would like to be able to put a custom button before the 'delete' button but before everything else. 

My thoughts on how this is achievable:
Right now we stack the buttons in collection (see below)
<img width="243" alt="screen shot 2018-06-03 at 7 17 46 pm" src="https://user-images.githubusercontent.com/487798/40895222-e11c2dd0-6762-11e8-9e3d-c29020d9bb35.png">

So on `$position` we just need to allow additional information rather then just 'beginning' or 'end' such as 'update', 'preview', etc. That would define where it should be placed after.

`$afterButton = $this->buttons->firstWhere('name', $position);` 

This gets us the button info to be placed after, however what I am struggling to figure out is how to get its current position. After that we can use `$this->buttons->take(someCount)` push the new one to the end and then merge the new first set to the ending set.

Example:

```php
$totalButtons = $this->buttons->count();

$before = $this->buttons->take($position-1);
$after = $this->buttons->take(-$totalButtons-$position);
$before = $before->push($button);

$this->buttons = $before->merge($after);
```

**Comment by tabacitu** [comment]
Hi @AbbyJanke ,

I tink you've overthinking this :-) I personally solve this problem by removing the delete button and adding it again :-) It's a hack, I know, but it works, and I think the code is easier to read than reordering the Collection is some way. And I don't see how it would stop working in the future:

```php
$this->crud->addButtonFromModelFunction('line', 'open_google', 'openGoogle', 'end'); // custom button
$this->crud->removeButton('delete');
$this->crud->addButton('line', 'delete', 'view', 'crud::buttons.delete', 'end');
```

----


Sorting arrays/collection is a huge pain in the a$$, so I'd rather leave that to Laravel if possible :-) Plus, anything we do in this area should probably follow how Laravel does things, since that'll be the intuitive option for Laravel developers. That's why ```buttons``` is a Collection, which I hope all such properties will become, in the end (some are arrays right now).

That being said, we do have a last parameter that is called "position", and we could use polymorphism to make that parameter:
- beginning - puts at the beginning (uses ```prepend()```)
- end - puts at the end (uses ```push```)
- closure - runs the closure 

But I think that'll bring more headache than necessary, since as I said, ```$buttons``` is a collection, and quick fixes like the above are probably more intuitive than a closure.

**Comment by AbbyJanke** [comment]
I agree that it is abit overthinking. And I have done the hackish way you mentioned on some. But here is where I'm coming from.

Button Example:
Preview, Update, Revisions, Delete, Regenerate, Reissue

Say you want to move Regenerate and Reissue after Update but before Revisions, its just causing you to delete two buttons, then re-add them. In my opinion it just adds additional lines of code that could cause confusion letter down the road like "why did i delete this then re-add it" and I was just throwing ideas out there.

**Comment by tabacitu** [comment]
Pfff... yeah, I think you're right, not an extraordinary solution. But I think NOT deleting buttons and saying "_put this after this, put this before this_" isn't any any clearer, tbh. This probably looks cleanest to me:

```php
// remove all buttons in a row, so we can add them in the right order
$this->crud->removeAllButtonsFromStack('line');

// line stack
$this->addButton('line', 'preview', 'view', 'crud::buttons.preview', 'end');
$this->addButton('line', 'update', 'view', 'crud::buttons.update', 'end');
$this->addButton('line', 'regenerate', 'view', 'regenerate', 'end');
$this->addButton('line', 'reissue', 'view', 'reissue', 'end');
$this->addButton('line', 'revisions', 'view', 'crud::buttons.revisions', 'end');
$this->addButton('line', 'delete', 'view', 'crud::buttons.delete', 'end');
```

This would probably be easiest for a new developer to read, right? But it _would_ require the first developer (that does this) to dig into ```Buttons.php``` and see which ones are added... so yeah...

**Comment by AbbyJanke** [comment]
I agree with that. I know i open a few random “issues” but just i try to open them mainly for discussion and thoughts before i dive into them. Will consider it closed.

**Comment by tabacitu** [comment]
Haha don't worry about it @AbbyJanke . I agree - this is how progress is made :-)
