### ISSUE TITLE
Way to use `table` field for separate table in DB?

### ISSUE THREAD

**Issue by valetzyzy** [Laravel-Backpack/CRUD#1448]
I just want to use `table` field type to store items in separate table. Not JSON.

I have `range_rental` table and `ranges` as one to many relation. 

![range_rentals](https://user-images.githubusercontent.com/3648860/41088282-6b525fc2-6a3f-11e8-977d-e6d9a6e3d778.png)

and want to use `table` for storing in `ranges` table in DB
![6ac79c0-screen_shot_2016-09-26_at_19 54 04](https://user-images.githubusercontent.com/3648860/41088377-adc1eeb8-6a3f-11e8-9f4f-746330fa0f9d.png)

Thanks,
Cheers

**Comment by tabacitu** [comment]
Hi @valetzyzy ,

Backpack doesn't have anything like that right now. But you should be able to easily customize the save process, to save in a different table and get data from a different table:

Option A) Overwrite the ```store()``` and ```update()``` methods to save to a different table. And the ```edit()``` method to pull the information for that field from a separate table.

Option B) Use Laravel Accessors and Laravel Mutators to do everything in the model. Ex ```setTableAttribute()``` and ```getTableAttribute()``` would store things in a different table instead of that one.

Hope it helps.
Cheers!
