### ISSUE TITLE
[Feature] Datatables Editor

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1464]
I've seen a lot of requests/discussions on being able to easily edit entries without loading a new page, etc. I am wondering if we should look into into including 'Editor' which is made by Datatables and we can make things happen.

https://editor.datatables.net/

Just curious if this is something others feel we should include by default, maybe we add a config variable (bool) to enable it or not. From looking at the documentation there is 1 new css, 1 new JS, and small amount of additional loading:

```javascript
new $.fn.dataTable.Editor( {
    ajax:  '/api/staff',
    table: '#myTable',
    fields: [
        { label: 'First name', name: 'first_name' },
        { label: 'Last name',  name: 'last_name'  },
        // etc
    ]
} );
```

would require us also loading the columns as fields within the JS but i think this might be a convenient option since we are generally loading from DB when using backpack generators.

**Comment by tabacitu** [comment]
Mine's a downvote, but I guess I could be persuaded otherwise. 

My CONs:
- the editor is a paid product, so using it would require people to yet another the license (annoying);
- we'll have pretty much the same functionality once the create/edit forms become AJAX (4.0), but with zero extra dependencies; and building it ourselves will also allow us to create things like Matrix fields (CRUD inside CRUD);
- I highly doubt it'll be easy to integrate this library with every possible field type, validation, tabs, etc; while building it ourselves definitely will;

**Comment by AbbyJanke** [comment]
Derp, didnt say it was paid. Nothing i saw said paid. I’m okay with waiting not something i really need but i just noticed it while looking at datatables docs for first time in awhile tbh ans wanted to open the thoughts on it.

**Comment by pxpm** [comment]
I would stick with tabacito on this one. Implementing ajax cruds would allow us to more costumization and less dependencies is allways batter.

**Comment by tabacitu** [comment]
Let's close the issue for now. If anybody else has thoughts on this - please reopen or reply.
