### ISSUE TITLE
How to save uploads without a mutator?

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/CRUD#1478]
Sometimes a mutator is not convenient. 

**How to save uploads without a mutator?**

I've managed to do it like this:

    public function store(StoreRequest $request)
    {
        $redirect_location = parent::storeCrud($request);
        
        $this->crud->entry->uploadFileToDisk($request->logo,'logo', 'public', 'company/logo');
        $this->crud->entry->save();
        return $redirect_location;
    }

    public function update(UpdateRequest $request)
    {
        $redirect_location  = parent::updateCrud($request);

        $this->crud->entry->uploadFileToDisk($request->logo,'logo', 'public', 'company/logo');
        $this->crud->entry->save();

        return $redirect_location;
    }

However, it doesn't delete files and doing two saves seems strange. 

I wish we could have a way of setting a function to perform the saving. 

Something like:

            [ // image
                'name'   => 'logo', // the db column for the foreign key
                'label'  => 'Logo',
                'type'   => 'upload',
                'upload' => true,    
                'disk' => 'public'            
               'function' => 'saveLogo'
            ],

or letting set the function to null

               'function' => null

so the user can do it manually:

    public function update(UpdateRequest $request)
    {
        $this->data['logo']=Model::mySaveFunction($request->file('logo'));
        ....
    }

right now, a mutator makes impossible to use packages like: 
https://github.com/CodeSleeve/laravel-stapler

what do you think?

**Comment by AbbyJanke** [comment]
What I do is create a function within a controller example example:

```php
private function upload($request, $attr, $path = null) {
   $this->crud->entry->uploadFileToDisk($request->logo, $attr, 'public', $path);
}
```

then you just call the upload function, 90% of the time its public folder being uploaded to, you can adjust the path if you want, but the it saves some thought but idk.

The biggest question i have with your thought is, where would we store that function? In the controller? in the model (in which case whats the point cause you can just put the mutator there) To me the way you do it seems the best option if you do want a mutator.

**Comment by tabacitu** [comment]
Hmm... @eduardoarandah as you've shown, we can totally do the upload somewhere else. The Controller is another option, of course, but only when you don't want to do stuff in the Model. For most use cases, I think the Model is the best place to have the upload logic, because... the Model is the DB interaction layer... and uploading a file is something that happens _along with_ updating the db column...

Another place to do this (while still having it in the model) would be in an [Eloquent Observer](https://laravel.com/docs/5.6/eloquent#observers) or maybe [Eloquent Events](https://laravel.com/docs/5.6/eloquent#events) directly. But they require a separate file for this, which I hate. I hate crating a class with only one method, then registering that class etc. Maybe they support anonymous functions? I don't think so... Food for thought.

But we should be able to use Eloquent Events in the boot() method:

```php
<?php

namespace App;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use CrudTrait;

    protected $table = 'categories';
    protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = ['name', 'slug', 'parent_id', 'image'];
    // protected $hidden = [];
    // protected $dates = [];

    public static function boot()
    {
       parent::boot();

       $attribute_name = "image";
       $disk = "public";
       $destination_path = "folder_1/subfolder_1";
    
       self::creating(function ($entry) {
           $entry->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
        });

       self::updating(function ($entry) {
           $entry->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
        });

       static::deleting(function($entry) {
            \Storage::disk($disk)->delete($entry->image);
        });
    }
```

Would this work for you @eduardoarandah ? I guess it could still conflict with other packages, since the packages want to do _the same thing_. Right?

**Comment by lloy0076** [comment]
Ok, this is an ask-it-on-stackoverflow type question...
