### ISSUE TITLE
Any Chance of using eventy in upcoming version ?

### ISSUE THREAD

**Issue by deepakSP** [Laravel-Backpack/CRUD#1487]
thanks for great package.

just saw eventy package today and my first reaction was this can be helpful in backpack admin panel !!

though we have custom events but i think using enenty will help make more customizable !

eventy package - https://github.com/tormjens/eventy/

**Comment by OwenMelbz** [comment]
HEEEEEEEEEEEEEEEELLLLLLLLLLLLLLL No :D

One of the biggest benefits of Backpack is that it sticks very close the traditional MVC and Laravel fundamentals - which means debugging and extending incredibly easy (assuming your know OOP)

Moving to an abstraction as vague as events/filters are horrible for long-term maintenance as anybody can do anything from anywhere - you have no clear path of debugging and no structure. It works okay in WordPress because they expect you pump all your custom logic in via `functions.php` which there is no comparable concept in Laravel.

If you want events - Laravel has its own built-in event system which you can just create your own BaseCrudController and fire them or run custom methods in any way.

As far as I'm aware it's always been considered as good practice on BackPack to have a base model/controller which allows you to customise the flow of a crud controller and overwrite/extend whenever needed.

Remember with Laravel you also have the ability to engage with the IoC container which means if you want to completely overwrite a method without publishing it you can always return back a decorated version of the classes you want to extend with custom functionality!

**Comment by lloy0076** [comment]
I agree with @OwenMelbz - and I'm almost tempted to just close this.

**Comment by tabacitu** [comment]
Hi @deepakSP ,

I'm glad @OwenMelbz got on his funny rant to explain why he doesn't like Eventy :-)) Because I _literally_ couldn't say it better myself. 

I'm afraid I agree with everything Owen said, and **I don't see us implementing Eventy in Backpack anytime soon**. My thought when going through eventy was just "_Well... Laravel has a way better architecture than WordPress. Why borrow from WP?!_ ". But Owen said it better.

Cheers!
