### ISSUE TITLE
[Feature req] Asterisk shown in create/update forms for required fields

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1493]
Issue was raised by @AbbyJanke .

My opinion on this, in short 
- having a ```'required' => true``` attribute on the addField() declaration would be ok, it would definitely be a solution, but it _would_ require telling the CRUD that a field is required in two places - once in the addField() and once in the Request file;
- ideally, we should be able to see which fields are required _automagically_; that would be the best way, I think;

**Comment by OwenMelbz** [comment]
@AbbyJanke @tabacitu it already exists xD

https://github.com/Laravel-Backpack/CRUD/blob/master/src/public/crud/css/form.css

```
       $this->addField([
            'name' => 'title',
            'attributes' => [
                'required' => true,
            ],
        ]);
```

Then you get

![add_consultant____apollo](https://user-images.githubusercontent.com/1094740/42278834-e2091066-7f93-11e8-8a82-5191663ec72a.jpg)

Has been in the core since November 2016!

**Comment by tabacitu** [comment]
Ouch :-)) 

Haha thanks @OwenMelbz , I guess I forgot about it for a minute. I actually use it on a bunch of projects.

**Comment by tabacitu** [comment]
I created a PR that adds the asterisks automatically, without being too much trouble.

https://github.com/Laravel-Backpack/CRUD/pull/1495

Let me know what you think.

Cheers!
