### ISSUE TITLE
Crud total count problem with group by

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/CRUD#1519]
Crud query total record return 1 or x (wrong count) on group by

After many tries, I found the problem on total record when using groub by on crud.
`$totalRows = $filteredRows = $this->crud->count();`
In AjaxTable.php

This return 

> Showing 1 to 1 of 1 entries

In Laravel, we use get() method before using count() and it correct. Does it any solution for Backpack CRUD?

**Comment by tabacitu** [comment]
Hi @bahman2216 ,

Yeah, using ```groupBy``` with Eloquent is a b#7ch. Generally, if you need a GroupBy, it's probably easier to create a new Model or use a custom controller & view instead of Backpack. But some simple GroupBys should be doable. If you use groupBy in ```setup()```, by the time the request reaches ```AjaxTable::search()```, ```$this->crud->query``` should already have the GroupBy applied. So the total should calculate just fine. But please be careful - sometimes when you use GroupBy, the result of the query is NOT a collection of models. If it's not an Eloquent Collection, Backpack can't display it in table form. 

**If you need to change something in that method just create a ```search()``` method inside your EntityCrudController - you can do whatever you want in it and Backpack will use your method for searching, not the one in the package.**

But I don't think your solution is feasible. By calling ```get()``` before ```count()``` you're basically using:
- ```get()``` to get all entries from the db, as a collection
- ```count()``` to count _that collection_. It will NOT use SQL count. It will count the collection, after it has gotten all entries. It works for a few dozen/hundred items. But when there are millions of entries, the page would load in minutes. 

So not a good solution to call ```count()``` after ```get()```, I think.

Hope it helps.
Cheers!
