### ISSUE TITLE
Date Range does not support fake fields.

### ISSUE THREAD

**Issue by Addgod** [Laravel-Backpack/CRUD#1530]
# Bug report

### What I did:
I tried to store a date range in the extras field. But it does not persist.

### What I've already tried to fix it:
This is due to the compactFakeFields function expects the $field['name'] to be part of the request. But the daterange saves into two seperate fields. But this is not checked for in the function.

I tried to overload the attributes on the model, but they are later overwritten when the extras attribute is set.

### Backpack, Laravel, PHP, DB version:
Laravel 5.6 and Backpack CRUD 3.4.13

**Comment by tabacitu** [comment]
Hi @Addgod ,

Hmmm… I guess you’re right - the ```date_range``` field type was created specifically to store the ```start_date``` and ```end_date``` in separate columns in the db, I didn’t think of this use case at the time…

I guess the only thing that _can_ be done is to create a custom field type starting from ```date_range```, that saves the information inside one input, as JSON, instead of two inputs. If that hidden field where the JSON is stored has the same name as the one used in addField(), Backpack will then pick it up even if it’s a fake field. 

This means:
- creating a new file inside ```resources/views/vendor/backpack/crud/fields/date_range_json.blade.php```;
- using this ```date_range_json``` field type instead of ```date_range```;
- modifying ```date_range_json.blade.php``` to store the value inside one hidden input; AND to take the value from that one input (of course);

Sorry to be so late to reply on this - must have fallen through the cracks.
Replied in case it helps somebody in the future…

Cheers!
