### ISSUE TITLE
Filters not working properly

### ISSUE THREAD

**Issue by Evanslooten** [Laravel-Backpack/CRUD#1531]
I am having an issue with filters. I added the following simple filter to my CRUD in setup() but don't see any output in the log. 
`$this->crud->addFilter(
            [
                'name' => 'test',
                'type' => 'simple',
                'label' => 'Test'
            ],
            false,
            function() {
                \Illuminate\Support\Facades\Log::debug("Filter Applied");
            }
        );`

I have also added a line to log when the crud is loaded, to ensure my logging works properly.
`\Illuminate\Support\Facades\Log::debug("CRUD LOADED", ['Filters' => $this->crud->filters()]);`

No filters are shown as applied when clicking the simple filter button.

` [2018-07-10 13:24:39] CRUD LOADED {"Filters":[]}`

crud ^3.4
base ^0.9.0
Laravel ^5.6.0

**Comment by tabacitu** [comment]
Hi @Evanslooten ,

Just copy-pasted your code - worked fine for me, it wrote in the log file. Maybe you have your .ENV  file configured so DEBUG won't be logged?

Hope it helps.
Cheers!

**Comment by Evanslooten** [comment]
The debug log information from when the CRUD first loads is in the log, but nothing from when the filter is activated. Any suggestions on where to look first?

**Comment by Evanslooten** [comment]
I'm trying to do some additional debugging to get to the root of this, here is what I have so far. Any assistance based on this information would be appreciated! 

I added debug log entries at several points in backpack/crud/src/PanelTraits/Filters.php 
The one of particular note is debugging the output of $this->doingListOperation. The IF (below) is never triggered because the return is always false, so the filter logic would seemingly never be applied.

Why would this be false when listing CRUD entries? Am I misunderstanding the code?

`// if a closure was passed as "filter_logic"
        if ($this->doingListOperation()) {
            if ($this->request->has($options['name'])) {
                if (is_callable($filter_logic)) {
                    // apply it
                    $filter_logic($this->request->input($options['name']));
                } else {
                    $this->addDefaultFilterLogic($filter->name, $filter_logic);
                }
            } else {
                //if the filter is not active, but fallback logic was supplied
                if (is_callable($fallback_logic)) {
                    // apply the fallback logic
                    $fallback_logic();
                }
            }
        }`

**Comment by tabacitu** [comment]
The results are not loaded on page load, with GET. They're loaded with AJAX by DataTables, using the POST method. That POST request goes to the search() method. But all CRUD requests pass through ```setup()```. But I recommend you take a closer look at your controller rather than the insides of Backpack - since it seems to be a problem only in your project. 

What does your setup() look like? In your ```setup()```, what does ```dd($this->request()->input()->all());``` output? You should be able to load the page fine, then add the dd() above to your setup() and when trying to filter you should be able to see the response in your Developer Tools, under Networking. If you strip the request of its parameters or the filter name doesn't match with input name, that's your problem.

Hope it helps.
