### ISSUE TITLE
Cannot view Date Range Reports

### ISSUE THREAD

**Issue by msjakas** [Laravel-Backpack/CRUD#1532]
CANNOT VIEW A REPORT WITHIN A SPECIFIC DATE RANGE. THE OPTION TO SET RANGE OF DATES DOES NOT APPEAR ACTIVE TO ME.

**Comment by tabacitu** [comment]
Hi @msjakas ,

Sorry, I have no idea what you're talking about. There is no "report" in Backpack. 

I suspect your problem is with an admin panel built _by a web developer_, with Backpack. Not a Backpack issue. **If you're a user of an admin panel created with Backpack for Laravel, please contact your web developer.**

Cheers!
