### ISSUE TITLE
[Bug] Select/Select2 Multiple cannot update a hasManyThrough relationship.

### ISSUE THREAD

**Issue by juniorgarcia** [Laravel-Backpack/CRUD#1545]
# Bug report

### What I did:
Tried to use a `select2_multiple` field type to update a relationship who comes from a `hasManyThrough` relationship.

### What I expected to happen:
The pivot table should be synced with the information sent.

### What happened:
I've got the error `Method Illuminate\Database\Query\Builder::sync does not exist.`

### What I've already tried to fix it:
Nothing, since it seems that this field type try to sync a direct relationship, not a query builder type.

### Backpack, Laravel, PHP, DB version:
- backpack/crud: 3.4.23
- laravel/framework: v5.6.27
- PHP 7.2.5
- MySQL 5.7.22

### Example of code
```
// UserCrudController.php

$this->crud->addcolumn([
  'label'     => 'Subsidiary',
  'type'      => 'select2_multiple',
  'name'      => 'subsidiaryCities',
  'entity'    => 'subsidiaryCities',
  'attribute' => 'subsidiaryNameWithCityName',
  'model'     => 'App\SubsidiaryCity',
]);

// App/Models/User.php
public function subsidiaryCities()
{
    return $this->hasManyThrough(SubsidiaryCity::class,
        SubsidiaryCityUser::class, 'subsidiarycity_id', 'id', 'id',
        'user_id');
}
```

The query works properly, but I can't sync.

**Comment by promatik** [comment]
Hi @juniorgarcia!
Can you please give us more information about your models?

I'm asking you this because I don't believe `hasManyThrough` relations should have a field and be "edited".

I'll give the example on [Laravel Docs](https://laravel.com/docs/8.x/eloquent-relationships#has-many-through) regarding `hasManyThrough` relations.

```
countries
    id - integer
    name - string

users
    id - integer
    country_id - integer
    name - string

posts
    id - integer
    user_id - integer
    title - string
```

A user `belongsTo` a country, and a user `hasMany` posts, so;
- a `country` **has many** `posts` **through** `users`.
- a `post` **has one** `country` **through** the `user`.

To include a field type `hasManyThrough` the idea would be to have it on a `country` Model? And remove or add `posts`?
Or have it on a `post`, and add or remove `countries`? It would be impossible because a post belongs to a `user`, a country can't remove the posts of their users 🤷‍♂️

@tabacitu and @pxpm what do you think about this? Am I missing any use case?

**Comment by juniorgarcia** [comment]
Hello, how are you? Well, unfortunately I'm no longer part of the project which I found this issue, hence, I have no more access to the source code nor remember about the details.

I'm sorry for that.

**Comment by tabacitu** [comment]
Thanks for the update @juniorgarcia ! It's been more than 2 years so that's understandable 🤣 😞 sorry about that.

@promatik after our meeting yesterday I think I agree with you. I don't see any use case where an admin should be able to create/edit a `hasOneThrough`/`hasManyThrough` relationship. Because that'd basically mean editing the intermediary entry. Which is OK when it's just a pivot table, but in this case, it's NOT a just pivot table, it's a real entry with meaning outside the `hasOneThrough`/`hasManyThrough` relationship - so editing it might have unintended consequences.

To rephrase, I've used `hasOneThrought` & `hasManyThrough` relationships myself, and I find them useful. But I think they're more meant to be used when READING, not CREATING or UPDATING entries... at least that's how I see it.

@pxpm you're the relationship expert here, what do you think? Do you see any use case where we should be supporting `hasOneThrought` / `hasManyThrough`? Both from the admin perspective and from the developer perspective?

**Comment by promatik** [comment]
@pxpm reminding you on this 🙌

**Comment by tabacitu** [comment]
Bump @pxpm - if you agree with @promatik and I, let's close this issue please.

**Comment by pxpm** [comment]
I will be the one giving it the last hammer!

I do agree with @promatik . 

I was trying (and tried before, this is not the first time I look at this issue), to make sense from what @juniorgarcia tried to do, from what it seems at the time, the user can have many subsidiaries and it seems it would be suitable for a belongsToMany relation, and if you need a pivot model (SubcidiaryCityUser) you should be totally fine with that and not with this relation. 

That said, I don't think this relations should be editable, otherwise the changes would be made at intermediary tables.
