### ISSUE TITLE
Relationships without fillable

### ISSUE THREAD

**Issue by mgralikowski** [Laravel-Backpack/CRUD#1568]
# Bug report

Let's assume simply field with 1:1 relation.

        $this->crud->addField([
            'name' => 'type_id',
            'label' => 'Type',
            'type' => 'select',
            'entity' => 'Type',
            'attribute' => 'name',
            'model' => "App\Models\Type"
        ]);

### What I did:

Add new row to db.

### What I expected to happen:

See in db row with data and type_id  

### What happened:

> General error: 1364 Field 'type_id' doesn't have a default value

### What I've already tried to fix it:

Make fillable type_id but is ugly hack for me. In my opinion timestamps, ids and foreign keys should not be in fillable array. 

Second option is make type_id nullable, then type_id will be set after insert but it impacts on column structure. I don't want to set nullable for columns which shouldn't to be.

Third option is global Model::unguard() - still ugly.

Solution: Associates methods should be placed before save() method.

### Backpack, Laravel, PHP, DB version:

All newest.

**Comment by tabacitu** [comment]
Hi @mgralikowski ,

I'm afraid I don't agree with you here. **I don't see any real why IDs should not be fillable**. Fillable is used to define what can be mass assigned. What columns it's ok for the user to define. Timestamps, of course, are not OK. Wouldn't let someone change created_at or updated_at in a form. But **IDs are in forms, you have selects for them. They're fillable in practice, so they should be fillable in code**.

You can find workarounds for this - you can use the store() and update() methods to save this value manually, after the regular saving has been done. But I don't recommend this - I recommend making them fillable. Just my opinion.

Cheers!

**Comment by mgralikowski** [comment]
I don't agree. Mass assigned is only for simply attributes. If you put there foreign keys then you are put your system on the risk. For example - users are able to edit theirs profiles - simply crud, form with inputs like name, surname. Users table has foreign column like institution_id used to connect user with parent object. Now, i can edit form by browser console and add hidden column "institution_id" with any value. I don't have validation for non existing inputs in my form so...

**Comment by tabacitu** [comment]
@mgralikowski in my opinion that's a problem for the "edit profile" logic, which is user-facing and should have stricter security. Not a problem for the create/update in a CRUD panel. For example, in the "edit profile" screen in Backpack\Base we treat this problem at the validation layer (the FormRequest):

```php
class AccountInfoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        // only allow updates if the user is logged in
        return backpack_auth()->check();
    }

    /**
     * Restrict the fields that the user can change.
     *
     * @return array
     */
    protected function validationData()
    {
        return $this->only(backpack_authentication_column(), 'name');
    }
```

You can see that only the name and email/username columns are passed to the actual controller. No institution_id, id, created_at or anything like that that might also be in the users table. I think that's a good place for this logic, because _it really is_ part of validation - we're making sure if the user has added extra inputs, we ignore them.

If you're giving access to the admin panel to regular users, who might try to hack it, I recommend:
1) don't :-) the admin panel should be for admins;
2) make sure all fields that you want the user to be able to edit are also in the FormRequest; then you can use $request->validated(), either in the save/update method, or in the FormRequest as ```validationData()``` (the example above);

I'm not saying I'll never consider separate saving for relationships, if it turns out it's bad practice to have ids in fillable. I'm saying it doesn't seem like good practice _now_.

**Comment by mgralikowski** [comment]
Of course, admin area is for admins so unguard model is ok for me but still i could fell to be more pro, if can i achieve connecting Models without this hack ;)

Fillable array you can set once and globally for a model. It's more simply than settings validationData in every Request. And it works only with request, sometimes you don't have use them. In Laravel documentation there is no such recommendation to use validationData, while about fillable there is.

Another example:

- edit profile (name, surname. gender)
- edit photo (photo_url)

All 4 fields are in fillable list. Go to edit photo subpage. We only validate photo_url as required and is url and is this guy try add hidden input with his name - i have no problem with this ;) It's still his name and i don't care how and where he can update it ;) It's what why Mass Assignment was created.

**Comment by tabacitu** [comment]
I'm sorry, I guess we just have to agree to disagree here :-) In my opinion, that's not what mass assignment was created for. I could totally change my opinion if others support your proposal, but right now I think we shouldn't do this... Sorry.
