### ISSUE TITLE
Elfinder known vulnerabilities

### ISSUE THREAD

**Issue by ellannon** [Laravel-Backpack/CRUD#1569]
# Bug report

### What I did:
We installed backpack CRUD with elfinder and paid the Unlimited Commercial Projects License

### What I expected to happen:
We expected elfinder functionality with no security risks

### What happened:
A website we are developing with backpack and the elfinder included in has been hacked twice via known elfinder vulnerabilities. There are many exploits easy to find about that. Essentialy the exploits can reach out the uploads folder via elfinder post urls and install root kits. The elfinder creators recommends to have the package always updated to the last version because of that.

### What I've already tried to fix it:
We had to remove all elfinder package entries in the project.

### Backpack, Laravel, PHP, DB version:
Backpack 3.3, Laravel 5.4, PHP 7.1, MySql 5.6

**Comment by tabacitu** [comment]
Whooow. **@ellannon can you please email me at hello@tabacitu.ro with the vulnerability used to hack your projects?**

I have a bunch of apps with Elfinder myself, and even paid security experts to test them - they found some stuff you can to Elfinder, but since Elfinder is only shown to the admin, the security risk was always considered low. We never ever recommended using Elfinder for end-users, or making Elfinder available outside the Auth / Admin middleware - I expect that was your issue?

Thanks a lot for bringing this up.

Cheers!

**Comment by ellannon** [comment]
Hello @tabacitu, thanks for your answer.

We keep elfinder inside the Auth/Admin middleware. In fact, in the hacked project, we have elfinder as default inside backpack because we are not using it, and, of course is not available to the end-user.

About the vulnerability, we just know they were using some exploit software that allow the hacker to upload phtml files in the uploads directory and then turn it into php files so they can execute that file to generate a root kit. But we could not reproduce this attack on ourselfs.
For us, the solution was remove elfinder from vendor directory because the project was already published. Sorry for not being more useful about that.

I also would say that elfinder author recommends to not have older versions of the plugin, and google is filled up with bunch of exploits to attack elfinder known vulnerabilities. Maybe it should not be into backpack, or, at least it should be "disableable" or be just an option as the optional modules (LangFileManager, PageManager, etc.)

**Comment by tabacitu** [comment]
Sorry to hear you've had this kind of issue - never pleasant. I agree with making elFinder optional, it has been so for a few months now - ever since we made an installer for Backpack\CRUD: at installation time it asks you if you want it. If not, it doesn't require it in composer. Most projects don't need it, in my opinion.

I've studied the issue quite a bit in the past few hours and:
- it looks like [there has been just one major security issue](https://snyk.io/vuln/composer:studio-42%2Felfinder)
- [it's been properly fixed in March 2018](https://github.com/Studio-42/elFinder/blob/2.1/Changelog#L70-L90)
- the hack does not seem to be possible under the last 2 version, where I tested it
- the hack is only possible if the attacker is NOT stopped at the middleware level (authentication)

This means:
- we should all run ```composer update``` to make sure we don't run version 2.1.36 and 2.1.37; I'll ask everyone to do so with the Backpack newsletter, thank you for letting us know;
- we should NOT be scared of using elFinder in the future;
- only websites where the attacker has had access to the elFinder interface have been vulnerable, so (I hope) very few;

For you specific use case, I recommend you investigate how the attacker has gained access to the admin interface - you might still be vulnerable. Maybe not file system, but data integrity. **Are you sure you don't have a silly password for an admin, or the default admin user, or the registration open in production?**

Cheers!

**Comment by tabacitu** [comment]
PS. Make sure you've changed your SSH key - [it might have already been compromised](https://snyk.io/vuln/SNYK-PHP-STUDIO42ELFINDER-72129).

**Comment by ellannon** [comment]
Hello @tabacitu 

When we investigated this hack we observed that the hacker was always entering via uploads folder and in the server logs we saw bunch of requests to elfinder urls but we don't know how they could bypass the authentication because when we tried to reproduce the attack on ourselfs we could not.

Said so, we discarded that the hacker had access to the admin or even the filesystem because, if so, he would have made a lot of more damage and, at the moment we removed elfinder, the attacks stopped.

Thanks for your answers, I will let you know if we find something else about that

**Comment by tabacitu** [comment]
Totally understand. To debug what the issue was for you, do you have any way of checking how your ```config/elfinder.php``` file looked like? Maybe in git or something?

I'm interested in this bit, if it was different in your file:
```php
    /*
    |--------------------------------------------------------------------------
    | Routes group config
    |--------------------------------------------------------------------------
    |
    | The default group settings for the elFinder routes.
    |
    */

    'route' => [
        'prefix'     => config('backpack.base.route_prefix', 'admin').'/elfinder',
        'middleware' => ['web', config('backpack.base.middleware_key', 'admin')], //Set to null to disable middleware filter
    ],
``` 

Maybe the ```admin``` middleware wasn't specified there...?

**Comment by ellannon** [comment]
Hello @tabacitu,

Thanks for your interest,

In the config/elfinder.php we have this (I think is the default):

`'route' => [
        'prefix'     => config('backpack.base.route_prefix').'/elfinder',
        'middleware' => ['web', 'admin'], //Set to null to disable middleware filter
    ],`

**Comment by tabacitu** [comment]
Huh... that looks fine. Thank you @ellannon . I'm afraid this is as far as we can go to track down what happened, with the current information available.

I'm going to close this, since this months' newsletter is already typed out and mentions this. But I'll keep an eye on it, and think about what we can do more to find out.

Thanks for bringing this up @ellannon !
Cheers!

**Comment by kkpriscila** [comment]
@tabacitu , Any news on that?

**Comment by tabacitu** [comment]
@kkpriscila we weren't able to reproduce the vulnerability if elFinder was behind the ```auth``` 
 or ```admin``` middleware -- which of course it always should. We told everyone using the newsletter to upgrade to get the elFinder bugfix - that's why I closed the issue, we consider that we've done all we can, and people will be protected once they do a ```composer update```.

**Comment by froid24** [comment]
Hello!

What's the correct way to upgrade elfinder? Will this do the trick?
composer update studio-42/elfinder

I now have elfinder 2.1.46 running on laravel 5.7, and I saw the following warning on https://github.com/Studio-42/elFinder :

![image](https://user-images.githubusercontent.com/26799334/57643163-c540b180-75c1-11e9-9dde-e05b6612a6d2.png)

Thanks!

**Comment by tabacitu** [comment]
Hi @froid24 ,

Yes, ```composer update``` should pull the latest one for you. Thanks for letting us know about this, I'll email everybody and recommend they do a ```composer update```.

Cheers!

**Comment by tabacitu** [comment]
PS. Keep in mind that in Backpack, **elFinder is only available to admin**, after they login. So _even if_ the elFinder bug is major, it can only be exploited by admins. Since we tend to trust admins not to be malicious, the bug will probably not be exploited in Backpack projects, unless an admin's credentials are stolen. In which case the attacker had access to upload/download files from the server anyway.

That being said, OF COURSE you should update to the latest elFinder. Please do :-)

**Comment by froid24** [comment]
I run the following command, updating elfinder from 2.1.46 to 2.1.49:

composer update studio-42/elfinder

But when I go using elfinder, I see that the reported version is still 2.1.46. Am I missing something? That's why I asked if that was enough...

![image](https://user-images.githubusercontent.com/26799334/57716400-9722a680-7681-11e9-9195-ff7e4ddb9cc5.png)

**Comment by tabacitu** [comment]
Ha! Romanian! Also, did NOT know my name shows up there for the translation - nice :-)

That's weird @froid24 , the update worked well for me on an L5.8 instance. **After the update, did you re-publish the assets? ```php artisan elfinder:publish```**

![Screenshot 2019-05-16 at 11 28 30](https://user-images.githubusercontent.com/1032474/57838666-d4944a80-77cd-11e9-9cd4-16b312b1b962.jpg)

**Comment by froid24** [comment]
I have run:

composer update studio-42/elfinder
composer require barryvdh/laravel-elfinder
php artisan elfinder:publish

Also cleared cache/views. No change, still reporting 2.1.46 in that dialog...
Any ideas?

Thanks!

**Comment by tabacitu** [comment]
Hmm... and are you sure the package gets updated? If you go to ```vendor/studio-42/elfinder/Changelog``` is the 2.1.49 version the first on mentioned?

If not, it might be that another requirement (maybe you're using an old Laravel version) prevents elfinder from getting to the latest version.

**Comment by tabacitu** [comment]
Also, your JS might be cached by the browser. Try Ctrl+Shift+R  / Cmd+Shift+R to make sure the browser doesn't use old files.

**Comment by froid24** [comment]
Darn, it was the cache (even though I think I cleared everything locally). Thanks so much!
