### ISSUE TITLE
[Bug] datetime field breaks when using $dates/$dateFormat/$casts

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/CRUD#158]
If you set a a crud field using `datetime` and the database column type `datetime` similarly to

```php
$this->crud->addField([
    'name' => 'date',
    'label' => 'Date',
    'type' => 'datetime'
]);
```

then you try define the date column within your model such as

```php
protected $dates = ['date'];
protected $casts = ['date' => 'date'];
```
As the browser submits the data in an ATOM/ISO8601 style e.g. `2016-01-01T12:00:00`

It then errors around `at Carbon::createFromFormat('Y-m-d H:i:s', '1991-03-28T12:00')` as its expecting `Y-m-d H:i:s` but is getting `Y-M-d\TH:i`

To get rid of the error you must remove the date casting from the model

**Comment by tabacitu** [comment]
Pfff... this is awful... Damn it. Honestly, I've kept trying to find a solution, but the only one that works so far is creating a mutator on the model:
```php
	public function setDatetimeAttribute($value) {
		$this->attributes['datetime'] = \Date::parse($value);
	}
```

We **could** put a notice inside the ```datetetime``` field documentation saying _"If you use datetime attribute casting, you'll need to also set this mutator"_ but... I don't really like it...

Any other ideas?

**Comment by OwenMelbz** [comment]
This is the only one I had, but hopefuly the date-picker CFT (custom field type, I'm going acronym style) will replace it anyway?

**Comment by tabacitu** [comment]
Ok then, I added that in the documentation. I hope we'll figure out a better solution in time and come back to this.

Hmm... I don't know... I don't think the ```datetime-picker``` CFT needs to replace ```datetime```. We could keep both. The picker does provide a way better UX on desktop, but the native one provides a better one on mobile (loads the mobile OS's datepicker). So I think it's better to let the developer choose between them, no harm in that. Right?

P.S. I'll go ahead and close this issue since we do have a solution for the bug and it's implemented in the docs. You can still comment, obviously.
