### ISSUE TITLE
[4.1][Package / Custom Field] Feature improvement: table field actually posting an array

### ISSUE THREAD

**Issue by hvdklauw** [Laravel-Backpack/CRUD#1582]
I was playing around and needed the exact functionality of the table field.
But when adding validation I discovered that the data being posted was a string, and not an array.
which makes validating the json a whole lot harder then it needs to be.

Looking at the code I see angular doing a whole lot of work to serialize the data into a single hidden field while the actual fields are right there in the html.

before:
```html
<input class="form-control input-sm" type="text" ng-model="item.{{ $prop }}">
```

after:
```html
<input class="form-control input-sm" type="text" name="{{ $field['name'] }}[<% $index %>][{{ $prop }}]" ng-model="item.{{ $prop }}">
```
This makes the whole thing post as an array, allowing for server side validation without too much trouble. (You do have to specify the $casts variable on the model to actually store it correcly).

So with a field definition of:
```php
[
    'name' => 'languages',
    'label' => trans('admin.customer.columns.languages'),
    'type' => 'custom-table',
    'entity_singular' => 'language',
    'columns' => [
        'code' => 'Locale',
        'name' => 'Name',
    ],
    'min' => 1,
],
```

and validation of:
```php
'languages' => ['array', 'min:1'],
'languages.*.code' => ['required', 'string'],
'languages.*.name' => ['required', 'string'],
```

Now I get that I can make a pull request for this, but before I do all that I think we should discuss if it should be changed or if it should be a new field type.

[Here](https://gist.github.com/hvdklauw/26f07d75c0a2d008d831c082c1a4055a) is a gist with the whole custom field, but all that I changed is shown above and I removed the other field plus the bit of logic to fill it.

What would be left to do:
- [ ] Documentation
- [ ] Tests?
- [ ] Maybe figure out a way to move the errors to the actual fields.

**Comment by tabacitu** [comment]
Hi @hvdklauw ,

Sorry for taking so long to get to this - some things have fallen through the cracks. I'm surprised nobody else has pitched in yet. Great work on this, thank you for taking the time to create an alternative, write about it and share it here. Really appreciate it.

I don't think we can merge this as-is, because it would be a breaking change for everybody who was using the ```table``` field type, with little benefit (since their validation is most likely already customized for receiving a string).

But I think it's a good candidate for a custom package, once Backpack 4.0 is out. We plan to make it REALLY easy to:
- create a package from a skeleton
- drop you custom field
- change a few lines the documentation
- register this field on backpackforlaravel.com so others can use it

I'll leave this issue open, and come back to you once we have the process ready for creating custom packages.

Thanks again - and sorry for the late reply.
Cheers!

**Comment by tabacitu** [comment]
Hi @hvdklauw ,

I see this hasn't gotten any traction since 2018-2019 - so it looks like not a lot of people are bothered that the result of the `table` field is a JSON instead of an array. For that reason, I'm going to close the issue. Of course, I'm open to re-opening it,  if anybody else stumbles upon this and think it's a good idea to do this in the Backpack core.

Please note that in the meantime:
- the `table` field type has been rewritten from angular to jQuery;
- we've created [a tutorial for people to create add-ons](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial); it should be pretty easy to create an add-on with a table field type that posts an array;

Thanks for opening this nonetheless @hvdklauw - from a certain point on, a software project can only become better if users like you push forward with proposals and changes. So it's much appreciated!
 
Cheers!
