### ISSUE TITLE
You should have show permissions by default or delete the preview button

### ISSUE THREAD

**Issue by linqiuyu** [Laravel-Backpack/CRUD#1583]
Add $this->crud->allowAccess('show') to each controller is annoying,Especially when adding other synergic capabilities to your site.

**Comment by tabacitu** [comment]
Hi @linqiuyu , 

I agree. ```show``` will be enabled by default on the next version bump (3.5), since we can't enable it with a non-breaking change. It's a relatively small change, and most developers will want it, but we can't _force_ people to have it. It has to be mentioned in an upgrade guide, and released as a breaking change.

We time our breaking changes with Laravel upgrades, so that you upgrade both in one go. So our next breaking change upgrade will probably be in 1-2 months, when Laravel releases 5.7.

Cheers!

PS. If you find yourself doing more stuff in all your CrudControllers, I recommend you create a trait, and use that trait on all your CrudControllers.
