### ISSUE TITLE
SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute

### ISSUE THREAD

**Issue by enniosousa** [Laravel-Backpack/CRUD#1597]
# Bug report
Using SQL Server drive on CentOS 7 (prodution environment) shows me this error `PDO::getAttribute(): SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute`.

### What I did:
Use de field select in crud controller

### What I expected to happen:
No bugs :)

### What happened:
`PDO::getAttribute(): SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute`

### What I've already tried to fix it:
Yeah! I found a improvised solution. For some reason `CrudTrait::isColumnNullable()` is the source of problem. The SQL Server drive version that I use doesn't support it. You can see this [code here](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/code-structure/master/operation/Backpack%5CCRUD%5CCrudTrait%3A%3AisColumnNullable)
So in `resources/views/vendor/backpack/crud/fields/select.blade.php` I remove the snippet code following:
```
@if ($entity_model::isColumnNullable($field['name']))
     <option value="">-</option>
@endif
```

About this issue, you can know more about [here](https://github.com/Microsoft/msphpsql/issues/733)

### Backpack, Laravel, PHP, DB version:
Laravel: 5.5.42
PHP: 7.0.27
backpack/base: ^0.7.16,
backpack/crud: ^3.2,
```
[user@localhost maqui]$ yum info msodbcsql
Loaded plugins: fastestmirror, replace
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Loading mirror speeds from cached hostfile
 * base: linorg.usp.br
 * epel: mirror.globo.com
 * extras: centos.xpg.com.br
 * updates: linorg.usp.br
 * webtatic: us-east.repo.webtatic.com
Installed Packages
Name        : msodbcsql
Arch        : x86_64
Version     : 13.1.9.2
Release     : 1
Size        : 16 M
Repo        : installed
From repo   : packages-microsoft-com-prod
Summary     : ODBC Driver for Microsoft(R) SQL Server(R)
License     : https://aka.ms/odbc131eula
Description : This package provides an ODBC driver that can connect to Microsoft(R) SQL Server(R).
```

**Comment by tabacitu** [comment]
Hi @enniosousa ,

Thank you for the bug report and sorry for the late reply. I'm afraid I still don't have a solution for this. ```isColumnNullable()``` provides a great functionality for other DMBS (mysql, posgre, sqlite), it's unfortunate that SQL Server does not support this, but since nobody else has commented on this, it seems SQL Server usage on Backpack (just like it is on Laravel) is very _very_ low.

Since SQL Server isn't explicitly supported by Backpack, I don't think we should provide a solution for this in the package - removing that line also removes the feature for other DBMS.

Sorry the solution isn't pleasant - but you do have to live with  ```select2``` overwritten, looks like. Out of curiosity - did you encounter any other issues with using Backpack with SQL Server? 

If there aren't many problems (as I'd expect), we _could_ start providing support for SQL Server, and fix this issue and the others. Not 100% sure it's a good idea, but we _could_ do that. If so, let me know what other issues you've countered - would help us a lot.

Thanks again for reporting this - it helps. Sorry for not providing a fix in the core code.
Cheers!
