### ISSUE TITLE
hierarchical select field : order and hierarchy in select entries

### ISSUE THREAD

**Issue by breizhwave** [Laravel-Backpack/CRUD#1610]
I have a product table that has n to 1 relation ship (extract from product model below) to a category that's reorderable : I use the select field and it works fine for the  edit operation, but is it possible to display the category by order and displaying the hierarchy  ? in my case I jsut get a simple select ordered by default ? thanks

    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id', 'id');
    }

in categry crud controller : 

  $this->crud->enableReorder('name', 10);
        // NOTE: you also need to do allow access to the right users: 
        $this->crud->allowAccess('reorder');

**Comment by breizhwave** [comment]
And here's the answer : thanks to @samsebastian ([issue 502](https://github.com/Laravel-Backpack/CRUD/issues/502#issue-210219755)) for raising the issue somewhere around 2 years ago, I'm suprised I could not find any other mention of that one : here's a piece of code that will display hierarchical structure in the select2 field , sample code for newscrud article controller : 

https://gist.github.com/breizhwave/512adcda4354d6a63d6b1596ea360cae

**Comment by tabacitu** [comment]
Thank you for sharing your solution @breizhwave ! **Hmm... maybe we should consider including your ```select2_grouped``` as a default field, in Backpack?** Anybody else - what do you think?

In the meantime, I would love it if you wrote a short article on your blog (or backpack's about this), providing the example too. Would love to mention it in our monthly newsletter too - sounds like a solution many would enjoy, even if we don't include it as a default field. What do you think?

**Comment by breizhwave** [comment]
Well @tabacitu this is great news, glad you consider it useful because for me I could not do without hierarchical structures. I'll write that blog entry for sure , when is your newsletter due ? you'd mind if I include a quick word about nova and how backpack still competes so well  (mainly -in my opinion- because of the answer you just made ... finally :) first one wins, I sent the same question to our friend Otwell :)

**Comment by breizhwave** [comment]
OK @tabacitu here's my post if you want to have a look at this wonderful piece of analysis

[http://www.webmasterbulletin.net/2018/10/backpack-nested-field/2446](http://www.webmasterbulletin.net/2018/10/backpack-nested-field/2446)

**Comment by tabacitu** [comment]
Hi @breizhwave ,

Great article - I’ll be sure to promote it in November's newsletter. Of course it’s ok to mention Nova :-)

I did not end up sending one in October, because there wasn’t anything BIG to say. I like to send as few newsletters as possible - I personally hate when projects bombard me with news about them, I wouldn’t want Backpack to become the same.

Thanks again.
Cheers!

**Comment by tabacitu** [comment]
@breizhwave , on second thought, I think this would be a _great_ addition to Backpack. I think it would be _very_ useful for working with things like Categories and other models that use the same ‘lft’, ‘rgt’, ‘depth’ nested set.

I’ve polished and improved the field since it had a few issues (did not work multiple times per form, etc) and will merge it into master as ```select2_nested``` - I think it’s a better name, since this isn’t actually to group options (as the original), but to show a nested model.

Deviation from ```select2```:
![screenshot 2018-11-09 at 15 28 25](https://user-images.githubusercontent.com/1032474/48265047-27163800-e434-11e8-94af-3b74cf8ad282.png)

Screenshot:
![screenshot 2018-11-09 at 15 36 32](https://user-images.githubusercontent.com/1032474/48265516-5e391900-e435-11e8-9b3c-5913d0840215.png)

PR here: https://github.com/Laravel-Backpack/CRUD/pull/1687

Thanks again - very useful, I think!
