### ISSUE TITLE
Overriding search method to make a column searchable seems to remove my action buttons

### ISSUE THREAD

**Issue by scottjs** [Laravel-Backpack/CRUD#1641]
# Bug report

I want to make a column searchable in the CRUD panel but not show it in the list of columns. I found some notes [here](https://github.com/Laravel-Backpack/CRUD/issues/101) that appears to allow me to use `$this->crud->addColumn()` to append additional columns to the search. 

However, when I do this my action buttons seem to get replaced with this custom column and I'm not sure why. 

### What I did:

```
public function search()
{
    $this->crud->addColumn([
        'name' => 'primary_contact_id',
        'label' => 'Primary Contact',
        'type' => 'select',
        'entity' => 'primary',
        'attribute' => 'firstname'
    ]);

    return parent::search();
}
```

### What I expected to happen:

No visible changes to the column view but allows the search field to also search for the primary contact name. 

### What happened:

The action buttons were removed and replaced with my custom column instead.

Before:
<img width="744" alt="screen shot 2018-09-18 at 14 55 03" src="https://user-images.githubusercontent.com/994732/45692942-dda41d80-bb53-11e8-9ed8-60e6531bff6e.png">

After:
<img width="1016" alt="screen shot 2018-09-18 at 14 54 44" src="https://user-images.githubusercontent.com/994732/45692947-e3016800-bb53-11e8-9e3d-f295269e389d.png">

### What I've already tried to fix it:

Overriding the entire search method to see if it's an ordering issue, but I'm not able to work out how this works internally to try other things. 

### Backpack, Laravel, PHP, DB version:

Backpack: 3.4
Laravel: 5.6
PHP: 7.1.20

**Comment by tswonke** [comment]
Yes, same to me.

Just looking for the same: Using the search in a table field that is not declared as a column.

**Comment by jsvini** [comment]
You could add a custom search logic in a column to include other columns in the search, without overriding the search method:


```php
$this->crud->addColumn( [
	'name'        => 'my_field',
	'label'       => 'My visible column',
	'type'        => 'text',
	'searchLogic' => function ( $query, $column, $searchTerm ) {
		$query->orWhere( $column['name'], 'like', '%' . $searchTerm . '%' );
		// add other fields
		$query->orWhere( 'my_hidden_field', 'like', '%' . $searchTerm . '%' );
	}
] );
```

**Comment by tswonke** [comment]
Yeah, this is a very good "quick&dirty" solution :)

**Comment by tabacitu** [comment]
@jsvini that’s a nice hack, thank you :-) I think we should provide an official solution to this, since it’s a pretty common scenario.

## Solution A

The most intuitive solution would probably be to allow developers to add “invisible” columns, that get searched, but aren’t visible in the list view. We could:
- have a “visible” attribute on the columns, which is true by default;
- use ```getVisibleColumns()``` instead of ```getColumns()``` in the list view, but keep using ```getColumns()``` in search;

So it would be as easy as:

```php
$this->crud->addColumn([
   'name' => 'description', // The db column name
   'label' => “Description", // Table column heading
   'visible' => false, // show or hide the column from the list view
]);
```

## Solution B

A solution with less impact on existing features would be to have something like ```addColumnToSearch()```, which would just add it to another property on the $crud, say… ```$additionalSearchColumns```, which would get merged with the other columns in ```applySearchTerm()``` alone. So you’d use it like:

```php
$this->crud->addColumnToSearch([
   'name' => 'description', // The db column name
   'label' => “Description", // Table column heading
]);
```

Maybe a better name would be ```addSearchableAttribute()``` or… I don’t know.

---

What do you guys think? Any better solutions?

**Comment by tswonke** [comment]
IMO we shouldn't use any kind of fake column here. I think this is misleading. It never shows up, or do I miss something? Why do we need "label" for this?

I tend to something like your `addSearchableAttribute()` (or a similar name), but without using our columns array.

Maybe something like this with 3 ways to use:

```php
// simple string
$this->crud->addSearchableAttribute('column_name');

// array of simple strings
$this->crud->addSearchableAttribute(['column_name1', 'column_name2']);

// closure for special searches
$this->crud->addSearchableAttribute(function() {...});
```

**Comment by tabacitu** [comment]
@tswonke you make a good point... It’s not _actually_ a column, it’s just an attribute you make searchable.

**Comment by tabacitu** [comment]
@tswonke , @scottjs @jsvini I've inadvertently [pushed a solution for this](https://github.com/Laravel-Backpack/CRUD/pull/1703) yesterday, in the ```3.5``` release. We now have a ```visibleInTable``` attribute we can set as ```false``` on columns. I don't think this is the perfect solution we were discussing above, but it _is_ a solution. You can now do:
```php
$this->crud->addColumn([
   'name' => 'description',
   'visibleInTable' => false, 
   'visibleInModal' => false,
   'visibleInExport' => false,
]);
```
and it will be searchable, but show up NOWHERE in the list view.

I'll close the issue for now, since we do have a soluton. Let me know if you think it's not a particularly good one, and we'll create a PR to add ```addSearchableAttribute()``` like @tswonke proposed - that was definitely cleaner. And we'll move the conversation there.

Cheers!
