### ISSUE TITLE
Select Field limited by user data

### ISSUE THREAD

**Issue by jasonspick** [Laravel-Backpack/CRUD#1649]
# Bug report

### What I expected to happen:
I want to be able to add where clause to select 2 field for create and update. This is limited by user data. For example, a user can only select locations that belong to the users company. SO I want to add
`->where('company_id','=',Auth::user()->company_id) ` to the end of the field definitions.

### What I've already tried to fix it:
Use global scopes & select 2 ajax.
### Backpack, Laravel, PHP, DB version:

I'm not sure where to look on this. how would I accomplish this? Also for admins this would not be the case. Admins could select all. But that is easily done by if/ else.

**Comment by pxpm** [comment]
In the locations controller you can add a global scope, or a scopedRelation that return the relationship where the conditions are meet, eg. 

In your Location model:
``` 
public function scopedLocation() { return $this->where('company_id', backpack_user()->company_id); }

```

When defining the field, in the **entity**  key, you use the scopedLocation instead of the location relation.

This is pseudo-code, but hope it helps you.

BR,
Pxpm

**Comment by tabacitu** [comment]
Yup, I'm using @pxpm 's solution in a bunch of places and it works great. Thanks for sharing @pxpm .

Cheers!

**Comment by tabacitu** [comment]
PS. If you have _a lot_ of entries (1000+), I recommend using the select2_from_ajax field type instead. Since you define the results, it's a lot more customizable. We're working on ways to make it even easier to use, since it's a bit uncomfortable to create a route for it, but it _is_ a good solution to a lot of select2 customization issues.

**Comment by jasonspick** [comment]
@pxpm I needed a little more granular control than that. So what I ended up doing was making a custom select field that took a eloquent query. Then I did all my work in the model.
