### ISSUE TITLE
[4.0][Request] Make adding the same field / column / filter more DRY

### ISSUE THREAD

**Issue by breizhwave** [Laravel-Backpack/CRUD#1656]
Hello, this is a simple suggestion, hope you'll like it, in the philosophy of good coding, I like not to repeat myself, 

so I created this extra class to help setting fields and filters in the crudcontroller, in the form of  functions  , and more to create if you are inspired go ahead with new helper functions for declaring fields and filters. Basically for select (1 to n) fields, it replaces two calls (column and field) with long arrays to 1 call with a simple variable (model class name), if you have used _id naming convention for relationship key  it does the job automatically, example you can replace this call

`  $this->addBothField(  ['label' => 'Type',
           'type' => 'select',
           'name' => 'type_id',
           'entity' => 'type',
           'attribute' => 'name',
           'model' => "App\Models\Type"]);`

by this simple line :  `        $this->addBothSelectField(["model"=>"Type"], 1);`

same for filter declaration : `        $this->addSelectFilter("type_id","Type","Type");`

simplifies the writing and reading of your crud controller, of course instead of extending crudcontroller you'll now extend WaveCrudController or what ever the name you want to give

https://gist.github.com/breizhwave/b00caffddca41947a1f71f5789006685

**Comment by tabacitu** [comment]
Hi @breizhwave ,

Thanks for sharing your idea [and solution in gist - that's rare :-) and welcome]. 

I think it's a great idea, and there's definitely room for improvement in not repeating ourselves when writing fields / columns / filters. It's something that's been annoying me for a while now, and I think it's about time we find a solution and make it easier. I don't think we will include this in the core as-is, though - I don't think this should be treated with a new API call, but with _existing_ API calls. I think Backpack should be smart enough to know that you want the same kind of column / filter as the field was - that sounds like the intuitive behaviour to me. Not sure we can do that in the current iteration of Backpack, though, since there are a few inconsistencies between field, column and filter names. But in the next one - which is right around the corner, definitely!

The preferred solution: 
**For the next Backpack iteration (v4), most likely you will only need to declare the FIELDS, then Backpack will know what type the column / filter is, so it will intelligently guess it.** So something like this:

```php

$this->crud->addField(['label' => 'Type', 'type' => 'select', 'name' => 'type_id', 'entity' => 'type', 'attribute' => 'name', 'model' => "App\Models\Type"]);

$this->crud->addColumn('type_id'); // guesses that it's a select, because that's what the field is
$this->crud->addFilter('type_id'); // guesses that it's a select, because that's what the field is

```

This will be even easier to implement if we use a configuration object, since loading fields / column / filters would then happen when Backpack wants, not when the developer wants:

```php

class ProductPanelConfiguration extends EmptyCrudConfiguration {

  public $model = App\Models\Product::class;

  // ..

  public function fields() {
     return [
        ['label' => 'Type', 'type' => 'select', 'name' => 'type_id', 'entity' => 'type', 'attribute' => 'name', 'model' => "App\Models\Type"],
        'text',
        'description'
     ];
  }

  public function columns() {
     return ['type', 'text', 'description'];
  }

  public function filters() {
     return ['type'];
  }

}

```

**What do you think about this alternative solution?**

Thanks, cheers!

**Comment by breizhwave** [comment]
I agree with you as long as it is simple like it is now, I would like the   configuration object option, but  it requires creating a new file, which makes two different files for each model, which could be hard to read or maintain when using like 10 models, may be using exsting aPI calls is a great idea but they are not implemented yet are they?

**Comment by flap152** [comment]
Here's what we did in a MyCrudController Class that extends CrudController:


```
public function addColField($commonDef,$fieldDef=[],$colDef=[], $form = 'both')
{
        // re-map some field types from column to types available to columns
        if (isset($commonDef['type'])){
            switch ($commonDef['type']) {
                case 'select2':
                    $colDef['type'] = 'select';
                    break;
                case 'select2_from_array':
                    $colDef['type'] = 'radio';
                    break;
                case 'checkbox':
                    $colDef['type'] = 'check';
                    break;
            }
        }
        $this->crud->addField(array_merge($commonDef,$fieldDef),$form);
        $this->crud->addColumn(array_merge($commonDef,$colDef));
    }
```


- We skip the `->crud` part
- First array is common attributes. Second is field specific. Third is column specific. We merge them in to respective calls
- We map (our) commonly used types to equivalent column type. This is obviously incomplete, but not all fields can becom column, I think.

**Comment by sergeyugai** [comment]
As I've been working on "Backpack Fields as Object" (https://github.com/Laravel-Backpack/CRUD/issues/1351), I decided to address this issue as well.

I came up with an idea to combine fields into field collections and apply common attributes directly on that collection - that way, with one line, attribute is distributed onto all fields inside it.

And its possible to combine all types of fields in collection, making it possible to call, say, ->tab('Primary') to send all of the fields onto 'Primary' tab, regardless of their type.

This is something I'm experimenting with right now.
Here is the repo: https://github.com/sergeyugai/backpack-fields-as-classes
I've written some ideas behind that in the issue mentioned above.

**Comment by tabacitu** [comment]
Hi guys,

I'm afraid it doesn't look like we can/should be doing this in v4. Ever since PR #2000 , configuration for fields & columns will be split inside different configuration blocks (or methods - TLDR example [here](https://github.com/Laravel-Backpack/CRUD/issues/1600#issuecomment-527022719)). So starting with 4.0 you won't actually have access to fields when defining columns (or vice-versa).

You can still do something like what @flap152 suggested [here](https://github.com/Laravel-Backpack/CRUD/issues/1656#issuecomment-461831377), but it wouldn't be Backpack's responsibility, but the developer's. Personally I'd do:
```php
public function setup() 
{
   $commonFieldsAndColumns = ['first_name', 'last_name', 'another one']; 
   // these above can also be arrays, of course, defining other field types like select/table/whatever

   $this->crud->operation(['create', 'update'], function() {
       $this->crud->addFields($commonFieldsAndColumns);
       // add extra fields here
    });

   $this->crud->operation(['list'], function() {
       $this->crud->addColumns($commonFieldsAndColumns);
       // add extra columns here
    });
}
```

Which I think is a good solution for this problem, since it still allows us to have operations (list, create, update) completely separated, and add fields&columns only for the current operation (and this way, make the CrudController load faster, and make the CrudPanel object less bloated).

I'm sorry to say this @breizhwave , but I don't think we're going to push another solution for this in Backpack v4 (apart from my example above which should work fine). I might be wrong on this decision, of course. Please let me know if you think so. If a lot of people think I'm wrong, we'll reopen this and give it another chance.

Cheers!
