### ISSUE TITLE
CKEditor not showing

### ISSUE THREAD

**Issue by jim1506** [Laravel-Backpack/CRUD#1725]
I am using the latest version of Backpack with a new project and am getting somewhere, 
I have a a longtext field for a flag description (details of how the flag was adopted) and have added this to the controller

    $this->crud->addField([   // CKEditor
              'name' => 'flagInfo',
              'label' => 'flag info',
              'type' => 'ckeditor',
              // optional:
              'extra_plugins' => ['oembed', 'widget', 'justify'],
              'options' => [
              'autoGrow_minHeight' => 200,
              'autoGrow_bottomSpace' => 50
                ]
            ]);

But nothing shows on the form as you can see
![25-11-2018 18-27-56](https://user-images.githubusercontent.com/123184/48982879-fe529b80-f0df-11e8-8140-add7e516464b.png)

I also ran 

    php artisan backpack:base:version

but got the following error:

![25-11-2018 18-22-00](https://user-images.githubusercontent.com/123184/48982897-1e825a80-f0e0-11e8-9080-d2036126df65.png)

I have an issue with uploading images which I will make a separate issue. here

**Comment by jim1506** [comment]
I have found that it is something to do with the options (which I cut and pasted from your site). If I change to:

    $this->crud->addField([   // CKEditor
              'name' => 'flagInfo',
              'label' => 'flag info',
              'type' => 'ckeditor',
            ]);

The editor appears.

**Comment by tabacitu** [comment]
Hmmm you're right @jim1506 - the extra_plugin won't work as-is because the "justify" plugin does not exist in the main release - it was an example of how you can add plugins, but you _do_ also need to place the custom plugin folder in ```vendor/backpack/ckeditor/plugins```. 

I've removed the ```justify``` plugin from the docs, to not confuse users https://github.com/Laravel-Backpack/Docs/commit/24032529c45ac3a9faa4a9e3971bfda9bdf3b6d8

Thanks, cheers!
