### ISSUE TITLE
Field type browse_multiple is missing from doc?

### ISSUE THREAD

**Issue by Dakaa** [Laravel-Backpack/CRUD#1738]
# Bug report

**Comment by tabacitu** [comment]
Thank you @Dakaa - you're right, thank you. We haven't yet officially released the browse_multiple field type because it looks like it still has a few quirks. Yes, you can select multiple items, but it doesn't really show them after you click Save.

There's a little more work to be done there, before we can add it to the docs.

Thanks for the heads-up.
Cheers!
