### ISSUE TITLE
Sort data by *_count

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/CRUD#1744]
Hi,

could it be possible to integrate a possibility to sort the data by `xyz_count` column? I couldn't find anything related to this.

**Comment by pxpm** [comment]
Override the search() function of the controller. That function is called when drawing datatables. You can return the ordered results from there ? Can you give it a try? Thanks

**Comment by tabacitu** [comment]
Yes, you should be able to do it as @pxpm recommends. 

I'd add another option: to _create that count column in your database_, and actually calculate and update it when records change. This would deviate from SQL normal form, but for big databases it's the only reasonable way to do it. Otherwise SQL queries could take way too long (order by count).

Hope it helps.
