### ISSUE TITLE
Backpack DatePicker change event not fired on jquery

### ISSUE THREAD

**Issue by msdev20** [Laravel-Backpack/CRUD#1751]
# Bug report
Backpack DatePicker change event not fired on jquery

### What I did:
```
/* $field['parent'] = 'date'; */
$("[name='{{$field['parent']}}']").on('change', function() {
alert('call');
});
```
### What I expected to happen:
alert not fired.
### What happened:
alert call.

### What I've already tried to fix it:
change in date_picker.blade.php on line:114

```
- $field.val(sqlData);
+ $field.val(sqlData).trigger('change');
```

### Backpack, Laravel, PHP, DB version:
Backpack/Crud: 3.4
PHP: 7.2

**Comment by tabacitu** [comment]
Hi @msdev20 ,

I'm sorry to get to this so late. Some issues have slipped through the cracks.

It seems like there have been considerable changes to the ```date_picker``` field since you posted. Can't find the line you mentioned. Let me know if this is still an issue for you, and if so, please give me more details on how this impacts the functionality of the date picker.

Sorry again, and thank you for raising the issue.
Cheers!
