### ISSUE TITLE
Cant add place holder in select2 field.

### ISSUE THREAD

**Issue by jishnu2292** [Laravel-Backpack/CRUD#1800]
Cant add placeholder in select2 field

**Comment by tabacitu** [comment]
That's true. I'm afraid it's a limitation due to how select2 uses placeholders - https://select2.org/placeholders It won't just parse the ```placeholder``` attribute and use it, which is... unintuitive and unexpected. I know.

Since adding support for placeholders would make this column unnecessarily difficult to understand, and it's a column A LOT of people use as example to how to create a new column type, I think it's safer to not have the placeholder feature in this, I'm afraid.

You do have a few workarounds, though:
- use the ```select``` column instead, which has placeholders;
- use the ```hint``` attribute to specify the placeholder;

Sorry I couldn't be of more help.
Cheers!

**Comment by jishnu2292** [comment]
Ok. Thank you.
I Can't use hint  attribute. While adding entry using CRUD, the _first option_ in the select field will be always selected. I dont want the first option selected. Is there any way to add an option at the beginning without having value?

**Comment by tabacitu** [comment]
Yes, your db column should be NULLABLE. Backpack will then pre-select an empty option, by default.

**Comment by ridislam** [comment]
@tabacitu how can i set a text for pre-selected empty option?
