### ISSUE TITLE
How to use fields in custom views?

### ISSUE THREAD

**Issue by arunharidas** [Laravel-Backpack/CRUD#1802]
# Bug report

**Comment by arunharidas** [comment]
How do I show backpack fields in my custom view ?

**Comment by pxpm** [comment]
That's not a bug report, that's a general question, you have better channels to ask for help.

I could give you the answer here, but to make sure next time you know where to ask this kind of questions, i will leave you here the link: [gitter chat](https://gitter.im/BackpackForLaravel/Lobby) :)

**Comment by tabacitu** [comment]
Haha totally. @arunharidas in order to use Backpack fields in your own custom views, take a look of how they're used in Backpack. Go through the "create" view and every view it loads - you'll quickly understand how they're loaded, and be able to do the same in your views.

Do keep in mind you also need the save/update logic for the fields to work, which is inside the Create and Update traits.

Hope it helps. Thanks for pitching in @pxpm .
Cheers!
