### ISSUE TITLE
addColumn(visibleInModal=>false) after addColumn(visibleInTable => false) : Error in modal view.

### ISSUE THREAD

**Issue by DonDiegoAA** [Laravel-Backpack/CRUD#1824]
# Bug report

### What I did:
I used  'visibleInTable' => false in a column, and 'visibleInModal' => false in the next column

```
$this->crud->addColumn(['name' => 'iban_number', 'type' => 'text', 'label' => 'IBAN', 'priority' => 5, 'visibleInTable' => false]);

$this->crud->addColumn(['name' => 'phone', 'type' => 'text', 'label' => 'Téléphone', 'priority' => 3, 'visibleInModal' => false]);
```

### What I expected to happen:
First column **iban_number** hidden in list view but displayed in modal view,
second column **phone** displayed in list view but hidden in modal view.

### What happened:
List view is correct, iban_number is hidden and phone is displayed, but modal view is incorrect, iban_number is still hidden and phone still displayed.

![list_is_ok](https://user-images.githubusercontent.com/6011568/53039069-8d244980-347e-11e9-8755-e3f8187a8260.png)

![modal_error](https://user-images.githubusercontent.com/6011568/53039073-90b7d080-347e-11e9-95fa-593264dd6835.png)

### What I've already tried to fix it:
Clean all laravel cache, apply the same logic to another model, same result, search in backpack source code, set the 4 Visible options to the columns, composer update, ...

Note that 'visibleInModal' => false is working as expected if no visibleInTable=>false is present in previous column.

### Backpack, Laravel, PHP, DB version:
BackPack 3.5
Laravel 5.7.24 and 5.7.27
Php 7.1.7
MySQL 5.7.19

**Comment by selvinkuik** [comment]
I've also encountered this issue in my project and would like to see a fix.

**Comment by tabacitu** [comment]
Hi @DonDiegoAA & @selvinkuik ,

Thanks for reporting the issue, and following up on it. It looks like the issue is not the second column being hidden by the first one. But the first column (iban) does not get shown in the modal if it's hidden in the table.

So for a certain column, it's like ```visibleInTable = false``` also forces ```visibleInModal = false```. That was not intentional, it's a bug that I just fixed here - https://github.com/Laravel-Backpack/CRUD/pull/1880

I will merge and tag this later today, so it'll be available with a ```composer update```.

Thanks for reporting this.
Cheers!
