### ISSUE TITLE
Image (base64 code) not displaying in CRUD

### ISSUE THREAD

**Issue by ravor44** [Laravel-Backpack/CRUD#1838]
# Bug report

### Backpack, Laravel, PHP, DB version: Backpack v 3.6 / Laravel 5.8 / PHP 7.2 / MySQL 5.7

Link to StackOverflow question: https://stackoverflow.com/questions/55252544/render-base64-code-as-image-in-laravel-backpack-crud-view

**Comment by tabacitu** [comment]
Hi @ravor44 ,

There is no default ```base64_image``` column type in Backpack ([all columns here in docs](https://backpackforlaravel.com/docs/3.6/crud-columns#image)). So Backpack just treated your column type as ```text```. Since it's a "text" column, it shows the first characters of your blob.

You can [create a custom column type](https://backpackforlaravel.com/docs/3.6/crud-columns#creating-a-custom-column-type) that shows your image from the base64 string. Consider re-using the ```image.blade.php``` file - Backpack does have an ```image``` column type that shows images from an URL. 

**Background:** There have been talks regarding a ```base64_image``` column type some time ago - some suggested adding it in the core (because it would be intuitive), others motioned against it, because we should _probably_ discourage people from storing images as base64 strings in the database. I'm still torn, but leaning towards having it. If you do create the column type for yourself, consider submitting a PR with it - that way the discussion is reopened and we might include it in the core.

Cheers!
