### ISSUE TITLE
Usage reporting of Crud is running on every  boot of CrudServiceProvider ?

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/CRUD#1844]
According to [CrudUsageStats](https://github.com/Laravel-Backpack/CRUD/blob/master/src/CrudUsageStats.php#L45-L48) the sending of the usage stats doesn't actually happen every ~100 pageloads.

It's merely a random generator of a number between 1 and 100, so the condition is either useless or incorrect as a generated number is almost 99% of the time **NOT** 1.

A simple try of this code should prove that:

```php
$run = 0;
for ($d=0; $d < 101; $d++) { 
    if (rand(1, 100) != 1) {
        $run++;
    }
}
echo $run;
```

I think this should rely on some other method of running it..

@tabacitu - i realise this isn't an actual issue and it's probably a low priority one, but i think this code can be improved :)

**Comment by tabacitu** [comment]
Hi @niladam ,

Thanks for the heads-up. Yes, I realise there's a _posibility_ of 1/100 for the stats to be sent, so it doesn't _actually count_ the requests and send it every 100 requests. That's ok with us.

We opted for this because:
- we don't really _need_ accurate sending every 100 requests; we just need people to sometimes see the notification bubble, and be annoyed enough to purchase a license code;
- we don't really _want_ accurate usage stats; if we did have 1 request every 100 we'd basically have accurate analytics of how many requests are made to that website (just multiply our results by 100); and that's not a responsibility we want :-)

Thanks for taking the time to write this though. There are many _many_ ways we can improve the usagestats and licensing [as I'm sure you've noticed if you've looked at the code ;-) ], but this abort using a random number is not one of them, in my opinion. It's _good enough_, since it provides _some_ annoying bubbles, but doesn't actually give us a ton of information so that we'd take on data processing responsibilities.
 
Cheers!
