### ISSUE TITLE
Why you need my secrets info?

### ISSUE THREAD

**Issue by fiftysoft** [Laravel-Backpack/CRUD#1853]
Hi can you explain why you need to read all env config and database connection and send it to your server ?

https://github.com/Laravel-Backpack/CRUD/blob/1da6191320a74a8eb24546fef74aa839f13e37a3/src/CrudUsageStats.php#L38

do you mention that in docs in clear way ?

**Comment by tabacitu** [comment]
Hi @fiftysoft ,

Sure. **Like most paid software, our "call home" function helps us see when people use Backpack commercially without a license code.** It's industry best-practice, and the _only_ way we can track unlicensed usage, since our source code is public on Github.

We only send 
- the Backpack license code (which helps us track unlicensed usage)
- basic server information (that we use to understand how developers use Backpack)

**We don't send _all env config variables_ to our server** - that would be a privacy nightmare. We also don't send any information about your app's users (so no GDPR issues - we wouldn't touch that). We only send the minimum amount of info, that would be helpful to us to understand _where_ Backpack was used to develop an admin panel, by _who_ and _how_.

Here's everything that we actually send: https://github.com/Laravel-Backpack/CRUD/blob/1da6191320a74a8eb24546fef74aa839f13e37a3/src/CrudUsageStats.php#L53-L67

You'll notice there's **no private information** there apart for the Backpack license code (which we already have in our db, so we just match it with your website). So **no encryption key, no db user or password, nothing sketchy**. Plus, **the information is sent on a randomized schedule**, in less than 1% of all requests, so we can't create accurate analytics about your usage (how many pageviews, etc). This is intentional - we're not interested in that stuff - we only want to know _when_ our software is used illegally, and _how_ it's used (which Laravel version, which DB engine, which Backpack version).

Hope this answers your question.
Cheers!
