### ISSUE TITLE
It's So easy to find uploaded file name

### ISSUE THREAD

**Issue by fiftysoft** [Laravel-Backpack/CRUD#1854]
you can use UUID its better then md5 for original file name ,

for example i can regenerate same md5 name using same method you use but i will need to brute force the time and the time is not so hard maybe you need only 60 (1 minute between upload time and time when time() function called at server) try to find the right file name,

https://github.com/Laravel-Backpack/CRUD/blob/1da6191320a74a8eb24546fef74aa839f13e37a3/src/CrudTrait.php#L192

https://github.com/Laravel-Backpack/CRUD/blob/1da6191320a74a8eb24546fef74aa839f13e37a3/src/CrudTrait.php#L240

**Comment by tabacitu** [comment]
Hi @fiftysoft ,

Backpack is meant to help you build administration panels, so it assumes you place a certain level of trust in the people that use your admin panel. This, however, is _not_ a point where we trust the users not to guess a filename they wouldn't otherwise have access to.

I'm afraid I don't agree with you on this one. **I think it is _highly unlikely_ for someone to guess the md5 hash**, so that they can guess the file name. They would need to have raw access to the database or files, to know its ```created_at``` timestamp, then try every milisecond to see which one works. But my point is - **if a malicious user already has access to your db / files, you have bigger problems than the md5 hash of an uploaded file**. 

You should be able to easily overwrite the ```uploadFileToDisk()``` method in your Model if you wish to use UUIDs - but by default Backpack does not use UUIDs. And I don't think there's a useful benefit in using them here. Please let me know if you disagree - I'm wrong _at least_ once a day, just like everyone else :-)

Cheers!
