### ISSUE TITLE
Date Picker cannot be manually edited 

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#1878]
Similar to #1771 the date cannot be manually edited either.
Same issue, but also same solution !

**Comment by timbertens** [comment]
hi @tabacitu 

I was too optimistic here I'm afraid.  You are right I've the commenting out that part again and it does not work as expected.  
I believe there is some data entry speed benefit in being able to enter dates without using the date picker, but not a huge issue at the moment of course

**Comment by anandphulwani** [comment]
Post PR keyboard navigation on popover works, but the value still cannot be edited directly on the textfield. @tabacitu Can you reopen this issue ?

**Comment by pxpm** [comment]
@anandphulwani by design datepicker does not allow manually editing dates. It's not backpack fault, it's just the way the plugin is designed. However I think found something that can make it work, but I am not 100% sure, and it's definatelly an hack. 

Basically you listen to events and update the value yourself, something like:

```
$picker.on('change.dp', dateChanged);
$picker.change(dateChanged)

function dateChanged(ev) {
    $(this).datepicker('hide');
    
    //code to update the input
}
```

I haven't tried this myself yet, if you happen to try it out and it works (without much hacking), share with us and we might be able to merge it into the core. 

Best,
Pedro

**Comment by anandphulwani** [comment]
@pxpm Check this out, tell me if you like it, i can setup a demo for you to check, if you like it i can send you a PR for merge.
@tabacitu Pls have a look.

![recording](https://user-images.githubusercontent.com/3785927/105827734-5a7b1800-5fe8-11eb-8fff-365c4fd901d4.gif)

**Comment by tabacitu** [comment]
@anandphulwani what is this, magic?! 😂 Did you use a different JS plugin?

**Comment by anandphulwani** [comment]
@tabacitu Yes i did, a little magic 😄  by modifying 2 libraries, and wait you haven't seen the half of it, is there any way to connect to you directly, i want to show you the demo.
