### ISSUE TITLE
`show` in `CrudController` doesn't take into account `addClause` calls.

### ISSUE THREAD

**Issue by MajedDH** [Laravel-Backpack/CRUD#1879]
# Bug report

### What I did:
I've used this code to include the count of a relation in the query:
```
$this->crud->addClause('withCount', ['logs as hidden_logs_count' => function ($query) {
    return $query->where('status', '=', 'hidden_logs_count');
}]);
```
### What I expected to happen:
it worked while listing the records, so it should when showing a single entity.
### What happened:
When I show a single record it just calls `$this->crud->getEntity($id)` which doesn't use the inner query of `CrudPanel` . so it ignores any `addClause` call.
### What I've already tried to fix it:
i've overriden `Show($id)` , copied it's code and modified the `getEntity` part. actually i replaced it :
old code:
```
$this->data['entry'] = $this->crud->getEntry($id)
```
new code:
```
$this->data['entry'] = $this->crud->query->find($id)
```
and it worked
### Backpack, Laravel, PHP, DB version:
backpack/base: 0.9.*
backpack/crud: 3.4.33
php: 7.1.22
db: mysql 5.7.23

**Comment by tabacitu** [comment]
Hi @MajedDH ,

I see how this would be confusing... It's not straightforward that ```addClause()``` only applies to the list operation. But that's what's happening. In the next version of Backpack we intend such calls to be made to _that particular operation_, so it's clearer. 

We don't currently have a way to ```addClause()``` to operations that happen upon an entry (Show, Update, Delete etc). Only for mass operations (like List). **What you've done seems like a good solution, but take note that ```getEntry()``` also took care of adding the fake fields. So if you're using fake fields for this entity, those will not show up in Show.** Take a look at ```Read::getEntry()``` to replicate its functionality.

Thanks again for bringing this up, but unfortunately there's no non-breaking fix we can push on this. Since a lot of people use addClause() to _restrict access_ to certain entries, pushing this to everyone would make their show/edit/etc stop working for those entries.

Cheers!
