### ISSUE TITLE
Status on unregistering routes?

### ISSUE THREAD

**Issue by markacianfrani** [Laravel-Backpack/CRUD#1881]
I was looking to remove some of the default routes that get created ('bulk-clone', 'bulk-delete', 'details', 'translate', etc) since I'm not using any of them. 

The only thing I could find was a TODO reference in CrudRouter.php to 'Give developers the ability to unregister a route.' 

Are there any plans for implementing this soon or does this functionality already exist some place else? If not, would this be a good PR to submit?

**Comment by pxpm** [comment]
Route system is going to be changing in v4.0 .

I think there will be no new developments in this matter until v4.0.

But the ability to remove unused routes is as must.

MC

**Comment by tabacitu** [comment]
Indeed. Thank you @pxpm . No new developments for routes in 3.x. I want developers to be able to enable/disable routes, along with operation - I'm currently unhappy with the fact that each CRUD has more routes than strictly necessary. We're looking for a general solution that would:
- allow developers to enable/disable routes; ideally inside the EntityCrudController, instead of fiddling in a separate routes file;
- allow package developers to create new routes for their custom operations, ideally inside the EntityCrudController;

Please join the talk here about what to do in v4: https://github.com/Laravel-Backpack/CRUD/issues/1877#issuecomment-490605514
