### ISSUE TITLE
Space at the end of all text columns

### ISSUE THREAD

**Issue by jrpub** [Laravel-Backpack/CRUD#1889]
There is a space at the end of all text columns in Backpack, which is not practical to copy paste.

![user1](https://user-images.githubusercontent.com/26855134/57813255-c283bf00-776f-11e9-876b-76e558a164b9.png)

Note the space at the end of the admin.

![user2](https://user-images.githubusercontent.com/26855134/57813285-d7605280-776f-11e9-9f39-93dccbca31f3.png)

Here, there is no space, which is better when double-clicking a word to copy-paste it. 

This is due to the following line in columns/text.blade.php

```
<span>
	{{ (array_key_exists('prefix', $column) ? $column['prefix'] : '').str_limit(strip_tags($value), array_key_exists('limit', $column) ? $column['limit'] : 50, "[...]").(array_key_exists('suffix', $column) ? $column['suffix'] : '') }}
</span>
```
The line return after the big line (and before the `</span>`) is taken into account, and appears as a space. It is a bit weird, but I tested it on FF and Chrome (Might be a bug in Blade?)

I can propose a patch to put everything on one line:

```
<span>{{ (array_key_exists('prefix', $column) ? $column['prefix'] : '').str_limit(strip_tags($value), array_key_exists('limit', $column) ? $column['limit'] : 50, "[...]").(array_key_exists('suffix', $column) ? $column['suffix'] : '') }}</span>
```

Would it be ok?

Thanks

**Comment by tabacitu** [comment]
Right! Totally @jrpub - looks pretty inconvenient. It turns out it was not only that, but also a new line after the ```span```. I've gone ahead and done this for a few more columns - though it's probably only useful for ```text``` and ```number```. I'll tag the update later today so you can get it with a ```composer update```. Just want to include a few more small fixes in this 3.6.21 release.

Thanks for bringing this up.
Cheers!
