### ISSUE TITLE
[3.6][Feature Request] Revisions - Unclear which specific entity you are viewing history for

### ISSUE THREAD

**Issue by juventus18** [Laravel-Backpack/CRUD#1946]
When viewing an entity's revisions page, it is unclear which specific entity you are viewing (it only shows the entity type/model name).

This makes it difficult to know which entity you are viewing the history for in isolation (for example, a printed copy of the revisions page). I'd like to know that I'm viewing revisions for "Art 221" rather than "Course"

Lucky for us, the Revisions package provides an entity method `identifiableName()` thru the `Revisionable` trait (you are supposed to override this method in your model to provide a meaningful name for the entity, instead of the ID, for example). We can use this method to show the user the name value of the entity for which they are viewing.

I pretty much have a PR ready for this, but decided not to submit because I would need to change some CSS to make it look decent, and also some lang files for better context/syntax (I don't know the styling implementation well enough yet to decide if my CSS changes would introduce side-effects or not, and I can only speak English, so I wasn't sure the policy of changing lang files). The PR basically boils down to adding `<h2>{{ $entry->identifiableName() }}</h2>` in the `revisions.blade.php` (line 23 seems an appropriate location). I figured I'd just let @tabacitu decide how to style it and figure out the lang (but if you want me to decide, LMK and I'll submit PR)

I see v4.0 is on the horizon and this package will be deprecated, so it is understandable if you choose not to push this feature, but I do hope you consider having it in v4.0 (hopefully the new audit package will be able to support something similar).

Thanks!

**Comment by tabacitu** [comment]
Hi @juventus18 ,

Now that you mention it, it's super-annoying and super-obvious to me that this page is missing a distinctive headline :-) Thank you.

I don't see a way for us to introduce this as a non-breaking change in 3.6, since it would require people to use ```identifiableName()``` on their model. **For 3.6, the only decent workaround I see is adding this in your EntityCrudController** to replace the page's subheading with something more informative:

```php
    public function listRevisions($id)
    {
        $result = parent::listRevisions($id);
        $this->crud->setSubheading('Listing revisions for '.$this->data['entry']->identifiableName(), 'listRevisions');
        return $result;
    }
```

---

I'm not so sure Venturecraft\Revisionable is deprecated any more. 10 days ago they added Laravel 6.0 support - which is awesome. I hope we'll get to keep it - I'm very happy with it.

PR for v4 here, in case we get to keep Venturecraft\Revisionable - https://github.com/Laravel-Backpack/CRUD/pull/1963 Let's move the conversation there if you feel we could improve it.

Thank you for bringing this up.
Cheers!
