### ISSUE TITLE
[Feature]  Implementation of laraberg in backpack for batter page builder

### ISSUE THREAD

**Issue by vikrampariharcodereadr** [Laravel-Backpack/CRUD#1957]
Well is a issue for new feature in laravel backpack.
i am trying to build a new page in backpack, and found some difficulty to build better design.

So i have  a suggestion for add this package in laravel backpack.

Example: http://demo.laraberg.io/articles/137/edit

**Comment by tabacitu** [comment]
Hi @vikrampariharcodereadr ,

Thank you for the suggestion. We're considering it for v4. Please join the [issue here](https://github.com/Laravel-Backpack/CRUD/issues/1872).

_Personally_ I am a bit hesitant to use it for a real project for a client:
- it has A LOT of features, but it also means there's a lot that can go wrong; I've found Gutenberg/Laraberg to be a bit wonky in my tests; Sometimes it freezes the window for a few seconds; Other times it doesn't preview the images that I've chosen; Stuff like that;
- it saves the HTML output in the database (if I'm not mistaken);
- once you give so many features to a user, you can't take them back, and there's nothing to replace it with;

I do understand why people like it, though. It's super-clean and it has A LOT of features. So we'll probably include a Laraberg field type in v4 if people want it. But _personally_, for my projects, I think saving this much HTML directly in the DB column is a bad idea. I'd rather save JSON. That's why we've created an alternative, which is 90% ready, which we call the [layout field type](https://github.com/Laravel-Backpack/CRUD/issues/1873). It's a lot more basic than Gutenberg (we don't have the resources of Automattic) but it sticks to good programming practices.

Thanks for bringing this up. Let's continue the conversation in [that other issue](https://github.com/Laravel-Backpack/CRUD/issues/1872) please.
Cheers!
