### ISSUE TITLE
[4.0][Feature Proposal] Dynamic default field values based on GET parameters

### ISSUE THREAD

**Issue by jrpub** [Laravel-Backpack/CRUD#1959]
In my code, I often add a row button in tables to add a related model easily. 

For instance, I have a "store" and "book" models, with a 1-N relation (one store has many books), I want, from the table "store", to add a book linked to one store, so I add a button in each row of "store", leading to the URL `/admin/book/create?store=2`

Then, in my `BookCrudController`, I add such code:

```
$request = request();
$this->crud->addField([
            'name' => 'store_id',
            'label' => 'Store',
            'type' => 'select2',
            'entity' => 'store',
            'attribute' => 'name',
            'model' => 'App\Models\Store',
            'default' => $request->has('store') ? $request->input('store') : null,
            'attributes' => [
                'autocomplete' => 'off',
            ]
 ]);
``` 
It works: the store is automatically selected in the book creation form. However, it is not very readable/practical, as the `autocomplete=off` is required to avoid cached values by the browser.

It would be nice to have this feature, like this:
```
'default' => 1
'default_from_request' => 'store'
```
If `store` is a parameter of the request, then it is selected as the default value and the autocomplete is automatically added, otherwise the `default` is taken into account.

Not sure if there is a better mean to do it, but with such a feature, it would simplify the way to link tables/models between them.

**Comment by tabacitu** [comment]
Hi @jrpub ,

Thanks for bringing this up. I don't know... it seems to me like we already have a good solution for default values - the one you mentioned is both:
- already available for all field types
- invisible (the admin would not be able to see/modify the default value from the URL)

I'm reluctant on adding default values through GET parameters because:
- it needs to be added to _all field types_;
- as a developr, when adding a default value, you'd need to (1) remove the Add button and (2) replace it with your own button, with that GET parameter in the URL; this alternative process seems unintuitive to me - I think it's much more intuitive to plug in the default value when you do ```addField()```; I think "autocomplete=off" is a small tradeoff for setting the default value in an intuitive place;

I'm leaning towards declining this feature request, I'm afraid - seems like a lot of work (both for the feature, and for the end-developer who would use it) for little benefit. Of course, I might be wrong - it's been known to happen :-) I'll leave this issue open for feedback for a while, to let others voice their opinion.

Cheers!

**Comment by tabacitu** [comment]
Hi @jrpub ,

On second thought, I think I'm going to close this now, I'm sorry. As I said before, I don't think this is really necessary, since we already have a way to do this, and this second way is NOT better than the first, in my opinion. It might be useful for your current project, but I think adding this second option to do this... it would just complicate most Backpacker's lives.

Again - sorry.
Cheers!
