### ISSUE TITLE
$this->crud->addClause strange behaviour

### ISSUE THREAD

**Issue by adrenaxus** [Laravel-Backpack/CRUD#2022]
# Bug report

### What I did:

I want to add a clause to my ArticleCrudController in order to filter my articles so that only articles with a certain page_id are shown:

This is my URL: _http://example.com/admin/articles/9_ (where 9 is the page_id)

I have added this route to my custom.php

`Route::get('articles/{id}', 'ArticleCrudController@index');`

and this is the logic behind my addClause:

```
$segments = request()->segments(); //get url segments
$page_id = $segments[count($segments)-1]; //get last segment, definetely works
$this->crud->addClause('where', 'page_id', $page_id);
```

### What I expected to happen:

Only articles with page_id corresponding to $page_id are shown.

### What happened:

The collection is empty. No articles shown. No error.

### What I've already tried to fix it:

Oviously I thought that $page_id is empty or has wrong content, but after checking it is not! It works perfectly. If I substitute $page id with some static working page id like this:

`$this->crud->addClause('where', 'page_id', "9");`

it works! And $page_id exactly contains "9" which I have chekced with dd(). I even tried to cast it to int, still no luck.

How is this even possible? I'm at the end of my rope here...

### Backpack, Laravel, PHP, DB version:
backpack/crud: 3.5
PHP: 7.2.21
MySQL: 14.14

###Question on Stackoverflow
If you are interested, this is my question on SO regarding the same issue: https://stackoverflow.com/questions/57752772/addclause-always-returns-empty-collection

**Comment by tabacitu** [comment]
That's weird indeed :-) Can you try dumping the generated SQL, see if there's a difference between manually using 9 and using the variable?

```php
dd($this->crud->query->toSql());
```

**Comment by adrenaxus** [comment]
Hello Tabacitu,

Thank you for your quick reply! Very much appreciated. I was trying to get the query but didn't know you could do `$this->crud->query->toSql()`, awesome.

However, interestingly enough it doesn't matter whether I use `$this->crud->addClause('where', 'page_id', "9");` or `$this->crud->addClause('where', 'page_id', $page_id);` - the output is always

`"select * from `articles` where `user_id` = ? and `page_id` = ?"`

But using the static ID works as expected, I only see articles with `page_id` of 9.

**Comment by tabacitu** [comment]
Huh that's weird. I bet it's something super-small, that once you debug you can't believe you've spent so much time on this :-)

I think it could be:
- that you're using string/integer as a query parameter (my suggestion - typecast to string not integer)
- something with how you've overwritten the routes, or parse the route segments;

I'm afraid I can't help more with debugging this - it really depends on your custom code. Since it's not a Backpack bug, I'm going to close the issue. I suggest you post on StackOverflow with the ```backpack-for-laravel``` tag if you can't get to the bottom of it.

Sorry I can't be of more help.

Cheers!

PS. Backpack already uses the ```/article/{id}``` route for the [Show operation](https://backpackforlaravel.com/docs/3.6/crud-operation-show). Your CrudController is a RESTful controller, so that route points to the ```show()``` method. Wether your overwrite gets registered is a matter of _where_ you've put that route - _before_ or _after_ the ```CRUD::resource()``` call. I suggest you use a different route - at least you'd exclude problems coming from overwriting an existing route.
