### ISSUE TITLE
[3.6][Feature] enum type can be auto-set again

### ISSUE THREAD

**Issue by fzhantw** [Laravel-Backpack/CRUD#2059]
# Bug report

### What I did:
Because DBAL doesn't support enum type, CrudPanel::autoSet() takes enum as text now.
That's inconvenient for me.

### What I've already tried to fix it:
Maybe we can try using SQL query like "SHOW COLUMNS FROM [table name]" to check enum type?

### Backpack, Laravel, PHP, DB version:
Backpack 3.6.31
Laravel 5.8
PHP 7.3.9
MySQL 5.7.24

**Comment by tabacitu** [comment]
Ah, yes. That's a tricky one, that we haven't gotten around to fixing yet. SQL query would fix it, yes, and it's the way we _used to_ have it fixed. But some people wanted to use Backpack with NoSQLs like Mongo and such. With the query in place, it made Backpack completely unusable to them. It also caused problems for PosgreSQL. And SQLServer. So we've removed the "ENUM" autoSet support, to at least let non-MySQL developers use Backpack. I would like a solution to autoset ENUM columns, but we found no solution using DBAL (since it doesn't support ENUM eitehr). And in the past it's been such a pain in the a$$ that it's been better to just remove support for ENUMs.

In either case - if you're relying heavily on ```setFromDb()``` - I personally recommend against using it. For prototyping, or super-simple CRUDs, sure. But for anything more important, I recommend you manually choose which columns/fields to show. The reason being that ```setFromDb()``` rarely gets updates. Because we _can't_ push non-breaking updates to it. Because it would change thousands of admin panels in ways the developer wouldn't expect, we rarely (if ever) update its functionality - only once every 6 months, when we can make a breaking change and have an upgrade guide. Which is... very inconvenient, both for Backpack maintainers and for Backpack developers.

Food for thought. Open to a solution to autoset ENUM columns, using DBAL - if you can think of one, please let me know and re-open the issue.

Cheers!

**Comment by fzhantw** [comment]
I made a quick hack by injecting enum type into DBAL.
Not stable.
Need more quality assertion.
Just take a try.
