### ISSUE TITLE
view_namespace does not override

### ISSUE THREAD

**Issue by KevinRignault** [Laravel-Backpack/CRUD#2069]
Hi :) 

It seems that the _view_namespace_ in config.backpack.base does not works properly.
When I use a custom namespace, like this : 
'view_namespace' : 'vendor.everess.'

I got this error : 
View [vendor.everess.auth.login] not found.
The file does not exists, right, but the backpack one should be called.

I see this method : 

```
function backpack_view($view)
    {
        $theme = $originalTheme = config('backpack.base.view_namespace');

        if (is_null($theme)) {
            $theme = $originalTheme;
        }

        $returnView = $theme.$view;

        if (! view()->exists($returnView)) {
            $returnView = $originalTheme.$view;
        }

        return $returnView;
    }
```

But here, $theme = $originalTheme, so I make this fix : 

```
function backpack_view($view)
    {
    	$originalTheme = 'backpack::';
        $theme = config('backpack.base.view_namespace');

        if (is_null($theme)) {
            $theme = $originalTheme;
        }

        $returnView = $theme.$view;

        if (! view()->exists($returnView)) {
            $returnView = $originalTheme.$view;
        }

        return $returnView;
    }
```

Do you think it's correct ? 
Or maybe I failed somewhere in the config !

Thanks for your feedback,

**Comment by tabacitu** [comment]
Ugh. I'm pretty sure this happened recently when we fixed some merge conflicts with the original solution. 

Of course you're right @KevinRignault - thanks a lot for spotting this, and letting us know. I've just implemented your solution and it works like a charm! 

Let me know if you find anything else with the view_namespace functionality, or how easy it is for you to use. Out of curiosity - what do you plan to use it for - a different theme entirely, or just moving the views to a different folder?

Cheers!

**Comment by KevinRignault** [comment]
Hi @tabacitu, 

Thanks for your quick feedback :) 

This feature is really good, in the previous Backpack v3, I've made a package to build a new theme but this method is easier ! 

I also find a solution to override crud views in the same folder - 
In the Laravel AppServiceProvider, I added this line in the register method : 
$this->loadViewsFrom(resource_path('views/vendor/everess/crud'), 'crud');

In this way, the hint 'crud' also search views in the folder and we can have a complete package with all views in the same folder.

In order to have a complete theme, ready to use, I think is to have a package with views, sass, js .. so I work on a package like this :)

The Backpack project is really awesome, very good job !

Keep in touch,

**Comment by zmorris** [comment]
@tabacitu Doesn't work as of Backpack 5.4.14.

I've tried every permutation in `config/backpack/base.php` of:

* `'view_namespace' => 'vendor.myviews.',`
* `'view_namespace' => 'vendor.myviews.base.',`
* `'view_namespace' => 'vendor.myviews.base.inc',`
* `'view_namespace' => 'myviews.',`
* `'view_namespace' => 'myviews.base.',`
* `'view_namespace' => 'myviews.base.inc.',`

etc I can think of, with periods, colons, everything, even copying the whole backpack views folder from vendor and trying the same thing in `AppServiceProvider::register()`. No error, no log entries, no nothing, it just fails. Even after `php artisan config:clear` and reloading the browser a bunch to maybe regenerate views.

Can you share an example with a full directory structure in `resources/views` and the `view_namespace` value that works?

Or is there an example project that shows how to use `view_namespace`? Or are there unit tests we can run that show the `view_namespace` working? Maybe I could step through that in XDebug.

The instructions at https://backpackforlaravel.com/docs/5.x/base-how-to#create-a-new-theme-child-theme are somewhat ambiguous, so I don't know what to do. I need to have a way to create views outside of `resources/views/vendor`.

Thanks for any help you can provide!

**Comment by zmorris** [comment]
@tabacitu I managed to fix it [🎉](https://emojipedia.org/party-popper/)

Here's a full working example:

```php
# config/backpack/base.php

'view_namespace' => 'my_namespace.base.', // resources/views/my_namespace/base falls back to resources/views/vendor/backpack/base falls back to vendor/backpack/crud/src/resources/views/base
// 'view_namespace' => 'backpack::', // resources/views/vendor/backpack/base falls back to vendor/backpack/crud/src/resources/views/base

# (optional) equivalent method by KevinRignault in AppServiceProvider::register() with config left as default 'view_namespace' => 'backpack::'

public function register()
{
    $this->loadViewsFrom(resource_path('views/my_namespace/base'), 'my_namespace');
}

# project structure:

# copied manually from vendor/backpack/crud/src/resources/views/base
resources/views/my_namespace/base/inc/sidebar_content.blade.php
resources/views/my_namespace/base/inc/topbar_left_content.blade.php
resources/views/my_namespace/base/inc/topbar_right_content.blade.php
resources/views/my_namespace/base/dashboard.blade.php

# created by: `composer require backpack/crud`
vendor/backpack/crud/src/resources/views/base/inc/sidebar_content.blade.php
vendor/backpack/crud/src/resources/views/base/inc/topbar_left_content.blade.php
vendor/backpack/crud/src/resources/views/base/inc/topbar_right_content.blade.php
vendor/backpack/crud/src/resources/views/base/dashboard.blade.php
```

*\*Note the discrepancy in how the namespace must be `my_namespace.base.` instead of `my_namespace.` for all path hierarchies to match form.*

If trying this in a local dev environment, be sure to clear caches:

```shell
php artisan config:clear
php artisan view:clear
```

Just FYI: I substituted `backpack` everywhere you see `my_namespace` above for my namespace and folders, and it all "just worked". So there's no conflict with the `backpack::` namespace in vendor.

***

The problem was due to:

1. The [recommended](https://backpackforlaravel.com/docs/5.x/base-how-to#create-a-new-theme-child-theme) `'view_namespace' => 'my_namespace.'` setting in `config/backpack/base.php` pointing to `resources/views/vendor/backpack` is inconsistent with the `vendor/backpack/crud/src/resources/views/base` path hierarchy corresponding to the `backpack::` default.
   - I worked around it by specifying `'view_namespace' => 'my_namespace.base.'` but Backpack's scan should instead start at `resources/views/my_namespace/base` when we specify `'view_namespace' => 'my_namespace.'`
   - It could be a missed opportunity, because customizing folders outside the `base` folder is difficult as it stands now. Maybe that's intentional, so I tend to think of this kind of design decision as a bug/feature. I'd recommend fixing it in the next major version release and documenting the upgrade steps for the user's view hierarchy.
   - I've noticed this trend throughout the documentation: it says what to do without providing examples or enough details. The docs need to be very specific, similar to what's written above. Some additional examples:
      - Most users will end up repeating the steps above if they want to populate the left sidebar with their own view outside of a vendor folder. It would be better to read an array from config or have a callback method in CrudController or a CrudService so Backpack can fetch the list from us without involving the frontend.
      - I had to dig deep into the styling to figure out how to widen the sidebar to fit the item names. This is not future-proof, because the next Backpack version will likely change css rule(s). And I still can't figure out how to make the sidebar overlap the page content (like it used to) rather than shift it right.
      - I couldn't figure out how to turn off beautified column names to show exact database column names instead. That's opinionated behavior that might be undocumented and/or doesn't seem to have a corresponding setting?
      - Setting `'responsiveTable' => false` in `config/backpack/operations/list.php` shows the horizontal scrollbar, but causes the `(+)` icon to disappear from the start of each row. Again, that's opinionated behavior outside of core functionality, which creates a feeling of anxiety for users (I still don't know how to fix it). It's best to decouple behaviors into separate settings with sane defaults.
      - The search field appears to search all columns, with no way to pass a hint like `id:123` or specify column(s) or even set a debounce time between keystrokes. Most people are going to need to tweak this, so again it feels a bit opinionated.
2. (Minor) the [setting](https://github.com/Laravel-Backpack/CRUD/blob/main/src/config/backpack/base.php#L44) `show_getting_started` in `config/backpack/base.php` defaulted to true after upgrading to `backpack/crud` 5.4, so the edits I was doing to my local copy of `dashboard.blade.php` weren't being reflected in the browser, which sent me down a rabbit hole.

But hey, it's pretty great now that it's working! I went into detail above with the hopes of improving your process, not to nitpick. The problem with the above issues is that they force people to learn nearly the entirety of your framework to do even the simplest things (like populate the sidebar). In fairness, this is a huge problem with nearly all frameworks, so no explanation is needed.

To anyone reading this: please @ me about any mistakes and I'll try to correct them, thanks!

***

Backpack's default configuration for comparison:

```shell
# installed by: `php artisan backpack:install --no-interaction`
resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
resources/views/vendor/backpack/base/inc/topbar_left_content.blade.php
resources/views/vendor/backpack/base/inc/topbar_right_content.blade.php
# (optional) copied manually from vendor/backpack/crud/src/resources/views/base/dashboard.blade.php
resources/views/vendor/backpack/base/dashboard.blade.php

# created by: `composer require backpack/crud`
vendor/backpack/crud/src/resources/views/base/inc/sidebar_content.blade.php
vendor/backpack/crud/src/resources/views/base/inc/topbar_left_content.blade.php
vendor/backpack/crud/src/resources/views/base/inc/topbar_right_content.blade.php
vendor/backpack/crud/src/resources/views/base/dashboard.blade.php

# .gitignore and .dockerignore rules (some projects don't track vendor folders, so had the namespace fix not worked, here's a fallback way to specify exceptions):
# /resources/views/vendor
/resources/views/vendor/*
!/resources/views/vendor/backpack/
```

**Comment by tabacitu** [comment]
Thanks a lot for the write-up @zmorris ! 

I agree, this will change in v6, and we'll allow custom directories with better docs. That's when we'll add "themes". Instead of specifying the `view_namespace` you'll probably be specifying the `theme`, which will point to a directory in `resources/views/vendor/backpack/themes/your-theme-name` (or a custom directory if you want). That will allow you to create a theme to override _some_ files. For anything else, Backpack will fall back to files in the "parent theme". Since the blade files will be more atomic (small and many), we hope this will allow you to create a super-custom UI, more easily.
