### ISSUE TITLE
remove Button not working in  v 4.0

### ISSUE THREAD

**Issue by tifaahmed** [Laravel-Backpack/CRUD#2091]
# Bug report

### What I did:
```
public function setup()
    {
        $this->crud->setModel('App\Models\Social');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/social');
        $this->crud->setEntityNameStrings('social', 'socials');
        $this->crud->removeButton('create');
        $this->crud->removeButton('edit');
        $this->crud->removeButton('delete');
    }

    protected function setupListOperation()
    {
        // TODO: remove setFromDb() and manually define Columns, maybe Filters
        $this->crud->setFromDb();
        $this->crud->removeButton('create');
        $this->crud->removeButton('edit');
        $this->crud->removeButton('delete');

    }
```
### What I expected to happen:
delete create and delete and edit buttons 
![2019-09-26_150823](https://user-images.githubusercontent.com/35181458/65690543-922e2480-e06f-11e9-914c-50643326550c.png)
### What happened:

nothing happened

**Comment by tabacitu** [comment]
You're totally right, thank you @tifaahmed for spotting this and letting us know. It's now fixed, a ```composer update``` should fix it for you, and you'll be able to do ```removeButton()``` inside the ```setupListOperation()``` method. Make sure you're running 4.0.5 or higher.

Note that you STILL won't be able to do it inside setup(). At that point, no button had been placed by the operation. If you want to keep your calls inside ```setup()```, please make sure you put them within [operation closures](https://backpackforlaravel.com/docs/4.0/crud-tutorial#option-2-operation-closures).

So this won't work:
```php
public function setup() {
     // ..
     CRUD::removeButton(''create);
}
```

But both of these will work:
```php
public function setup() {
     // ..
     CRUD::operation('list', function() {
         CRUD::removeButton('create');
     });
}

protected function setupListOperation() {
     CRUD::removeButton('create');
}
```

Personally, I recommend doing things inside ```protected setupXxxOperation()``` methods, so that you can re-use those methods in different operations.

**Postmortem:**
- ```removeButton()``` did not work inside ```setup()```, or inside ```setupListOperation()```, but it did work inside an [operation closure](https://backpackforlaravel.com/docs/4.0/crud-tutorial#option-2-operation-closures);  
- this was due to the fact that operation closures were run AFTER ```setupXxxOperation()``` methods; but operation themselves (for ex: CreateOperation), used operation closures to set buttons;
- so if you did ```removeButton()``` in ```setup()``` or ```setupListOperation()``` it could not be removed, because it hadn't been set yet;

**The fix:**
I've changed the order in which configurations are being applied:
- first, all operation closures are being run;
- then, all ```setupXxxOperation``` methods are being run;

This is something that's more intuitive anyway, because ```setup()``` is usually the first method in the file. So you'd somehow expect things to be run in the order they're written:
- first the ```setup()``` method with its ```$this->crud->operation('list', function() {});```
- then the ```setupXxxOperation()``` method;
