### ISSUE TITLE
[4.0.5] [Bug] Error message string showing escaped formatting

### ISSUE THREAD

**Issue by SamSebastien** [Laravel-Backpack/CRUD#2114]
# Bug report

### What I did

Received a 500 error from the server.

### What I expected to happen

Receive an error message.

### What happened

Received message with overly escaped characters.

![image](https://user-images.githubusercontent.com/9647970/66008972-dbf98d80-e4fb-11e9-9426-95a590430959.png)

### What I've already tried to fix it

The error was a 500 from server so I'm assuming the message is coming from the Frontend, but not sure where.

### Backpack, Laravel, PHP, DB version
Backpack 4.0.5, Laravel 5.8,  PHP 7.2

**Comment by tabacitu** [comment]
Hi @SamSebastien 

😆  overly-escaped - I like that. 

Tracked it down - it's because we were using ```{{ trans() }}``` in the buttons instead of ```{!! trans() !!}```. Changed it in 91c8287 - will get tagged and released later today, along with a few more fixes. Please do a ```composer update``` starting tomorrow for the fixes, and make sure you get 4.0.7 or higher.

Thanks for reporting this. 
Cheers!
