### ISSUE TITLE
Laravel app.js not affected when using backpack

### ISSUE THREAD

**Issue by mahamafzar** [Laravel-Backpack/CRUD#2179]
# Bug report

I added some library to laravel with npm and then i added them to app.js and i run npm run dev, But they are not loaded when i using backpack endpoints.

### LARAVEL VERSION:
laravel/framework                     v6.3.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.9      Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.4      Generate files for laravel projects

**Comment by tabacitu** [comment]
Hi @mahamafzar ,

Indeed, you can't add scripts to Backpack that way. Backpack assumes you're using Laravel's default ```app.js``` for your user-facing app, and that you want your admin panel completely separated from your user-facing app, so it doesn't use that file at all.

In order to add a script to app Backpack pages, you can add your script in the ```config/backpack/base.php``` file, [in this array](https://github.com/Laravel-Backpack/CRUD/blob/master/src/config/backpack/base.php#L114-L131). That'll make the script available on all pages. You can include a CND, a local script, whatever you want.

Hope it helps.
Cheers!
