### ISSUE TITLE
[4.x][Bug] File validation fails on edit

### ISSUE THREAD

**Issue by GrigoreAlexandru** [Laravel-Backpack/CRUD#2204]
# Bug report

### What I did

Edit file upload

### What I expected to happen

form passes validation

### What happened

form doesn't pass validation

### What I've already tried to fix it

-

### Backpack, Laravel, PHP, DB version

Backpack 4, Laravel 6, php 7.2

The validation 

`    public function rules()
    {
        return [
            'path' => 'required|file'
        ];
    }`
looks for an input with name 'path', however no such name is passed in the request when trying to update.
Checked on the demo project, can replicate

**Comment by pxpm** [comment]
@GrigoreAlexandru Hello there! :)

I tried to find your issue but could not get it, can you please try to clarify ?

In demo all file uploads are disabled. I tried looking at demo requests but couldn't find that rule.

[demo requests](https://github.com/Laravel-Backpack/Demo/tree/master/app/Http/Requests)

Can you point me to the right direction to check if it's a bug ?

Thanks in advance,
Pedro

**Comment by GrigoreAlexandru** [comment]
Hi @pxpm :)

Yes, you got the gist of it. I cloned the demo repo, added the rule and tried editing a crud after creating it with a file upload. With the validation rule set, the validation fails.

I'm thinking the upload field is un-editable by design ?

**Comment by pxpm** [comment]
After testing myself i think the correct solution to your problem would be adding the [sometimes laravel validation rule](https://laravel.com/docs/5.8/validation#conditionally-adding-rules)

I have submited an PR to de DOCS because it's not clear to everyone how Backpack internaly works, so if you want to have a read go ahead [https://github.com/Laravel-Backpack/Docs/pull/69](https://github.com/Laravel-Backpack/Docs/pull/69) 

As i think this will be solved with my solution i will be closing this issue. As i think it's more of a miss-communication than a bug. 

Please if you think this is not solved or have any doubt how to implement please go ahead in our [gitter chat](https://gitter.im/BackpackForLaravel/Lobby)

Best,
Pedro
