### ISSUE TITLE
[4.1][Feature] Use getRouteKey() instead of getKey() to allow for UUIDs that are not primary keys

### ISSUE THREAD

**Issue by MasterBratac** [Laravel-Backpack/CRUD#2212]
# Bug report
When changing route key by overriding getRouteKeyName() as laravel docs read to change the url key backpack does not comply with the change
### What I did
Override
```php
public function getKeyName()
{
return 'uuid';
}
```

### What I expected to happen

I expected the url to be of format /user/{uuid}/edit as opposed to /user/{id}/edit

### What happened

no change in operation

### What I've already tried to fix it
Made the following changes to 
Backpack\CRUD\app\Library\CrudPanel\Traits\Read
```php
public function getCurrentEntryId()
    {
        if ($this->entry) {
            //return $this->entry->getKey();
             return $this->entry->getRouteKey();
        }
.......................

public function getEntry($id)
    {
        if (! $this->entry) {
            //$this->entry = $this->model->findOrFail($id);
            $this->entry = $this->model->where($this->model->getRouteKeyName(),$id)->firstOrFail();
            $this->entry = $this->entry->withFakes();
        }

        return $this->entry;
    }

``` 
For this to work all references in blade files that reference 
```php
$entry->getKey();
//Need to be changed to 
$entry->getRouteKey();

```
I have tested this breifly and I do not see any errors.

### Backpack, Laravel, PHP, DB version
Laravel - 6.5.0
PHP 7.2.21
Backpack 4.0.12

When I run ```php artisan backpack:version``` the output is:

**Comment by MasterBratac** [comment]
Also note that the delete trait also needs changed 
Backpack\CRUD\app\Library\CrudPanel\Traits\Delete
```php
public function delete($id)
    {
        //return (string) $this->model->findOrFail($id)->delete();
        return (string) $this->model->where($this->model->getRouteKeyName(),$id)->firstOrFail()->delete();
    }
```

**Comment by MasterBratac** [comment]
As Well for update 
Backpack\CRUD\app\Library\CrudPanel\Traits\Update
```php
public function update($id, $data)
    {
        $data = $this->decodeJsonCastedAttributes($data);
        $data = $this->compactFakeFields($data);
       // $item = $this->model->findOrFail($id);
        $item = $this->model->where($this->model->getRouteKeyName(),$id)->firstOrFail();

        $this->createRelations($item, $data);

        // omit the n-n relationships when updating the eloquent item
        $nn_relationships = array_pluck($this->getRelationFieldsWithPivot(), 'name');
        $data = array_except($data, $nn_relationships);
        $updated = $item->update($data);

        return $item;
    }
```

**Comment by pxpm** [comment]
Hello @MasterBratac 

Thanks for submitting this issue. 

As you can see this is something that changes some core functions of CRUD, and i am not sure that it only needs this small changes. 

We need to create a proper PR and test everything beforehand. 

I will label and tag this issue. 

IF in the meanwhile you got yourself time and want to submit the PR i will happily test it :)

Best,
Pedro

**Comment by MasterBratac** [comment]
@pxpm I will try and get that done this weekend so it can be tested.Thanks.

**Comment by justinmoh** [comment]
Thanks @MasterBratac for brought up this issue. Indeed, the core package itself should use `$entry->getRouteKey()` instead of `$entry->getKey()`.

`Backpack CRUD` mainly deals with frontend interactivity, which usually accesses models through on route resource. In any __serious__ project, the usage of different route resource identifier (like uuid) is very common.

It's probably due to simplicity or unknown legacy issues, the package stop at the straightforward `->getKey()` approach, but I really hope this could be tested and merged.

**Comment by pxpm** [comment]
Hello @MasterBratac 

I was having a second look at this issue, as we are using `getKey()` in backpack, you could set the `$primaryKey` in your model to uuid ? Not sure it will work, give it a try.

It also as the `$keyType`, [ laravel doc](https://laravel.com/api/6.x/Illuminate/Database/Eloquent/Model.html)

Don't forget cached routes and configs.

Let me know how it goes :+1: 

Best,
Pedro

**Comment by tabacitu** [comment]
Hi guys. Thanks for bringing this up.

I haven't tested UUIDs on Backpack in a while, but last time I did, I was able to use them pretty easily, by specifying a custom ```$primaryKey``` and ```$increments``` false on the model, like @pxpm said. PLEASE NOTE! I said ```$primaryKey``` not ```getRouteKeyName()``` 😄 I think there are two scenarios here, which I've outlined below, best to talk about them separately.

I think I see why there's confusion here. **Backpack doesn't use [route model binding](https://laravel.com/docs/6.x/routing#route-model-binding)**. You'll notice when you defined the route (if you manually did that), you're not plugging a Model into the CRUD route. You're just pointing it to a CrudController, and the Model is defined inside the CrudController. That's why overwriting ```getRouteKeyName()``` on your model does nothing - because the route model binding functionality isn't actually used by Backpack. We could use it, of course, but I don't see the benefit of it right now. I think it's better to define the model inside the controller, so that everything you need to define about your CRUD stays inside one file - the ProductCrudController for example. I'm open to using route model binding, if it adds any benefit, but I don't see any. Maybe I can be convinced otherwise.

Let's dig into this issue. Copy-paste from the [Model class in Laravel](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Model.php):

```php
    public function getKeyName()
    {
        return $this->primaryKey;
    }

    public function getKey()
    {
        return $this->getAttribute($this->getKeyName());
    }

    public function getRouteKey()
    {
        return $this->getAttribute($this->getRouteKeyName());
    }

    public function getRouteKeyName()
    {
        return $this->getKeyName();
    }
```

I think there are two scenarios here:

## Scenario 1 (UUID == primary key)

In your model you've done:

```php
$primaryKey = 'uuid';
```

Or

```php
public function getKeyName() { return 'uuid'; }
```

I think this is the way MOST people use UUIDs. Once you have UUIDs on your Model, they're the primary key.  So ```getKey()``` and ```getRouteKey()``` will return the same thing. AFAIK, **this scenario already works in Backpack**. You just need to overwrite ```$primaryKey``` on your model to specify the UUID column.

So for this use case, it's no use changing ```getKey()``` to ```getRouteKey()```. The return of those methods is exactly the same, all the time.

## Scenario 2 (UUID + separate primary key)

In your model you've done:
```php
public function getRouteKeyName() { return 'uuid'; }
```

Because you can't overwrite ```$primaryKey```, because both of these are true:
- you're using UUIDs as route keys;
- you're using regular primary keys too (incremented integers);

This one is trickier. You're probably:
- using UUIDs because you don't want people to be able to see/increment IDs in the URL;
- still using INT keys too because you think it'll be slightly faster to do DB operations that way;

I suspect you guys are struggling here, in Scenario 2? If so, please tell me why you've chosen to have both UUIDs and INT primary keys. What do you see as the benefit of using both? Where would you like to use UUIDs, and where INT keys? Personally I've never used both, I don't see the point. If you're using UUIDs on your routes, you're making DB calls using them anyway. So maybe you're using UUIDs for user interactions, but INT keys in commands, crons, things like that when no user interaction is needed?

Cheers!

**Comment by MasterBratac** [comment]
@tabacitu  yes scenario 2 is what I am doing. Exposing UUID in URL and then INT incrementing keys internally. I could be completely off base but the reason I am doing this ( or would like to ) is for loading relations. The speed difference between how laravel stores a UUID as a 32 varchar vs INT or BigINT. 

This way the internals should be a lot faster. How much I do not know, I suppose that really depends on the amount of records. I have one table that will start with nearly 100k records in it and grow from there.(Vehicles)

**Comment by tabacitu** [comment]
Got it @MasterBratac , thank you! I've already created PR https://github.com/Laravel-Backpack/CRUD/pull/2314  making these changes everywhere. Let me know if I missed something, or if I've overdone it. Please help make the PR better - it's a HUGE change so we have to make sure we don't break stuff.

But I'll be honest with you - **it might take a while for us to merge this into ```master```**. There are so many changes, in so many important files, that I can't be 100% confident this won't break people's apps. That's why I'd rather push this change when we launch 4.1 (most likely in February 2020), no sooner.

If you want to use this feature until then, one way is to use this PR's branch. So in your ```composer.json``` you should require backpack/crud version ```dev-support-uuids-plus-int-pks``` instead of ```4.0.*```, then run ```composer update```. Let me know how that branch works for you, and if you find any bugs related to this.

Cheers!

PS. Closing the issue, let's move the conversation to PR https://github.com/Laravel-Backpack/CRUD/pull/2314
