### ISSUE TITLE
sidebar is not active when click create button 

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/CRUD#2224]
# Bug report

### Backpack, Laravel, PHP, DB version:
Backpack 4.0
Laravel 6.0
PHP 7.2
mySQL 5.8

**Comment by tabacitu** [comment]
Thank you @gumpon ! 

Moved the issue to Backpack\CRUD since the layout and scripts are included there starting with v4. Backpack\Base is no longer used in v4.

@pxpm I was able to confirm the issue on v4: the links did NOT turn active when using Create, Edit or Preview operations. I've fixed it in PR #2225 - will be merged later today as 4.0.15

Thanks again for bringing this up @gumpon - quite a big bug that we were unaware of.
Cheers!
