### ISSUE TITLE
Is there any way to add custom js or js listener events for specific crud ?

### ISSUE THREAD

**Issue by ahmadkureshi** [Laravel-Backpack/CRUD#2250]
Hello I wanna know is there any way to add a custom js or at least listeners for just one specific crud ?

**Comment by pxpm** [comment]
Hello @ahmadkureshi .

Thanks for your interest in backpack. 

One way you can achieve adding custom js to your crud is by adding a [view field type](https://backpackforlaravel.com/docs/4.0/crud-fields#view) 

And in that view you can push scripts to any backpack stack.

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
@ahmadkureshi you can also [add a widget](https://backpackforlaravel.com/docs/4.0/base-widgets#creating-a-custom-widget-type) on any Backpack page you want (including all CRUD Operations). Then in that widget, you'd have the javascript you want, my recommendation is to push it to the ```after_scripts``` stack so that it's echoed at the end of the file, before the ```</body>``` tag, after jQuery and everything else has been loaded.

**Comment by ahmadkureshi** [comment]
thank you @pxpm and @tabacitu  for sharing the ways to add custom js. before your reply, i added js for all admin pages and added the condition when page URL is (specific crud) then to run js but thanks the widget and field type way are better and I think the best one adds a widget as you said to push it after the scripts as it is appropriate. 

Thank you for this wonderful backpack crud service and making development easier efficient and time-saving (Y)
