### ISSUE TITLE
[4.0][Feature Request] change pagination prev/next button and disable tfooter of datatable

### ISSUE THREAD

**Issue by paranoid73** [Laravel-Backpack/CRUD#2265]
Hi , 
I use https://backpackforlaravel.com/
by default, it shows :
[![enter image description here][1]][1] <br>
but i want applying it : <kbd>Previous</kbd> <kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> <kbd>4</kbd> <kbd>5</kbd> <kbd>...</kbd> <kbd>10</kbd> <kbd>Next</kbd> on all pages .
i don't see `<` or `>`. And next allow us to disable tfooter or footer of datatable.
It will be very nice to find this in Backpack  ,Thank you in advance

  [1]: https://i.stack.imgur.com/jdN3c.png

**Comment by pxpm** [comment]
@tabacitu i give this a look, datatables indeed have the some functionality related to this. Change pagination style, or hide it etc. But i don't think it is worth going much further on this.

If this is something we can provide, i say we should go with simple options like:

tFoot could have a switch functionality like: `show_footer => false` by default is true.

About the pagination also a switch `full_text_pagination => true` by default false. 
If true we get `next and previous` lang strings.

Both settingAPI for listOperation.

It's something we should add ?

Best,
Pedro

**Comment by tabacitu** [comment]
@paranoid73 in order to have "Previous" and "Next" instead of "<" and ">" you can create a ```resources/views/vendor/backpack/crud/inc/datatables_logic.blade.php``` file with the contents of the file in the package, but change [these two lines](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/inc/datatables_logic.blade.php#L183-L184).

@pxpm I don't think this is a customisation we should make easier. Most people must be happy with "<" and ">", since it's the first I hear about it. Personally I think that's better, since it's more general, and it doesn't even need translation. Plus it takes up less space on the screen. Let's close the issue for now. If more people ask for it, we might reconsider.

Cheers!
