### ISSUE TITLE
[4.0][Feature request] Customizable buttons on create/update form

### ISSUE THREAD

**Issue by oddvalue** [Laravel-Backpack/CRUD#2291]
At the moment lists can have custom buttons https://backpackforlaravel.com/docs/4.0/crud-buttons
It would really handy to have similar functionality for the create/update forms.
Equally it would be useful to be able to add to or alter the save actions.
e.g. add a save as draft option.

These buttons could be added to a new stack type.
e.g. `above-form` and `below-form`
Alternatively `below-new-form`, `below-edit-form`, etc... if that level of granularity would be useful.

**Comment by tabacitu** [comment]
I agree! 

It's something I've wanted for a while too, but never gotten to do it. There have been PRs for this for 3.6:
- https://github.com/Laravel-Backpack/CRUD/pull/658
- https://github.com/Laravel-Backpack/CRUD/pull/657

Not sure it's the best implementation, but I think they're a good starting point. We'll keep you in the loop @oddvalue - thanks for opening this.

**Comment by tabacitu** [comment]
@oddvalue I think you'll be happy to find that we're working on a solution for this - check out #2356 , which will get polished and merged in 2-3 weeks, when Backpack 4.1 is launched.

Closing this because I'd rather have all feedback about this in one place, in #2356 

Cheers! Thanks for raising the issue.
