### ISSUE TITLE
Many unnecessary queries

### ISSUE THREAD

**Issue by ludioao** [Laravel-Backpack/CRUD#231]
Hey @tabacitu . 

I'm with a "empty" controller, using the same generated by your package.
Also i'm using Laravel Debugbar, that is showing me around 88 queries to show ONLY 5 items, i've changed your controller to get data by repository and now the queries amount down from 88 to 64. 

I've changed this:
`$this->data['entries'] = $this->data['crud']->getEntries();`
to this:
`$this->data['entries'] = $this->productRepository->all();`

What's wrong? :(

-- The query problem: `select * from `users` where `users`.`id` = '1' limit 1`

Regards,
Lúdio.

sorry for bad english hahaha, i hope you understand.

**Comment by OwenMelbz** [comment]
@tabacitu you got any thoughts about this?

@ludioao you cannot just change to "productRepository" globally as it would not be dynamic, imagine somebody had "Gallery" but will still be something to think of

**Comment by tabacitu** [comment]
Hi guys,

So your problem would have been easily solved by eager loading your relationships. This would have fixed it, reducing your number of queries reasonably:
```php
$this->crud->addClause('with', 'permissions');
```

Buuut... I went a little further with the optimizations, because it had to be done at _some point_. So here's what I just pushed. It's invisible, but I think it's cool:
- instead of the syntax above, you can now use ```$this->crud->with('permissions');``` or ```$this->crud->with('permissions', 'roles');```;
- optimized "select" and "select_multiple" columns to use less queries;
- in the table view, we're now automagically eager loading any relationships you're using within the columns, be that "select", "select_multiple" or any other column that has an "entity" attribute;

I tried it on a number of CRUDs and it reduced my number of queries from 20-90 down to 3-6. Basically, I don't think it's possible to have a table with more than 8 queries now :-)

@ludioao , please give it a go with ```composer update``` and tell me what you think.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by zschuessler** [comment]
Thanks @tabacitu this is great!

Commit here for anyone curious as I was:
https://github.com/Laravel-Backpack/CRUD/commit/5062f668edf3a552e60c7da30a267e4bb32dc95d

**Comment by ludioao** [comment]
@tabacitu Is there any problem with the view... the eagerload still not working as well.

**Comment by tabacitu** [comment]
@ludioao still having a big number of queries?

**Comment by unstoppablecarl** [comment]
There appears to still be many unnecessary repeat calls to `CrudController::getEntry()`. There should be a clear way to get the entry and cache it, and if needed a way to get a fresh entry object.
