### ISSUE TITLE
Make this compatible with Laravel 5 Boilerplate

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/CRUD#239]
I use https://github.com/rappasoft/laravel-5-boilerplate to scaffold up an app I'm working on.  I would love to be able to add this CRUD capability.  L5 Boilerplate uses the AdminLTE as well, so it shouldn't be too much of a leap to make this compatible.  

I may create a fork and try to implement this, but was interested to see if anyone else had this or if there were any existing ideas for this.

**Comment by tabacitu** [comment]
Hi @jsiebach ,

Using it on a laravel-5-boilerplate shouldn't be too difficult. In theory, you only need to modify the [Backpack\Base views](https://github.com/Laravel-Backpack/Base/tree/master/src/resources/views), by placing them in your ```resources/views/vendor/backpack/base/```. If they have the same name, Backpack will then pick up your views, instead of the ones in your package. 

But there's currently no plan to officially support it. It would be one more thing to watch, update and offer support for and we just don't have the manpower to do that right now. But if you do it for your project, you could open-source it. I'd be more than happy to link to it and send people there. We could even create a tutorial on the new [backpackforlaravel blog](https://backpackforlaravel.com/articles/tutorials) (pretty windy there right now). I'm sure you'd be helping a bunch of people out. Plus, you'd get some views and stars to your GitHub profile, since the respository would be there.

Interested?

**Comment by jsiebach** [comment]
Yea sure!  I will play around with it and see if I can get it working.  Thanks.

**Comment by OwenMelbz** [comment]
Will be awesome to see how this turns out!

I'm just going to close this now to keep the place tidy :) but let us know once you've done it!
