### ISSUE TITLE
Adding attributes/inputs to the saveAllInputsExcept setting doesn't work as expected - I end up with unwanted inputs in the final request used to store/update

### ISSUE THREAD

**Issue by dantheman99** [Laravel-Backpack/CRUD#2404]
# Bug report

I may have just misunderstood what the operation setting `saveAllInputsExcept` is designed to be used for, but I think I've found a bug in `getStrippedSaveRequest()` in `src/app/Library/CrudPanel/Traits/Fields.php`.

I'd be more than happy to submit a PR.

### What I did

Inside a `setupUpdateOperation()` I've put:

`$this->crud->setOperationSetting('saveAllInputsExcept', array(
		    'my_input_name'
	    ));`

### What I expected to happen

I suspect the `getStrippedSaveRequest()` is meant to remove the `my_input_name` input from the request, which it does.

### What happened

But, I end up with extra inputs in the request, such as `_token` and `http_referer`.

The problem is in this line - `$this->request->except($this->getOperationSetting('saveAllInputsExcept'));`

This returns all the original inputs, from before Backpack had filtered the request, except for `my_input_name`. Whereas it should (unless I misunderstood what it's meant to do) return only  the inputs I've specified via `addField()` or `modifyField()` or from setFromDb() but without `my_input_name`.

I.e. `return $this->request->only($this->getAllFieldNames());` is not quite the opposite of `return $this->request->except($this->getOperationSetting('saveAllInputsExcept'));` in the way that I think it was meant to be.

So, the result is that inputs such as `_token` are passed through to the storing/updating code and it tries to store these values in the DB, in columns such as `_token` and of course I get an error because of this.

### What I've already tried to fix it

I could only achieve the expected behaviour by directly editing the code of the `getStrippedSaveRequest()` method. Here is what I changed it to:

```
public function getStrippedSaveRequest()
    {
        $setting = $this->getOperationSetting('saveAllInputsExcept');

        $data = $this->request->only($this->getAllFieldNames());

        if ($setting == false || $setting == null) {
            return $data;
        }

        if (is_array($setting)) {
            return Arr::except($data, $setting);
        }

        return $this->request->only($this->getAllFieldNames());
    }
```

**Comment by tabacitu** [comment]
Hi @dantheman99 ,

Indeed, to make it as general as possible we did NOT force the exclusion of things like ```_token``` or ```http_referer```, no matter what.

When you do ```$this->crud->setOperationSetting('saveAllInputsExcept', array( 'my_input_name' ));```, what happens is that the _default_ array of inputs to exclude gets overwritten with your array. You can find that array in your ```config/backpack/crud.php``` file. By default it's this:
```php
            // Before saving the entry, how would you like the request to be stripped?
            // - false - ONLY save inputs that have fields (safest)
            // - [x, y, z] - save ALL inputs, EXCEPT the ones given in this array
            'saveAllInputsExcept' => false,
            // 'saveAllInputsExcept' => ['_token', '_method', 'http_referrer', 'current_tab', 'save_action'],
```

If you modify the array there, the change will apply to ALL CRUDs. If you use ```setOperationSetting()``` inside a CrudController, the change will only apply to that CrudController.

Back to the config file - we've included an example of all inputs that should be excluded if you choose to go that way. I recommend you use that array too, and just add your input. So:

```php
$this->crud->setOperationSetting('saveAllInputsExcept', ['my_input_name', '_token', '_method', 'http_referrer', 'current_tab', 'save_action']);
```

We've chosen to do it this way because:
- some people overwrite the create/update form and don't use some of those special inputs;
- some people overwrite the create/update form and use new special inputs they don't want saved;
- so we thought the best way to go about it, is the one that allows maximum customisation; even if it's less intuitive;

I don't think there's a need for a PR here, but thank you for offering. I might be wrong though :-) It's been known to happen. Let me know if you think we should reopen this and discuss better ways to do it. We'll do so.

Cheers!

**Comment by dantheman99** [comment]
Thanks for the explanation, all clear.

Yeah, I agree with your reasoning for doing it the way you've done it.

I'll explicitly add `_token` etc to my `setOperationSetting` call.
