### ISSUE TITLE
[BEHAVIOUR] Select_from_array column error if value is not in array or null.

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#2451]
# Bug report
Undefined index: xx (View: C:\laragon\www\crudContact\vendor\backpack\crud\src\resources\views\crud\columns\select_from_array.blade.php) {"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Undefined index: xx (View: C:\\laragon\\www\\crudContact\\vendor\\backpack\\crud\\src\ esources\\views\\crud\\columns\\select_from_array.blade.php) at C:\\laragon\\www\\crudContact\\vendor\\backpack\\crud\\src\ esources\\views\\crud/columns/select_from_array.blade.php:27)

### What I did
        $this->crud->addColumn([
            'name'  => 'nationality_id',
            'label' => trans('contact.nationality'),
            'type'  => 'select_from_array',
            'priority' => 2,
            'options'   => $this->getCountries(),
            ]);

### What I expected to happen

Return "-" when key not exist

### What happened

Undefined index: xx

### What I've already tried to fix it

In field from table
"ar"  This key exists in the array.
"xx" This key does not exist in the array

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.15.1   The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                2.0.3     Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         4.0.40    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6     Generate files for laravel projects
backpack/logmanager                   3.0.3     An interface to preview, download and delete Laravel log files.
backpack/permissionmanager            5.0.6     Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                     3.0.2     Application settings interface for Laravel 5 using Backpack CRUD.

**Comment by pxpm** [comment]
Hello @DanielKimmich . Thanks for reporting.

In `select_from_array` column it is assumed that if the value **DOES NOT** exist in array, it is `null`, not some random string that does not exist in array. 

@tabacitu do you think it's worth to check if value exists in options before trying to echo ? Technically we are doing things well, it's not expected that if the column is a select from an array of values, the value don't be either one of the values of the array, or null. It would not kill having a check here if value is present before echo, but that way, null or some random value will endup as an `-` in the column, and `-` would have two meanings, what I think it's a very bad pratice. 

https://github.com/Laravel-Backpack/CRUD/blob/57b416820c740851e51a960102dd6c08fafc4b2f/src/resources/views/crud/columns/select_from_array.blade.php#L27

As for you @DanielKimmich , checkout the file, specialy the line I posted above, you can overwrite that field to suit your needs. Don't forget to copy the file first to your resources folder, otherwise it will be replaced when you update backpack.

https://backpackforlaravel.com/docs/4.0/crud-columns#overwriting-default-column-types

Best,
Pedro

**Comment by DanielKimmich** [comment]
Thank you very much for the reply

A possible solution and to differentiate from null use the value "?"

                if(array_key_exists ($values , $column['options'] )) {
                    echo $column['options'][$values];
                } else {
                    echo '?';
                }

**Comment by pxpm** [comment]
Indeed @DanielKimmich that would make the difference.

Thing is, if you have a list of values that are available to that column (i mean, column in database), the values in that column should always be on that list no ? You should use the same list when creating the db record ?

That's why I am wondering if even creating a visual diference, it makes sense in terms on application logic. 

Maybe you better using the closure column, and if check yourself if item is not in array return whatever text you want to the column. No need to overwrite any files.

Best,
Pedro

**Comment by DanielKimmich** [comment]
Yes, the same list is used. What can happen is that for some reason options are removed from the list and then it is unrelated to the other tables and can cause this error.
Thanks, but using the closure column requires a more development.
D.K.

**Comment by tabacitu** [comment]
Hmm... this was a little trickier to decide than I originally thought 😄 

At first I agreed with @pxpm here:

> It would not kill having a check here if value is present before echo, but that way, null or some random value will endup as an - in the column, and - would have two meanings, what I think it's a very bad pratice.

But then I thought about it, and I guess the data _could_ get corrupted from the front-end forms (not Backpack admin interface). And in that case, it would be a pain to debug by the admin, since all that Backpack would do is throw an error like this:
![Screenshot 2020-02-16 at 09 16 24](https://user-images.githubusercontent.com/1032474/74600642-217ab980-509d-11ea-8bb4-082f52bfe30b.png)

I've created a PR that provides a fallback in case the value is not in the array. But I think a better fallback would be the actual value (ex: ```xx```) instead of ```-``` or ```?```. That would be most informative, I think. And would:
- fix @pxpm 's problem of ```-``` having two meanings;
- fix @DanielKimmich 's problem of having to explain what ```?``` means;

PR here: https://github.com/Laravel-Backpack/CRUD/pull/2455
Merging now.

Let me know if you think we should change this in any way - for now at least we do _something_ in this use case.

Cheers!

**Comment by DanielKimmich** [comment]
Excellent, thank you very much.
