### ISSUE TITLE
Repeater Field for N-N relationship

### ISSUE THREAD

**Issue by PhouvanhKCSV** [Laravel-Backpack/CRUD#247]
Hi

I wonder if how can we do something like repeater-field (or whatever name).

For example: I have 3 tables:
1. products: hold all products
2. components: hold all components
3. product_component: hold all product components, 1 product has many component and 1 component belong to many product. (N-N)

| products | components | product_component |
|------------|------------|-------------------|
| id | id | product_id |
| name | name | component_id |
| unit | unit | quantity |
| created_at | created_at |  |
| updated_at | updated_at |  |

I can archive this (n-n insert/update) with `select2_multiple` field type if i only have `product_id` and `component_id` in `product_component` table, but i cannot insert `quantity` because there is no field for it.

it will look similar to `table` field type except table field only have `text input` and it is store data as JSON in one column, which in my situation `component_id` field should be `select or select2` type, `quantity` should be `number` type and store to different columns.

Could we do something like this which take care all CRUD operation?
(Example: [https://github.com/DubFriend/jquery.repeater](https://github.com/DubFriend/jquery.repeater))

<img width="787" alt="screen shot 2016-11-18 at 4 56 16 pm" src="https://cloud.githubusercontent.com/assets/10794184/20426774/44950f96-adb3-11e6-8a5c-c8b68c9dfea1.png">

**Comment by tabacitu** [comment]
Hi @PhouvanhKCSV ,

I think this is a pretty specific need, I don't think implementing a solution for this in the core backpack would be general enough to be useful to most people/needs.

But you can implement it for your project by creating a custom field starting from [the table field](https://laravel-backpack.readme.io/docs/crud-fields#section-table). If it's self-contained in that one file, I think we can put it up on backpackforlaravel.com - I plan to have a "snippets" area for this kind of stuff, so that we can all reuse niche code that others have created and already works.

Does that sound like a good solution to you?

Thanks, cheers!

**Comment by PhouvanhKCSV** [comment]
Thank you for you suggestion @tabacitu 

The ideas is like #132 where we can add other fields rather than `text input`
