### ISSUE TITLE
[4.x] Bump Line-Awesome/Font-Awesome version

### ISSUE THREAD

**Issue by juventus18** [Laravel-Backpack/CRUD#2485]
It looks like BP is using v1.1 of Line-Awesome, but the package is now v1.3. Backpack should update the package so we have access to all current icons (for example `<i class="las la-icons"></i>`  is missing).

I tried to update the package by placing the CDN into `config/backpack/base.php` but it broke other icons like the sort icons at top of DataTable headers and the icon on left side to expand all table values (triple dots).

I could probably make the PR for this, but I won't be able to get to it for a while if someone else wants to pick it up...

**Comment by juventus18** [comment]
I think the best option would be to make it a composer dependency so we can update whenever we want, but there is no package yet (at least none I can find on https://packalyst.com/)

**Comment by tabacitu** [comment]
Indeed, thank you @juventus18 , it's now on the list for the upcoming 4.1 launch (due next week probably, after Laravel 7 is launched).

If I remember correctly, we kept postponing this line-awesome upgrade because after 1.1 they actually changed the folder structure. So we had to either do some magic to publish it to the same folders and filenames, or wait for the next version of Backpack to come around, when we can push breaking changes. And it's _almost_ here now 😄

**Comment by tabacitu** [comment]
Fixing in https://github.com/Laravel-Backpack/CRUD/pull/2553

This will be a breaking change. Line Awesome has changed syntax in line with Font Awesome 5.x. The good news is that there are 1000+ icons now, and they have parity with the free version of Font Awesome. The bad news is that some icons just don't work anymore, you have to find the new counterparts. For example:
- ```fa-group``` is now ```fa-user-friends```
- ```fa-newspaper-o``` is now ```fa-newspaper```

More information will be available in the PR, and in the upgrade guide.
Closing for now, as it will be treated in https://github.com/Laravel-Backpack/CRUD/pull/2553
