### ISSUE TITLE
Summernote field: add link modal is behind overlay

### ISSUE THREAD

**Issue by megatommy** [Laravel-Backpack/CRUD#2493]
# Bug report
Hello, this is the first time I'm reporting an issue, so let me know if I have to change anything :)

### What I did

I've added a summernote field to an entity with a "add link" button. When I'm on the edit page and I click the "add link" button, the modal appears, but "behind" the overlay. This causes the whole page to be unusable and a refresh is needed (since you cannot close the modal because of it).

I checked if it also happens on the demo of Backpack, and also there it happens

### What I've already tried to fix it

I saw that adding `dialogsInBody: true` as an option to the summernote initialization solved my issue. I was thinking - since all summernote fields will have to have this option - to add the `dialogsInBody: true` as a default.

If I'll figure out how to create a Pull Request I will create one if it's appreciated. 

According to my composer.lock file I'm running backpack/crud version `4.0.41`

These screenshots are from the Backpack demo itself:

![image](https://user-images.githubusercontent.com/5624704/75613442-15c3d400-5b2e-11ea-8cba-0501ef3a3209.png)
![image](https://user-images.githubusercontent.com/5624704/75613455-30964880-5b2e-11ea-8d3e-20151edb877a.png)

**Comment by tabacitu** [comment]
@megatommy - don't worry about it, this is one of the best issue reports I've seen all year 😄 Excellent! 🎈 🎉 Thank you!

I can confirm the problem, and the solution. No need for a PR this time - I've pushed the hot fix in https://github.com/Laravel-Backpack/CRUD/commit/192eb8c833b30f2fbedd7705f13ad888b4b02f30 . It's already on the ```master``` branch, it'll be tagged and available with a ```composer update``` later today, as Backpack\CRUD 4.0.42 (patch release).

Thanks again for taking the time to report this, and to craft such a good issue - it _really_ helps in pushing fixes faster. For reference, this issue was probably caused by Bootstrap 4, where they require the modals to be directly inside the ```<body>``` element. Details here https://github.com/Laravel-Backpack/CRUD/commit/192eb8c833b30f2fbedd7705f13ad888b4b02f30 .

**Comment by megatommy** [comment]
@tabacitu thank you for the compliment! If I find anything else I'll let you know! I only recently started usng Backpack and I already like it a lot! Keep up the good work!
