### ISSUE TITLE
Hi, I would like to customs preview page in backpacker. I want to show image with my preview column. So, what should I go with this?

### ISSUE THREAD

**Issue by sokvebolkol** [Laravel-Backpack/CRUD#2544]
# Bug report

### What I did

??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
Sorry I don't understand what you're trying to achieve, but [check out the docs for the Show operation](https://backpackforlaravel.com/docs/4.0/crud-operation-show) and on [creating a custom column type](https://backpackforlaravel.com/docs/4.0/crud-columns#creating-a-custom-column-type). They might help.

Closing this since it's not the appropriate medium for this conversation. Please read the notice above.

**Comment by sokvebolkol** [comment]
Dear @tabacitu, thank you for answering my question. That is help me to find solution:)
