### ISSUE TITLE
Set Checkbox dependency[question]

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2573]
Hello, I spent dime hours trying to find the solution to this problem, reading the documentation and some threads in stackoverflow, and I did not find the answer.
I am trying to define two checkboxes (A, B) in which when check A allows me to check B, but if unckeck B it should also unchek A.
Is there some way defining some extra attribute with the field checkbox to achieve this? Or will I have to create my own field? Maybe apply some JS but where?
I've seen the field checklist dependency but I don't have two separate tables and I don't think it's the best option to achieve something as simple as this.

**Comment by tabacitu** [comment]
Hi @rUriarteDev ,

We don't have anything like as a default field. Best to [create a custom field type](https://backpackforlaravel.com/docs/4.0/crud-fields#creating-a-custom-field-type), since the JS logic itself should be pretty simple. You can start from the ```checkbox``` field, or take inspiration from the ```checklist_dependency``` field - that might help.

Cheers!
