### ISSUE TITLE
Malformed JSON in "table" field when casting

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/CRUD#259]
I have a table as a field type in my model, but when I update the model, the JSON in the database isn't right.  This is what I'm seeing:

`"[{\"form_field_name\":\"name\",\"readable_key\":\"Name\"},{\"form_field_name\":\"email\",\"readable_key\":\"Email\"}]"`

Where it should be 

`[{"form_field_name":"name","readable_key":"Name"},{"form_field_name":"email","readable_key":"Email"}]`

When I turn off auto-casting by commenting out `protected $casts = ['fields'=>'array'];`, the DB column saves properly.  Is this an encoding issue of some kind?

I currently solve this by using an extra accessor for the decoded version of the property.

**Comment by OwenMelbz** [comment]
have you tried changing the $casts to `json` rather than `array` ?

**Comment by jsiebach** [comment]
Tried, no luck - it saved it in the same malformed way and also doesn't make it any easier to access on the other end

**Comment by tabacitu** [comment]
I don't want to be _that guy_, but isn't it actually recommended to store JSON escaped in the db, because it's more secure? 

I mean, look at the description of PHP's ```addslashes()``` method: _This function can be used to prepare a string for storage in a database and database queries._ Similar with ```mysqli_real_escape_string()```, ```pg_escape_literal()```, ```pg_escape_string()```.

For my purposes, I think it's ok to store it that way, as long as the attribute casting gets rid of the slashes when you retrieve it. Wouldn't you agree? What would be the downsides of storing it this way?

Cheers!

**Comment by jsiebach** [comment]
This isn't storing a JSON string in the DB though, its storing a JSON encoding of a string.  The DB column is a text column, but it is including quotes around the JSON, and then escaping the quotes throughout the JSON.  Basically, this is what you would see if you called `json_encode(json_encode($foo))`.  Attribute casting doesn't get rid of this issue on the retrieval side - it automatically calls `json_decode()` on the attribute, but that still returns a string, which is something we can't iterate over.

To put it another way - the request value when you post `table` field is a string.  When you use casting, be it object or array, Laravel calls `json_encode()` on the attribute when you save it.  So now we have encoded it twice.  On retrieving the attribute, we're only decoding once and left with a string.

I have solved this by writing a mutator for the field that over-writes the normal behavior of Laravel casting.  The `$casts` ensures that it is `json_decoded` on the way out, but the mutator function DOESN'T encode it on the way in - because the table field already sends an encoded string:

    protected $casts = [
	'fields' => 'object'
	];

	public function setFieldsAttribute($json)
	{
        $this->attributes['fields'] = $json;
	}

Outside of writing either an accessor or a mutator, the only way I could think of to improve this would be to re-write the `table` field blade template to make it's value an array of objects when serialized.  Then Laravel would receive an array and encode it as intended.  But if we're going to post a string, we can't let Laravel cast it for us on the way in.

Hope that all makes sense and I'm not missing something - thank you!

**Comment by OwenMelbz** [comment]
@jsiebach @tabacitu 

I've had a look into this and figured out where the issue lays.

Basically when using `$casts = array/json/object` - laravel will convert the PHP array/object into unescaped json and save it into the database.

However, the table input sends JSON to the server, which effectively is a string.

So as I mentioned before, laravel will convert array/objects into json. The field is already json.

So it effectively htmlescapes it and puts it into the database, which means you cannot use the json data as you'd expect, especially when you use the json database type it cannot look it up etc.

The trouble comes from the form sends JSON to the server, not an array/object, so laravel casting wont work.

Currently the way to get it to work without realising a new version would be

```php
protected $casts = []; // DO NOT CAST IT

public function getJsonAttribute($value)
{
     return json_decode(stripslashes($value), true);
}

```

I'm going to have a look to see if the data can be sent as an array rather than json from the form.

**Comment by OwenMelbz** [comment]
I've added a new point of processing within the create/update methods.

This allows an entry point to mutate data behind the scenes, which also includes fixing the above issues

**Comment by OwenMelbz** [comment]
Added into [consolidated issue list](https://github.com/Laravel-Backpack/CRUD/issues/285), as there is a PR and a work around, I'm closing off this to keep the place tidy, can still be discussed however :)

**Comment by tabacitu** [comment]
Boom! Fixed by the latest push, in ```Backpack\CRUD 3.1.48```. Great teamwork here, guys :-)

Cheers!

**Comment by OwenMelbz** [comment]
Lovely :) is that mergable with 3.2?

**Comment by tabacitu** [comment]
Yup, done that too.

**Comment by OwenMelbz** [comment]
Woo! Must say, been using 3.2 for around 1.5 months now happily, havent come across any other issues (except the ones i've added PR for) so thats surely a good sign!

**Comment by tabacitu** [comment]
:-) yup. Two stable branches FTW! Laravel 5.4 is launching in January, and Backpack\CRUD 3.2 the next few days. I bet we will have all major features finished by then, so 3.2 might end up being the first LTS Bakpack\CRUD version.

**Comment by OwenMelbz** [comment]
That would be lovely :D although **"my ideal"** 3.2 release would have

https://github.com/Laravel-Backpack/CRUD/pull/289
https://github.com/Laravel-Backpack/CRUD/pull/287
https://github.com/Laravel-Backpack/CRUD/pull/283
https://github.com/Laravel-Backpack/CRUD/pull/224
https://github.com/Laravel-Backpack/CRUD/pull/165
https://github.com/Laravel-Backpack/CRUD/pull/164
https://github.com/Laravel-Backpack/CRUD/pull/162
https://github.com/Laravel-Backpack/CRUD/pull/157
https://github.com/Laravel-Backpack/CRUD/pull/136
An updated version of -> https://github.com/Laravel-Backpack/CRUD/pull/124

**Comment by MickaelTH** [comment]
![2017-07-08 001771](https://user-images.githubusercontent.com/26375917/27985232-b0edbb88-6411-11e7-9141-adfa1eb47ec5.png)

It seems I have the same issue. The doc inform that we should cast the column, or shoud we not?

Using CRUD 3.2.13
