### ISSUE TITLE
cannot edit n to n 

### ISSUE THREAD

**Issue by sokvebolkol** [Laravel-Backpack/CRUD#2590]
# Bug report
array_key_exists(): The first argument should be either a string or an integer
### What I did
I do the crud n to n. 
??

### What I expected to happen
I can insert update and delete the data with n ot n relationship. 
??

### What happened
I can insert and delete, but I can't edit it
??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by sokvebolkol** [comment]
Now, it is working with the error, but I cannot show the option with select order.
This is my edit view:
![image](https://user-images.githubusercontent.com/44717892/77281234-1d276900-6cf9-11ea-8a2d-b098d99c6d05.png)
Please, anyone, help me

**Comment by tabacitu** [comment]
Sorry @sokvebolkol , but I really can't figure out what the problem is, without knowing exactly what you've done - what field have you've added, how you've done that, how the relationships are defined in your Model.

That being said, I've just tested all relationship fields a few days ago and they worked fine. So it's most likely a problem in you code, not Backpack.

**Comment by sokvebolkol** [comment]
This is my event model:
    public function speakers(){
        return $this->belongsToMany('App\Models\Speaker')->withTimestamps();
    }
And This is my speaker model:
    public function events(){
        return $this->belongsToMany('App\Models\Event')->withTimestamps();
    }
After migrate table, It worked fine. I can insert and delete. But I cannot edit the data as I mentioned above. please help me:)
