### ISSUE TITLE
How to create a modal button with Backpack?

### ISSUE THREAD

**Issue by tsnobre90** [Laravel-Backpack/CRUD#2607]
# How to create a modal with Backpack?

Dear colleagues, for Backpack study purposes, I would like to know how to create a modal button next to the select state, as shown in the screen project below?

I have the following project of screens to add state.

![Adicionar Estado](https://user-images.githubusercontent.com/57007736/77834380-27939980-7123-11ea-8615-ff625d716276.png)

<br>

And the next to add city.

![Adicionar Cidade](https://user-images.githubusercontent.com/57007736/77841114-41ee6700-7165-11ea-8c42-cead0499bdb5.png)

<br>

However I want to click on add state to open a modal without the user having to leave the add city screen as shown in the image below.

![Adicionar Cidade com Estado](https://user-images.githubusercontent.com/57007736/77834922-3714e180-7127-11ea-97c3-4808c27e92ab.png)

<br>

However, I did not find it in the Backpack documentation, and being able to make the following screens to date, as shown in the StateCrudController and CityCrudController.

![Backpack-Estado](https://user-images.githubusercontent.com/57007736/77835180-0df55080-7129-11ea-9839-1ab4874ebc6a.png)

![Backpack-Cidade](https://user-images.githubusercontent.com/57007736/77835184-151c5e80-7129-11ea-89af-86d7d6642561.png)

<br>

Following the standard Backpack documentation, below are the state and city CrudController codes:
        
        //StateCrudController
        $this->crud->addField([
                    'name' => 'name',
                    'type' => 'text',
                    'label' => 'Nome'
        ]);
        
        $this->crud->addField([
                    'name' => 'abbreviation',
                    'type' => 'text',
                    'label' => 'Sigla'
        ]);
        
        //CityCrudController
        CRUD::addField([
            'label'     => 'Nome do Estado',
            'type'      => 'select2',
            'name'      => 'state_id',
            'entity'    => 'states',
            'attribute' => 'name',
        ]);

        CRUD::addField([
            'label' => 'Nome da Cidade',
            'type' => 'text',
            'name' => 'name',
        ]);

#### Sorry me my English

Thiago Nobre

**Comment by AbbyJanke** [comment]
Hello @tsnobre90 under the `config/backpack/crud.php` you will find settings for each type of CRUD operation. If you look under `create` you will see the `defaultSaveAction` you are looking for the 'save_and_edit` this will take users back to the update screen. Also if you look at the green button there is an error, if you select that you can manually choose each function that you would like. If you do not want users to be able to do that you can set `showSaveActionChange` to false in the save config area.

**Comment by tabacitu** [comment]
Thanks for the help @AbbyJanke . Buttaaa... it sounds to me like that's not what @tsnobre90 asked for 😆  The way I read it, he's looking to create a _related entry_ inside the create/update form. I might be wrong though.

@tsnobre90 if you're looking for something like this:
![2020-03-30 12 00 10](https://user-images.githubusercontent.com/1032474/77894666-40fd2880-727e-11ea-8faa-63604e6c5619.gif)

I have _very_ good news. The feature is ready, but not yet launched. We call the new field "relationship" (instead of select) and the actual operation InlineCreate. To use it, though, you have to upgrade to Backpack 4.1, which is currently in alpha, but I expect it'll reach a "_stable beta_" status by the end of the week. Take a look at:
- [Backpack 4.1 upgrade guide](https://backpackforlaravel.com/docs/4.1/upgrade-guide)
- [relationship field in 4.1](https://backpackforlaravel.com/docs/4.1/crud-fields#relationship)
- [InlineCreate operation in 4.1](https://backpackforlaravel.com/docs/4.1/crud-operation-inline-create)

Hope it helps.
Cheers!

**Comment by tsnobre90** [comment]
Thanks for the help @AbbyJanke!

That cool, @tabacitu!

Thanks for the help. I am a big fan of your work.

But as I am not getting all the necessary resources in a timely manner to develop my system for the College's Undergraduate Work, I am resorting to pure Laravel. However, I would love to use all of these features in the future.

I would also like to ask other questions about Backpack, related to permissions. Do I open another discussion forum or take advantage of this forum?

**Comment by tabacitu** [comment]
No problem. If it's related to https://github.com/Laravel-Backpack/PermissionManager, please open an issue there.
