### ISSUE TITLE
Datatable pagination are not working properly work with backpack

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2650]
# Bug report

I add column reorder option to datatable after that if i change the column order using column reorder it work. that page table header and body value also reorder according to column reorder but if i go to another page using pagination tab (next) then that page table header only reordered and table body did not reordered.

I expect pagination page table body also look reordered.

How to fix this in backpack datatable?

If i implement same thing in datatable only it works perfectly.
sample: [http://live.datatables.net/liqiluga/2/edit](url)

**Comment by tabacitu** [comment]
Hi @senthu1994 ,

I'm afraid I don't understand. What do you mean by "_column reorder option_"? Is it a datatable plugin? Show us some code/link please. It sounds to me like you've customized the ```datatables_logic.blade.php``` file, but something doesn't work with your modified file, right?

Cheers!

**Comment by senthu1994** [comment]
Hi @tabacitu Yes your are correct i modified `datatables_logic.blade.php` and add some datatable plugin to that
for reorder purpose i add 
`colReorder: {
            enable: false
        },` in that file.

**Comment by tabacitu** [comment]
Got it. In that case I'm sorry, we can't help with that. We keep Github for bugs only. Please ask for help on our Gitter or StackOverflow, but I doubt anybody will be able to help since it's about how you customised that file. 

What you're saying _should theoretically_ be possible. But keep in mind we're also using a bunch of other DataTables plugins like Responsive and Export - and DataTable plugins regularly have conflicts between them - that might be your problem.

Sorry I can't be of more help.
Cheers!

**Comment by senthu1994** [comment]
Hi @tabacitu I already added in stackoverflow [https://stackoverflow.com/questions/61073611/datatable-pagination-not-working-properly-work-with-backpack](url) But no one yet response for my question. If you have time please response it. Anyway thanks.
