### ISSUE TITLE
[4.1.x] Select2 mismatched styles (different height than regular select or other inputs)

### ISSUE THREAD

**Issue by juventus18** [Laravel-Backpack/CRUD#2655]
# Bug report

### What I did

the styling for `select2` form controls does not match that of other controls

### What I expected to happen

styling should match

### What happened

using latest Chrome, the `select2` form controls have a "smaller height" from other elements. You can see this on the demo page https://demo.backpackforlaravel.com/admin/article/1031/edit
(the `select2` fields are shorter than "Status", for example). Its hard to notice on that page because they are on different lines, but I have some fields that are side-by-side and it is really obvious

### What I've already tried to fix it

nothing. I think some of the bundle CSS needs to be modified to work with CoreUI

### Backpack, Laravel, PHP, DB version

Whatever the demo is running lol

**Comment by tabacitu** [comment]
Totally agree! 

It's something I've noticed too, and bothers me every time, but I never got around to fixing it.

**Comment by juventus18** [comment]
I'm not sure if this is exact, but I was able to get it close using:
```
.select2-container .select2-selection {
	line-height: 1.6 !important;
	height: 2.375rem !important;
	border-radius: 3px !important;
}
```
in a custom css file. 

If the load-ordering is changed as suggested in #2283 I don't think `!important` will be needed

**Comment by tabacitu** [comment]
Note: also important is [your comment here](https://github.com/Laravel-Backpack/CRUD/issues/2283#issuecomment-613037020)

**Comment by martijnb92** [comment]
I would be happy to submit a pull request for this however I'm not sure what would be the best option.
Cleanest option would be to edit the custom file in the backstrap theme package
`@digitallyhappy\backstrap\src\scss\_custom.scss`
The fastest would be to edit `public\packages\backpack\crud\css\edit.css` / `create.css`

The CSS is a bit all over the place, I assumed the `public\packages\backpack\crud\css\...` files are for custom edits but the files `lists.css` and `form.css` are not empty. 

Why is the content of those two files not included in the build via the backstrap _custom.scss file?
Isn't it better to adjust the backstrap theme by moving the _custom.scss file to the CRUD repo, since those edits are specifically made for Backpack? 
It would only require a small adjustment to the build process..

I created a custom build myself to overwrite some of the variables to fit my theme.

**Comment by tabacitu** [comment]
I see places where we can put that bit of CSS:
(A) inside the `form.css` file - but the fix will only be available to people who install Backpack after this;
(B) inside the `form_content.blade.php` file - but then it'd be loaded even if there's no Select2 on page;
(C) inside Backstrap's `src/scss/_custom.scss` file - but again, it'd only be available to people who install Backpack after this;
(D) inside the fields that actually use Select2; yes it will be duplicated across fields that use `select2` for now; but once we do https://github.com/Laravel-Backpack/CRUD/pull/2652 , in Backpack 4.2, that bit of CSS can be loaded only once per page; 

I'm inclined to say option (D) has the most benefits, but it would introduce a bit of a mess until 4.2. Option (C) would also be a good one in my opinion, since we already have Select2 CSS overwrites in that file. 

What do you guys think?

**Comment by promatik** [comment]
@tabacitu I think we should go for option (A), add it inside `form.css` because;

1. It's not a super important change that everyone should be getting now.
2. We wouldn't bloat our fields with general rules that should not be there.

I believe the rules inside form.css and list.css should be on backstrap custom, maybe the best solution is to migrate rules from these files on v4.2 and leave these files for the developers. And maybe then, on v4.2, create some kind of system to be able to push new css rules in case we need.

**Comment by tabacitu** [comment]
@promatik agreed - `form.css` it is, we can push it as a non-breaking change in 4.1. 
Can you or @martijnb92 please put together a PR for this and test it out?

Cheers!

**Comment by promatik** [comment]
I've just created a PR to fix this, let's move the conversation there; https://github.com/Laravel-Backpack/CRUD/pull/3397
