### ISSUE TITLE
Bug in route:list after installing package

### ISSUE THREAD

**Issue by shivanikoko** [Laravel-Backpack/CRUD#2693]
# Bug report

### Give Error:
![image](https://user-images.githubusercontent.com/12964707/79733967-92e01e00-8313-11ea-9a05-57bcf8262d8d.png)

**Comment by tabacitu** [comment]
Oh ok, I understand now @shivanikoko . Indeed, if you have a different User model, or don't want to use App/Models/BackpackUser, you should change the configuration to use your custom User model, after you first install Backpack. 

There's a note about this in [Step 3 of the installation process](https://backpackforlaravel.com/docs/4.0/installation#install-core-packages) - you must have missed it. So I'll close the issue, since the docs mention it.

Cheers!
