### ISSUE TITLE
Bulk action not working for large data collection

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2697]
I have created an opreration to select rows by bulk action, if I select all rows by the first checkbox, I get a total of 1464 rows (crud.checkedItems.length), but my variable $entries in the operation only get 1001 rows, this number is static if I select more than 1001 rows, no matter how many rows are selected 1k, 2k, 3k ...
Then the operation is not performed on all the selected rows, but only on the first 1001.

THIS IS MY BUTTON FOR BULK OPERATION
```php
@if ($crud->hasAccess('asistenciaFBH') && $crud->get('list.bulkActions'))
<a href="javascript:void(0)" onclick="asistenciaFBH(this)" class="btn btn-sm btn-secondary bulk-button"><i
    class="fa fa-check"></i>Asistio (FBH)</a>
@endif
@foreach (Alert::getMessages() as $type => $messages)
@foreach ($messages as $message)
<div class="alert alert-{{ $type }}">{{ $message }}</div>
@endforeach
@endforeach

@push('after_scripts')
<script>
  if (typeof asistenciaFBH != 'function') {
    function asistenciaFBH(button) {

        if (typeof crud.checkedItems === 'undefined' || crud.checkedItems.length == 0)
        {
            new Noty({
            type: "warning",
            text: "<strong>{{ trans('backpack::crud.bulk_no_entries_selected_title') }}</strong><br>{{ trans('backpack::crud.bulk_no_entries_selected_message') }}"
          }).show();

          return;
        }

        var message = "Esta seguro que desea cambiar el estado de :number inasistencias a asistencias ?";
        message = message.replace(":number", crud.checkedItems.length);

        // show confirm message
        swal({
        title: "{{ trans('backpack::base.warning') }}",
        text: message,
        icon: "warning",
        buttons: {
          cancel: {
          text: "{{ trans('backpack::crud.cancel') }}",
          value: null,
          visible: true,
          className: "bg-secondary",
          closeModal: true,
        },
          delete: {
          text: "Aceptar",
          value: true,
          visible: true,
          className: "bg-primary",
        }
        },
      }).then((value) => {
        if (value) {
          var ajax_calls = [];
          var asistio_route = "{{ url($crud->route) }}/bulk-asistio";

          // submit an AJAX delete call
          $.ajax({
            url: asistio_route,
            type: 'POST',
            data: { entries: crud.checkedItems },
            success: function(result) {
              Object.keys(result).forEach(function(status) {
              //result.forEach(function(status) {
                if (status == false) {
                  Object.keys(result[status]).forEach(function(message) {
                    console.log(status)
                    new Noty({
                    timeout: false,
                    type: "info",
                    text: "<strong>Algunos datos no son validos</strong><br>"
                      +Object.keys(result[status][message]).length
                      +" Registros no se pueden modificar porque no cumplen la siguiente condicion: <br>"
                      +message
                    }).show();
                  });   
                }

                if (status == true) {
                  Object.keys(result[status]).forEach(function(message) {
                    new Noty({
                    timeout: false,
                    type: "success",
                    text: "<strong>Datos actualizados</strong><br>"
                      +Object.keys(result[status][message]).length+" "
                      +message
                    }).show();
                  });              
                }         
              });
              crud.checkedItems = [];
              crud.table.ajax.reload();                   
            },
            
            error: function(result) {
              // Show an alert with the result
                    new Noty({
                    type: "error",
                    text: "<strong>Operacion Fallo</strong><br>"
                  }).show();
            }
          });
        }
      });
      }
  }
</script>
@endpush

```
THIS  IS MY OPERATION
```php
<?php

namespace App\Http\Controllers\Admin\Operations;

use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

trait AsistenciaFBHOperation
{
    /**
     * Define which routes are needed for this operation.
     *
     * @param string $segment    Name of the current entity (singular). Used as first URL segment.
     * @param string $routeName  Prefix of the route name.
     * @param string $controller Name of the current CrudController.
     */
    protected function setupAsistenciaFBHRoutes($segment, $routeName, $controller)
    {
        Route::post($segment . '/bulk-asistio', [
            'as'        => $routeName . '.asistenciaFBH',
            'uses'      => $controller . '@asistenciaFBH',
            'operation' => 'asistenciafbh',
        ]);
    }

    /**
     * Add the default settings, buttons, etc that this operation needs.
     */
    protected function setupAsistenciaFBHDefaults()
    {
        $this->crud->allowAccess('asistenciaFBH');

        $this->crud->operation('list', function () {
            $this->crud->enableBulkActions();
            $this->crud->addButtonFromView('bottom', 'asistenciaFBH', 'asistenciaFBH', 'end');
        });
    }

    /**
     * Show the view for performing the operation.
     *
     * @return Response
     */
    public function asistenciaFBH()
    {
        $this->crud->hasAccessOrFail('update');

        $entries = $this->request->input('entries');

        $hoy = Carbon::now();
        $data = collect();
        foreach ($entries as $key => $id) {
            if ($asistencia = $this->crud->model->find($id)) {
                $fi = $asistencia->inscripcion->fecha_inscripcion;
                $fi = Carbon::parse($fi);
                if (($asistencia->asistencia_fbh == true) or ($asistencia->asistio == true)) {
                    $data->push([
                        'status' => false,
                        'message' => 'No se puede asignar una asistencia a un registro que ya tiene ese estado',
                        'comensal' => $asistencia->inscripcion->user->name,
                        'fecha' => $asistencia->inscripcion->fecha_inscripcion,
                    ]);
                } elseif ($hoy->toDateString() > $fi->toDateString()) {
                    $data->push([
                        'status' => false,
                        'message' => 'No se puede editar una asistencia anterior a la fecha de hoy',
                        'comensal' => $asistencia->inscripcion->user->name,
                        'fecha' => $asistencia->inscripcion->fecha_inscripcion,
                    ]);
                } else {
                    $asistencia->asistencia_fbh = true;
                    $asistencia->fecha_asistencia = Carbon::now()->toDateTimeString();
                    $asistencia->save();
                    $data->push([
                        'status' => true,
                        'message' => 'Registros Fueron actualizados correctamente',
                        'comensal' => $asistencia->inscripcion->user->name,
                        'fecha' => $asistencia->inscripcion->fecha_inscripcion,
                    ]);
                }
            }
        }
        $data = $data->groupBy([
            'status',
            function ($item) {
                return $item['message'];
            }
        ], $preserveKeys = true)->toArray();
        $data = response()->json($data);
        return $data;
    }
}
```
![image](https://user-images.githubusercontent.com/39219144/79923128-4841cd00-840b-11ea-9b59-4f8859895985.png)
![image](https://user-images.githubusercontent.com/39219144/79923264-82ab6a00-840b-11ea-8efd-0745ba004fc2.png)

**Comment by tabacitu** [comment]
Hi @rUriarteDev ,

As I said in your other issue https://github.com/Laravel-Backpack/CRUD/issues/2696 - I think you're really stretching what Bulk operations are supposed to be 🤣  If you're determined to do bulk operations on 2000 entries at once, please follow my recommendations there. Doing something on 2000 rows is a different ballgame than doing the same thing on 20.

That being said, I was curious why the very specific 1001 number so I tested this myself - looks like you can increase your ```max_input_vars``` in your PHP configuration to get over this limit:
![Screenshot 2020-04-22 at 07 38 04](https://user-images.githubusercontent.com/1032474/79941484-16f9e900-846d-11ea-9116-34314055f235.png)

You can. But you shouldn't. From my point of view, whenever you hit a PHP configuration limit, you SHOULD NOT think about changing that config value. You SHOULD think about how to do things differently, so that you don't hit that limit. It's not PHP, it's you 😆 As I said, BulkOperations really aren't supposed to be performed on 2000 entries at once. It makes no sense to show 2000 rows at once, and select 2000 rows - nobody's ever going to read 2000 rows.

Maybe a better idea would be to create a new button, something like "Do X for visible entries". Then you wouldn't need the bulk buttons - you'd perform the action on the current ```$crud->query```. That should also work if you have filters applied. That's one way to circumvent the 1000 ```max_input_vars``` limit. But you should still properly code the operation itself, using a queue or something, so that it doesn't take a lot of time.

Hope it helps. I'm going to close this, as I can't consider this a bug in Backpack. It's a PHP config issue on your machine.

Cheers!

**Comment by rUriarteDev** [comment]
Ok you convinced me to change this haha, i will try another implementation for this, but still my biggest concern is the response time of the other issue, when you can please take a look on my answer.

**Comment by ahmadmobaraki-updivision** [comment]
Hello @tabacitu ! 
This is how I'm going to implement bulk operation on thousands of rows (filtered rows not checked by checkbox); please advise if it's a good practice or not.

We have a custom bulk edit operation that shows a "Bulk edit" button in the list page, it is used to edit some specific db table fields. Basically the button is a simple blade view, when clicked, a modal form shows up with some empty input fields to bulk edit. when the user fills the inputs and submits the form, it sends an ajax request to controller action. Now to send the actual $query of the filtered results to the backend, I use `{{ $crud->query->toSql() }}` inside my js code in my blade view. So for example inside the action we receive something like this: "select * from users when name like %abc%..." a string! then we run this raw query and perform the edit operation on each of the results one by one (of course in a queue!). 

Thank you so much in advance!

**Comment by o15a3d4l11s2** [comment]
I need to check this in details, but here is a case where I got a similar problem (reaching `max_input_vars`) and we approached it by sending all data as single JSON variable instead of multiple variables: https://github.com/Laravel-Backpack/CRUD/issues/3722

Related to @ahmadmobaraki-updivision I think sending the selected ids only in the way I described would be safer.

**Comment by ahmadmobaraki-updivision** [comment]
@o15a3d4l11s2  Thank you! I need to perform bulk operation on thousands of rows like 3000!  it's not possible to see/select them in the page.

**Comment by pxpm** [comment]
Hello @ahmadmobaraki-updivision you should "re-apply" the filters from the datatable url otherwise your query may be tempered I guess?

We are working on an export package (got a bit delayed since we are not confortable yet with the solution, working on it 🙃 ), but we needed this bit of functionality, so when the user click the button we send the datatables url and search term, and re-apply it on the php side. 

So basically you re-apply it, and apply the changes in the rows returned from the query, the same rows you have in datatables without having to "show all on page". 

Solution provided by @o15a3d4l11s2 is good if you are circunventing some hundred limit, for thousands I agree with @ahmadmobaraki-updivision that it's not feasible to have all entries show on page so that you can select them with the bulk action. You are better having a dedicate button and re-apply the query constrains like I explained before. 

Cheers guys 🥂

**Comment by ahmadmobaraki-updivision** [comment]
Thanks a lot @pxpm! How can data be tempered?  I didn't quite get what you mean by datatable url, do you mean url query string? (I guess not :smile: ) I'm using backpack/crud v4.1 and it's using jquery datatables.  really appreciate if you can give me an example or a link to docks/example :pray:.

**Comment by Slick-preoccupied510** [comment]
@ahmadmobaraki-updivision https://lnkr.fun/94cf719
