### ISSUE TITLE
[4.0.58] Sidebar collapse when refreshing page after clicking mobile filter toggle button

### ISSUE THREAD

**Issue by LeviZandbergen** [Laravel-Backpack/CRUD#2707]
# Bug report

### What I did

I tried showing the mobile filter toggle button by default (on desktop)

### What I expected to happen

The filter button collapsed the filters.

### What happened

the filters collapsed but the sidebar also collapsed after a refresh

### What I've already tried to fix it

removed the "navbar-toggler" class from the "filter_navbar.blade.php" filter button

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.2.28 (cli) (built: Feb 18 2020 12:54:18) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v6.18.3@4e48acfaba87f08320a2764d36c3b6a4a4112ccf

### BACKPACK VERSION:
4.0.58@03432680d8ed839bcbd99ce57aed61bcf7a1b695

**Comment by tabacitu** [comment]
Thanks for the bug report @LeviZandbergen ! We're on it.

**Comment by tabacitu** [comment]
@LeviZandbergen we're currently in a spree, trying to fix absolutely ALL bugs in 4.1, and I came across this again. Seems to be a minor issue that has slipped through the cracks (sorry for that), but at both first and second read it sounds like it's not quite a bug. But I might be wrong so please let me know.

The way I understand it:
- you adopted a "_filters hidden by default_" behaviour on both desktop and mobile; filters are hidden, click the toggle to show them - both on mobile and desktop; **what exactly did you do to achieve that?**
- you were surprised that the sidebar also gets open/closed, after a refresh, which is definitely not expected or normal; but that _might be_ because of what you did to implement the hidden-by-default behaviour for filters - **can you please share how you did that to make sure?**

Since that behaviour is not a default, I can't quite say this is a bug. So I'm going to close it. However, if there's something we can do to make it _easier_ to adopt this alternative behaviour, while not breaking current behaviour, I'm happy to do it.

Cheers!
