### ISSUE TITLE
Is there a reason for keeping a separate copy of the request in CrudPanel

### ISSUE THREAD

**Issue by orette** [Laravel-Backpack/CRUD#2791]
# Bug report
I'm completely new to Backpack and Laravel, so i might be doing this wrong

### What I did

I overrode ```prepareForValidation``` in my ```FormRequest``` to merge additional values into the request before validation.

```
protected function prepareForValidation()
{
    $user = backpack_user();

    // Is there a cleaner way to achieve this?
    // If not done the merged values are stripped by ```getStrippedSaveRequest```
    CRUD::addField(['name' => 'requester_id']); 

    $this->merge([
        'requester_id' => $user->id,
    ]);
}
```

### What I expected to happen

I expected the values set to be included in what is returned by ```$this->crud->getStrippedSaveRequest()```

### What happened

I realized that ```CRUD::getFacadeRoot()->request``` and ```Request::instance()``` are distinct 

```
protected function prepareForValidation()
{
    $request = CRUD::getFacadeRoot()->request; //Used in getStrippedSaveRequest to get values to be saved
    dd($this, $request); // $this is Request::instance() which is what is actually validated
}
```

### What I've already tried to fix it

```
protected function prepareForValidation()
{
    $user = backpack_user();
    $request = CRUD::getFacadeRoot()->request;

    CRUD::addField(['name' => 'requester_id']);
    // dd(CRUD::getFields(), CRUD::getCurrentOperation(), $this, $request);

    $request->merge([
        'requester_id' => $user->id,
    ]);
}
```
The above works but the additional values are not validated when ```$this->crud->validateRequest()``` is called. I would have to do ```$request->merge(['requester_id' => $user->id,]); ``` also for them to be validated.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 19 2020 20:12:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.5.2@3a3b3f7fea69813f5a03449c6314bfb42c3ccf78

### BACKPACK VERSION:
4.0.59@404ece5e7d164d30de6a715fe31aa3a373f4269b

**Comment by martijnb92** [comment]
You could use an `creating` observer to achieve the same functionality without overriding backpack functions

**Comment by pxpm** [comment]
Hello @orette and welcome to our community. 

Indeed `getStrippedSaveRequest` is kind of a safe guard in Backpack. It strips out anything from request that developer did not explicitly init with `addField`. But you also custumize this behaviour.

https://github.com/Laravel-Backpack/CRUD/issues/2404 - check if this helps you. 

One easy trick would be to add what you want as an hidden field so that it will get posted along with form and will be included in request.

Another option would be to overwrite the create/update functions to meet your own needs. https://backpackforlaravel.com/docs/4.1/crud-operation-create#callbacks

Also, I will let the bot close this so you get links to our alternative mediums. We use github for issues/feature requests, not general questions.

If you think i am wrong, and sometimes i am, please re-open. 

Wish you the best,

**Comment by orette** [comment]
I do think this is a bug as it changes the expected result of core functionality without a clear explanation. While I have gotten  an answer to my side question of "What would be a better way to add a non input field for later use", I think it should be clear as to why two copies of the request is kept. I probably did a bad job of asking the main question, so i'll give it another shot.

As stated in the [Laravel documentation](https://laravel.com/docs/7.x/validation#prepare-input-for-validation), 

> If you need to sanitize any data from the request before you apply your validation rules, you can use the prepareForValidation method.

The issue is, data sanitized or updated in any form is not what gets ultimately inserted in the database, as a copy of the request is made before `prepareForValidation` and `rules` are called from `FormRequest`, and the data from the copy is what is inserted.
