### ISSUE TITLE
[Feature request] Allow mime_types filter on browse field

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/CRUD#2794]
Currently the `browse` field type does not have a `mime_types` attribute to filter files, while the `browse_multiple` field does. It would be nice to have the same function on the `browse` field.

**Comment by tabacitu** [comment]
Indeed! Thanks for the heads-up @jnoordsij . Until then, you should be able to use [the ```browse_multiple``` field](https://backpackforlaravel.com/docs/4.1/crud-fields#browse_multiple) with `'multiple' => false`.

Now that I think of it... I don't know why we keep both fields... Instead of having different code for `browse`, we could just load a `browse_multiple` field with `multiple` set to `false`...

**Comment by jnoordsij** [comment]
Yes, maybe replacing the `browse` field by the `browse_multiple` field, with default value `false` for the `multiple` option would be the best solution. Then you can also deprecate the `browse_multiple` field (though leaving it in for backwards compatibility might be wise) and just document the single remaining `browse` field.

**Comment by tabacitu** [comment]
👍  My thoughts exactly. Much easier to remember `browse` than `browse_multiple`.

**Comment by tabacitu** [comment]
Wow thanks a lot for PR #2812 @jnoordsij ! 
Let's close the issue, and move the conversation there.
