### ISSUE TITLE
Repeatable field return '[]' string after deleting all entries

### ISSUE THREAD

**Issue by themagnifico** [Laravel-Backpack/CRUD#2820]
# Bug report

### What I did

- I defined a repeatable field
- I entered some entries
- I saved the entity
- then I edited the repeatable field deleting ALL the entries
- I saved the entity

### What I expected to happen

I expected to get a `null ` value as if the repeatable field had never been compiled.

### What happened

The field return a string (2) "[]"

### What I've already tried to fix it

Asking if this is the expected behavior

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.15 (cli) (built: Feb 18 2020 12:45:47) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

### BACKPACK VERSION:
4.1.4@4303aa07ec0c597abfcfe83896558ca6e98f0d6a

**Comment by justinmoh** [comment]
It's the expected behaviour.

This is actually a question of "what is the default value of the `repeatable` input". Please note that the input value of `repeatable` will always be string as was intended to be used with `json_decode`.

Now, if you create a repeatable, leave it untouched and submit, it will give you a json string, and decode it it'll show something like:

```php
array:1 [
    0 => array:3 [
        "name" => "",
        "email" => "",
        "mobile" => "",
    ]
]
```

If you click on the cross and delete the default element, you know that under the hood the array is removing one of its associating child element. In our case, it removes `array[0]`, and the remaining is an empty array.

In such situation, __repeatable field return '[]' string after deleting all entries__ is an expected behaviour. AFAIK it is intact with other backpack input element concerning json.

If you think such behaviour gives you some troubles, you can illustrate an example situation, perhaps it worths further discussion.

**Comment by themagnifico** [comment]
It makes totally sense.

I had a default `null` value in the repeatable column entries because i added that column in an existent table.

I am going to close the issue.

Thanks a lot.

**Comment by tabacitu** [comment]
Wow - thanks a lot for the detailed explanation @justinmoh - I couldn't explain it so clearly even if I tried. Good job!

**Comment by stevebeyatte** [comment]
@justinmoh by adding the empty array, it makes it impossible to query the database for null values. 

Using a query like`where repeatable_column IS NULL OR where repeatable_column = '[]'` doesn't work.

Or maybe there's another way to query for null values in a repeatable column that would be ok with an empty array?

**Comment by pxpm** [comment]
@justinmoh @stevebeyatte thanks for your pacience waiting and circunventing this issue, this was due to the fact that repeatable was beeing "pre-parsed" in javascript and that led to un-expected behavior. 

Just tried this out myself in 4.2 branch where we completely refactored repeatable to be like regular form fields submitting arrays instead of json, and I can confirm that in this new version, when the value is empty it will save `null` in the database.

This version is due to be out in a few days! 

Thanks for sticking with us! 

Pedro

**Comment by tabacitu** [comment]
![yey_cap](https://user-images.githubusercontent.com/1032474/146362857-4b87c9c9-e22a-4ec3-a371-8e949f3dd995.gif)

**Comment by stevebeyatte** [comment]
Right on time! Thanks so much.
