### ISSUE TITLE
[4.1][Bug] Fluent filed relationship create operation - database missing column

### ISSUE THREAD

**Issue by soufiene-slimi** [Laravel-Backpack/CRUD#2826]
# Bug report

### What I did
I update an existing crud controller fields to use the new fluent syntax.

### What I expected to happen
I expect everything to work fine.

### What happened
When I enter the create view and submit my data, a database error says that column xxx_id cannot be null, but the field in the edit view works well.

the field is defined as show below:
```php
<?php
// UserCrudController
CRUD::field('profile');
```
it's a simple user <=> profile relationship (the user have the column profile_id)

### What I've already tried to fix it
I set the column profile_id to be nullable in the migration file, re-migrate, and the problem is gone. But when the column is not nullable, the create operation does not work.
Also, you have to define the fillable attributes in the model, and if you have any validation for **profile_id** you have to change it to **profile** or the creation will not work too.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:48) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

### BACKPACK VERSION:
4.1.4@4303aa07ec0c597abfcfe83896558ca6e98f0d6a

**Comment by tabacitu** [comment]
Ah, I think there's a misunderstanding here @soufiene-slimi . Correct me if I'm wrong:
- that field used to be a `select` or `select2`, something like that; which needs the `name` to be the _column name_ (in the db table) - so it was `profile_id`;
- you changed that to be a `relationship` field, which needs the `name` to be the _relationship name_ (on the model) - which is `profile`;
- your Request file kept needing `profile_id`, which was NOT provided by the Create form; so the validation failed;
- but if you change your Request file too, so that the validation needs `profile` (not `profile_id`) , that should fix it;

Right?

**Comment by soufiene-slimi** [comment]
That's the easy part of the problem, if you don't set the column profil_id to be nullable in the database the field will not work, but when you set it as nullable, the profile_id will be filled in the database !! This is the strange part of the problem hhhhhhhh

**Comment by soufiene-slimi** [comment]
Hello @tabacitu, @pxpm, If an observer is used to capture the data while saving a model, you cannot get the relationship if the relationship field is used.

**Comment by tabacitu** [comment]
Hmmm that's weird @soufiene-slimi ... doesn't the Eloquent relationship update the profile_id automatically when saving? That's what I was expecting. We'll investigate, thanks.

Until then, you can still use the `select2` field type - which should have none of the quirks above - just do:
```php
CRUD::field('profile')->type('select2');
```

What do you think @pxpm ? Is this because if we specify it as a _relationship_ (not an attribute), Eloquent will do the saving for the entry FIRST, then relationships LATER? If so... I don't think there's much we can do about it. Other than change the `name` to `product_id` (for 1-n relatationships) like you first coded it... but... you know, it overwrites the name, it'd be the only field that does that... AND it would be a breaking change at this point...

**Comment by mgralikowski** [comment]
I think my PR https://github.com/Laravel-Backpack/CRUD/pull/3199 could fix this issue ;)

**Comment by tabacitu** [comment]
@soufiene-slimi I've just tested this over and over again and can't seem to replicate the issue. Either it's been fixed since, or I've tested it wrong. But I don't seem to be able to get the same thing. Happy to reopen if I'm wrong and this is still an issue.

But here's what I did, inside NewsCRUD:
![2020-09-12 08 47 08](https://user-images.githubusercontent.com/1032474/92995814-d3b01d80-f4d4-11ea-9cfb-e3bb2a86d6b5.gif)

And it worked fine for me, it saved the entry (including the `category_id`) without a hitch.

Note that my video above is filmed with `$this->crud->addField('category')` but I'm also getting the exact same result using:
- `$this->crud->field('category')`
- `CRUD::field('category')`
- `CRUD::addField('category')`

(of course, it's the same thing)
