### ISSUE TITLE
[Bug] class 'MongoDB\Database' does not have a method 'getDoctrineDriver'

### ISSUE THREAD

**Issue by kamilkozak** [Laravel-Backpack/CRUD#2883]
# Bug report

### What I did

I used an fluent syntax to create the field. The database is mongodb (jenssegers / laravel-mongodb)
eg `CRUD::field('price')->type('number')`

### What I expected to happen

The backpack will display the fields as usual.

### What happened

`call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getDoctrineDriver' {"userId":1,"exception":"[object] (ErrorException(code: 0): call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\\Database' does not have a method 'getDoctrineDriver' at /mnt/c/laragon/www/protyre/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:279)`

### What I've already tried to fix it

Everything works normally when it uses the old syntax

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by pxpm** [comment]
I searched all our project for: `getDoctrineDriver` and I could not found any reference to it.

From the code you posted the error comes from: `/mnt/c/laragon/www/protyre/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:279)`

I think I cannot be of much help here.

If you think I am wrong, and sometimes I am, please re-open. 

Best,
Pedro

**Comment by MeerKatDev** [comment]
Hello!

I try to write it here, because in the other repo it's not an issue either, but actually to solve this I had to edit your file, so I suppose here the change should happen. I do think this issue was dismissed way too quickly.

As of v4, this library doesn't have support for MongoDB, especially for [this library ](https://github.com/jenssegers/laravel-mongodb), which is the de facto mongodb library for Laravel.

In this framework, you assume that all databases are supported by doctrine/dbal, but this is not the case, because it doesn't have an interface common to mongodb, and that means that while Backpack assumes any connection will have a doctrine driver/connection, mongodb (or at least that library) doesn't provide it. 

I could make a quick fix this and make it work by editing [AutoSet.php](https://github.com/Laravel-Backpack/CRUD/tree/master/src/app/Library/CrudPanel/Traits/AutoSet.php):

```php
    public function getDbTableColumns()
    {
        if (isset($this->autoset['table_columns']) && $this->autoset['table_columns']) {
            return $this->autoset['table_columns'];
        }

        $conn = $this->model->getConnection();
        $table = $conn->getTablePrefix().$this->model->getTable();
        $columns = [];
        $casts = $this->model->getCasts();
        foreach ($this->model->getFillable() as $name) {
          $columns[$name] = new Column($name, Type::getType((isset($casts[$name])) ? $casts[$name] : 'text'));
        }

        $this->autoset['table_columns'] = $columns;

        return $this->autoset['table_columns'];
    }
```
and here:
```php
    public function getDbColumnTypes()
    {
        // $this->setDoctrineTypesMapping();

       ...
```

The first reflects the fact that MongoDB won't give a "schema", and I had to take the columns from the model. 

The second method is full of functions calling the `getDoctrineDriver`, which gives a whole host of issues.

Given that this is a paid library and that mongodb is very much used as a db, I do think this issue deserves more attention than a quick dismissal @pxpm .

**Comment by pxpm** [comment]
Hello @MeerKatDev thanks for taking time to take a look at it. 

This issue was from almost one year ago, and in the meantime we have trying to make Backpack the most compatible possible with other DB types other than SQL. 

I'v also created a PR that allow MongoDB (and probably other No-SQL dbs) to work with BP. Check it here: https://github.com/Laravel-Backpack/CRUD/pull/3401

It have been postponed to 4.2 as we have bug squashing as a priority in 4.1. Some code of that PR had already changed while fixing bugs in 4.1, so it might need a little polishing.

I do agree with you that we should support, or atleast try, but as you can see, commenting out code that is there to make SQL work in favor of MongoDB is not the way to go. 

Going back about the PR, I don't think it's a Breaking Change, so we might be able to merge it in 4.1, but our focus have been in other places. That said, if you give it a try let us know in the PR thread, it would help to speed up the merging process, now, or in 4.2 anyway.

Wish you the best,
Pedro

**Comment by MeerKatDev** [comment]
Hi, thanks for the reply. 

Yes, I saw that PR, after writing the answer above. I see you're trying, it's not easy, architecturally speaking.

I absolutely didn't mean to say that you should put that code in the library, it was meant as a quick fix for people stumbling upon here :)  

I will give that PR a try, just give a couple of days :) 

Cheers
Luca
