### ISSUE TITLE
[Bug] Loading CSS or JS file for a particular Operation stopped working

### ISSUE THREAD

**Issue by martijnb92** [Laravel-Backpack/CRUD#2923]
# Bug report

As stated in the docs Backpack [support loading](https://backpackforlaravel.com/docs/4.1/crud-how-to#customize-css-and-js-for-default-crud-operations) custom css and JS depening on the CRUD operation.

However this appears to be incorrect, since Backpack 4, all path's are changed to /packages instead of /vendor.
For example:
\src\resources\views\crud\list.blade.php

```
<link rel="stylesheet" href="{{ asset('packages/backpack/crud/css/crud.css') }}">
<link rel="stylesheet" href="{{ asset('packages/backpack/crud/css/form.css') }}">
<link rel="stylesheet" href="{{ asset('packages/backpack/crud/css/list.css') }}">
```

The same for the JS files. This is done in all views in \src\resources\views\crud\

There are two options,

**- Just edit the packages/backpack/crud/(..) files**
_Pros:_ 
Should just work
_Negative:_
Upgrading packages might remove your edits if not careful

**- Move these custom files to vendor/backpack/crud/(..)**
_Pros:_
Overwriting views is done in the same way
Keep custom files separate from the packages provided by Backpack
_Negative:_
?

Additionally I propose to only include the files if they exist. By default they are all empty/unused.
```
@if(file_exists('asset')) 
This prevents 4-6 calls to unused files.
@else
```

**Comment by tabacitu** [comment]
Thanks @martijnb92 . Totally agree - your second options sounds better to me - no negatives 😄  Thoughts @pxpm ?

**Comment by pxpm** [comment]
Hello guys.

I have a double opinion on this one.

I agree that we should move the folders, backpack crud is not a package provided/used by backpack crud. @martijnb92 got a point in there. 

I could also agree that we could `check if exists` before but not sure if that is not more expensive than including a 0 byte file, maybe not.

Also from newcomer perspective I think by default those files should be published along with backpack assets, even empty they clearly state where user should do the overrides. But that could lead to unwanted behavior in case developer deletes them, and then run the backpack command publish again they will be empty published again.

What we could do is remove those files from main backpack publish command, and create a new command that publishes only the `override` files. 

Have a setting that by default is `true` => `publish_backpack_override_assets` and when running the backpack publish command if this setting is true we also publish the override files, if false we only publish the `package` files.

This way developer can control when to publish this assets or if publish them at all.

That in combination with `file_exists` should do the trick.

**Comment by martijnb92** [comment]
That would be a great solution. 

However I noticed not all CSS files are empty by default. (https://github.com/Laravel-Backpack/CRUD/issues/2655#issuecomment-643600379)
For example the files `lists.css` and `form.css`, why is that CSS not included in bundled Backstrap CSS?
Why not refactor the code a little bit and move the content of those files to the bundle?

This will make sure those files are only being used _only_ for custom/override CSS/JS.

**Comment by tabacitu** [comment]
I think for now the fix for this (because it's a bug in 4.1 i'm afraid) would be to:
- include the file from vendor if it exists
- if not, include the file from package if it exists

That way I think we get the best of both worlds:
- we load the file from vendor [like the documentation says](https://backpackforlaravel.com/docs/4.1/crud-how-to#customize-css-and-js-for-default-crud-operations), and like people would expect if coming from 4.0 or 3.x;
- we fall back to the file from package if it doesn't (so there's not console error that the file does not exist);
- we recommend people NOT to edit anything in `packages`, not even those files; that way it's safe for us to re-publish those files whenever we want (for example upon `composer update`);

What do you think @martijnb92 & @pxpm ?

**Comment by martijnb92** [comment]
That would be a good solution, however I do see one problem.

For example somebody wants to add some custom styling to the list view.
**Expected:**
User creates the `list.css` file in the vendor directory according to the docs and it would be included in correct operation. 
**Actual:**
Unfortunately, the `list.css` file also exists in the package folder, and it is _not_ empty. Since the vendor file will be loaded, the default content of `list.css` from packages will no longer be loaded. So unless the contents of the package version will be copied to vendor first, some styling will be missing. This will also prevent any further updates to the default styling supplied by Backpack since it's now outside of Backpack's version control

So this solution will only be working if by default all files are empty and are strictly being used to overwrite existing styles or create some new styling. This can be accomplished by moving the contents of `list.css` and `form.css` to the main styling.

**Comment by tabacitu** [comment]
Long time no see 😀 I've finally found time to tackle this in 4.2. And thanks to a few changes in 4.2 I can happily say that... we probably don't need these files at all. So I've decided to remove them entirely in 4.2 - please see my PR here https://github.com/Laravel-Backpack/CRUD/pull/3942 for a complete explanation of my logic.

I'll close this issue, since it's no longer going to be a problem in 4.2 (them being removed and all). But this could be a controversial change, so @martijnb92 please let me know in that PR if you think that's a huge mistake or anything - open to feedback.

Thanks again for reporting this.
Cheers!
