### ISSUE TITLE
Listview Column Visibility Dropdown - Elements Cutoff

### ISSUE THREAD

**Issue by axelzuzek** [Laravel-Backpack/CRUD#2945]
# Bug report

### What I did

Crud List with ~30 columns. Enabled export buttons. 10 records per page. Click on "Column Visibility" Button 

### What I expected to happen
All columns visible in dropdown -  or a scrollbar
??

### What happened
the first ~7 columns are not visible (cut of by the crudTable_wrapper) 
??

### What I've already tried to fix it
tried to change various overflow settings without any success.
??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.6 (cli) (built: May 12 2020 11:38:54) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.15.0@739c44a3f7041430a3fb357f2dcfdb78f55005d7

### BACKPACK VERSION:
4.1.9@849623e7bf499c3f206c19a80146d01f27e2cd0d

**Comment by pxpm** [comment]
Hello @axelzuzek 

This is indeed a problem we are aware of. We could not find a proper solution for time beeing.

One way of achieving something similar to what you describe add to the element:

`<div class="dt-button-collection dropdown-menu" role="menu" style="display: block; top: -773px; left: 0px; overflow-y:scroll; height:500px;">`

This will force a scrollbar to be shown whenever the elements strech more than 500px in page and you could scroll all the columns. This is not an elegant solution, nor responsive I think. 

We should apply some `calc` to get the container `width` and work from there. CSS is not my beach I am sorry. 

Will ping @promatik here, to see if he could come up with a solution for it. 

If you find a proper working solution please let us know. 

Best,

**Comment by promatik** [comment]
@pxpm I did some tests and I'm afraid the #2953 is not enough to solve this problem.

By only removing the overflow I have this:
![image](https://user-images.githubusercontent.com/1838187/85237722-ef011480-b420-11ea-9d5d-91afbe60569b.png)

I managed to get this:

![image](https://user-images.githubusercontent.com/1838187/85238033-09d48880-b423-11ea-9d8d-09faa49741ef.png)

This avoids removing that overflow hidden rule from the crud table (since we still don't know what it's used for).

To accomplish this, I had to add css and js, @pxpm what's the proper place to add this? The css may be "list.css", what about the js? should it be bundled or should it go to "list.js" as well?

**Comment by tabacitu** [comment]
Ugh! This is gonna be one of those issues that seems small but they're tricky 😄 

Update: #2953 just got merged, but like @promatik said this is not a complete solution; it helps a little bit, because the dropdown can be a little bigger (bigger than the table itself), but when the dropdown is bigger than the viewport it still gets cut off (by the viewport). It's better, but not complete.

@pxpm and @promatik I agree with you guys that a very good solution in terms of UX would be to _have a scrollbar_ on dropdowns that are bigger than the page height; I wouldn't do this with `calc` though, I would probably do it with JS alone; to make the scrollbar appear you also need to set the exact height of the element (as far as I know) so first you have to _detect it_, which we can do with JS. We could also do it with `calc()` I guess, or even by [setting the height relative to the viewport](https://www.w3schools.com/cssref/css_units.asp) with `max-height: 95vh` I guess.

If possible, I think we should code this in a way that will fix _any_ large dropdown, not just _this_ dropdown. I don't know a lot of places where this could happen again, but I do know one example - in the translatable Edit button you could be faced with the same issue - have 15 languages active and only one row and it's the same problem all over again (notice you can't even see English in the dropdown menu):
![Screenshot 2020-06-22 at 16 30 47](https://user-images.githubusercontent.com/1032474/85293253-c5d69780-b4a5-11ea-81c2-8a432abcea62.png)


I'm surprised that bootstrap doesn't do this itself - seems like quite a good solution you guys have come up with (scrollbar when dropdown is too large).

To answer your question @promatik 
- if it's a one-off solution (only in list, only for this button) a good place for it would probably be inside `datatables_logic.blade.php`. It's a mess, but adding something there will be a non-breaking change since nobody ever overwrites that file. Alternatively, `list.blade.php` also allows you to add JS to the operation and it's not as bloated 🙄 
- if it's for all Backpack pages, then one possible place would be `scripts.blade.php` - it would bloat it up a little bit, but again, nobody overwrites it so people are able to get the update with a `composer update`;

I've played around this for quite a while but haven't pinpointed a perfect way to do it. Best I could do was `height: 95vh; top:95vh; overflow-y: auto;` but it still clips the first 4-5 items for some reason. @promatik what did you use as CSS to get the result above (with the scrollbar)?

**Comment by promatik** [comment]
@tabacitu my solution was pretty simple, just a few lines of css and another of js.

```scss
.dropdown-menu {
    overflow: hidden scroll;
    max-width: 168px; // Because if it's too large, it goes out of the screen
}
```
Then, the JS sets the dropdown max height equal to the crud table height.

```javascript
document.querySelector("button.buttons-colvis").onclick = e => 
    document.querySelector("#crudTable_wrapper .dropdown-menu").style.maxHeight = 
    document.querySelector("#crudTable").offsetHeight + "px";
```

Maybe we shouldn't be setting the max width with css, we should set the `left` with javascript too, based on the width of the dropdown.

Also, this was a solution just for the dropdown inside the crud table, didn't know yet about the translations :)
