### ISSUE TITLE
image.blade.php & base64_image.blade.php are the same (both upload base64)

### ISSUE THREAD

**Issue by RamiMustaklem** [Laravel-Backpack/CRUD#295]
Both of these files are almost identical and they both upload base64 images.
Is there a way to change image.blade.php to upload an object which contains
1. file, 2. cropData, 3. rotationData, etc... and do the processing using Intervention.

Since I do not think the cropper's output could be other than dataUrl or Blob.

There are difficulties validating dataUrls among other things.

**Comment by gotrecillo** [comment]
We could embed the cropData and rotation data as exif using this:
https://github.com/hMatoba/piexifjs

Then we could use a Accessor to generate the image and saving the url in our model.

**Comment by tabacitu** [comment]
Hi guys, 

Check out step 2 in the "image field" documentation - https://laravel-backpack.readme.io/docs/crud-fields#section-image - it explains how to create an accessor to upload the file, not a base64 image.

Hope it helps. Cheers!

**Comment by gotrecillo** [comment]
Hi.

That doesn't make it any different from base64_image, we can implement the same accessor to convert the image and create a file.

In both inputs what we are sending is a string. A big one. So big that it is easy for it to go beyond the max_post_size in php.ini. 

Additionally we cant use laravel native file validations in our StoreRequest because the input is a string.

To solve those two problems we can send the actual file not just plain text, crop it in the accessor with the cropdata found it the exif data of the image.

I have done it in the past. I could make a pull request creating a new field type called differently from image and base64_image so we don't break compability

**Comment by OwenMelbz** [comment]
Can it work with the exact same cropping ui? As I think that's important.

Submitting PRs always welcome if you have the time

**Comment by tabacitu** [comment]
@gotrecillo that sounds like a great idea, I'm very open to it. 

But first, let's track down what the difference between the fields would be:
1) ```base64_image``` - has cropper UI, sends string and stores base64 string;
2) ```image``` - has cropper UI, sends string, uploads file and stores filename; 
3) ```upload``` - no cropper UI, sends file, uploads file and stores filename;
4) ```upload_image``` - ???cropper UI???, sends file, uploads file and stores filename;

If there's no cropper UI in this new field, we could just use ```upload``` for this, couldn't we?
If there is a cropper UI in this new field, I'm definitely up for this PR. Maybe we even find a way to make it backwards-compatible and replace ```image```.

Thanks, cheers!

**Comment by RamiHarri** [comment]
@tabacitu 

What's different in #4. upload_image is that it has a cropper UI, but sends an object that has:
1- fileObject
2- cropData
3- rotateData
etc... 

All image processing is done on the server, plus Laravel File Object validation is applicable.

cheers

**Comment by RamiMustaklem** [comment]
@tabacitu 

What's different in 4. upload_image is that it has a cropper UI, but sends an object that has:
1- fileObject
2- cropData
3- rotateData
etc... 

All image processing is done on the server, plus Laravel File Object validation is applicable.

cheers

**Comment by lloy0076** [comment]
If there is a PR, please reopen. 😄
