### ISSUE TITLE
[Bug] $this->crud->getFields('create')

### ISSUE THREAD

**Issue by mikiman2028** [Laravel-Backpack/CRUD#2963]
# Bug report

### What I did

dd ($this->crud->getFields('create'));

### What I expected to happen

get array of fields

### What happened

In my trait I'm trying to get list of fields used in create operation on my crud. I'm getting empty array.

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 7.4.7 (cli) (built: Jun 12 2020 07:44:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.16.1@dc9cd8338d222dec2d9962553639e08c4585fa5b

### BACKPACK VERSION:
4.1.10@cf33f991b97de99cefa1dcd2e6beeeeda8116514

Thanks for support

**Comment by mikiman2028** [comment]
dd ($this->crud) returns: 
![image](https://user-images.githubusercontent.com/22446697/85540352-29340700-b617-11ea-8ff0-078da9d1d98f.png)

**Comment by tabacitu** [comment]
Hi @mikiman2028 ,

The fields are stored inside `$this->crud->settings`. Actually, pretty much _everything_ is stored in there. 

But depending on what trait you're talking about, you might or might not see them there. Because the fields are only added to `settings` by the Create operation, if you you're _outside_ the Create operation you won't see them in `$this->crud->settings` either. If that's your use case (the trait you're talking about is a different operation or something), there are a few options:
- (A) add your fields in a more general method, ex `public function setupFields()`; call that method in `setupCreateOperation()` and wherever else you'd like;
- (B) move your addField statements from `setupCreateOperation()` to `setup()`, which will make the fields present in `settings` for ALL operations; (this one is not recommended; it works, but it kind of bloats up all other operations)
- (C) straight up call `setupCreateOperation()` inside your custom operation, and you'll get the fields;

Hope it helps!

**Comment by tabacitu** [comment]
I'll close the issue since it's not a bug, but feel free to reply if my directions above don't help.
Cheers!

**Comment by mikiman2028** [comment]
Thank you for pointing me in wright direction  :-)
