### ISSUE TITLE
[Bug] Unable to add CRUD custom button both at the top and bottom simultaneously since Backpack 4.x

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/CRUD#2972]
# Bug report

### What I did

$this->crud->addButton('bottom', 'xxx', 'view', 'crud::buttons.xxx');
$this->crud->addButton('top', xxx', 'view', 'crud::buttons.xxx');

### What I expected to happen

My custom button will appears both at the top and bottom of the table (At least this is the case prior to Backpack 4.x)

I think a button at top and button is important for UX in bulk actions.
1. If the button is placed at the top, user have to scroll back to the top after selecting lots of entries and reaching the end of the list.
2. Placing the button at the bottom is not an option too since it is "hidden" by default and user will be forced to scroll until the end of the list even if they only need to select a few entries from the top rows.

If this is intended behaviour for Backpack 4.x, can I at least request Backpack4.x to give me an option to make it works just like Backpack 3.x?

### What happened

My custom button only appears at the bottom of the table.

### What I've already tried to fix it

I tried setting the $replaceExisting parameter to false, i.e.
$this->crud->addButton('bottom', 'xxx', 'view', 'crud::buttons.xxx', 'end', false);
$this->crud->addButton('top', 'xxx', 'view', 'crud::buttons.xxx', 'end', false);

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.12 (cli) (built: Nov 19 2019 13:58:02) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.12.0@c2fff1e9879494a6f853593b3c517dc9922bbb51

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by pxpm** [comment]
Hello @drionix 

Sorry for late reply.

There is something preventing your from using different names for the button ? Like: `button_name_top` and `button_name_bottom` ?

The reason why the button is not appearing is because you are adding the button with the same name, so the last replaces the first, That way we guarantee that the button names are unique, so you could use `modify('button_name', $modifications)` that calls: `$button = $this->buttons()->firstWhere('name', $name);` 
So even adding two buttons with same name, if you need to manipulate something that would always apply to the first button. 

I think this is more a documentation issue rather than a bug. Let me know if I am wrong and re-open if needed.

Thanks for raising the issue.

Best,
Pedro
