### ISSUE TITLE
[Feature Request] Automatic handling of 'relationship' field types for LIST, SHOW and MODAL

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#3004]
# Feature Request

I have a CUSTOMER table which has relationship with 'COUNTRY' and 'STATE' tables.   I have defined necessary functions in model, foreign keys relationship in migration and everything works fine.  However what I noticed is...

In my setup() function of CRUD Controller, I have below code which helps me fetche the corresponding STATE NAME and COUNTRY NAME - from respective tables.

```
        CRUD::column('state');
        CRUD::column('country');

```
However, in SHOW and MODAL extra attributes for **state** and **country** getting surfaced because those columns are automatically picked up from the TABLE.

### What's the feature you think Backpack should have?
Auto hide them if they are referenced by above notation.

### Have you already implemented a prototype solution, for your own project?
The present workaround is to hide those columns explicitly from the user in setup() or corresponding methods.

```
        //--hide foreign keys
        CRUD::column('state_id')->visibleInShow(false)->visibleInTable(false)->visibleInModal(false);
        CRUD::column('country_id')->visibleInShow(false)->visibleInTable(false)->visibleInModal(false);

```

**Comment by tabacitu** [comment]
Hi @srigurubyo ,

By default both the modal and Show Operation show everything that's inside the List operation. I think that's the most intuitive and useful use case - where you'd want to see EVERYTHING about that entry.

If I understand correctly, you suggest only showing the attributes that have NOT been already shown in the list? If so, I'm afraid I don't agree with you 😄 It might make sense for your use case, but for the overwhelming majority of use cases I think it's best to show everything, otherwise:
- if you hit directly the Show operation, you wouldn't have _everything_, you'd need to go out to the table to see some attributes; bad UX;
- when you open the modal, you can see more details about one entry, but since the identifiable attribute for that entry was in the table, you won't see that one so you can forget / not be sure what entry the modal is about;

The solution you have is the one to go, in my opinion. If you want to explicitly not show those columns, you can do that. I'm open to reconsidering this, if more people think I'm wrong - I often am. But until then I'm going to close the issue, since it's not something we plan to do. 

Thanks for raising the issue.
Cheers!

**Comment by srigurubyo** [comment]
Probably I have not articulated the problem well.

Please refer code below:  

```
    public function setup()
    {
        .....
        .....
        CRUD::column('state');
        CRUD::column('country');
        
        //--hide foreign keys
        CRUD::column('state_id')->visibleInShow(false)->visibleInTable(false)->visibleInModal(false);
        CRUD::column('country_id')->visibleInShow(false)->visibleInTable(false)->visibleInModal(false);
    }
```
When a table has reference to another table (CUSTOMER belongsTo COUNTRY) essentially you want to add stuff inside SETUP/LIST and CREATE functions of the CRUD controller.  As backpack has inbuilt logic and adheres to Laravel syntax when I declare CRUD::column('country') inside my setup() function, it AUTOMATICALLY adds column to my LIST, SHOW (because the field has been named as per Laravel standard.

However, because my CUSTOMER table has country_id as column it also displays 'country_id' as another column in my LIST/SHOW which I have to manually hide (see above code).

So in nutshell, backpack display the same field twice (1) as per Laravel standard (of having _id) and (2) backpack standard of CRUD::column('country') notation. 

So, my humble opinion would be to make some standard to display of those fields which strictly adhere to Laravel standard of _id.

Hope I am clear now.
