### ISSUE TITLE
[Help] Using multiple tables for authentication - still want to use backpack authentication mechanism

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#3018]
# Report

We are building a quick prototype.  There are three types of users (admins, employees, and visitors) stored in different database tables.  I am comfortable with the backpack admin portal so doesn't want develop different UI / views for the application.  

I am wondering **what is the recommended way to extend backpack to use different tables for authentication** - respective to the type of user logs in.

Any guidance is appreciated here from the experts.

**Comment by tabacitu** [comment]
Sorry @srigurubyo but this is not a bug or feature. Please post on Github _only if it qualifies as one of those_.

**Comment by srigurubyo** [comment]
> Sorry @srigurubyo but this is not a bug or feature. Please post on Github _only if it qualifies as one of those_.

@tabacitu I completely agree with you and sorry for the inconvenience caused.

However I had posted few questions on stackoverflow as well reddit but never got any response.  Since I do not see any other active channels (like slack) I am left with only posting my questions here.  I understand this is not the right channel to discuss queries.  

I am willing to start a 'slack' channel if you are fine with it.  Given the backpack's capabilities, I really feel a slack channel will help spread it's reach in the market.

**Comment by tabacitu** [comment]
@srigurubyo personally I don't like synchronous communication. I think everybody is working on their own thing so asynchronous is better most of the time - it allows us developers to do _deep work_ without being interrupted or distracted by notifications.

In my opinion, chatrooms are a difficult thing to do _right_:
- if you have too few people, they're not useful because you don't get answers in the expected time;
- if you have too many people, they're not useful because they're a jumbled mess;

That being said, we have a Gitter chatroom already, and I'm not very happy with that one either - rarely spend any time there. But there are people who spend time there, who don't share my hate for chatrooms 😄  Try that for quick questions.

I don't think we need a Slack, we've had one a few years back but dropped it - it's one more thing to maintain and it doesn't provide any benefit over Gitter. 

Cheers!
