### ISSUE TITLE
[Feature Request]Add a filter to an ajax relationship Field request

### ISSUE THREAD

**Issue by dauvray** [Laravel-Backpack/CRUD#3026]
# Feature Request

### What's the feature you think Backpack should have?

Allow the possibility of adding conditions to the Ajax query with the relationship field like others select2

    [   // relationship
        'type'          => "relationship",
        'name'          => 'category', // the method on your model that defines the relationship
        'ajax'          => true,
        'inline_create' => true,
        'options'   => (function ($query) {
             return $query->orderBy('name', 'ASC')->where('section_id', 1)->get();
        }),
],

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core feature

**Comment by pxpm** [comment]
Hello @dauvray 

If you are using FetchOperation to setup your ajax routes you can use `'query' => function($query) { return $query->where(.....'); }`

Otherwise you can manipulated the ajax response route to respond with your own query restrictions.

I think this feature is something we already provide. 

If you think i am wrong, please re-open. 

Wish you the best,
Pedro

**Comment by dauvray** [comment]
Thank you @pxpm 

I don't understand the concept. I can't see where to put this query atribute.
In my project i have a Crud for Articles and a Crud for Projects.
Each belongs to a section with differents categories
So when i update an article, i want to see the categories related to articles.

I'm using FetchOperation to setup my ajax routes but  I am unable to config the query for each Crud.

**Comment by tabacitu** [comment]
Sure @dauvray, I'll try to explain in my words. It's impossible to manipulate the query (use an additional WHERE statement) when you define an AJAX field, because that's not where the dropdown items are calculated and shown. 

The dropdown items are calculated and shown by the Fetch operation on the CrudController, which the `relationship` field needs. So in this example:

```php
class ProductCrudController
{
    public function setup() {}

    public function fetchCategory() {
        return $this->fetch(App\Models\Category::class);
    }

    public function setupCreateOperation() {
        $this->crud->addField(['name' => 'category', 'type' => 'relationship', 'ajax' => true]);
    }
}
```

When you do `addField`, you just declare - _hey Create operation, remember to include the `relationship.blade.php` file inside the Create form_. That blade file contains ZERO entries for the dropdown, they're fetched using AJAX because that's what you specified. The PHP code that retrieves the options for the dropdown is the `fetchCategory()` method, which is the right place to put the WHERE statement, like @pxpm said. Here are [the docs for the Fetch operation](https://backpackforlaravel.com/docs/4.1/crud-operation-fetch#how-to-use) which explain all the customization options.

Hope this clears things up.
Cheers!
