### ISSUE TITLE
[Bug] hasMany relationship cannot be stored.

### ISSUE THREAD

**Issue by ChuiSauCE** [Laravel-Backpack/CRUD#3031]
I have Question and Answer models and simple One to Many relation ship as below:

```
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
   use CrudTrait;
   ...
    public function answers()
    {
        return $this->hasMany(\App\Models\Answer::class);
    }
   ...
}
```
```
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use CrudTrait;
    protected $fillable = [
        'question_id',
        ...
    ];

    public function question()
    {
        return $this->belongsTo(\App\Models\Question::class);
    }
}
```
On QuestionCRUDController:
```
<?php
...
class QuestionCrudController extends CrudController
{
    ...
    protected function setupCreateOperation()
    {
        ...
	CRUD::addField([
		'label' => "Answers",
		'type' => 'select_multiple',
		'name' => 'answers',
		'entity' => 'answers',
		'attribute' => 'description',
		'model' => 'App\Models\Answer',
	]);
        ...
    }
    ...
}
```

This is listing answers properly but can't store the values.

It's my first time using backpack so I tried to create same scenario with Demo repo. Relationships between Monster and PostalBox is already set. I've basically added those lines to MonsterCrudController:

```
protected function setupCreateOperation()
{
    ...
    $this->crud->addField([ 
	'label' => 'Select_multiple',
	'type' => 'select_multiple',
	'name' => 'postalboxes', // the method that defines the relationship in your Model
	'entity' => 'postalboxes', // the method that defines the relationship in your Model
	'attribute' => 'postal_name', // foreign key attribute that is shown to user
	'model' => "App\Models\PostalBox", // foreign key model
    ]);
    ...
}
```

But no luck. List appears, I make selection, click save and nothing is stored.

Should I use crud controller's create and update methods to manually update answers or this is just a bug about hasMany relationship?

### PHP VERSION:
PHP 7.3.5 (cli) (built: May  1 2019 13:17:17) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.19.1@4f373c373915ec828e3374029919a6fe946ed6d9

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by mahasadhu** [comment]
@ChuiSauCE `select_multiple` type that you use in `QuestionCRUDController` is for `many to many` relationship with pivot / join table. For `one to many` relationship, I think you should use `select` or `select2` field type

try to change your config to this and see whether it's working or not:
```
        CRUD::addField([
		'label' => "Answers",
		'type' => 'select',
		'name' => 'answer_id', // change this to actual column name that you use in your table
		'entity' => 'answers',
		'attribute' => 'description',
		'model' => 'App\Models\Answer',
                'autoset'     => false,
	]);
```

**Comment by ChuiSauCE** [comment]
@mahasadhu questions table doesn't have answer_id column, answers table do have question_id which

**Comment by mahasadhu** [comment]
@ChuiSauCE then that's called a `many to many` relationship, not an `one to many`.

You'll need a pivot table to combine those questions and answers data, and set the relation properly through the Laravel model, using `belongsToMany`

**Comment by ChuiSauCE** [comment]
@mahasadhu Answer belongs to one question, not many. To summarize:
Question->hasMany(Answer)
Answer->belongsTo(Question) (answers table has question_id column)

**Comment by pxpm** [comment]
@ChuiSauCE thanks for pitching in. 

From my understanding you should NOT edit the hasMany relation part, or if you do, you should do it with your own implementation because depends alot on you app logic.

Here you have some laravel discussion about it: https://github.com/laravel/framework/issues/3251 

When you create an answer it belongsTo a question. 

If you allow editing the question answers (hasMany) you can add an answer that belongs to another question and you need to set null, or delete the record from previous relations or update. 

You are in QuestionCrud with a field select_multiple answers. You select 1,2 and 3 answers for your Question with id 1.

What you should do is get the answers from database with those ids and for each of them change the `question_id` to 1.

Then you create another Question (id = 2), and select answers 1, 4, 5.

What you should do is get answers with those ids and for each of them change the `question_id` to 2. But now answer 1 does not belong to question 1 anymore. It belongs to question 2.

Now you go to question 1 and delete all the answers. (2-3)

Should we do what? Get all answers that belong to the edited question and set `question_id` null? Should we delete the answers entirely from database? 

Here you find one approach to this problem: https://github.com/laravel/ideas/issues/150

Maybe I am not seeing the big picture and this is something we should implement. 

This are my toughts, I might be wrong, been there alot of times :) 

Let me know what you think.

Best,
Pedro

**Comment by ChuiSauCE** [comment]
@pxpm Thank you for your answer

Well, if you don't think of it this way and start searching why it's not working since it's mentioned in the docs, it can take a while to understand.

It's better to handle it in person as you mention. There is no need of further discussion but it would be nice to if it was mentioned in the docs.

I've chosen to store them as JSON directly on questions table and works like a charm with repeatable fields.

BR,
Can
