### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lucidlive** [Laravel-Backpack/CRUD#3044]
# Bug report

**My Setup**

I have a **Posts** model and a **Posts Type** model. 
The posts model has a "post_type_id" field to store the relation.

On the Posts model, I declare the _hasOne_ relation like so:

```
public function type()
{
    return $this->hasOne('App\Models\PostType', 'id', 'post_type_id');
}
```

**The Backpack Problem**

In my **Post CRUD Controller**, I have the following under _setupCreateOperation()_

```
CRUD::addField([
            'label' => "Type",
            'type' => 'select',
            'name' => 'post_type_id',        // the db column for the foreign key
            'entity' => 'type',              // the relationship name in your Model
            'attribute' => 'name',           // foreign key attribute that is shown to user
]);  
```

When editing or creating a post, the form looks correct and I can see all the Post Types in the select box. Great!

The problem is that when I save the form I get an error:

**Add [post_type_id] to fillable property to allow mass assignment on [App\Models\PostType].**

The error makes no sense because "post_type_id" exists in the "Post" model (not PostType model) and it is fillable on the Posts model.

What am I do wrong?

**Comment by tabacitu** [comment]
Hmm... I might be wrong @lucidlive but the first thing that stands out to me is that you probably want a 1-n relationship there, not 1-1. Wouldn't a PostType be able to be linked to MANY Posts? In that case you wouldn't use `hasOne()` but `belongsTo`.

I think that's your problem. Check out the [Laravel docs on HasOne](https://laravel.com/docs/7.x/eloquent-relationships#one-to-one) - that relationships is for when you just want to move some attributes from the main table to a secondary table. So you'd have `posts` and `post_details`, something like that. So for 1-1 relationships, yes, a new row for `post_type` tries to get added whenever you add a new `post`. Which is why you're seeing the error. But for 1-n relationships (what I think you should be using) that wouldn't happen.

I'll close this issue since I'm pretty sure that's your problem - not using the correct Laravel relationship type. But we can reopen if it's a bug in Backpack. Let us know.

Cheers!

**Comment by lucidlive** [comment]
Hi @tabacitu, okay yes you are correct. However, with a belongsTo relationship I get an integrity violation on the database.

**Example Error**
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' (SQL: update `posts` set `id` = ?, `posts`.`updated_at` = 2020-07-20 15:32:51 where `id` = 20626)`

`at Connection->runQueryCallback('update `posts` set `id` = ?, `posts`.`updated_at` = ? where `id` = ?', array(null, '2020-07-20 15:32:51', 20626), object(Closure))
in Connection.php line 625`

The code in the PostCrudController remains the same. If I remove the specific field for post type then everything works as expected.

**Comment by pxpm** [comment]
Hi @lucidlive 

My suggestion is to have a look at [Backpack/NewsCRUD](https://github.com/Laravel-Backpack/NewsCRUD) package. 
You need to view it like: 

- `Article` is your Posts. (Has a BelongsTo relation with Category)
- `Category` is your Post Type. 
 
Check models, database schema and controllers as an example. 

I am with @tabacitu on this one, I still think this is something related with a bad implementation rather than a Backpack bug.

If you find i am wrong and this a bug please re-open.

Wish you the best,
Pedro

**Comment by lucidlive** [comment]
My apologies, the problem was actually quite obvious. I had the wrong field value in the belongsTo relationship. It was defined as **id** when it should have been **post_type_id**.
