### ISSUE TITLE
GeneratorsServiceProvider not found 

### ISSUE THREAD

**Issue by shankhadevpadam** [Laravel-Backpack/CRUD#310]
Class 'Laracasts\Generators\GeneratorsServiceProvider' not found 

while install in laravel  5.3

**Comment by OwenMelbz** [comment]
You done a `composer update` and `composer install` ? after installing the https://github.com/Laravel-Backpack/Generators package?

**Comment by tabacitu** [comment]
Also @shankhadevpadam , did you use the demo or did you do [a clean install on Laravel 5.3](https://laravel-backpack.readme.io/docs/installation-on-laravel-53)?

**Comment by shankhadevpadam** [comment]
i have fixed it but login page show 404 error.

**Comment by tabacitu** [comment]
Did you try ```/login``` or ```/admin```? ```admin``` is the good one. The other one is the standard Laravel login.

**Comment by shankhadevpadam** [comment]
This one also fixed. 

Thanks for your support.

**Comment by OwenMelbz** [comment]
I'll close this off then :) If you need anything more you can keep replying here!

**Comment by shankhadevpadam** [comment]
/admin/elfinder page not found.

**Comment by tabacitu** [comment]
@OwenMelbz , the ```Class 'Laracasts\Generators\GeneratorsServiceProvider' not found``` error is my bad - the update I pushed today for the generators and base caused this. 

Apparently composer does NOT run the "require-dev" flag on packages in /vendor/, but only for the "root" composer. I knew this, but got excited and forgot. I am on this right now, I've just pushed a few fixes into Base so that the error is not thrown anymore, but I still haven't fixed it entirely (generators still don't get installed).

The Demo should work fine.
The regular installation process has this bug right now - the generators are not automatically installed by composer.

Since we're currently in a huge user spike (because of the [laravel-news post](https://laravel-news.com/laravel-backpack)), priority numero uno is to fix this stupid mistake I made, so new users have zero problems. So I'm on this. Will follow up.
