### ISSUE TITLE
[Feature Request] [4.1.0] Repeatable field (non-pivot) - save in database

### ISSUE THREAD

**Issue by alan-smith-be** [Laravel-Backpack/CRUD#3103]
# Feature Request

### What's the feature you think Backpack should have?

Save in database repeatable field (in non-pivot database scheme)
save relation repeatable relation like : 
HasMany, MorphMany

### Have you already implemented a prototype solution, for your own project?

Yes : create, update, delete relations.
TODO : manage form validations.

### Do you see this as a core feature or an add-on?

Core feature

**Comment by alan-smith-be** [comment]
files modified :
backpack\crud\src\app\Library\CrudPanel\Traits\
- Create.php
- Update.php

[Traits.zip](https://github.com/Laravel-Backpack/CRUD/files/5027287/Traits.zip)

**Comment by tabacitu** [comment]
Hi @alan-smith-be ,

Thanks for reaching out. I'm afraid I don't quite understand what you're proposing here. Could you please rephrase - maybe on the second try I will 😇? Would the repeatable point to full-fledged Eloquent Models, and store them in their right database tables?

Cheers!

**Comment by alan-smith-be** [comment]
Hello @tabacitu ,

Yes that's it.

Example :
Order has many orderItems (each one has his own db table with eloquent model).
One the edit form, you can edit the order and the order items, where order items are using your repeatable functionality.

The complete model is saved in the DB, in their respective tables. - create/update/delete

As I said, for now the validation operations are not implemented.

KR,

**Comment by tabacitu** [comment]
Thanks a lot for opening the issue - and providing code @alan-smith-be ! 🥳  

I've put your code into PR https://github.com/Laravel-Backpack/CRUD/pull/3200 so that it's easier to test & work with. Let's move the conversation there please, to move this towards a mergeable feature.

I won't try to test / make it work / modify it in any way in the next few weeks. We're currently in a feature freeze, trying to reach bug zero (even minor bugs). But I will look at it once we're done with that. So please let me know if you have thoughts about my notes there, if you're able to work on it a little bit more or are busy and would like us to do that, etc.

Again, thank you - it's a very cool feature indeed! And much needed. I needed this myself once for `Invoice` and `InvoiceItem` and had to code something custom, this feature would have probably saved me a few hours.

Cheers! Let's move the conversation to PR https://github.com/Laravel-Backpack/CRUD/pull/3200
