### ISSUE TITLE
[Bug] File does not exist on external storage

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#3115]
# Bug report

### What I did
show an image, but it doesn't exist in storage

```php
    //PHOTO
        $this->crud->addColumn([
            'name' => 'names.data14',
            'label' => trans('contact.photo.profile_image'),
            'type' => 'image',
            'disk' =>  Config::get('settings.contact_disk'), // 'dropbox',
             'height' => '150px',
             'width'  => '150px',
        ]);
```

### What I expected to happen

see broken link

### What happened

Spatie\Dropbox\Exceptions\BadRequest
path/not_found/... (View: C:\laragon\www\crudContact\vendor\backpack\crud\src\resources\views\crud\columns\image.blade.php)

### What I've already tried to fix it

modify the following in columns and fields "image.blade.php"

```php
    if (preg_match('/^data\:image\//', $value)) { // base64_image
      $href = $src = $value;
    } elseif (isset($column['disk'])) { // image from a different disk (like s3 bucket)
        if (Storage::disk($column['disk'])->exists($column['prefix'].$value) )
          {  $href = $src = Storage::disk($column['disk'])->url($column['prefix'].$value); }
        else
          { $href = $src = asset( $column['prefix'] . $value); }
    } else { // plain-old image, from a local disk
      $href = $src = asset( $column['prefix'] . $value);
    }
```

### PHP VERSION:
PHP 7.4.7 (cli) (built: Jun  9 2020 13:36:15) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.23.0@17cbce101f2fc78e61a6135861823563c7cfb50b

### BACKPACK VERSION:
4.1.16@4c2264f8dd52381aa891136edb61e8d4083a033d

**Comment by tabacitu** [comment]
@DanielKimmich I see there have been fixes to the `image` column since then. I just tested this and it looks to be working fine, so I'll assume somewhere between 4.1.16 and 4.1.25 it's been fixed.

Let me know if that's not the case, and after a `composer update` you're still having issues with the `image` column type, and we'll reopen.

Cheers!

PS. For me, normally, when I encounter this kind of issue, it's a mismatch between the path stored in the DB column, and the _public_ asset path. And they're solved using the `prefix` attribute on the column.

**Comment by DanielKimmich** [comment]
The problem continues, this occurs when the file is deleted directly in the public repository and in the db continues related to the file.

Cheers!

**Comment by tabacitu** [comment]
Oh I understand. But... isn't that normal @DanielKimmich ? 😄 If the file is deleted without the DB being updated... it's normal for an error to be thrown. Don't you see it the same way @DanielKimmich ?
