### ISSUE TITLE
[Bug] hasMany relationship field not working

### ISSUE THREAD

**Issue by yabbou** [Laravel-Backpack/CRUD#3122]
# Bug report

### What I did

**PurchaseOrderCrudController.php:**
```
     CRUD::addField([
            'label'     => 'PO Line Items',
            'type'      => 'relationship',
            'name'      => 'pOLineItems', 
            'entity'    => 'pOLineItems', 
            'attribute' => 'product_name',
        ]);
```
**PurchaseOrder.php:**
```
    public function pOLineItems()
    {
        return $this->hasMany(\App\Models\POLineItem::class);
    }
```
**POLineItem.php:**
```
    public function purchaseOrder()
    {
        return $this->belongsTo(\App\Models\PurchaseOrder::class);
    }
```

### What I expected to happen

I expected the `POLineItems` to be added to the `PurchaseOrder`.

### What happened

Although the save went through, changes made in the `PurchaseOrder` crud were not stored in the database.

Interestingly, changes made in the `POLineItem` crud _were_ saved to the database, and even displayed in the `PurchaseOrder` crud. (But they still could not be changed from that crud.)

### What I've already tried to fix it

I tried using the `select` fields, but they did not work either. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### LARAVEL VERSION:
v7.19.0@67d6d9688122dcf6c449b74ddc873fc9934e81e6

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323
```

**Comment by tabacitu** [comment]
@yabbou - sorry to hear you're having problems. I'm a bit skeptical that it's a bug in Backpack though. I see the relationship field is working fine inside our [online demo](https://demo.backpackforlaravel.com/admin/login). 

I'm wondering - do you really need to specify `entity` and `attribute` there? If the relationships are properly defined, Backpack should pick them up automatically. If you do specify `entity` manually, you might also need to define `pivot` then, to let Backpack know it should store the info inside the pivot table. I've just finished adding more comprehensive documentation on the attributes needed by a field that works with related entries - please [check it out here](https://backpackforlaravel.com/docs/4.1/crud-fields#optional-attributes-for-fields-containing-related-entries). Might help you understand how you've overwritten the attributes Backpack guesses, and if it's been done correctly.

I'll close this for now, since it looks like user error/misconfiguration. Let me know if the info above doesn't help you solve it, or you still think it's a bug in Backpack. I might be wrong it's happened before 🤣 

Cheers!

**Comment by yabbou** [comment]
Does Backpack require pivot tables even for **one-to-many** (1-n) relationship? The demo seems to be treating the hasMany relationship like a **many-to-many** (n-n), which _would_ require a pivot table.

![image](https://user-images.githubusercontent.com/36824257/90544674-79ca6b00-e155-11ea-8a14-ec5cf4c26b01.png)

**Comment by yabbou** [comment]
For anyone else whom it might help, here is a very basic means of overriding the update function:
 
**PurchaseOrderCrudController.php:**
```
public function update()
    {
        $this->crud->hasAccessOrFail('update');
        $request = $this->crud->validateRequest();

        // (1) remove prev polineitems from po 
        $id = $this->crud->getCurrentEntryId();
        POLineItem::where('purchase_order_id', $id)->update(['purchase_order_id' => null]);
       
        // (2) add new polineitems to po
        $ids = $this->crud->getStrippedSaveRequest()['pOLineItems'];
        POLineItem::whereIn('id', $ids)->update(['purchase_order_id' => $id]);

        //update po  
        $item = $this->crud->update(
            $request->get($this->crud->model->getKeyName()),
            $this->crud->getStrippedSaveRequest()
        );
        $this->data['entry'] = $this->crud->entry = $item;

        // show a success message
        \Alert::success(trans('backpack::crud.update_success'))->flash();

        // save the redirect choice for next time
        $this->crud->setSaveAction();

        return $this->crud->performSaveAction($item->getKey());
    }
```

**Comment by tabacitu** [comment]
> Though, does Backpack require pivot tables even for one-to-many (1-n) relationships, such as a hasMany? 

It doesn't, no. 

> The demo seems to be treating the hasMany relationship like a many-to-many (n-n), which would require a pivot table.

Huh... that would be weird. @pxpm could you please take a look and let me know what you think? Is this a problem in Backpack or no?
