### ISSUE TITLE
Cannot see any column on mobile if bulk actions are enabled [Bug] 

### ISSUE THREAD

**Issue by alfonsocuccaro** [Laravel-Backpack/CRUD#3139]
# Bug report

### What I did

I have opened a CRUD table where bulk actions are enabled and responsive is **NOT** disabled 

### What I expected to happen

I would like to see also at least one column beyond the checkbox column

### What happened

On mobile I only see the checkbox for the bulk actions
![image](https://user-images.githubusercontent.com/6061785/90899097-b3a2a800-e3c7-11ea-87cc-60300527debd.png)

### What I've already tried to fix it

I have seen [the documentation](https://backpackforlaravel.com/docs/4.1/crud-columns#define-which-columns-to-show-or-hide-in-the-responsive-table), but it seems there is no way to come out from this situation. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
Wow thanks a lot for posting you solution @alfonsocuccaro . What changes have you made inside `datatables_logic.blade.php`?

**Comment by alfonsocuccaro** [comment]
Hi, I have made the following changes:

1. At line `122` I have removed `scrollX: true` (it seems to cause the problem)
2. At line `208` I have added the `momentum-x` css class to the table wrapper to enable the overflow-x

Let me know if you want further information or if you need a tester.

Thank you

**Comment by alfonsocuccaro** [comment]
@tabacitu I'm sorry but I just noticed that the solution I posted is not related to this issue but to #3138

**Comment by tabacitu** [comment]
Hmm... actually @alfonsocuccaro , this might need a mobile-only solution... but let's call it an "out-of-the-box" solution 🤣 

Even if we do find a way to show all of them, I expect we'll have another problem - the viewport is just TOO SMALL to show more than one column. To show both the checkbox and a text column with a reasonable amount of characters (100-120-140) that you understand what item the row is about.

So here's what I propose, open to feedback: **what if we hide the bulk actions on the smallest viewport size?** Since you wouldn't be able to properly see and use everything, it's no use showing them anyway. And if you _do_ want to use bulk actions on mobile, you only have to turn your device around, on landscape, and it'll show.

What do you think of this solution @alfonsocuccaro ? @pxpm ? @promatik ?

**Comment by alfonsocuccaro** [comment]
@tabacitu I'm using Laravel backpack since few weeks so I don't know really well what Backpack "hides" in its background, but I think it could be affordable a mobile-only solution where portrait view is not "limited". Look at the image to see what I think we could do: giving to the checkbox a little space I think it could be nice and useful.

![image](https://user-images.githubusercontent.com/6061785/91176944-4d799600-e6e3-11ea-9569-0153117b7dec.png)

**Comment by promatik** [comment]
Hi @alfonsocuccaro!

First off all, thank you for rising this issue and to provide a solution for it, it was a known bug, quite difficult to solve. So rising the issue made us look at it and work on it once again, and in the meantime, I think we came up with a solid solution for it.

#3331 fixes most of the problems related to crud table 🙌 like the other issue you open https://github.com/Laravel-Backpack/CRUD/issues/3138 about aligning table header.

I'll close this in favor of #3331.
Since it's a breaking change it will get merged only on 4.2.
