### ISSUE TITLE
[Bug]  I can't get all the deleted data

### ISSUE THREAD

**Issue by mmt2597** [Laravel-Backpack/CRUD#3144]
# Bug report

### What I did
This is my only clause no other else.
`CRUD::addclause('whereNotNull', 'deleted_at);` and i tried to displayed as sql raw by doing this 
`dd($this->crud->query->toSql());` and it shows `'messages'.'deleted_at' is null` is always using null
![image](https://user-images.githubusercontent.com/26489387/90969232-d7c9ca80-e528-11ea-88cf-bdc916a94868.png)

I have actually one deleted row
![image](https://user-images.githubusercontent.com/26489387/90969328-b61d1300-e529-11ea-9273-c5b6d488ffd0.png)

I can't get any data 
![image](https://user-images.githubusercontent.com/26489387/90969321-9dacf880-e529-11ea-9453-6497f8fd743c.png)

**Comment by pxpm** [comment]
Hello @mmt2597 , thanks for the report.

I don't think this is a backpack bug, but rather a bad implementation on your side. 

If you use SoftDeletes in your models, to query the trashed items you must use `withTrashed()` on the query, otherwise Laravel will automatically append the `is null condition` so when you query the model you won't get the `deleted` items. 

You have also `onlyTrashed()` to query only the trashed items. 

I recommend you check Laravel Documentation on Soft Deletes: https://laravel.com/docs/7.x/eloquent#querying-soft-deleted-models

If I am wrong and this is indeed a backpack bug, please re-open this issue and let me know so I can investigate further. 

Best to you,
Pedro
