### ISSUE TITLE
Class 'CRUD' not found when running artisan

### ISSUE THREAD

**Issue by nateluzod** [Laravel-Backpack/CRUD#315]
Running into this issue when using `artisan`

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'CRUD' not found
```

This is after a fresh `composer update`

The error goes away when I update my routes to remove reference to this class:

```
// Admin
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function()
{
  // CRUD::resource('challenge', 'Admin\ChallengeCrudController');
  // CRUD::resource('solution', 'Admin\SolutionCrudController');
  // CRUD::resource('status', 'Admin\StatusCrudController');
});
```

Definitely requiring crud in my composer.json file:
```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "backpack/base": "^0.7.11",
        "backpack/crud": "^3.1",
        "backpack/newscrud": "^2.1",
        "backpack/permissionmanager": "^2.1",
        "backpack/pagemanager": "^1.1",
        "backpack/MenuCRUD": "^1.0",
        "backpack/settings": "^2.0"
    },
```

I'll keep at it, but if anyone knows a fix it would be helpful.

**Comment by tabacitu** [comment]
Hi @nateluzod ,

I'm pretty sure you missed [step 2 of the Backpack\CRUD installation](https://laravel-backpack.readme.io/docs/installation-on-laravel-53#section-3-install-backpackcrud):

2) Add this provider to your config/app.php, after "base":

        Backpack\CRUD\CrudServiceProvider::class,


Make sure you've done all the steps please, otherwise you're sure to have problems. Also, a ```php artisan dump-autoload``` might help.

Cheers!
