### ISSUE TITLE
[Bug] Illegal offset type when I am using repeatable to store pivot data

### ISSUE THREAD

**Issue by rashmiranjanrrs** [Laravel-Backpack/CRUD#3152]
# Bug report

### What I did

 CRUD::addfield([
            'name'      => 'categories',
            'label'     => 'Testseries Modules',
            'type'      => 'repeatable',
            'entity'    => 'categories',
            'pivot'     => true,
            'fields' => [
                [
                    'type'    => 'select_from_array',
                    'name'      => 'category_id',
                    'options'   => Category::get()->pluck('name','id')->toArray(),
                    'wrapper' => ['class' => 'form-group col-md-6']
                ],
                [
                    'name'    => 'time',
                    'type'    => 'time',
                    'label'   => 'Time',
                    'wrapper' => ['class' => 'form-group col-md-6'],
                ],
            ]
        ]);

### What I expected to happen

![ice_screenshot_20200825-193828](https://user-images.githubusercontent.com/54047909/91184938-d7892500-e70a-11ea-8695-255d4c5029e5.png)

_I have TestSeries and categories table and there is a pivot table for storing the testseries_id and category_id with time. I am trying to do things by repeatable field but it's throwing me this Error._

### What happened

**Its throwing Illegal offset Error.**

Please help me with this. Thank you.

**Comment by pxpm** [comment]
Hello @rashmiranjanrrs 

Have a look at: https://github.com/Laravel-Backpack/CRUD/pull/2938

It's a work in progress but from last tests it was working

**Comment by rashmiranjanrrs** [comment]
No still it's not working. Check this ss where actually its throwing error.

![ice_screenshot_20200827-234050](https://user-images.githubusercontent.com/54047909/91479531-3394aa80-e8bf-11ea-9855-55ed4c21d46b.png)
![ice_screenshot_20200827-234135](https://user-images.githubusercontent.com/54047909/91479575-427b5d00-e8bf-11ea-930c-edd06b68cdbf.png)

**Comment by pxpm** [comment]
Hello @rashmiranjanrrs 

From your code I don't think you are using the code in the PR I provided. 

Also please remove `pivot => true` from your repeatable field definition, there is no need/usage for it in repeatable field and that is triggering the error you are describing.

If you remove it you will not trigger that error and are able to handle the pivot saving process on your own (overwritting save function, using mutators et all ... )

I don't think this is a bug in backpack, because repeatable ** IS NOT ** a pivot handler field. We don't mention it in the docs either. We plan to add some kind of support for it like in the PR I direct you, but it's not implemented yet. 

I am going to close this because I am almost sure that using `pivot => true` here is causing the error (and you should **NOT** use it here). 

They way to do it is to intercept the repeatable field in your controller and save it to whatever table you like.

If I am wrong please re-open. Also feel free to keep any discussion even if this is closed. 

Wish you the best,
Pedro
