### ISSUE TITLE
(Question) Output extra value to view or add own method and view in crud controller

### ISSUE THREAD

**Issue by Webpicasso** [Laravel-Backpack/CRUD#316]
Hi there,

first I wan't to thank you for this great laravel package. It's an amazing time saver :smile: and I'll support you with paying a commercial license.
CRUD works fine for me an I got all up an running. Now I came to some special requirements and  I would be happy if could give me some help for that. 

I have created a CRUD for budget planing. In the overview  I want to output the total amount of all visible cols at the end of the table. What is the best way to get the value from the controller to the view without changing the core package? 

If I need some more modifications in the view:
Is it possible to use an own method and view within a crud controller? (I got this only working by adding a new method "get" to the CrudServiceProvider.php).  

Thanks in advance
Christian

**Comment by tabacitu** [comment]
Hi @Webpicasso ,

Glad to hear that! Let's break it down:
1. Yes, you can use your own method and view within your ProductCrudController. Just add a route to it in your web.php file. For example:
```php
// Admin Interface Routes
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function()
{
        Route::get('product/custom-method', 'ProductCrudController@customMethod');
	CRUD::resource('product', 'ProductCrudController');
});
```

2. So what I understand is that you want a column that shows the total (a sum of other columns). If I were you, I'd do as much as possible in the model, since you might use that total somewhere else in your application. So in the model I'd use a [Laravel accessor](https://laravel.com/docs/5.3/eloquent-mutators#defining-an-accessor) for the total. Say:
```php
    public function getTotalAttribute($value)
    {
        return $this->attribute_1 + $this->attribute_2;
    }
```
Even thought that column doesn't really exist, you'll now be able to use $product->total everywhere, like it did. So adding a column in the CRUD will be simple. In your ProductCrudController:
```php
$this->crud->addColumn('total');
```

There are _a bunch_ of ways to customize/extend Backpack, because of its simple architecture. I strongly recommend you go through [this page](https://laravel-backpack.readme.io/docs) and do everything it says under "getting started". It will really _really_ speed you up.

Cheers!

**Comment by tabacitu** [comment]
P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by Webpicasso** [comment]
Hi @tabacitu,

thanks for the fast answer. I meant the total amount of one field in all rows (not column, sorry, was a typing error before) and I want to ouput total amount in an extra row at the end of the table. Should I build an own view or is there another way? 

Thanks
Christian

**Comment by tabacitu** [comment]
Oh I get it now. I think the cleanest & fastest way is with a separate controller method and view, yes.

Cheers!

**Comment by thatoe** [comment]
Overwrite your index function and get total value in your index function.

`$items = $this->data['crud']->getEntries();`
`$items->total = $this->data['crud']->getEntries()->sum('column');`

and in list.blade.php 

`@if(isset($entries->total))`
     `Total - {{$entries->total}}`
`@endif`
