### ISSUE TITLE
Error 404 after first login

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/CRUD#3185]
I just install version 4.1 with laravel 7.x and after create user and login to dashboard it return Error 404 not found with route /home

**Comment by pxpm** [comment]
@bahman2216 

Maybe you can try to clear the caches. `php artisan route:clear` `php artisan config:clear`.

If you haven't overriden the default login controller you should be redirected to `/dashboard` not home.

```php
 // Redirect here after successful login.
        $this->redirectTo = property_exists($this, 'redirectTo') ? $this->redirectTo
            : backpack_url('dashboard');
```

Let me know.

Best,
Pedro

**Comment by pxpm** [comment]
@bahman2216 I may have misleaded you here.

Make sure you are installing the latest version of Backpack. Indeed we had home in our codebase, I could not found it anymore because it was removed in #3111 and tagged with BP version: [4.1.17](https://github.com/Laravel-Backpack/CRUD/releases/tag/4.1.17)

I am going to close this, as I think this is solved. 

If I am wrong please re-open. 

Wish you the best,
Pedro

**Comment by kiba91** [comment]
@pxpm I have same issue. I clone my local site to another dev computer. I get 404 error when accessing /admin pages. 
I can access the welcome page successfully.

I've tried your suggestion to clear the cache but it doesn't help. Is there any other cause that makes the admin 404. thanks
