### ISSUE TITLE
Case Insensitive Search

### ISSUE THREAD

**Issue by PolywickStudio** [Laravel-Backpack/CRUD#320]
At the moment, I am coding:

$this->crud->orderBy('name', 'asc');

This is good, however, I need case insensitive search. Is there a way to do so in Backback CRUD?

**Comment by OwenMelbz** [comment]
Hey. As mentioned on Gitter, it is just laravels default ordering system and then uses datatables on the frontend.

So your best bet is to dig around the documentation for those yourself or wait for the Xmas period to pass and wait for somebody to have time to explain.

I'd also recommend going to Stackoverflow as this is laravel specific rather than Backpack.

Good luck!
