### ISSUE TITLE
[Feature Request] Tailwind Support for backstrap?

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/CRUD#3249]
# Feature Request

Hi,
I saw a related post in backpack base package but that doesn't apply here.. but just wanted to know if there is any plan on tailwind implementation? or should we start working on child theme structure instead?

**Comment by tabacitu** [comment]
Good question. We don't have any plans for supporting/moving Backpack onto Tailwind at the moment. It is possible to do, of course, with a "child theme" as you said. But it'd basically mean having to rewrite all blade files, or creating a compatibility layer - using `@apply` to get the same classes as Bootstrap/CoreUI, but coded in Tailwind. Which is something that will not bring enough benefit to be worth doing, in my opinion, and then we'd need to maintain two themes, not one. We'd do it, if your users ask us too, but it doesn't really make sense to be honest.

All in all, I don't think TailwindCSS is a good choice for an admin panel. We tried it, prototyped a solution, even bought TailwindUI to see if it'd make sense to use it - and it doesn't. The way I see it:
- Tailwind might be a great choice for the user-facing part of the website, if you have a custom design that doesn't use the Bootstrap grid; start from scratch, create whatever you want;
- for all other purposes, when you're working with a ready-made design, which _does_ use a grid system like Bootstrap's, nothing beats Bootstrap in terms of how fast you can get things done; for admin panels in particular that's the smart way to go, in my opinion:
   - the grid system is standard, Bootstrap's will do just fine;
   - there are endless options for plugins on Bootstrap;
   - there are endless options on "how to do x" for Bootstrap;
   - having a Bootstrap theme like Backstrap available means you can copy-paste HTML blocks from the Backstrap theme;

The only _valid_ argument that Tailwind makes against Bootstrap, in my opinion, that it'll make your app "_not look like Bootstrap_" is mute when talking about admin panels. Tailwind admin panels look exactly like Bootstrap admin panels. They both look like _admin panels_ 😄 

Of course, there are some cool things about Tailwind, the helpers are so much more intuitively named, and TailwindUI just looks freakin' spectacular in terms of design. But the benefits Bootstrap brings to the table are just too many to be worth the switching cost for admin panels, in my opinion. You get everything done for you, from design to responsiveness to huge community benefits. Difficult to top that.

I'll keep reevaluating this decision as the time goes by and there are more developments regarding Tailwind and Bootstrap. And of course, I'm open to being convinced otherwise. But at the moment it really doesn't make sense to use Tailwind for admin panels. If what you're looking for in a CSS framework is for it to save you time, Bootstrap will continue to save you WAY more time than Tailwind, when building admin panels.

**Comment by tabacitu** [comment]
To anybody interested in the topic - I've closed this because we use Github as a to-do list and this is not currently a to-do. But please reply if you think I'm wrong/right/whatever 😄 I expect this issue to be up for debate for quite a while 😆
