### ISSUE TITLE
Sidebar bug

### ISSUE THREAD

**Issue by nekulin** [Laravel-Backpack/CRUD#3319]
If I have 2 links

1) page1
2) page2

then immediately 2 will be active, this is not correct. I rewrote your script, I think it's better.

sidebar.blade.php

Before

```

@push('after_scripts')
  <script>
      // Set active state on menu element
      var full_url = "{{ Request::fullUrl() }}";
      var $navLinks = $(".sidebar-nav li a, .app-header li a");

      // First look for an exact match including the search string
      var $curentPageLink = $navLinks.filter(
          function() { return $(this).attr('href') === full_url; }
      );

      // If not found, look for the link that starts with the url
      if(!$curentPageLink.length > 0){
          $curentPageLink = $navLinks.filter( function() {
            if ($(this).attr('href').startsWith(full_url)) {
              return true;
            }

            if (full_url.startsWith($(this).attr('href'))) {
              return true;
            }

            return false;
          });
      }

      // for the found links that can be considered current, make sure 
      // - the parent item is open
      $curentPageLink.parents('li').addClass('open');
      // - the actual element is active
      $curentPageLink.each(function() {
        $(this).addClass('active');
      });
  </script>
@endpush
```

After

```
@push('after_scripts')
  <script>

      var currentRoute = "<?= array_values(explode('.', Route::current()->getName()))[0] ?>";

      var $currentPageLink = $(".sidebar-nav li a[data-route='" + currentRoute + "'], .app-header li a[data-route='" + currentRoute + "']");

      // for the found links that can be considered current, make sure 
      // - the parent item is open
      $currentPageLink.parents('li').addClass('open');
      // - the actual element is active
      $currentPageLink.each(function() {
        $(this).addClass('active');
      });
  </script>
@endpush
```

I added data-route for convenience, example

```
<li class='nav-item'><a class='nav-link' data-route="page1" href='{{ backspace_url('page1') }}'><i class='nav-icon la la-question'></i> Page 1</a></li>

<li class='nav-item'><a class='nav-link' data-route="page2" href='{{ backspace_url('page2') }}'><i class='nav-icon la la-question'></i> Page 2</a></li>
```

**Comment by pxpm** [comment]
Hello @nekulin 

Thanks for the report.

Could you please share the code you added to sidebar (to add the links) ? Also the full links ?

Thanks,
Pedro

**Comment by tabacitu** [comment]
Thanks for reaching out @nekulin . Indeed we have a known hole inside the sidebar item activation logic. We've talked about it in more detail here https://github.com/Laravel-Backpack/CRUD/pull/3121 and tried to find a solution, but in the end... we didn't. I'd love to have this fixed though.

I haven't tested your solution, I'm sure it works, but right off the bat I see a problem - it adds the `data-route` attribute, which makes it A LOT easier to track which route is which, but... it also _makes it a huge breaking change_. If we do that, we'd have to tell everybody to update their sidebar items, just to fix this small bug, because people will not have that in their files. Which is... you know... not good 😀 Also, even if we were to do this in 4.2 when we _can_ introduce breaking changes, I don't know if we _should_ do it like that, because it adds mandatory code to ALL sidebar items, only to fix a very particular corner case.

See what I mean? This is a small but tricky one 😀

But maybe we reframe your idea a little bit, maybe it takes us on a good path... Maybe another (non-breaking) option would be to _yes_ add a data attribute as a differentiator, but make it _optional_. But, if we're to do something like that... we need to also take into account that one CRUD can include multiple routes, with multiple route names, one for each operation. So you'd also have `product.create` and product.update` that also need to trigger that sidebar item to be active... So we're kind of back to square one, aren't we...?

**Comment by nekulin** [comment]
All routers will work, add data-route and check whether it is already installed to support the old version.

**Comment by tabacitu** [comment]
Got it, thanks @nekulin . Unfortunately we can't add data-route at the moment, it would be a huge breaking change. We'll take another look before we launch 4.2. Until then please see #3121 for a workaround.

Cheers!
