### ISSUE TITLE
setDefaultPageLength and setPageLengthMenu not working?

### ISSUE THREAD

**Issue by 411x** [Laravel-Backpack/CRUD#3326]
Laravel Framework 7.28.4
Backpack 4.1.27
PHP 7.3

Hello,

Following this chapter : https://backpackforlaravel.com/docs/4.1/crud-cheat-sheet#page-length
I tried to add more rows to a crud (I would like to display 50 lines instead of the default 10). 

In my app/Http/Controllers/Admin/BlablaCrudController.php :

```    /**
     * Configure the CrudPanel object. Apply settings to all operations.
     * 
     * @return void
     */
    public function setup()
    {
        CRUD::setModel(\App\Models\Blabla::class);
        CRUD::setRoute(config('backpack.base.route_prefix') . '/blabla');
        $this->crud->setDefaultPageLength(50);
        $this->crud->setPageLengthMenu([50, 100, 150]);
    }
```
- Yes, i have more than 50 rows to display
- I cleared all the laravel caches
- I cleared my session
- I tried the static syntax

But this does not seem to be working.  Am I missing something?

**Comment by pxpm** [comment]
Hello @411x thanks for bring this to our attention.

You are totally right. The documentation is missing on that point. 

At the moment, and if you check in default config, the way to setup the paginator length is: `[[array, of, values], [array, of, labels]]`, if you don't specify the labels you still need to specify a multidimensional array, so in your scenario: `[[50, 100, 150]]`

But this brings another thing to my attention. It's really not ideal to have to specify multidimensional arrays if we can specify a single array, or even better, if you want to specify `key => 'label'`.

Instead of just changing the documentation I went ahead and submited PR #3332 that should allow you to define the paginator as it is described in the docs.

In the meanwhile and while we merge the fix, please use the solution I provided. If it went ahead and test the code in the PR #3332 let there a comment about your experience.

I will be closing this, let's address anything related with this issue in the PR thread. 

Wish you the best,
Pedro
