### ISSUE TITLE
[Feature Request] Make the curd operations notifications more human-readable

### ISSUE THREAD

**Issue by soufiene-slimi** [Laravel-Backpack/CRUD#3329]
# Feature Request

### What's the feature you think Backpack should have?

Make the curd operations notifications more human-readable, something like **The product has been modified successfully.** instead of **The entry has been modified successfully.**. using the `$this->crud->entity_name` we can pass the entity singular name as a translation attribute.

As a preview of the changes in the update operation:
```diff
// show a success message
-- \Alert::success(trans('backpack::crud.update_success'))->flash();
++ \Alert::success(trans('backpack::crud.update_success', ['entry' => mb_strtolower($this->crud->entity_name)]))->flash();
```
### Have you already implemented a prototype solution, for your own project?

Yes, once this feature gets approved I'll fire a PR.

### Do you see this as a core feature or an add-on?

This should be a core feature.

@tabacitu, @pxpm

**Comment by promatik** [comment]
@soufiene-slimi there is an issue open that addresses part of this problem; https://github.com/Laravel-Backpack/CRUD/pull/3106

Part of it, because to improve these alerts you'll have a problem in most of the languages, at least in Portuguese you'll need the pronoun in this sentence, otherwise it's "worse" to use the entity name.

**Comment by soufiene-slimi** [comment]
Thanks for the ref @promatik, Duplicate of #3106
