### ISSUE TITLE
[Bug] CRUD::addField(...) does not resize fields

### ISSUE THREAD

**Issue by yabbou** [Laravel-Backpack/CRUD#3338]
# Bug report

### What I did
```
   CRUD::addField([
            'type'        => "select",
            'name'        => 'vendor',
            'size'        => '4',
        ]);
```
### What I expected to happen

Size the `vendor` down to `col-4` column.

### What happened

The `vendor` field remained 100% width.

### What I've already tried to fix it

The other format works perfectly.

```
CRUD::field('vendor')->size(4);
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.8 (cli) (built: Jul  9 2020 11:30:39) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.19.0@67d6d9688122dcf6c449b74ddc873fc9934e81e6

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323
```

**Comment by tabacitu** [comment]
Hi there, thanks for opening the issue! 

To achieve the same thing using the array syntax you should do:

CRUD::addField([
    'name' => 'name',
    'wrapper' => ['class' => 'form-group col-md-6'],
]);

That should work for you.

I believe this isn't properly explained anywhere - at least not the way I see it now:
- The _fluent_ syntax allows you to define stuff in a shorter more convenient way, it has helpers/shorthands to do stuff like "size" but behind the scenes what that method does is set the "wrapper['class']" on that field to "col-md-6".
- The array syntax is the _verbose_ form - everything you define inside it has to be the exact same way it's received in the field blade file. That might be considered a downside, but it also yields great power - it allows the dev to overwrite anything Backpack considers a default. What the dev defines using the array syntax is law. 

We're in a bit of an awkward moment with the docs, where both syntaxes are used (because they're both supported) so I understand why this might be confusing. But generally I'd say use the fluent syntax, it's shorter. Only use the array syntax if you want to overwrite something (or you like it better).

----

But I think you bring up a good point. That we should maybe explore further.

As a dev, you'd _expect_ the same thing to work in the array syntax... so maybe we need to support it?

On the other hand, it would be quite unintuitive to define the array syntax one way, and have the CrudPanel overwrite your array to match the format it needs. To define "size" => 6 and have it turn it into a wrapper. And then there's the problem of _other_ helpers/shorthands we'll be introducing in the future. To be honest, it sounds like adding shorthand support to the array syntax will be a nightmare to both devs and maintainers. Yes it would probably make it faster to do this one thing, but it'll make it difficult to understand how it works, and difficult to actually work 😅 

I'm going to give this some more thought and maybe reopen, but for the moment I don't think it's worth adding this. Open to debate.

Cheers!

---

I guess the _fluent syntax_ will only be getting better in time (with more shorthands) while the _array syntax_ will have feature parity (of course) but it will not (and cannot) have the same kind of shorthands like "size". So maybe in 4.2 we use the fluent syntax everywhere in the docs, and only have a separate page to explain the array syntax as an "_advanced use case_".
