### ISSUE TITLE
[Bug] after login revisit to login should redirect to home_link

### ISSUE THREAD

**Issue by shiroamada** [Laravel-Backpack/CRUD#3353]
# Bug report

### What I did
after I successful login the **admin** user, I visit again to `/admin/login`, it redirect to `/`,

### What I expected to happen
I expect to redirect to "home_link" location 'admin/dashboard'

### What happened
It redirect to `/`

### What I've already tried to fix it
I install Laravel/Breeze, I can set it from the `RouteServiceProvider`
`public const HOME = '/';`
But it want to separate from admin and normal user, How can I set the it path?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.12.3@6707480c5f0db7aa07537f9ad93255b64b65b85e

### BACKPACK VERSION:
4.1.26@ae68ca24844929ac38d2e792197551e823c43570

**Comment by danilopolani** [comment]
Can you check the content of your `RedirectIfAuthenticated` middleware?

**Comment by pxpm** [comment]
Hello @shiroamada 

Thanks for raising your issue. 

You can configure what happens when user is autenticated using `RedirectIfAuthenticated` laravel middleware. 

We use github for issue and feature requests so I am going to close this. For this kind of questions it's better to use Stackoverflow or our Gitter chat. Also reddit or twitter. work sometimes. 👍 

I will let the support bot close this issue so you get the links to our social mediums, usually it's better to ask there first before opening issues, there are alot of people contributing there and helping each other.

Best,
Pedro
