### ISSUE TITLE
it might be issue in muli upload field

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#337]
Hi @tabacitu 

for multiupload field

when i put this function in model
```
public function setMultiIconImagesAttribute($value)
    {
    $attribute_name = "multi_icon_images";
    $disk = "public_folder";
    $destination_path = "/uploads/products/icon_images";

        $this->uploadMultipleFilesToDisk($value, $attribute_name, $disk, $destination_path);
    }

for  $destination_path it never accept the first "/";

instead of  $destination_path = "/uploads/products/icon_images";
it gets saved in table like "uploads/products/icon_images" without "/"

thank you in advance



```

**Comment by OwenMelbz** [comment]
I think technically that is correct.

Imagine your web server root was

```
/var/www/mywebsite.com/public
```

if it stored `/uploads/products/icon_images/image.jpg` then it would not exist.

If you did something like `file_exists('/uploads/products/icon_images/image.jpg')` this would return false, because the starting / assumes it to be from the start of the operating system.

However it is actually located in

```
/var/www/mywebsite.com/public/uploads/products/icon_images/image.jpg
```

So by having a relative route, it checks from the application root, rather than the operating systems root.

When you pull out items from storage/uploads folder to get displayed on the frontend you can use laravels built in `asset()` function, which will handle all the `/` for you. eg if you did `asset('uploads/products/icon_images/image.jpg')` you should get back `http://mywebsite.com/uplaods/products/icon_images/image.jpg`

If you REALLY want a `/` at the start, then you'll need to create a `getMultiIconImagesAttribute` function, which appends it to the start, or you'll need to create your own upload function
