### ISSUE TITLE
[Clarification] jQuery to manipulate radiobuttons no longer supported

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#3382]
# Bug report

Upgraded a project from 4.0 to Backpack 4.1 that uses jQuery to manipulate radiobuttons on a certain form. Backpack seems to no longer support the manipulation of radiobuttons (and maybe others?) through jQuery as they cannot be referenced anymore.

### What I expected to happen

Since the jQuery is very simple I expected it to still work as before

```
if (data.accounttype==1) {
  $("#account_type_id_1").prop("checked", true);
} else {
  $("#account_type_id_2").prop("checked", true);
};
```
But it doesn't work this way anymore. 

### What happened

I believe that since commit https://github.com/Laravel-Backpack/CRUD/commit/432c7ad624f17a4f4ef39b16adb16062ebcf972f#diff-a2efdb166bd02ef6c483c84a018ba61da52a4f1eb04985589d695c37a266bda7 where it was facilitated to have radiobuttons in repeatables there is a hidden input being added to the code and the name properties from the radiobutton input were removed.

### What I've already tried to fix it

There are some alternative ways to reference the actual radiobutton, but since there is a randomised ID and there is no longer a name property for the radiobutton (it got taken over by the hidden field) I believe there is no longer a way to this.  So something like this doesn't work either

`$("input[name=account_type_id][value='1']").prop("checked",true);`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.15.0@22e4182fa0885dea3772106c3b6df705b7c7363e

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

**Comment by pxpm** [comment]
@timbertens thanks for raising this issue. 

This change was needed to make radios work inside repeatable containers (where the fields are added with JS, and cannot have a name (otherwise would be submitted as main form fields)).

We already had some discussion about this, and probably we are going to use `[arrayed][field_names]` (if it's possible, we haven't started working on this yet) instead of removing the name from the inputs. 

IT should still be possible to achieve what you want with a little bit more effort:

- select the hidden input and get the closest `form-check`.
- get radios inside the previous selected container: `$("input[type=radio][value='1']").prop("checked",true);`

@tabacitu we might need to add this to upgrade guide ? 

Best,
Pedro

**Comment by tabacitu** [comment]
Hmm... I think it's unlikely that many people have been manipulating the radio buttons with JS, so I don't think it's worth adding it to the upgrade guide. But we should definitely have a working solution for those who search and stumble upon this issue.

@timbertens can you please share your previous code so we find a proper alternative to it, for you and anybody else who needs this in the future? It should definitely be possible to do the same thing but with a different selector (and action).

Cheers!

**Comment by timbertens** [comment]
@pxpm in my tests I did something similar (see first comment), but I've got the problem that the value set by jquery did not sync back to the hidden field, so I had to set both the radiobutton for the UI and the hidden field to hold the actual data. 

@tabacitu yeah, it is not really a standard operation.  For your reference: in my case it is a custom field that looks up value (VAT number) over the VIES webservice and fills in the company details.

I ended up changing the previous code

```
if (data.accounttype==1) {
  $("#account_type_id_1").prop("checked", true);
} else {
  $("#account_type_id_2").prop("checked", true);
};
```

into this

```
if (data.accounttype==1) {
  $("[name='account_type_id_dummy'][value='1']").prop("checked",true);
  $("[name='account_type_id']").val("1");
} else {
  $("[name='account_type_id_dummy'][value='2']").prop("checked",true);
  $("[name='account_type_id']").val("2");
};
```

and adding an attribute 'name' to the radio field like this

```
'attributes' => [
  'name' => 'account_type_id_dummy',
]
```

**Comment by tabacitu** [comment]
Oh, got it!

Thanks for sharing your solution @timbertens - I'm sure someone will find that useful. One small note though - I'm pretty sure that will make the field NOT work inside the repeatable, the fact that it needs a `name`. But that's totally fine, I think custom fields don't necessarily need to work inside `repeatable`. If they're only used in _one spot_, they should work in that _one spot_. For that purpose, if you haven't already done so, my recommendation would be to _name that field something else_, like `custom_radio` instead of overwriting the `radio` field. That will allow you to: 
- use the `custom_radio` field type in that one place where you need it to work like that;
- use the stock `radio` field type anywhere else (including inside a `repeatable` field); and get updates for it;

> in my case it is a custom field that looks up value (VAT number) over the VIES webservice and fills in the company details.

Ugh... VIES... say no more! 😂 Recently had to deal with that webservice... what a pleasure 🙄

Closing because it has a solution.
Cheers!

**Comment by timbertens** [comment]
no problem! Just for clarification: the VIES lookup field is the custom one, the radiobuttons are still the default ones. But you're right that VIES lookup fields will only work in certain conditions, don't have the ambition to make into a repeatable field, they don't deserve it.  If VIES would have their repo over here, I think GitHub would explode 😂

**Comment by tabacitu** [comment]
Haha definitely. If you didn't know about this, I use this package to make VAT-work _a little_ easier in Laravel: https://github.com/dannyvankooten/laravel-vat . Maybe it helps you too.
