### ISSUE TITLE
Translate labels with translation strings stored in `resources/lang` directory

### ISSUE THREAD

**Issue by masetto** [Laravel-Backpack/CRUD#3390]
I don't know if field labels can translated by resources/lang/<mylanguage>.json. 
Now in crud controller I do this:
```
foreach (CRUD::fields() as $k => $c) {
   CRUD::field($k)->label(__($k));
}
```
but it seems a mess. How can I do better? Couldn't you add this feature?

**Comment by pxpm** [comment]
Hello @masetto thanks for the proposal.

You can use any laravel functionality for translations, `arrayed.notation` or `__('string')` but I think you already know that anyway: https://laravel.com/docs/8.x/localization#using-translation-strings-as-keys

You solution seems very clean, other than that define the label "per field".

In backpack we just `echo` the label whatever developer gives us, we don't enforce any `translation method` 

```php
<label>{!! $field['label'] !!}</label>
```

We might be able to run `__($field['label'])` by default, but I think that could bring in some other problems, like don't wanting the label to be translated because the same string should be translated somewhere else, but not there. Then there is no way of telling `don't translate this please`. 

So I think the way we built it, is the most intuitive. Not everyone needs translations, who needs them can easily add them. 
I personaly don't see what you did like `A BIG MESS`, nor adding `->label(__('some'))` in the field definition, but it's my personal opinion. 

If that is something you will use in all your cruds, you can abstract that to a trait `RunsLabelsThroughTranslation` and add it to your controllers. Then you can override backpack `create` and `update` functions https://backpackforlaravel.com/docs/4.1/crud-operation-create#callbacks and run your `$this->applyTranslatedLabels()` by default. 

Maybe I am not seeing the big picture. Do you have any other suggestion on how we could implement it @masetto ?

Best,
Pedro

**Comment by masetto** [comment]
Hello @pxpm, thanks for your answer. 
I think we could add a property as `public $traslateLabels = false` in AutoSet trait (`vendor/backpack/crud/src/app/Library/CrudPanel/Traits/AutoSet.php`). Then in function `makeLabel` we could update like this:
```
...
$label = trim(mb_ucfirst(str_replace('_', ' ', preg_replace('/(_id|_at|\[\])$/i', '', $value))));
if ($this->translateLabels) {
    $label = __($label);
}
return $label;
```
What do you think about?
However, it's not so important. I can do as you suggested.

**Comment by promatik** [comment]
I agree on implementing something like that.
I think I've always used translations on my CRUDs, it doesn't bother me to use it like;
```php
->label(__('some'))
```

Another option, could be;
```php
->transLabel('some')
```
and perhaps;
```php
->transPlaceholder('some')
```

**Comment by tabacitu** [comment]
Hey guys,

I also don't mind doing `->label(__('some'))` - I think that is clean enough.

From what I know, 90% of admin panels don't have translations. The overwhelming majority of admin panels, even if they are for multi-language websites, keep their admin panels in one language alone, since the admins all speak one language. As such, I don't think a wide solution like `public $traslateLabels = false` would be appropriate. At least that's my first thought about it - might be wrong.

What @promatik proposed though... sounds like a super-simple solution, that could work very well. We'd just add a few more helpers to the `CrudField` object, something like `transLabel()`, `transPlaceholder()`, `transHint()` which do `->label(__($value))` behind the scenes. It could even work as a Backpack add-on - since the `CrudField` class is Macroable, there is the opportunity of adding methods to it on runtime. So we could split up this logic in an add-on, if we consider it's polluting the main with niche functionality. Not sure if needed.

For the moment though, we're in a feature freeze, focused on fixing all 4.1 issues. Let's think about this again with an open mind when we start working at 4.2. Thanks for raising this @masetto .

Cheers!

**Comment by tabacitu** [comment]
Changed my mind, I think `->label(__('some'))` is just as good as `->transLabel('some')`, but without us building or maintaining anything sooo... let's just use that. No need to add a wrapper on top of a Laravel feature, when that feature already exists.

Of course, I might be wrong - I often am. If you think us please let me know.

Cheers!
