### ISSUE TITLE
Error when using blueprint to create a model with a _ in the name i.e. my_entity

### ISSUE THREAD

**Issue by osieman1** [Laravel-Backpack/CRUD#3393]
# Bug report

I used blueprint to create a model for a model with an underscore in it.

 Models/override_value:
  OV_ID: integer
  OV_TIME: string:6
  OV_FROM: date
  OV_TYPE: enum:1,2

### What I expected to happen

I expected the sidebar to work as it does with the other models but it fails with:  The model does not exist.

### What I've already tried to fix it

Two things seem to be missing:
1) It cant connect to the model override_value.php

2) The column info is missing 
        CRUD::column('OV_ID'); 
        etc etc
and replaced with 
        CRUD::setFromDb(); // columns

I tried to remove the _ from the crudcontroller model request and the model php file, and add the missing fields but this has caussed other errors after it found the correct model.

### Backpack 4.1, Laravel 8, PHP 7.3, mysql 8

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.24 (cli) (built: Oct 27 2020 14:44:04) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.18.1@31747193c26ba0a9cb7929a912895d3cdefd10cf

### BACKPACK VERSION:
4.1.28@011e818304b3ebac28b673c1c91018590bdceb12

**Comment by tabacitu** [comment]
Hi @osieman1 - indeed you shouldn't use underscore in model names. That's against the Laravel convention, and PHP classes in general do not use underscore in their name. Since this seems to be a Blueprint problem (not Backpack) and I don't agree we should make it easier to create underscore models... I'm going to close the issue, sorry.

Feel free to convince me otherwise if you think I'm wrong, and we'll reopen. I'm wrong at least once a day like everybody 😅

Cheers!

**Comment by osieman1** [comment]
Hi @tabacitu t
I changed my model to be compatible quite a while back, so I am happy to close this one.

btw: great product and fantastic support in gitter.  

Thanks for the answer.
