### ISSUE TITLE
Allow developers to get the current crud entry based on route parameter

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/CRUD#3400]
# Bug report

### What I did

Referenced `$this->crud->entry->[property]` within a CRUD controllers `setupUpdateOperation()` function when editing an existing entry.

### What I expected to happen

A reference to $this->crud->entry to exist. 

### What happened

The reference to $this->crud->entry is null. 

### What I've already tried to fix it

Nothing.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.15-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.29.3@93f6d565a07045baa0e4b941ae1f733cd5984d65

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

**Comment by pxpm** [comment]
Hello @selected-pixel-jameson thanks for the report.

Backpack has no `setupFields` function built-in. Would you mind to clarify your question ? 

If you are refering to the `edit` function, have a look in Backpack code on how we get the entry: https://github.com/Laravel-Backpack/CRUD/blob/2298dd028d6379ad93973226018d87c21aa2c6c5/src/app/Http/Controllers/Operations/UpdateOperation.php#L64

Best,
Pedro

**Comment by selected-pixel-jameson** [comment]
Sorry. I meant `setupUpdateOperation()`

**Comment by pxpm** [comment]
Thanks for clarify @selected-pixel-jameson. 

Indeed is not possible to have the crud entry inside the `setupUpdateOperation()` because at the time that function is run we (Backpack) don't know what entry is going to be edited. 

If you notice, in my last comment where I refereed you to the `edit()` function, that's the first place where you get the editing entry, there we get the fields that you setup in `setupUpdateOperation()`.

```php
$this->crud->setOperationSetting('fields', $this->crud->getUpdateFields());
```
So if you want to get the entry and manipulate the fields based on the entry you would need to overwrite the `edit()` function, and add/remove your fields there based on current editing entry. 

Let me know if I missed something.

Best,
Pedro

**Comment by selected-pixel-jameson** [comment]
It seems like providing a reference to the instance that is going to be updated within the setupUpdateOperation() function would be a much more convenient and elegant way vs. forcing someone to figure out they need to override the undocumented edit() function and then write a function to filter out fields, add fields or create custom_html fields based on the current instance values. 

I’m just going to create a helper function that will pull the model id out of the URL and load the model that way within the setuUpdateOperation() vs trying to figure out how to add a conditional field within the edit function. 

 public function getCurrentModel()
    {
        $id = \Route::current()->parameter('id');
        $currentModel = null;
        if ($id) {
            $currentModel = $this->crud->getEntry($id);
        }

        return $currentModel;
    }



Jameson Parker
Owner & Software Engineer
www.selectedpixel.com
www.linkedin.com/in/jamesonwparker
(920) 203-4106

**Comment by pxpm** [comment]
That's a valid and very good solution. 

Technically if you know how to write stuff inside `setupXXXOperation` you know how to write it inside `edit()`. There are developers that prefer to ovewrite `edit` and `create` and add the fields there etc. you have `$this->crud` there too. 

There is documentation on how to overwrite crud operation functions https://backpackforlaravel.com/docs/4.1/crud-operation-update#callbacks

Not sure if it's something we should provide in core, or even how to do it properly in core if we do it.

We cannot use `setupUpdateDefaults`, The `defaults` for every operation, are loaded along with the `CrudPanel`, so even if you go to `ListOperation`, you will have the `UpdateDefaults` loaded. What you setup inside `setupUpdateOperation` is what is specific only for that operation, and we run it only when the specific operation is called. That said, if we do it inside `defaults`, sometimes we will have the entry, sometimes don't. 

Having an helper function like `getEntryFromUrlAttribute($attribute)` does not sound bad at all. That way we could tell devs if they want to get the entry inside the `setupXXXOperation` they could use it, even if we don't do it as a default for the operation.

I am in for anything that helps developers (like myself) to speedup our development, we here (Backpack) just need to make sure that we don't pollute (more) the CrudPanel with very niche cases. 

I don't think this is a niche case and it could be helpfull for anyone who needs it. 

That said, even if we don't make this into core I would probably just create an addon that adds this functionality to the crud (Crud is macroable, very easy to add anything without polluting the core)

@tabacitu @promatik  what you think about this ?

I think yesterday somebody asked about the same in gitter. (changing fields based on the current editing entry).

Thanks for the suggestion @selected-pixel-jameson .

Wish you the best,
Pedro

**Comment by promatik** [comment]
I totally agree, and I think this should be a core function, I have this helper for my projects since ever 😅. Many times I want to access the current entry when editing.

These are my helpers _(my crud controllers use a trait with it)_;

```php
public function getEntryId()
{
    return request()->route('id');
}
```

```php
public function getEntry()
{
    $id = $this->getEntryId();
    return $id ? $this->crud->getEntry($id) : null;
}
```

I agree on setting just the entry `$this->crud->entry`, so `$this->crud->entry->id ?? null` in case you need the `id`.

**Comment by soufiene-slimi** [comment]
Hi all, instead of a helper function that will result in one extra query, why not a simple hook (some sort of function with closure as parameter).

**Comment by promatik** [comment]
Maybe to avoid the extra query this should be a getter?
But getters are ugly on PHP  😅 and I don't know about performance ...

```php
public function __get($property) {
  if (property_exists($this, $property)) {
    return $this->$property;
  }
  if ($property === "entry") {
    $id = request()->route('id');
    $this->$entry = $id ? $this->crud->getEntry($id) : null;
    return $this->entry;
  }
}
```

**Comment by soufiene-slimi** [comment]
Hi @promatik, @tabacitu, maybe something like this:

```php
CRUD::field('ref')->label('Reference')->if(fucntion ($crud, $entry) {
    return (int) $entry->ref > 1000 && $crud->hasAccess('access_sensitive_data');
});
```

**Comment by tabacitu** [comment]
Boy do I have good news for you guys 😂

The existing ```$this->crud->getCurrentEntry()``` does just that 🤯😂, and can be used inside `setupUpdateOperation()` just fine. So this sounds to me like a documentation problem, rather than a feature request right?

**Comment by tabacitu** [comment]
Previously the only place where it was documented was [inside CRUD API page](https://backpackforlaravel.com/docs/4.1/crud-api#getters). But since this issue came up, it's obvious that might not be enough.

Maybe we need to mention this inside the Update operation too. Done - [just mentioned it there too](https://github.com/Laravel-Backpack/docs/commit/7e55975055af9d5c5bc9088d934da5fb8743edb3).

Let me know if you guys think there's another place to mention it, or a better/alternative wording for it. Difficult to get in the mindset of someone looking for this, since I'm the one that created the method. It's one of the pitfalls of documentation I guess - the person most likely to write the docs is the person less likely to be able to put himself in a users' shoes. For example if it were me, I would have been searching the docs for "_get current entry_" and I would have found it:
<img width="1612" alt="Screenshot 2020-12-23 at 08 37 59" src="https://user-images.githubusercontent.com/1032474/102996875-3ebcb780-44fa-11eb-909e-4e36c16440df.png">

But that's just because those are the exact words I would use - someone else might use different words.

Closing since I believe we already have a solution for this. But we should think about ways to better document it - let me know if you have ideas on that and we'll do it.

Cheers!

**Comment by iMokhles** [comment]
@tabacitu good and here's example of how to use it inside `store function`
in my example i'm checking the object if already exists or not based on a column identifier if there are an object with same identifier or not already added to DB if no it continue the creation otherwise it show and alert and redirect the user to the list view

```
public function store()
    {
        $this->crud->setRequest($this->crud->validateRequest());

        $req = $this->crud->getRequest();
        if ($object !== false) {
            $this->crud->setRequest($req);
            $this->crud->unsetValidation(); // validation has already been run
            $store = $this->traitStore();

            $newEntry = this->crud->getCurrentEntry();
            $newEntryId = this->crud->getCurrentEntryId();

            // you can use getCurrentEntry or getCurrentEntryId for any propose now 
            return $store;
       }
        \Alert::error('Object already exists')->flash();
        return redirect(backpack_url('object'));
    }
```
