### ISSUE TITLE
Installing 4.1 on Laravel 8 

### ISSUE THREAD

**Issue by MikePageDev** [Laravel-Backpack/CRUD#3403]
# Bug report

### What I did

Ran

`composer require backpack/crud:"4.1.*`

to install on Laravel 8

### What I expected to happen

It to install

### What happened

Received the following error.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - backpack/crud[4.1.22, ..., 4.1.x-dev] require doctrine/dbal ^2.5 -> found doctrine/dbal[v2.5.0-BETA2, ..., 2.12.x-dev] but it conflicts with your root composer.json require (^3.0).
    - backpack/crud[4.1.0, ..., 4.1.21] require laravel/framework ^7.0|^6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.12).
    - Root composer.json requires backpack/crud 4.1.* -> satisfiable by backpack/crud[4.1.0, ..., 4.1.x-dev].
``` 

### What I've already tried to fix it

I have tried to google for a solution but not found one. 

### Backpack, Laravel, PHP, DB version

Laravel 8.17
PHP 7.3.24

**Comment by tabacitu** [comment]
Hmm... that's odd. I just installed Backpack on a fresh Laravel project and it worked fine. 
@MikePageDev what does your `composer.json` look like?

**Comment by MikePageDev** [comment]
I have fixed this by removing doctrine/dbal and installing

**Comment by nihadatakishiyev** [comment]
I experienced similar conflict problem when trying to install doctrine/dbal to my Laravel 8 project in which backpack is already installed. Any idea why would that happen? @tabacitu 

![error](https://user-images.githubusercontent.com/48563852/107510303-29404180-6bbd-11eb-8bab-3f9176aca1b0.PNG)

I also attach a copy of my composer.json file. Thanks in advance!


[composer.txt](https://github.com/Laravel-Backpack/CRUD/files/5958130/composer.txt)

**Comment by lotarbo** [comment]
I have same problem, quick fix for me - remove composer.lock file 😁

**Comment by nihadatakishiyev** [comment]
Deleting composer.lock solved the first problem, however problem 2 still persists. 

![error](https://user-images.githubusercontent.com/48563852/107515623-b6d35f80-6bc4-11eb-9531-9395c1bb33fa.PNG)

**Comment by tabacitu** [comment]
Hi guys,

Indeed, Laravel 8 supports PHP 8, but it also supports _both_ DBAL v2.5+ and DBAL v3.x. Backpack _does_ support PHP 8 in the latest version, but it does _not_ yet support DBAL v3 (see https://github.com/Laravel-Backpack/CRUD/pull/3517). We do plan to add DBAL v3 support but it could take a few days - and depending on what we find it's possible that it'll be a breaking change.

If you don't have a reason to explicitly ask for DBAL v3 (you don't use DBAL v3 features in _your_ code), I recommend you remove the `doctrine/dbal` composer dependency in your project and run `composer update` - that should have the same result as @lotarbo and @MikePageDev  's solution. Doctrine/dbal v2.12.x does support PHP 8, so it should work just fine.

If you have _a dependency_ that needs DBAL v3, however, since Backpack doesn't yet support DBAL v3... that's where you have a problem. The only thing to do in that case is to wait from upgrading that dependency, until we manage to add DBAL v3 support in Backpack. Hopefully we'll be able to do so in a non-breaking manner 🤞

Cheers!
