### ISSUE TITLE
Page or Link - Update Menu Type do not clear the `page_id` data

### ISSUE THREAD

**Issue by kiddtang** [Laravel-Backpack/CRUD#3412]
# Bug report
Changing the type of the menu do not clear the previous field's content, the url generation is correct according to the type, but it causes unexpected result for relationship using "page_id"

Should consider clearing previous `type` data (i.e. `link` or `page_id`) after changing to the new `type`

### What I did:
Step 1: Create a Menu with type of `page_link`, Select a Page
Step 2: Edit the Menu and change the type to `internal_link` and Save

### What I expected to happen:
`page_id` data should be cleared to avoid unexpected result

### What happened:
![image](https://user-images.githubusercontent.com/26017547/67914163-43bdf980-fbca-11e9-8ccc-96b470a9bc6b.png)

**Comment by promatik** [comment]
Hi @kiddtang!
Thank you for your suggestion and sorry for taking so long to fix it.

That behavior wasn't the desired at all, the `page_or_link` field was in the need of some care from us for a long time 😅
So I took the time and end up refactoring the field. Since it's a major change on the field, we are going to postpone it to v4.2. It's already tagged for review in 4.2 when we finish up this version 🙌

If you have the need, and the time, you can take a look at the new field here; #3459. It should fix the issue you described.
Let's move the conversation to the new PR, thank you once again @kiddtang ✌
