### ISSUE TITLE
[Error] online tests are not running

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#3444]
![image](https://user-images.githubusercontent.com/7188159/103767586-ce915400-5018-11eb-8e75-e0f2b6dd2c01.png)

Tests are failing online. This `coverage` was introduced by @promatik https://github.com/Laravel-Backpack/CRUD/commit/b36e82fea410ce1efcc644764f1a70b5e73a689a

In my local development it uses PHPUnit 9.x and it's working as expected, but as you can see in online it uses 8.5 (it probably depends on the tested version of php).

So my guess here is that this last change is not compatible with earlier versions of phpunit but we allow them in composer.json `"phpunit/phpunit": "~8.0|~7.0|~9.0",`

I think before this change, phpunit complained about some failing schema on local but passed tests online and local so we just ignored the warning. 

Should we revert it ?

**Comment by promatik** [comment]
😬 @pxpm is it in any way important/relevant to run the tests on PHP Unit 8 online? If not, is it possible to move forward to PHP Unit 9?

**Comment by pxpm** [comment]
@promatik from my understanding the php unit 8 runs in earlier versions of php/laravel that we run the tests too. 

What I mean is that in some of our supported PHP versions the php unit is constrained at version 8, I think. 

This is what I understood from my research on this, maybe @tabacitu should show us the light 🌞

**Comment by tabacitu** [comment]
Ugh I see there are 3 distinct problems regarding tests:
 - [x] **Problem 1.** Indeed because of this change (https://github.com/Laravel-Backpack/CRUD/commit/b36e82fea410ce1efcc644764f1a70b5e73a689a) tests are no longer working when run under PHPUnit 8. We still need to support PHPUnit 8, because we support Laravel 6, which supports PHP 7.2.x; Reverting that particular commit seems to do the trick, we just need to remember to do it again once we drop support for Laravel 6. Until then, the notice is fine, we can live with it. Done in https://github.com/Laravel-Backpack/CRUD/pull/3472
- [ ] **Problem 2.** Php tests are no longer running online, on `push`, because apparently TravisCI demoted us to a lesser plan without letting us know, so for the past 2 months (!!!) they haven't run ANY test for us; I would have happily paid for TravisCI just out of convenience, but maybe it's time to move to Github Actions instead; I'm trying to do just that [here](https://github.com/Laravel-Backpack/CRUD/pull/3470/checks?check_run_id=1722907661); in the process I'll try to make sure we're testing under all possible permutations of Laravel version and PHP version; this should be super-helpful in determining edge cases; 
- [ ] **Problem 3.** Even when run under PHPUnit 9, Laravel 8 and PHP 7.4, one test seems to be failing - `CrudControllerTest::testCrudRequestUpdatesOnEachRequest()`; no idea when this started;

I'm on it. I'll keep you posted.

**Comment by tabacitu** [comment]
Done! We now have online tests again, working thanks to Github Actions. Merged to `master`. Made quite a few minor changes so @pxpm  / @promatik let me know if by some miracle they stop working for you on localhost. They shouldn't... as we're now testing on a lot more combinations. But we _are_ only testing on Ubuntu for now so... you never know.

**Comment by promatik** [comment]
Running well on windows too;
```bash
OK, but incomplete, skipped, or risky tests!
Tests: 243, Assertions: 367, Incomplete: 19, Risky: 1.
```
