### ISSUE TITLE
[Bug] Authenticated user is not available in error view.

### ISSUE THREAD

**Issue by martijnb92** [Laravel-Backpack/CRUD#3446]
# Bug report

### What I did

Visit a page which does not exists to trigger the error view.

### What I expected to happen

Different layout when user is authenticated.

### What happened

Both authenticated and non-authenticated users receive the same error page.

### What I've already tried to fix it

Since `backpack_user()` returns null on exception pages. 
`@extends(backpack_user() && (Str::startsWith(\Request::path(), config('backpack.base.route_prefix'))) ? 'backpack::layouts.top_left' : 'backpack::layouts.plain')` will always return `backpack::layouts.plain`

https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/error_views/layout.blade.php

This is a minor bug, _solved_ by changing that line to `@extends('backpack::layouts.plain')` 

### Backpack, Laravel, PHP, DB version

Backpack 4.1.30

**Comment by promatik** [comment]
Hi @martijnb92!
That's correct, I just tried on demo and it's not working, and it used to work.
I'll investigate further.

**Comment by promatik** [comment]
@tabacitu as far as I'm understanding, there's no way this worked before 😅

Because on a 404 errors, laravel doesn't load the `web` middleware, so no sessions.
Maybe they changed this behavior recently?

I found a way to solve this, with Fallback Routes (https://laravel.com/docs/8.x/routing#fallback-routes)
Should we go ahead and solve it with that? Or is there other way?

**Comment by promatik** [comment]
I'll close this for now, if #3447 isn't the right approach, we may re-open ✌
