### ISSUE TITLE
allowAccess problem 

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#345]
Hi 
I want to allow a user just creating access. So I added this code to CrudController:  

` $this->crud->allowAccess('create');`

but still I see the update and delete buttons . 
what is the problem ?

**Comment by tabacitu** [comment]
Hi @M0H3N ,

By default, CRUD gives access to ```['list', 'create', 'update', 'delete']```. In order to allow access ONLY to "create", please use:
```php
$this->crud->denyAccess(['list', 'update', 'delete']);
```

Cheers!

PS. Now that you mention it, maybe it makes sense to have
- ```$this->crud->denyAllAccess();``` 
- ```$this->crud->allowAccessOnlyTo()```

I've added a [Github issue](https://github.com/Laravel-Backpack/CRUD/issues/347) about this and it will be taken care of.
