### ISSUE TITLE
[Bug] Repeatable with field select2_multiple and relations

### ISSUE THREAD

**Issue by ElyasKhatinzadeh** [Laravel-Backpack/CRUD#3499]
# Bug report

### What I did

I need to use fields with relationship like select2_multiple in repeatable field. The problem is
1) For create method dosn't support to create fields with relations.
2) If i create relation in controller with my own code, for edit it backpack crud can't get default values.

### What I expected to happen

        CRUD::addField([
            'name'  => 'child', // belongsToMany relation
            'label' => 'Media',
            'type'  => 'repeatable',
            'pivot' => true,
            'tab'   => 'Files and Descriptions',
            'fields' => [
                [
                    'name'    => 'title',
                    'type'    => 'text',
                    'label'   => 'Title',
                    'wrapper' => ['class' => 'form-group col-md-6'],
                ],
                [
                    'name'      => 'media',
                    'label'     => "Attach File",
                    'type'      => 'select2_multiple',
                    'wrapper' => ['class' => 'form-group col-md-6'],

                    // optional
                    'entity'    => 'media',// belongsToMany relation
                    'model'     => "App\Models\Media",
                    'attribute' => 'name',
                    'pivot'     => true,
               
                    // optional
                    'options'   => (function ($query) {
                        return $query->orderBy('name', 'ASC')->get();
                    }),
                ],
                [
                    'name'    => 'message',
                    'type'    => 'textarea',
                    'label'   => 'Message',
                ],
                [
                    'name'    => 'type',
                    'type'    => 'hidden',
                    'value'   => 'digital',
                ],
            ],
            // optional
            'new_item_label'  => 'Add', // customize the text of the button
            'init_rows' => 2, // number of empty rows to be initialized, by default 1
            'min_rows'  => 1, // minimum rows allowed, when reached the "delete" buttons will be hidden
            'max_rows'  => 10 // maximum rows allowed, when reached the "new item" button will be hidden
        ]);`

### What happened

CURD work fine but field with relations (media with belongsToMany && belongsToMany relation) dosn't any affect (use it or not use dosn't any effect :| ).

### What I've already tried to fix it

I customize Create.php in backpack/crud/src/app/Library/CrudPanel/Traits because the repetable field for hasMany && belongsTo dosnt work true with pivote => true.

                foreach ($values as $pivot_id => $pivot_value) {
                    $pivot_data = [];

                    /* 
                    if (isset($field['pivotFields'])) {
                        foreach ($field['pivotFields'] as $pivot_field_name) {
                            $pivot_data[$pivot_field_name] = $data[$pivot_field_name][$pivot_id];
                        }
                    }
                    */
                    $relation_data[$pivot_id] = $pivot_value;
                }

                //dd($relation_data);

                try{
                    $model->{$field['name']}()->sync($relation_data);
                }
                catch(\Exception $e){
                    $model->{$field['name']}()->delete();
                    foreach( $relation_data as $key => $value)
                        $model->{$field['name']}()->create($value);
                }

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
PHP 7.3.2 (cli) (built: Feb  5 2019 22:55:35) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.31@e0c389acce2617099a69d0b6076dfad24385295f

**Comment by tabacitu** [comment]
Hi @ElyasKhatinzadeh - sorry to be late to reply, seems your issue slipped through the cracks. 

I'm sure you've found a solution by now, but for others who might stumble upon this issue, I believe a good solution would be [our InlineCreate operation](https://backpackforlaravel.com/docs/4.1/crud-operation-inline-create). It adds a "+ Add New" button next to your relationship field, so that the user can add a new related item on the spot, and then select it.

On the subject of extracting a field out of the `repeatable` element, so that it doesn't get saved inside the JSON, but separately as a real relationship in the db (that's what you're trying to do from what I understand), I would do that inside a [Laravel mutator](https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator) on the model instead. That way, any time the db column that stores the JSON is edited, your relationship also gets updated. Creating a separate operation should work just as well, but it seems a bit messy to me. It's a matter of preference I guess.

Anyway, since it's been so long since you posted the issue, I'm going to assume you've found a solution. If not, maybe the above can help.

Cheers!
