### ISSUE TITLE
Consider using a 3rd-party package for forms?

### ISSUE THREAD

**Issue by axyr** [Laravel-Backpack/CRUD#35]
Right now the setup of form fields is array based.

I think this will be limiting, since it is hard to customize form fields or add app specific logic and layout to how form (fields) look and work.

I thinks this is a well maintained form package : 

https://github.com/adamwathan/form

For the rest of this BackPack idea: I think its great!

**Comment by tabacitu** [comment]
Yes, @cristiantone and some other people have pushed toward using [LaravelCollective's Form](https://laravelcollective.com/docs/5.0/html).

I'm open to the idea but... honestly, I see very little benefits except for the fact that it looks cleaner than pure HTML + PHP. The way I see it:
- using no form package is limitless, 
- using a package has limits and when you reach that limit, you fall back to HTML+PHP. 

So what's the point of using it in the package, then?

Also, choosing one form package will somehow force developers to use the same one - and maybe they prefer a different one... Your thoughts?

**Comment by tabacitu** [comment]
After careful consideration when running through all fields in the 2.1 update, I've concluded that using a Form helper would do more harm than good, at least in the field types. 

Backpack\CRUD 2.1 will still ship with [LaravelCollective's Form](https://laravelcollective.com/docs/5.0/html), which is used in a few places where there are forms, but not for the actual field types, since it's way easier to understand and modify them when NOT using forms, and for this package I believe that's more important than pretty code.
