### ISSUE TITLE
[Bug] address_algolia breaks when it is on the same page twice

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#3508]
# Bug report

### What I did

Have two ```address_algolia``` type fields on one page

### What I expected to happen

Both fields to be fillable and sent correctly to the server

### What happened

Only the last entry in the DOM is populated and sent

### What I've already tried to fix it

```console.log```ing the JS in ```address_algolia.blade.php``` confirms this.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
v8.26.1@275c78c97e007e4a9d771d4d1caa1c77ebfdcf94

### BACKPACK VERSION:
4.1.32@1a65e15562989c8fda3d2941da7110ca4008e21e

**Comment by tabacitu** [comment]
Thanks for reporting this @olipayne . It's probably because of the JS, I remember there are some constraints there that made it difficult to make it work multiple times per page AND inside our `repeatable` field... our maintenance team will take a look.

I just wanted to drop by to mention that [Algolia is killing Places](https://www.algolia.com/blog/product/sunseting-our-places-feature/), so starting with May 2022, the API won't be available any more. We should probably:
- [ ] add a notice to this field's docs;
- [ ] (maybe) remember to hide its docs in Backpack 4.2 so at least new people don't use it;
- [ ] tell people to use our [address_google](https://backpackforlaravel.com/docs/4.1/crud-fields#address_google) field if they can;

Which reminds me 😀 @olipayne - what do you think about using `address_google` instead of `address_algolia`? 😂 Any reason you'd prefer algolia considering the above?

Cheers!

**Comment by pxpm** [comment]
@tabacitu in that case, I am all-in for just writting the deprecation notice and don't  spend 1 second more here. 
Maybe add the constrains we know atm into the docs:

- This field can't be used multiple times in the same form.
- This field can't be used in repeatable
- This field is going to be deprecated starting 4.2

You know the drill with JS and stuff related. Trying to fix this now to deprecate in a few seems a waste of time.

Let me know what you think so I can move this to the right place (trash bin 🗡️ )

Best,
Pedro

**Comment by olipayne** [comment]
After spending some time trying to create a non-colliding version of the javascript variables I gave up and ended up using ```address_google```. Completely in favour of deprecating this field type. It would be great to investigate a non-Google alternative, if possible.

**Comment by pxpm** [comment]
It should be possible. Thanks for the suggestion. 

For reference Algolia suggests in their page:

- Mapbox
- Google Places
- Geocode Earth

Best,
Pedro

**Comment by olipayne** [comment]
Please consider my issue resolved. For those who visit later, the solution is to not use ```address_algolia``` since the service will be deprecated soon.

**Comment by tabacitu** [comment]
Added soft deprecation notice to the docs - https://github.com/Laravel-Backpack/docs/pull/236

> After spending some time trying to create a non-colliding version of the javascript variables I gave up and ended up using address_google.

@olipayne I feel your pain. Tried it too, it wasn't as easy as expected 😂
