### ISSUE TITLE
[Bug] CRUD orderByRaw using unsanitized input

### ISSUE THREAD

**Issue by alitak** [Laravel-Backpack/CRUD#3542]
# Bug report

### What I did

Created a crud for users. I set order by, then added sql command to the request:
column%5D=0&order%5B0%5D%5Bdir%5D=asc;UPDATE users SET name=(SELECT password FROM users WHERE id=1) WHERE id=1--&start=0

### What happened

https://prnt.sc/10104yg

### What I've already tried to fix it

app/Library/CrudPanel/Traits/Query.php:149  return $this->query->orderByRaw($this->model->getTableWithPrefix().'.'.$column_name.' '.$column_direction);
If I remove lines 148-150, the order functionality remains, but the injection will not run.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.3 (cli) (built: Feb 27 2020 12:36:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.28.1@73dd43d92fcde6c6abc00658ae33391397ca119d

### BACKPACK VERSION:
4.1.34@d9ec59ab1f9fe03c7106911b5667d912c1cfe1f7

**Comment by tabacitu** [comment]
😱 Thanks a lot for letting us know about this @alitak . 

I was unable to reproduce the issue with the information above. I think I did the same thing, but there were no changes in the DB. Could you please send a quick email to cristian.tabacitu@backpackforlaravel.com with the exact steps to reproduce this? That would help us A LOT.

In the meantime, we pinpointed the only place where this problem can come from, and Pedro came up with quite an elegant solution in  https://github.com/Laravel-Backpack/CRUD/pull/3550 . Could you please confirm that fixes the problem for you?

Cheers! And thanks again - super grateful 🙏

**Comment by alitak** [comment]
Hi @tabacitu ,

I made a little research. Mysql 5.5 and mysql 8.0 is not affected for the injection 
![image](https://user-images.githubusercontent.com/6049721/108808790-aef1c300-75a7-11eb-8ecf-27aa29cb81bd.png), but we  must use mssql, which allows this: 
![image](https://user-images.githubusercontent.com/6049721/108808939-13148700-75a8-11eb-915b-df1b0f4d9c01.png)

I just upgraded BPcrud to 4.1.36, but unfortunately the sql injection still works.

**Comment by tabacitu** [comment]
Hi @alitak  - thanks for the update, and for looking into this.

I see your tests are directly in your SQL Manager - where I do expect that to work, of course. Are you able to do the same thing using Backpack? By making a GET/POST request? That's the part I can't replicate. If you can, can you please send over screenshots/videos/steps/anything?

**Comment by alitak** [comment]
Hi @tabacitu ,
sry, I missed the steps for reproduction:
![image](https://user-images.githubusercontent.com/6049721/108809594-7fdc5100-75a9-11eb-8fd4-b9ed64453a77.png)
on the developer toolbar right click on search, copy -> as curl
I checked in Postman: Import -> Raw text -> insert, continue -> import
![image](https://user-images.githubusercontent.com/6049721/108809675-a601f100-75a9-11eb-9219-54ae17fceb89.png)
To the body part I added the sql after last order=asc characters:
![image](https://user-images.githubusercontent.com/6049721/108809759-d8abe980-75a9-11eb-806c-6bcfbe9661f8.png)
If I send the request, the inserted sql will run.

**Comment by pxpm** [comment]
Hello @alitak and @tabacitu 

After some more research I am pretty sure that by default mysql-php does not allow stacked queries like @alitak pointed out. 

But the fact that it does not affect mysql does not make it irrelevant. We went ahead and fixed it in https://github.com/Laravel-Backpack/CRUD/pull/3550

But you stated that is not working for you the fix ? I'v just tested and I cannot submit nothing more than `asc` or `desc` as `dir` parameter. 

Can you make sure that you have 
https://github.com/Laravel-Backpack/CRUD/blob/779364646e3b57258b981ff9f1bdcd9887143836/src/app/Http/Controllers/Operations/ListOperation.php#L100

in your project ?

Best,
Pedro

**Comment by alitak** [comment]
Hi @pxpm and @tabacitu ,

I just double checked crud version. I started the day with composer update, but the backpack crud version was fixed to version 4.1.34 by my colleagues and I did not notice it. Your fix indeed fixes this problem, thank you for your work!

Unfortunatelly version 4.1.36 broked our production system, investigation is still on.

**Comment by pxpm** [comment]
Thanks again @alitak for raising this issue. 

If you want to share the error maybe I can have some light of what might be. 

I will be closing this, if you find anything else we can help with open a new issue so we can properly investigate. 

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
Glad to hear that @alitak . Let us know if it's something we did that broke your system 🙄 I'm pretty sure we had no breaking changes between those versions though.

@pxpm can you also test if this affects postgres db users? I know you had it running so it should be easier for you. 

Next steps:
1. Figure out exactly what kind of projects are possibly affected. For now it looks like a very narrow niche, projects that:
 - use Backpack 4.1.17-4.1.34
 - use something else than MySQL (that means MSSQL / PosgreSQL / SQLite / MongoDB - should try all of them and eliminate the ones that are actually ok)
 - expose a ListOperation to non-admins (aka users, aka people who cannot be trusted)

2. With that list above in hand, I will go through the Backpack stats, make a list of all projects in production/staging that match and send a direct email to each one, asking to run a composer update.

3. (Maybe) Publish a post on our blog.

4. (Maybe) Email our 20k+ security newsletter subscribers. This is why we've gotten their email for, after all. But depending on how confident we are that we've reached out to everybody affected individually... it might be better to NOT email those who are unaffected. It wouldn't be useful info to them.

@pxpm / @promatik do you think I've missed something in the process outlined above? Can you help me narrow down the list of specs for affected projects?

Thanks!

**Comment by pxpm** [comment]
@tabacitu MongoDB and other non-sql db's are safe because we don't run `raw` sql on them. Also, for example for mongo, Jessengers implements the same fix as we do in the interface for mongo with eloquent.

https://github.com/jenssegers/laravel-mongodb/blob/09fcda8d21edfeb49416893bf916e13647d79f4b/src/Jenssegers/Mongodb/Query/Builder.php#L496

Postgres can only speak for the last version with default configurations:

![image](https://user-images.githubusercontent.com/7188159/108860706-5c83c700-75e6-11eb-9d03-2b191d3807f8.png)

But from my research I found out that PG support stacked queries, so this might be something configurable per instance, or was implemented only in later versions.

**Comment by tabacitu** [comment]
Heads-up @alitak , I just deleted your comment with the exact steps to reproduce the issue. I think it's best that we keep those between us for a while, until people get to update. Super-grateful for you help on this 🙏

**Comment by tabacitu** [comment]
Update: 

I just tested this with MySQL 5.5+, PosgreSQL 10+ and SQLite. 

In my tests, I was unable to do any damage:
- MySQL fails and throws access failure;
- PostgreSQL fails and throws "cannot insert multiple commands into prepared statement";
- SQLite does not fail, but seems to ignore the added payload;

So it looks like:
- the impact is limited to SQL Server and maybe other less-used database systems;
- once again the tools we trust (Laravel, PDO, MySQL, PostgreSQL) saved our asses;

**If anybody wants to test this themselves, please send an email to cristian.tabacitu@backpackforlaravel.com and I'll happily give you the steps to reproduce**. The more people try it the more we can narrow down the number of applications that _might_ be affected.

----

**If anybody can get different results in their tests, and discovers MySQL / PosgreSQL / SQLite are possibly affected, please let us know. We're wrong sometimes too.**

----

In light of the good news above (that MySQL / PostgreSQL / SQLite are NOT affected, which probably covers 99.9% of all Backpack installs), I'm going to change our response to this situation. Here are the steps we're going to take:

- [x] drill into our statistics and make a list of all live apps that use Backpack, where there's a chance they're affected (read: they use Backpack 4.1.17-4.1.34 and something else than MySQL, PostgreSQL or SQLite);
     - DONE! There are only 164 live apps in this situation; Only 2 use SQL Server for sure, 162 use unknown DBMSs;
- [ ] reach out individually to each one who has purchased a Backpack license, because we have their email;
- [ ] for full transparency, post an article on our Blog about it (a few days/weeks afterwards, so that everybody affected had enough time to update); 

Fortunately, thanks to the fact that MySQL, PostgreSQL and SQLite are unaffected, I no longer think it's worth sending an email to the 20.000+ people on our security newsletter. 99% of them won't be affected. And the ones who _maybe_ are affected will have already been contacted individually. So nobody in that list will care.

Ok great! We have a plan now. I'll get to it.
It's going to be a busy week...

**Comment by alitak** [comment]
Hi @tabacitu @pxpm 

thank you for your quick fix, I really appreciate it. However we can not update the crud, because new version breaks our systems with relations. Should I open a new ticket, or changed someting with text type columns on relations?

**Comment by tabacitu** [comment]
Yes - please open a new issue if the update from 4.1.34 to 4.1.36 broke your system, and give as much detail as possible about where the issue resides. We're curious to see what the problem is. There are not that many changes between the two versions - https://github.com/Laravel-Backpack/CRUD/compare/4.1.34...4.1.36
