### ISSUE TITLE
[Feature Request] Use orderByWithPrefix() only when there are JOINS in the query

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3555]
@pxpm please check out https://stackoverflow.com/questions/66330452/force-using-orderbywithprefix-in-a-query-list-with-join

I think that's quite an nifty solution, that would further limit the use of `orderByRaw()` which... can only be a good thing 😂

What do you think, should we do that in the Backpack core - only add the db prefixes if there are JOINS? That's the only situation when they're needed, after all, right?

Cheers!

**Comment by robdex** [comment]
@tabacitu thanks! I have also reported this request here: #3536.

**Comment by tabacitu** [comment]
Ah, it slipped by me 😀  Thanks @robdex 🙏

**Comment by pxpm** [comment]
I'v been testing this with multiple selects and stuff, and I think this might only be needed when using the joins. 

Atleast the only reason why we added it was because of the `joins`, so I assume it's safe to only run `orderByRaw` when there is joins ? 

The sql protection is because running `sql raw commands` in other db platforms would not work anyway and cause errors. 

I will give it a try in my mongodb setup and get back to you with my findings.

Best,
Pedro

**Comment by pxpm** [comment]
Hello guys!

I'v just sumited PR #3596 to address this issue. From my tests we should be fine just checking for joins, that was the only reason we need to add the table prefix in the query. 

I am going to close this, let's move any conversations over to the PR thread. 

Best,
Pedro
