### ISSUE TITLE
[Feature] Permissions

### ISSUE THREAD

**Issue by aaranmcguire** [Laravel-Backpack/CRUD#359]
It would be great to have the ability to set permissions for certain actions, e.g. Delete.

Paired with the Laravel-Backpack/PermissionManager repo it would be nice to restrict certain actions from groups/users. If the user does not have the permission I would expect the menu item to be hidden and the page removed from routes.

**Comment by yingdongzhang** [comment]
@aaranmcguire 

I did pretty much what @OwenMelbz  said and it works pretty well. I am using Backpack Permission Manager.

Just want to point out that if you want to get the current authenticated user, you need to create a `setup()` method in your crud controller, and put the logic `$user = Auth::user();` in there then do your permission check and setup. Refer to [this issue](https://github.com/Laravel-Backpack/CRUD/issues/95).

In my case I have about 6 crud controllers, and each requires the same setup. In order to avoid code repeating I ended up creating a Trait and put all my permission setup in a method in the Trait class, and just call it in all my crud controllers.

**Comment by aaranmcguire** [comment]
I'll give it a go and let you know how I get on.

**Comment by OwenMelbz** [comment]
@yingdongzhang Hey,

Just read your reply, however 1 thing to note is, that issue you linked to is an old version, (i've noa added a note to that post saying not to do that)

You should not be adding a new function called `setup` you should be renaming your `__construct` to be setup, and removing the old `parent::__construct();` call if it exists.

But yes creating a Trait, then calling the method within it at the top of your `setup` function would be a clean way to repeat that functionality on your controller if you don't fancy using class inheritance

**Comment by yingdongzhang** [comment]
@OwenMelbz   Thanks for letting me know, I'll check it out. Cheers.
