### ISSUE TITLE
[Bug] Request URL too long repeatable json data

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#3608]
# Bug report
When repeatable json data is too long, server response is ERR_CONNECTION_CLOSED
### What I did
I have a crud with repeatable field. On edit, the json repeatable data is a get variable and if its too long the server maybe throws ERR_CONNECTION_CLOSED.
![image](https://user-images.githubusercontent.com/8792209/110972294-9967f180-833a-11eb-82d9-f8c74e10ca33.png)

### What I expected to happen
Prevent sending repatable data in url?

### What happened

When repeatable json data is too long, server response is ERR_CONNECTION_CLOSED

### What I've already tried to fix it

Making server configurations.

### Backpack, Laravel, PHP, DB version

4.1.33@a8c27854f2d7fb326deef48e4cae112bfcd506ae

**Comment by pxpm** [comment]
Hello @aberaldo 

I see you tried to fix it by making server configurations, does that configurations included `max_input_vars` and `post_max_size` ?

Let me know,
Pedro

**Comment by pxpm** [comment]
@aberaldo are you using: https://github.com/Laravel-Backpack/CRUD/pull/3439 ?

**Comment by pxpm** [comment]
Hello @aberaldo 

So I think we got to the bottom here. 

So here are my assumptions: 

You are using #3439 and have a `select2_from_ajax` field with your custom API endpoint. 

Please change `method => 'POST'` in your `select2_from_ajax` field, and also change your API endpoint to **POST** instead of **GET**.

You can also use FetchOperation https://backpackforlaravel.com/docs/4.1/crud-operation-fetch#documentation-box to setup your api endpoint, it already uses `POST`. 

NOTE: you still need to change the method to post in the field, because by default select2_from_ajax uses get!

I am going to close this issue, I think there is not much more that we can do than changing select2_from_ajax method to post by default in the next version.

Thanks for the report and have a nice day 👍 

Pedro
