### ISSUE TITLE
[Bug] column defination of user_id returns the name value instead of user_id value

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#3636]
# Bug report

For a long time, I have a column definition like this:

```php
[
    'name' => 'user_id',
    'label' => 'uID',
],
```

It always display the value of the user_id column on the table. However since a certain minor version (Can't recall exactly which), it now display the name value of that user_id. So I end up getting like "John Doe" instead of 8 (the user_id)

This does not happen with other foreign keys. Like staff_id for example

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 7.4.15 (cli) (built: Feb  4 2021 17:22:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.34.0@81892ca110795a9c46c7e198cba7763bfd2af0bf

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472

**Comment by pxpm** [comment]
@ziming if `type` is not specified, backpack will infer the type because `user_id` is seemingly a relation key and you have a relationship `user()` in your model, so for a column with `user_id` it will infer the relationship and the attribute to show.

There was a bug that was preventing this from working correctly, guess it was fixed. 

It's the same behaviour as fields, so you can setup `entity => false` to disable backpack behaviour, or specify the field type `type => 'text'` or specify the attribute you want to get from relation with `attribute => id`.

So all this will work:

```php
[
    'name' => 'user_id',
    'label' => 'uID',
    'entity' => false
],

[
    'name' => 'user_id',
    'label' => 'uID',
    'attribute' => id
],
[
    'name' => 'user_id',
    'label' => 'uID',
    'type' => 'text'
],
```

Let me know,
Pedro

**Comment by pxpm** [comment]
I think this is done by now. I will be closing this.

Please re-open if needed @ziming 

Best,
Pedro
