### ISSUE TITLE
[Feature Request] Disable submit button if any ajax request still pending

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#3688]
With cruds that have a lot of ajax request (dependant fields and stuff) if some requests take a little longer and user clicks on the submit button, the sent information might be missing the bits that were not received by that time by the ajax request. 

The solution would be to disable the `submit` button while there are any requests still going. 

As referenced by @o15a3d4l11s2 in Gitter, one solution would be to use the `pace-js` library to check this:  https://www.npmjs.com/package/pace-js 

But it might bring more weight to the table than we actually need, so the solution they use in pace goes along the lines described here: https://stackoverflow.com/questions/10783463/javascript-detect-ajax-requests

Intercept all `send` ajax requests and deal with their state.

**Comment by tabacitu** [comment]
I was for this, but now I'm against it 😅 I've realized Livewire will do AJAX requests all the time, so if you have a Livewire component onpage (eg: an omnisearch in the header) it's entirely possible for Livewire to block the submit button, which is a big no-no. I've seen others use Livewire for the notification bubble too (poll every x seconds) so if that happens, then the Submit button would disable for a second, every few seconds - that would amount to a terrible UX. I think it's better to do nothing, rather than risk that bad UX. So I'm going to close this.

**Comment by pxpm** [comment]
Nice catch with other ajax methods. But...
We can have a header in our ajax requests that we want for sure wait for execution and check for header presence in the request? Like inline create ajax and so on?

**Comment by tabacitu** [comment]
We could... but I still don't think this is worth doing, to be honest. Personally I've never run into this, and I think it's unlikely a lot of people would.

**Comment by pxpm** [comment]
Thanks for your comment @tabacitu 
I will be closing then, I still think that we should address this, but I agree we have more important stuff to fix/create and this probably would be auto-fixed when we switch to components. 

Cheers
