### ISSUE TITLE
ClearBtn on date_picker field

### ISSUE THREAD

**Issue by eaziweb95** [Laravel-Backpack/CRUD#3690]
The Clear button doesn't appear when I add the option clearBtn in the date picker field
```php
'date_picker_options' => [
    'language' => 'fr',
    'clearBtn' => 'true',
]
```
How can we reset the date ?

**Comment by promatik** [comment]
Hi @eaziweb95!
I believe your problem is related with the boolean `true`, instead of string.
You should use `'clearBtn' => true` instead of `'clearBtn' => 'true'`, note the apostrophe (`'`).

I just tested it:
![image](https://user-images.githubusercontent.com/1838187/116822770-ab1a8800-ab78-11eb-8240-d4d1fc5e1584.png)

I'll close this for now, if you still have the any issue please let me know ✌

**Comment by eaziweb95** [comment]
Thanks for your answer, it works now !
