### ISSUE TITLE
[Bug] Unable to add ShowOperation to UserCrudController

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#3707]
# Bug report

### What I did

In attempt to make the User entries viewable, not just editable, I added ```ShowOperation``` to ```UserCrudController```

### What I expected to happen

The Preview button to display and work

### What happened

Preview button works, upon clicking returns ```Call to undefined method Illuminate\Notifications\DatabaseNotification::identifiableAttribute()```

### What I've already tried to fix it

Removing the ```Notifiable``` trait from ```User``` fixes it, however then my User is not notifiable

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.5 (cli) (built: Apr 29 2021 16:01:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.40.0@a654897ad7f97aea9d7ef292803939798c4a02a4

### BACKPACK VERSION:
4.1.43@973e8ab33d42f02272f65e9688ea250fc9502d3d
```

**Comment by olipayne** [comment]
After digging in more, it looks like this is caused by ```CRUD::set('show.setFromDb', false);```. As it's trying to guess the column attribute to display, which this trait adds but doesn't have (?), it trips up here - https://flareapp.io/share/95JzxVM5#F64

After defining  ```setupShowOperation()``` on ```UserCrudController``` with only the fields I want, it works just fine.

**Comment by promatik** [comment]
Hi @olipayne!

This is probably already fixed with https://github.com/Laravel-Backpack/CRUD/pull/3643 PR.
It was merged but **not yet tagged**, it will be soon.

In the meanwhile, you can copy the fix to your source code, it will temporarily solve it until the next update.
Let us know if it does the job 🙌

I'll close this issue for now, if it doesn't fix your issue, please let me know ✌
Sorry for the trouble.
