### ISSUE TITLE
[Feature Request] deferLoading on DataTables

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3712]
It's been reported [here](https://stackoverflow.com/questions/67520500/can-we-avoid-the-initial-ajax-flash-with-datatables-deferloading) that on the ListOperation we now have an initial flash of unloaded content, then the loading spinner, then the content loads, which could be improved just by adding `deferLoading => false` to the DataTables configuration.  

It sounds like a good idea if it's that easy to do. The problem is - I don't see an initial flash. Do you guys?

**Comment by ericjanofski** [comment]
https://user-images.githubusercontent.com/24723635/118492458-a4961f80-b6e5-11eb-8390-19a562cd66c3.mov

Here's a video displaying what I'm experiencing. The page loads and the dataTables have black text, then it appears that the page loads a second time, (at least, the inspector html does a full rewrite of the dom), then the table turns white, the loader appears briefly, then the content pops in. 

It would be great if there was a way to configure an initial batch of content that php could load serverside, then use deferLoading to avoid the ajax takeover.

My concern is the client noticing the initial changes to the page and thinking it looks "buggy".

**Comment by pxpm** [comment]
Hello @ericjanofski 

I can see the "flick" you talk about, we draw the table headers, and then the table enters in a "loading state", making the content "white" while loading. 

To use the deferLoading we need to have some data in the initial request to populate the table, that's not how Backpack have it implemented. All the table data is get from the `ajax request`, so what you see in page first is just an "html" table (headers and stuff), and then datatable initialization script is run. At the time the first paint is made we have no info on what data will be displayed in the table. 

One workaround is making the table "appear" the same as it will be when loading starts (whiter) by styling the headers and the text to match the loading state, and when it finish loading remove the "whiter" classes to show the black bold ones!

That way the flick would not be noticeable because they look the same. 

@tabacitu you can make Chrome Devtools throttle your connection to be a 3G one and you will see the flick. In high connections the flick is unoticeable.

![image](https://user-images.githubusercontent.com/7188159/118675379-781bf980-b7f2-11eb-807d-6b79f6b1ecef.png)

Best,
Pedro

**Comment by ericjanofski** [comment]
Thanks Pedro, your response is much appreciated. I believe your proposed solution would be a step in the right direction. In order to attach classes or use a javascript callback would I be using the dataTables config file overwritten here:

/resources/views/render/backpack/crud/inc/datatables_logic.blade.php

or is there another way Backpack hooks into that?

Thank you for your time.

**Comment by pxpm** [comment]
@ericjanofski you can publish the view with: `php artisan backpack:publish inc/datatables_logic` it will be in your `resources/views` with vendor path.

If you found a solution that you are happy with and would like to contribute let us know, maybe it's a solution for backpack core, or could help other people that are annoyed by this "flick". 

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
Closing as non-priority. Happy to discuss if we have a PR.
