### ISSUE TITLE
[Bug]  Custom search logic for computational column 

### ISSUE THREAD

**Issue by LavinaHs** [Laravel-Backpack/CRUD#3718]
What I did
I am attempting to create custom sorting and search logic for a column that is calculated on select

In the public function i add an operation:

$this->crud->operation('list', function () {
$this->crud->groupBy('email')
->select('', DB::raw('count() as lastLoginAttempt'));
});

And then attempt to create a column:

    $this->crud->addColumn(['name' => 'lastLoginAttempt', 'type' => 'text', 'label' => 'Login count',
        'orderable' => true,
        'orderLogic' => function ($query, $column, $columnDirection) {
            return $query->orderBy('lastLoginAttempt', $columnDirection);
        },
        'searchLogic' => function ($query, $column, $searchTerm) {
            $query->orWhere('lastLoginAttempt', 'like', '%'.$searchTerm.'%');
        },
    ]);
What I expected to happen
I expect the column to now be sortable and searchable

What happened
The column is sortable and the orderLogic was able to recognize column 'lastLoginAttempt', but when adding the search logic it returns the error: "Column not found: 1054 Unknown column 'lastLoginAttempt' in 'where clause' at"

What I've already tried to fix it
Already posted ticket: [Bug] Custom search logic for computational column #3701, it was confirmed as fixed but after updating i still get the same error: "Column not found: 1054 Unknown column 'lastLoginAttempt' in 'where clause' at"

Backpack, Laravel, PHP, DB version
When I run php artisan backpack:version the output is:
### PHP VERSION:
PHP 7.3.28 (cli) (built: Apr 27 2021 17:19:33) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.45@c9918581306bc4a8d605b87b4757893baa03fcc1

**Comment by pxpm** [comment]
Hello @LavinaHs 

As far as I found in my research, SQL only allows the computed columns in `orderBy` clauses for the same condition, because of the order of evaluation. You need to make nested FROM table to make it work that way and that's not how Backpack applies the constrains in the query. 

You can read more about it here: https://stackoverflow.com/questions/41693097/reuse-calculated-column-in-where-clause and https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#Anchor_2

I think you can make it work using laravel modifiers `virtualAs` or `storedAs` depending on your needs. https://laravel.com/docs/8.x/migrations#column-modifiers

Laravel also has a `having` method for similar situations. https://laravel.com/docs/8.x/queries#havingraw-orhavingraw

Let me know,
Pedro

**Comment by pxpm** [comment]
Hello @LavinaHs sorry for such a late reply.

I hope by today you already found your answer or found another way of doing what you want.

I suggest you make your query work in SQL first and then migrate it into Laravel eloquent if possible, otherwise use raw sql. 

Backpack has nothing to do with "nesting the select", that's an SQL thing, Backpack just gets the query you provide and execute it, so if you are running intro trouble I suggest you first make it work in raw SQL and just then port it to Laravel application.

I am going to close this for now, but please if you still having trouble let me know in the comments or re-open if needed! I will try to help you the best I can. Start by dumping the `$query` with: `dd($query->toSql())` to get the query that backpack is about to execute. 

Wish you the best,
Pedro
