### ISSUE TITLE
[Question] Conditional Fields

### ISSUE THREAD

**Issue by noxify** [Laravel-Backpack/CRUD#372]
Hi,

currently i have two fields, `type` and `parent`, the `parent` field is only required even when the `type` has the value X. If the value is Y or Z, then the field is not required.

I know, i can add a condition in the `setup`method. But then I have to save the record.

Has someone an idea how to solve this?

Thanks!

**Comment by OwenMelbz** [comment]
When you create your crud controller, it will generate a Request along with it.

That stores your validation - this is just a normal laravel feature which you can read about https://laravel.com/docs/5.3/validation#creating-form-requests

So just add your custom validation in there.

I'm just gonna close this issue now as it's a support request rather than a package issue. Feel free to continue using it though

**Comment by noxify** [comment]
I think we have a misunderstanding here:

The question was: Is it possible with CRUD to show a field only when a another field has a specific value :)

**Comment by OwenMelbz** [comment]
Oh right, yeah you can do it using javascript and your own custom field.

Theres a PR for something which may be similar https://github.com/Laravel-Backpack/CRUD/pull/165

**Comment by noxify** [comment]
Awesome thanks :)
