### ISSUE TITLE
[Bug] Incompatible SluggableObserver

### ISSUE THREAD

**Issue by serdud** [Laravel-Backpack/CRUD#3723]
# Bug report

### What I did

Upgrade cviebrock/eloquent-sluggable to 8.0.7

### What I expected to happen

??

### What happened

`Declaration of Backpack\CRUD\app\Models\Traits\SpatieTranslatable\SluggableObserver::generateSlug(Illuminate\Database\Eloquent\Model $model, string $event): void must be compatible with Cviebrock\EloquentSluggable\SluggableObserver::generateSlug(Illuminate\Database\Eloquent\Model $model, string $event): bool`

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.0.1 (cli) (built: Jan  5 2021 23:43:39) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.42.1@41ec4897a70eb8729cf0ff34a8354413c54e42a6

### BACKPACK VERSION:
4.1.45@c9918581306bc4a8d605b87b4757893baa03fcc1

**Comment by bedoz** [comment]
Same here, the solution should be to remove generateSlug from Trait.
Function are identical.

**Comment by bedoz** [comment]
to be more specific, by checking the whole class, I would not be wrong, but you can remove the class entirely and recall the main one. it is extended but overwritten with identical functions. Did I say bullshit?

Thank you
Alex

**Comment by pxpm** [comment]
Hey @serdud and @bedoz 

There is already https://github.com/Laravel-Backpack/CRUD/pull/3625 that will do exactly that, remove the function. 

I am sure that when it was overriden it was to fix some bug/incompatibility with the underlaying package. But it was long long time ago. As @bedoz pointed out, they are very identical, but not the same. 

It's already in ready to merge, so probably on-hold because something triggered the @tabacitu spidey sense 😄 It should be merged soon. 

I will be closing this as it is already beeing addressed. 

Thanks,
Pedro

**Comment by tabacitu** [comment]
Update: just merged #3625 , will be tagged later today. @bedoz & @serdud  you'll be able to get it using a `composer update` starting tomorrow. Please let us know if it fixes it for you, or if it breaks anything else. It's a tricky one because we can't remember why that code was there in the first place, doesn't make a lot of sense 😅

Cheers!

**Comment by serdud** [comment]
@tabacitu @pxpm 
Hi. This issue related to another class. #3625 isn't fix it.

**Comment by pxpm** [comment]
Totally @serdud 

I am sorry I confused the names of functions.

I've submitted #3746 to remove this overrides from our package. 

I will be closing this now, I think this time for good :)

Thanks @bedoz for pitching in too, I guess you are totally right and we can remove the overrides. 

If you need to address something more in this regard, please do it in #3746 PR.

Thanks again,
Pedro
