### ISSUE TITLE
[Feature Request] Idea to improve reorder

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#3727]
Hi guys! How are you all? I'm here now to explain ad idea to improve reorder view, and i hope that this issue can be used as a idea repository for this page.

# Feature Request

### What's the feature you think Backpack should have?

I use a lot reorder page, also with level... but when we use this page for products or similar it can contain hunderds or rows, and it can be very difficult to find and reorder elements.
The first idea that jumps into my head is, what about using filters that can be created on list view also for reorder view?

I know that filters reduce the number of elements on the page and that it can create the problem of having multiple elements with the same positions on the lft and rgt fields for example, but using filters could mean that I have a list with elements that they are sorted separately and that having equal values between them is not necessarily a problem, as they would never be displayed together. I undestand the problem that could arise, but if you were aware of the problems that could arise and if used wisely and sparingly it could be very useful in my opinion.

what do you think, men? this is an idea that came to me, and others could come, I hope the community responds to this issue with other great ideas so we can talk about it and discuss it and make this amazing tool grow even more.

Take Care guys,
Alex

**Comment by pxpm** [comment]
I like the idea of "displaying few items", but I totally dislike the idea of having a broken/inconsistent tree.

One way I see this could be done, is instead of showing ALL products, we show a list of "product categories" (or any other thing you use to "filter" the products) as dropdown elements, so you can open 1 at a time and see the products inside that category to re-order.

But in this scenario ALL the products are shown in view, they are just hidden in category tabs, so while you see only "some products", you are still re-ordering the whole product tree so making it always consistent!

Something like this:
![image](https://user-images.githubusercontent.com/7188159/119640322-677e0b80-be10-11eb-9312-fa089e1a3337.png)

Let me know,
Pedro

**Comment by DanielKimmich** [comment]
What occurs to me to sort by filters or partial is that the numbering is not continuous. Define a numbering range by levels, for example level 1 the order is by thousands, for example 10,000, 20,000, etc. the second level for example 10.001 to 19.999, 20.001 to 29.9999.

That is, the values of ltf and rgt:
depth = 1 with 5 digits: 10,000, 20,000, 30,000
depth = 2 with 4 digits: 1.001, 1.002 to 9999 + level 1
depth = 3 with 3 digits: 101, 102 to 999 + level 2
depth = 2 with 2 digits: 11, 12 to 99 + level 1 + level 2
This of the number of digits or zeros could be defined by the variable "max_level".

Greetings,

**Comment by bedoz** [comment]
> I like the idea of "displaying few items", but I totally dislike the idea of having a broken/inconsistent tree.
> 
> One way I see this could be done, is instead of showing ALL products, we show a list of "product categories" (or any other thing you use to "filter" the products) as dropdown elements, so you can open 1 at a time and see the products inside that category to re-order.
> 
> But in this scenario ALL the products are shown in view, they are just hidden in category tabs, so while you see only "some products", you are still re-ordering the whole product tree so making it always consistent!
> 
> Something like this:
> ![image](https://user-images.githubusercontent.com/7188159/119640322-677e0b80-be10-11eb-9312-fa089e1a3337.png)
> 
> Let me know,
> Pedro

I like it very much, man. It should be easier to manage with large amount of data.

**Comment by bedoz** [comment]
> What occurs to me to sort by filters or partial is that the numbering is not continuous. Define a numbering range by levels, for example level 1 the order is by thousands, for example 10,000, 20,000, etc. the second level for example 10.001 to 19.999, 20.001 to 29.9999.
> 
> That is, the values of ltf and rgt:
> depth = 1 with 5 digits: 10,000, 20,000, 30,000
> depth = 2 with 4 digits: 1.001, 1.002 to 9999 + level 1
> depth = 3 with 3 digits: 101, 102 to 999 + level 2
> depth = 2 with 2 digits: 11, 12 to 99 + level 1 + level 2
> This of the number of digits or zeros could be defined by the variable "max_level".
> 
> Greetings,

It could be another good idea, sure, to avoid inconsistency orders.

**Comment by tabacitu** [comment]
Hey @bedoz ,

Been a while since you opened this issue 😅 Sorry for not replying earlier, I thought "_hmm... I don't know... let me sleep on it_" and apparently I slept on it for >1 year 😅

I agree with my previous self - I'm skeptical in introducing something filters to the `reorder` operation. I think that would:
- make the numbers non-consecutive
- introduce high complexity, for both users and maintainers

Granted, I don't have a better solution for you, for ordering large numbers of items. I really don't. But I also think there's no easy solution for this (as an interface). It really depends from project to project. If you get to _need_ to reorder hundreds of items with drag&drop... you're doing something wrong, I think.

So I'm going to close the issue - we do not plan on introducing something like this any time soon. Of course, I might be wrong - I often am. If you guys think I'm wrong on this (or anybody else stumbling into this issue), please let me know you arguments - we can talk about it and re-open.

Sorry for letting this sit for so long. And for the negative response.
Cheers!
