### ISSUE TITLE
[Bug] Repeatable field set 'showAsterisk' attribute as false

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#3765]
# Bug report
In blade of the repeatable field there is a line that sets 'showAsterisk' as false in . This prevent the user cant show an asterisk in the repeatable field 

https://github.com/Laravel-Backpack/CRUD/blob/53bc6028f445f9b2ecfb8893283f6b6087539353/src/resources/views/crud/fields/repeatable.blade.php#L48

So then in a repeatable field i want to do:

```php

[
'label'     => FeeLine,
'type'      => 'select2_from_ajax',
'name'      => 'fee_line_id', 
'attribute' => 'name',
'showAsterisk' => true,
],
```
The asterisk is not shown.

I dont know why is taht line but if its removed, the asterisk is shown

**Comment by pxpm** [comment]
Hello @aberaldo thanks for the report.

I was trying to figure out why would we specifically setup the `showAsterisk` as false in repeatable and find out that it might be to solve an issue when the `parent` (the repeatable field itself) is required. 

From my tests I find out that it does not solve the issue and the issue still persists, so if the parent repeatable is required, all the fields inside the repeatable field show the red asterisk.

![image](https://user-images.githubusercontent.com/7188159/124350137-cb071000-dbea-11eb-8acf-d482f887bb2b.png)

Even setting up `showAsterisk => false` would not make the asterisks go away from the repeatable fields. 

I found out that is due to a CSS rule not beeing correctly applied. 

I've submitted #3779 to address this issue. 

If you have time to give it a try, let us know in the comments of the PR if it fixed your problem :)

Thanks again,
Pedro
