### ISSUE TITLE
reorder actions column

### ISSUE THREAD

**Issue by masssoud** [Laravel-Backpack/CRUD#3817]
Hello everyone,

I have changed theme direction to RTL, and now actions column is last column at the left.
i want to reorder and put actions column at the beginning.how can i do it?

**Comment by tabacitu** [comment]
@masssoud  it shouldn't be terribly difficult to do as a customization - you can overwrite the `search()` method in your CrudController, which returns the columns... and just switch the order there. So something like this:

```php

    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation { search as originalSearch };

    public function search() 
    {
         $columns = $this->originalSearch();

         // TODO: do what you want with the columns

         return $columns;
     }
```

If you need this in multiple CRUDs, you can create a Trait out of it, and use your CustomListOperation instead of the stock one...

Hope it helps!

PS. How was it to turn Backpack's interface into RTL? I don't remember hearing about this need in a few years, and I haven't tried it myself so... I'm kind of our of the loop. Was it terribly difficult to do? What other problems did you face?
