### ISSUE TITLE
[Bug] New install command should not wait ad infinitum for user input

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3841]
# Bug report

### What I did

Someone reported that they were using `php artisan backpack:install` in their CI/CD pipeline, and now it's broken, because it hangs on the "_Would you like to install Backpack/DevTools?_" questions.

Let's:
- [ ] Wait 30 seconds, then default to `no`; [COULD DO]
- [ ] We have a flag so that that question is no longer asked; I propose `--no-devtools` [MUST DO]

I had no idea people are using `backpack:install` in their CI/CD pipeline. The probably shouldn't... but for those that do, we should have this covered.

**Comment by promatik** [comment]
On it ✌

**Comment by promatik** [comment]
@tabacitu it seems like there's no timeout for `ask()`.

---

There is a `--no-interaction` arg for artisan, that will skip the `ask()`.

`php artisan backpack:install --no-interaction` will auto answer no to DevTools install;

![image](https://user-images.githubusercontent.com/1838187/134900028-ce022d63-ba8e-4b1b-baa3-285de75d1adf.png)

@tabacitu `--no-interaction` solves the problem, should we implement a `--no-devtools`?
I'm against it, I think we should stick to the standards.

@pxpm please let us know what you think too ✌

**Comment by pxpm** [comment]
@promatik I would go with the `--no-devtools` since that specifically will answer `NO` to the install devtools question, but if in the future we add other options we can still answer `YES` to other questions while answering `no-devtools`. 

Let me know what you think!

Best,
Pedro

**Comment by promatik** [comment]
@pxpm in this case, this user wanted no interaction at all, because he is running `php artisan install` on CI/CD pipeline, so even if in the future we add more questions, for this user `--no-interaction` will be always required ...

**Comment by pxpm** [comment]
@promatik I think you got a point there. So I rephrase my thinking:

> we should add --no-devtools and --with-devtools options. That way people running install in CI could enable/disable it without answering the question. 

Let me know,
Pedro

**Comment by promatik** [comment]
@pxpm sorry for insisting 😅 but I don't see a use case of `--no-devtools` or `--with-devtools`.

Ok, here is my point of view;

- `--with-devtools` should not exist because it should always be "with devtools", we want people to see the ad ...
unless, they want no questions at all, because they are running on CI/CD pipelines, and in that case they have `--no-interaction`.

- And I think we should not adopt `--no-devtools` because now it would have exactly the same behavior as `--no-interaction`, but one day if we add another question "Install ProdTools?" people running pipelines would encounter the same issue because now they need update their scripts and add another arg `php artisan backpack:install --no-devtools --no-prodtools`. If we encourage them to use `--no-interaction` this will never be a problem.

Let me know if I'm missing anything here ✌

**Comment by tabacitu** [comment]
Totally agree with both of you: with @promatik that `--no-devtools` doesn't make sense NOW, because it'd to the exact same thing as `--no-interaction`. With @pxpm that if/when we'll have multiple questions, it'll make sense to add `--no-devtools` too.

Until then, `--no-interaction` should work great for this use case. Closing, thanks guys!
