### ISSUE TITLE
reorder items inside the repeatable field.

### ISSUE THREAD

**Issue by suro11777** [Laravel-Backpack/CRUD#3872]
reorder items inside the repeatable field.

What I did:
I read that this functionality was supposed to appear in version 4.1,
Laravel-Backpack/CRUD#2711

What I expected to happen:
but it is not. he's only in 4.2

What happened:
What I've already tried to fix it:
I copy the file from 4.2, a button appears in the left corner to move, but after saving everything is reset.
What else needs to be done to use this functionality

Backpack, Laravel, PHP, DB version:
PHP VERSION:
PHP 8.0.3 (cli) (built: Mar 25 2021 23:04:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

LARAVEL VERSION:
v8.63.0@8f3d280f36a427730c8c8fa34316c79eed38781e

BACKPACK VERSION:
4.1.54@6f0ddffbe2017ef0e0d9becf5e9f422a81d94c45

**Comment by tabacitu** [comment]
@suro11777 , indeed, we've decided to merge THAT repeatable sorting functionality into 4.2, not 4.1. So that feature isn't launched yet - we can offer no guarantees that it works yet, sorry. If it didn't work for you, it might be a bug in PR https://github.com/Laravel-Backpack/CRUD/pull/2711 and I see you've already posted there too, so I'm going to close this issue. The author of the PR or someone else involved will probably take a look at it soon.

But. Please note that PR just includes a DIFFERENT implementation of reordering (drag & drop). In the latest Backpack, there's a already sorting mechanism that is guaranteed to work (click-click). It's been merged 23 days ago in PR https://github.com/Laravel-Backpack/CRUD/pull/3685 and it works like this:

![2021-10-13 09 41 00](https://user-images.githubusercontent.com/1032474/137080857-73b17278-5077-4647-be1d-b0eef4e95690.gif)

So if you need reordering inside `repeatable` right now, what I recommend you do is use the one that's already built-in. If you don't have it yet, a `composer update` should bring it to you - make sure you're running v4.1.51+. Of course, you'd need to also delete the custom `repeatable` you added to your project. Note that the arrows don't show up if you only have one item inside the `repeatable`. They only show when it makes sense (there is something to be reordered).

Hope it helps.
Cheers!

**Comment by ramonluteijn** [comment]
have you found the problem?
i am having the same problem where the arraows are shown but on updating the order will reset.
