### ISSUE TITLE
[Bug] doctrine/dbal version conflict between Laravel v6 and Backpack 4.1

### ISSUE THREAD

**Issue by Ninja260** [Laravel-Backpack/CRUD#3910]
I installed backpack on my sample laravel project and It happens

- laravel version 6.20.26
- backpack version 4.1.*

bug screen shoot https://www.dropbox.com/s/008zs3pthvbf7y6/bug%20report.html?dl=0

**Comment by promatik** [comment]
Hi @Ninja260!

Backpack is compatible with both `"doctrine/dbal": "^2.5|^3.0"`.
https://github.com/Laravel-Backpack/CRUD/blob/master/composer.json#L39

Since you are using Laravel 6 you must install `doctrine/dbal` v2.5+.

```bash
composer require doctrine/dbal:^2.6
```

Please let me know if this solves your issue.
I'll close this issue for now, but feel free to reply if you still have any problems ✌

**Comment by Ninja260** [comment]
I already run
`composer require doctrine/dbal`

I find out that It added dbal version ^3.1 in composer.json file.
though the error do not change. 

in composer.lock file it only change the content-hash property of the json. Not else change was found after the command. 
I will carry out some tries and will report you back. Thanks for your fast reply, @promatik bro.

**Comment by Ninja260** [comment]
@promatik 
`composer require doctrine/dbal:^2.6`

this command really solve my problem.
