### ISSUE TITLE
[Bug] Toggle field doesn't work inside repeatable

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3924]
Reported here https://github.com/DigitallyHappy/toggle-field-for-backpack/issues/7 but can't move it to this organisation.

It really _should_ be working inside repeatable. Maybe we even move it to Backpack Core in 4.2... it's a pretty useful one.

**Comment by pxpm** [comment]
Hey guys!

Thanks for raising the issue @gcasaroseisnet !

Unfortunatelly there is not much we can do to make the field work inside repeatable in version 4.1. But I have good news, 4.2 is really close to be lunched and this is fixed by: https://github.com/Laravel-Backpack/CRUD/pull/3905

I've just tested and everything works as expected using that branch.

I am going to close this since we already have the fix for it!

Thanks again,
Pedro
