### ISSUE TITLE
[Bug] Error using a accessor as "attribute" on "relationship" field type with the "inline create" functionality

### ISSUE THREAD

**Issue by pabloblazquez** [Laravel-Backpack/CRUD#3945]
# Bug report

### What I did

I have a "relationship" field type, with the "create inline" functionality enabled. The target entity has two fields: "firstname" and "lastname". I also have generated an accessor called "fullname" which is the combination of them. This accessor is used in listings, selectors etc. And it is used as "attribute" definition in the relationship field.
```
CRUD::field('lawyers')
    ->label('Lawyers')
    ->type('relationship')
    ->attribute('fullname')
    ->ajax(false)
    ->inline_create([
        'entity' => 'lawyer',
        'force_select' => true
    ]);
```

### What I expected to happen

After creating the record with the "create inline" functionality, I expect that the created record is correctly displayed as a selected item in the "relationship" field. It should appear in the list of selected records, with the field "fullname" defined as an attribute.

### What happened

After creating the record, a selected item appears, but without text (only the box with the "x" to remove the association is visible).
![image](https://user-images.githubusercontent.com/5339542/142723559-e48dde14-6a0c-4e7c-ac6d-e9d77cea8640.png)

### What I've already tried to fix it

I think the problem comes from the fact that the field I am using is an accessor, and it is not a real field in the database. I think the programming that controls this does not take into account that the field defined as "attribute" can be a accessor.

### Is it a bug in the latest version of Backpack?

I am using the 4.1 backpack

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.0.6 (cli) (built: May  4 2021 23:31:41) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.6, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.58.0@1b819bf99d87bd543a4d4895e5b3350f61ea7a23

### BACKPACK VERSION:
4.1.51@756173cf6593c3d530fca0e54831763c796e24d8

**Comment by tabacitu** [comment]
Hi @pabloblazquez ,

Thanks for reaching out. I assume you already have an accessor (`getFullnameAttribute()`), not just a mutator (`setFullnameAttribute()`). 

I've never tried that myself (use an accessor as an attribute for a relationship field), but I guess it's a reasonable thing to assume would work. If it doesn't already, we'll try to make it work (if it's technically possible and reasonable).

Have you tried adding `fullname` to your `$appends` array on the Model?

```php
    protected $appends = ['fullname'];
```

I'll let Pedro take over for details - he knows more about this part than I do. 
Just wanted to give my quick idea above.

Cheers!

PS. If it turns out we cannot make it work (due to processing order - accessors are only applied after the DB query is returned), computed DB columns will definitely make it work for you, and improve performance (eg. a migration that adds `    fullname varchar(101) as (concat(first_name, ' ', last_name)) ` to that table). That's will offload the processing from PHP to the DB, which is much better at that. But yeah it's a data structure change and I know it's probably not what you're looking for.

**Comment by pabloblazquez** [comment]
Sorry, you're right, I always meant an "accessor", not a mutator. I've edited my original post to avoid doubts.

And thanks for the quick solutions, I'll try them.

**Comment by pabloblazquez** [comment]
Adding "fullname" to my $appends array on the Model works!.

```
protected $appends = ['fullname'];

public function getFullnameAttribute(): string
{
    return collect(['['.$this->code.']', $this->firstname, $this->lastname])->join(' ');
}
```

Thanks a lot!

**Comment by tabacitu** [comment]
Awesome. Happy to help.
