### ISSUE TITLE
[Bug] Save and back with translations

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/CRUD#3947]
# Bug report

Using https://backpackforlaravel.com/docs/4.1/crud-operation-update#translatable-models-and-multi-language-cruds
I've found two issues editing a field:
1. when you add a new record, language selector does'nt appear, you have to save a value then edit again
2. when a field jus have one value for a language, button "Save and back" does'nt works well, save but not go back 

### Is it a bug in the latest version of Backpack? YES

After I run ```composer update backpack/crud``` the bug... is it still there? YES

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.25 (cli) (built: Oct 23 2021 18:05:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v8.73.1@36dfae9d9ef7f88e8f9489c484a0a0609592bc21

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee

**Comment by promatik** [comment]
Hi @blondie63!

Thank you for your feedback, indeed, on create you cannot add the multiple languages your application may support. It only works on update. That's something we are aware of, and we don't have a solution for now.

Regarding the `Save and back`, it works by redirecting the browser to the previous page, what is happening, is that you switched languages inside the update page, then the Save and Back will lead you to the same update page but with the previous language.

This is something difficult to manage, because the behavior makes sense, but I understand it is confusing some times.

I can't see what we can do to improve this, this is not an issue in code, it's more of a behavior definition.

**Comment by tabacitu** [comment]
Hmm...

1. That's intentional, like @promatik said, only the Update operation has translations. This was done to force the admin into inserting an entry first in the main language (let's say EN), then translate it to multiple languages (let's say FR and IT). This has multiple benefits: less chance for error in big entries (eg. you forgot to fill in `title` for 4 languages, now you have to go through all of them to fill it in), easier to translate each individual field (because in FR and IT it will pre-populate the fields with the EN value). There are other ways in which the interface could be done, I agree... but the only one we thought of that would be as effective would be a `table` interface, where you see all translations in all languages at all times - basically a spreadsheet. But that's a very difficult feature to build, for very little benefit, the way we see it.
2. Ouch. I don't like that either, it can definitely be confusing to the user... but as @promatik said... I don't think there's much we can do about it... "back" is "back"... Changing the "back" behaviour for multi-language entries would be just as confusing to the other segment of people, who expect "back" to go "back"...

Sorry to not solve any of your issues @blondie63 . But it seems this is one of those rare cases where... there's actually nothing we can/should do about it.

Let us know if you disagree - we're wrong sometimes too, and we're open to suggestions.

Cheers!

**Comment by blondie63** [comment]
what do you think about this approach ?
https://blog.quickadminpanel.com/how-to-add-multi-language-models-to-laravel-quickadminpanel-2020/

**Comment by Mello21century** [comment]
I've done it myself on my project. I'll try to explain it as much as possible

This code goes into app\Models\Traits\HasTranslations.php
```php
<?php

namespace App\Models\Traits;

use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations as BackpackHasTranslations;
use Illuminate\Support\Arr;

trait HasTranslations
{
	use BackpackHasTranslations {
		BackpackHasTranslations::create as parentCreate;
		BackpackHasTranslations::update as parentUpdate;
	}


	/**
	 * Create translated items as json.
	 *
	 * @param  array  $attributes
	 * @return static
	 */
	public static function create(array $attributes = [])
	{
		$locale = $attributes['locale'] ?? \App::getLocale();
		$attributes = Arr::except($attributes, ['locale']);
		$non_translatable = [];

		$model = new static();
		$translatableFields = array_keys($model->getTranslationsAttribute());

		// do the actual saving
		foreach ($attributes as $attribute => $value) {
			if ($model->isTranslatableAttribute($attribute)) { // the attribute is translatable
				$model->setTranslation($attribute, $locale, $value);
			} else { // the attribute is NOT translatable
				$non_translatable[$attribute] = $value;
			}
		}
		foreach ($translatableFields as $translatableField) {
			foreach (request()->get($translatableField) as $locale => $value) {
				$model->setTranslation($translatableField, $locale, $value);
			}
		}

		$model->fill($non_translatable)->save();

		return $model;

	}

	/**
	 * Update translated items as json.
	 *
	 * @param  array  $attributes
	 * @param  array  $options
	 * @return bool
	 */
	public function update(array $attributes = [], array $options = [])
	{
		if (!$this->exists) {
			return false;
		}

		$locale = $attributes['locale'] ?? \App::getLocale();
		$attributes = Arr::except($attributes, ['locale']);
		$non_translatable = [];

		// do the actual saving
		foreach ($attributes as $attribute => $value) {
			if ($this->isTranslatableAttribute($attribute)) { // the attribute is translatable
				$this->setTranslation($attribute, $locale, $value);
			} else { // the attribute is NOT translatable
				$non_translatable[$attribute] = $value;
			}
		}
		$translatableFields = array_keys($this->getTranslationsAttribute());
		foreach ($translatableFields as $translatableField) {
			foreach (request()->get($translatableField) as $locale => $value) {
				$this->setTranslation($translatableField, $locale, $value);
			}
		}

		return $this->fill($non_translatable)->save($options);

	}
}
```

Add these two files into resources/views/vendor/backpack/crud/fields/

FILE: text_locale.blade.php
```php
<!-- field_type_name -->
@php($values = $crud->entry ? $crud->entry->getTranslations($field['name']) : [])
@foreach(config('backpack.crud.locales') as $langKey => $langValue)

	<?php
	$newField = $field;
	$newField['name'] = $field['name'] . '[' . $langKey . ']';
	$newField['label'] = $field['label'] . ' ' . $langValue;
	$newField['type'] = 'text';
	$newField['value'] = @$values[$langKey];
	?>
    @include('crud::fields.text', ['field' => $newField])
@endforeach
```

FILE: textarea_locale.blade.php
```php
<!-- field_type_name -->
@php($values = $crud->entry ? $crud->entry->getTranslations($field['name']) : [])
@foreach(config('backpack.crud.locales') as $langKey => $langValue)

	<?php
	$newField = $field;
	$newField['name'] = $field['name'] . '[' . $langKey . ']';
	$newField['label'] = $field['label'] . ' ' . $langValue;
	$newField['type'] = 'text';
	$newField['value'] = @$values[$langKey];
	?>
    @include('crud::fields.textarea', ['field' => $newField])
@endforeach
```

Now in your model that uses the HasTranslations trait change the trait to

```php
use App\Models\Traits\HasTranslations;
```

Now in any CRUD controller you may use those new fields
```php
CRUD::field('name')->label(__('Name'))->type('text_locale');
CRUD::field('description')->label(__('Description'))->type('textarea_locale');
```

Hope this helps

**Comment by blondie63** [comment]
> app\Models\Traits

I no have this path app\Models\Traits in my project
do I have to create it and put the file HasTranslations.php there?
Thanks

**Comment by pxpm** [comment]
@blondie63 inddeed, what @Mello21century suggests is to create your trait wherever you want, just make sure you use the correct namespace `App\Traits`, `App\Models\Traits`.. It's your organization that matters here. @Mello21century is just providing an example.

And yes, you need to create the two files @Mello21century mentions in `resources/views/vendor/backpack/crud/fields` if you want to use your field without adding aditional configuration. If you store the field in some other place you need to provide `view_namespace => 'your/field/path'` when defining the field in the CrudController so Backpack can pick it up. 

If you have any doubts please open a discussion or talk in gitter so we don't litter this thread with back and forth conversations.

Best,
Pedro

**Comment by blondie63** [comment]
ok, i've understood that putting your files in right folders, this override default backpack and spatie files.
The solution works very well, I just had to make two corrections:
inside file app\Models\Traits\HasTranslations.php i added "use Illuminate\Support\Facades\App;"
and change "\App::getLocale();" to "App::getLocale();"
Thanks for help

**Comment by pxpm** [comment]
@blondie63 Thanks for the feedback, it's nice to know it's working. Very appreciated the feedback!

Cheers man 🍺
