### ISSUE TITLE
[Feature Request] List Operation -- Jump to specific page.

### ISSUE THREAD

**Issue by trip-somers** [Laravel-Backpack/CRUD#3965]
# Feature Request

### What's the feature you think Backpack should have?

When paging through items in a List Operation, you basically only have 4 options: 1 page forward, 1 page backward, first page, or last page. I would be useful to be able to jump to any page in the range.

### Have you already implemented a prototype solution, for your own project?

I have not attempted this myself yet.

### Do you see this as a core feature or an add-on?

Core feature.

**Comment by tabacitu** [comment]
Hey @trip-somers ,

Thanks for the suggestion - we'll keep it in mind, but I don't think we'll include this any time soon. 

It seems like a very specific feature that very few people will actually use. When viewing a table, I think it's unlikely that somebody knows what _page_ they want to see. Most likely they know what _entries_ they want to see, and for that we have search and filtering. For that reason, I don't think it should be part of the core... it seems like a pretty niche feature to me.

Please don't let this stop you from adding other suggestions - we never lock issues on purpose, so that other people can come in and give their opinions. If it turns out we were wrong, we'll gladly admit that and go back on our decision. Of course, let us know if you disagree.

Cheers!

PS. You should be able to create that feature yourself, however, either by 
- (A) [publishing and changing](https://backpackforlaravel.com/docs/4.1/base-about#unpublished-views-1) `datatables.logic.blade.php` (but you'll be forfeiting updates to this file)... OR
- (B) [creating a widget](https://backpackforlaravel.com/docs/4.1/base-widgets#creating-a-custom-widget-type-1) (a blade file) with a dropdown and JS that does this, and including it before/after the table
