### ISSUE TITLE
[4.2][Bug] Error in text column in Permissions

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3984]
# Bug report

### What I did

Opened `Permissions` CRUD in 4.2

### What I expected to happen

Work

### What happened

Not work 😅 Are you getting the same thing @promatik ?

<img width="1279" alt="Screenshot 2021-12-04 at 08 14 04" src="https://user-images.githubusercontent.com/1032474/144699834-bfcb3e12-9bae-4aef-abe9-862a5d286eaf.png">

### What I've already tried to fix it

Nothing yet - currently deep into fixing other stuff.

### Backpack, Laravel, PHP, DB version

4.2

**Comment by tabacitu** [comment]
Ok so here's a weird one. If you `dd()` before (or after) that particular line... it's a string. It's definitely a string.

But it turns out the problem... is a DB entry. Backpack cannot echo out a table cell that says `logs` because... somehow Laravel tries to turn it into a `Logger` object 😱  If you rename that db entry to `logsss` it'll work just fine.

This is... WOW...

**Comment by promatik** [comment]
Hi @tabacitu!
I'm so glad this happened! this would be a HUGE error source, and it would be super hard for us to find what was happening, and we would certainly get negative feedback on this.

Fix is here https://github.com/Laravel-Backpack/CRUD/pull/4005.

Basically;
```php
is_callable('logs') // true
```
Because;
```php
$value = 'logs';
$value() // the same as;
logs() // returns an instance of \Illuminate\Log\LogManager
```

All our columns have that new feature, to verify if `value` is a callable.

```php
if(is_callable($column['value'])) {
    $column['value'] = $column['value']($entry);
}
```

it should become;
```php
if($column['value'] instanceof \Closure) {
    $column['value'] = $column['value']($entry);
}
```

**Comment by pxpm** [comment]
@promatik is better to check if it's a closure or check if it is a function and not string?

I ask because in other places to avoid this error we check: `is_callable($var) && !is_string($var)`. 

Not sure if your solution covers it 100%, if it does, is indeed simpler, just want to make sure. 

Best,
Pedro

**Comment by promatik** [comment]
@pxpm good point, I can't see a way for this not to work, an inline function is always an instance of `\Closure`, we can only send instances of `\Closures` right?
