### ISSUE TITLE
[WIP][REFERENCE] Relationships know limitations / edge cases

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4012]
- BelongsToMany/MorphToMany with pivot fields
    - [x] ⚠️ need manual code and an ajax field to don't allow the selection of the same entry as pivot relation - fixed by https://github.com/Laravel-Backpack/CRUD/pull/4064
    - [x] don't allow re-order of items, we can
        - (A) `unsync` and `sync` again everytime the entry is updated, might mess with id column in pivot, and/or timestamps
        - (B) create a way of repeatable storing the order in a defined developer column 

- HasOne / MorphOne
    - [ ] unable to add nested belongsTo subfields by `foreign_id` (they work as `relationName` though)
    - [ ] relations with pivot cannot be chainned (I have a PR to fix this, will submit after the "regular scenarios" are working)
    - [x] cannot delete data from HasOne input (see https://github.com/Laravel-Backpack/CRUD/issues/3944)

- HasMany / MorphMany
    - [x] after https://github.com/Laravel-Backpack/CRUD/pull/4016, when using the `repeatable` field for these relationships, the up/down arrows will not show (`repeatable` will have `reorder => false` on it); we should add a new attribute & functionality to the repeatable field: `order_input` (default `null`); when `order_field` is not null, we assume there's an input inside the group that stores the order, with that name; so we take that into account in the JS, by 
        - respecting that order at pageload;
        - updating those hidden inputs when the arrows are pressed, with the new order;

**Comment by tabacitu** [comment]
In addition to the quirks above, we also have the following things to do after  https://github.com/Laravel-Backpack/CRUD/pull/4054 (for reference, we have a breakdown of all relationships and their interfaces [here](https://github.com/Laravel-Backpack/CRUD/pull/4054#issuecomment-1007272418)).

TODOs:
- [ ] MUST merge https://github.com/Laravel-Backpack/CRUD/pull/4062
- [ ] MUST rename `pivotFields` to `fields` inside `repeatable_relation` (aka `relationship.entries`) because it's not ALWAYS on the pivot table;
- [ ] SHOULD create `relationship.entry` subfield - shows a repeatable with one item for `HasOne` and `MorphOne` relationships, so that the admin can remove that secondary entry entirely from the table;
- [ ] COULD create `relationship.multiselect` subfield - for `MorphTo` and `MorphedByMany` relationships, allows the admin to select multiple IDs from multiple tables; too complicated to do in 4.2;
- [ ] COULD show the `hasOneThrough`, `hasOneThrough`, `morphOneThrough` and `morphManyThrough` relationships in a disabled select (instead of aborting); but it only makes sense inside the Edit Operation;

As of this moment, **I think we should only do the quirks and the MUSTs**. The other stuff can wait until 4.2.x, they will be non-breaking changes. Instead of aborting in those cases, it'll show a field.

**Comment by tabacitu** [comment]
@pxpm head's up, I just finished the docs for `relationship` on 4.2 and I've decided we're going to use `subfields` (not `fields`, not `pivotFields`). From now on, we're going to use `subfields` for both `relationship` and `repeatable` (but the code should still work if you give `fields` or `pivotFields`, as aliases). I've written more about this here - https://github.com/Laravel-Backpack/docs/pull/303 if you want. Feel free to argue with me if you think this is a bad direction.

**Comment by tabacitu** [comment]
Update - I'm done refactoring and merging things inside `relationship`. The only thing left in order to close this issue and consider `relationship` finished is... fix the edge cases at the top of the issue. All yours @pxpm ! Let's tackle them one by one 💪

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4095
