### ISSUE TITLE
Horizontally dragabble datatable

### ISSUE THREAD

**Issue by er2es** [Laravel-Backpack/CRUD#4017]
# Feature Request

Horizontally srcollable datatable's

### Have you already implemented a prototype solution, for your own project?

Yes

### Do you see this as a core feature or an add-on?

Core feature

Code: 

`vendor\backpack\crud\src\resources\views\crud\inc\datatables_logic.blade.php`

```
.......
  dataTableConfiguration: {
        initComplete: function () {
            var tableBody = document.querySelector ('.dataTables_scrollBody');
            var headerTable = document.querySelector ('.dataTables_scrollHead');
            var curDown = false;
            var oldScrollLeft = 0;
            var oldScrollTop = 0;
            var curXPos = 0;
            var curYPos = 0;

            if (tableBody) {
                tableBody.addEventListener ("mousemove", function (e) {
                if (curDown === true) {
                    tableBody.scrollLeft = oldScrollLeft + (curXPos - e.pageX);
                    headerTable.scrollLeft = oldScrollLeft + (curXPos - e.pageX);
                    tableBody.scrollTop = oldScrollTop + (curYPos - e.pageY);
                }
                });

                tableBody.addEventListener ("mousedown", function (e) {
                    curDown = true;
                    e.target.style.cursor = 'grab';
                    curYPos = e.pageY;
                    curXPos = e.pageX;
                    oldScrollLeft = tableBody.scrollLeft;
                    oldScrollTop = tableBody.scrollTop;
                });

                tableBody.addEventListener ("mouseup", function (e) {
                    e.target.style.cursor = 'initial';
                    curDown = false;
                });

                tableBody.addEventListener ("scroll", function (e) {
                headerTable.scrollLeft = tableBody.scrollLeft;
                });
            }
        },
        ..................
        @if ($crud->getResponsiveTable())
```

**Comment by tabacitu** [comment]
I have good news for you @er2es . You can already do that, using `$this->crud->disableResponsiveTable()`. Check out the brief docs here - https://backpackforlaravel.com/docs/4.1/crud-api#responsive-table

Cheers!

**Comment by er2es** [comment]
hello

thanks for reply, but sorry - my mistake, i mean "Horizontally dragabble datatable", not scrollabe - i known the disableResponsiveTable function :) but on long tables, where this option not too pratical, i mean draggable is pratical function.

[https://drive.google.com/file/d/1eVrVc7IjxJ5v5u62elrzjwmgPL124pHD/view?usp=sharing](url)

**Comment by tabacitu** [comment]
Oh, I got it now, thanks for the GIF @er2es . So basically... this would make it a little easier to "scroll" horizontally on desktops, if the admin is not used to scrolling horizontally using their mouse/touchpad, correct? It doesn't improve anything for phones/tablets, because there you can already do this by scrolling.

We'll consider it, thanks. But please take note we're currently hard at work launching 4.2, so this will probably not get done in the next 2-3 weeks.

----

Until then... Or even if we don't do it in the core... I'm wondering... can this be isolated into a separate script, instead of having it in `datatables_logic.blade.php`? Because in 4.2 [we're launching a "script" widget](https://github.com/Laravel-Backpack/CRUD/pull/3912) and I think this could be very useful here. You could create a:

```php
class CustomCrudController extends CrudController
{
    public function setup()
    {
        Widget::add()->type('script')->content('assets/js/custom-datatables-scroll.js');
    }
}
```

And then your CrudControllers could all do:

```php
class ArticleCrudController extends CustomCrudController
{
    public function setup()
    {
        parent::setup();
        // the rest of the logic
    }
}
```

So if all this logic can be placed in a non-breaking JS file... it would be a cleaner way to do this, rather than overriding the `datatables_logic.blade.php` file and forfeiting its updates...

What do you think @er2es - is that possible?

Cheers!

**Comment by er2es** [comment]
hello @tabacitu , yes you're right, only on desktop with horizontal scroll would make it a little easier to "scroll"

and thanks, if you forget :) then i can make it easily with "script" widget too, without modify the core files

**Comment by tabacitu** [comment]
I'm back with a 6-month progress report: zero 😅 And since nobody else reacted to this, we've decided not to add this by default - no point. If someone wants it, they should be able to do it by adding a script, using the script widget. It's not great... but it's possible... 🤷‍♂️
