### ISSUE TITLE
[Bug] checklist_dependency old value breaks the whole Create/Update operation

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4051]
# Bug report

### What I did

Tried to Create a user in PermissionManager

### What I expected to happen

Form opens

### What happened

Big fat error:

<img width="1377" alt="Screenshot 2022-01-04 at 09 34 05" src="https://user-images.githubusercontent.com/1032474/148024632-a13b6b06-67cf-40b1-9bf4-c30488b08a64.png">

### What I've already tried to fix it

Changed those bits to `isset($old_primary_dependency)` and `isset($old_secondary_dependency)` thinking that's a small mishap in #3054 . Then the form loads. But no old value is populated at all.

### Is it a bug in the latest version of Backpack?

4.2

**Comment by pxpm** [comment]
Hey @tabacitu 

Indeed there is a bug on how I setup the dependencies, but that should be fixed in #4052 . 

The problem with old value is not new, it's there since the field exists basically. 

We setup the `secondary` entries as `disabled` when they get "auto-selected" from primary. 

I think we have 2 options here:
a) keep disabling the checkboxes, but create hidden inputs for them so they get submitted. 
b) style the checkboxes to look like disabled and use JS to prevent clicks, keyboard interaction etc. 

Let me know if this is something you want to pursue for 4.2 launch. 

Pedro

**Comment by tabacitu** [comment]
Hey Pedro,

Just tested and merged #4052 . From what I see, the only real _difference_ is this:

Before the user hits submit they see this:

<img width="705" alt="Screenshot 2022-01-05 at 14 10 15" src="https://user-images.githubusercontent.com/1032474/148215543-613a558e-1b2a-406e-b555-31f8abd95307.png">

After failed validation they see this:

<img width="712" alt="Screenshot 2022-01-05 at 14 10 48" src="https://user-images.githubusercontent.com/1032474/148215609-e8cb6754-fec1-45fb-b9dd-9f30c3a13f14.png">

----

This is the remaining problem you're talking about, right? If so... it's just an _interface problem_. What will get saved is still the same. What we should do, I think, is NOT add hidden inputs or change the style. We should probably _change the javascript_, so that on pageload, if "admin" is selected, its permissions will automatically be selected too. I see this is already happening when you click "Edit" on the User afterwards:

<img width="711" alt="Screenshot 2022-01-05 at 14 14 46" src="https://user-images.githubusercontent.com/1032474/148216084-27e5366a-6b94-415e-b05d-bc2dbdeed3a2.png">


----

This is a bug... but... it's low prio. We can launch with it.

**Comment by pxpm** [comment]
closed in favor of #4056 since the bug reported here had been fixed in #4052
