### ISSUE TITLE
Provide a way to define a default ordering inside ListOperation

### ISSUE THREAD

**Issue by joelmellon** [Laravel-Backpack/CRUD#4172]
# Feature Request

*What's the feature you think Backpack should have?*
### A way to specify a default sort column for a list operation, eg.
<img width="639" alt="Screen Shot 2022-02-09 at 5 05 11 PM" src="https://user-images.githubusercontent.com/13803216/153317047-f1fb1c81-21d6-4e65-9099-b40e0ff33db9.png">

---
*Have you already implemented a prototype solution, for your own project?*

### I've tried a couple methods but they don't work, eg.

- https://stackoverflow.com/a/63831852
- https://stackoverflow.com/a/57293048
- Even various combinations of both.

### Even if these methods did work, they feel very hacky. For the first example especially, since we have to find the index of the column we want to sort by (we can't reference it by name).

---
*Do you see this as a core feature or an add-on?*

### Core.
---
Thanks. 🙏

**Comment by tabacitu** [comment]
Hmm... I had no idea this is so difficult... thanks @joelmellon - I agree, we should make this a lot easier. I've tagged this appropriately so we do it.

In the meantime, I see in `ListOperation` we are applying the DataTable ordering `if (request()->input('order'))`, so how about doing the opposite here? You should be able to do something like this, right?

```php
// set a default orderBy clause (will be overridden by DataTable ordering)
if (!request()->has('order')) {
    $this->crud->orderBy('updated_at', 'DESC');
}
```

Let me know if that works for you.
Cheers!

**Comment by sudopeople** [comment]
> I see in `ListOperation` we are applying the DataTable ordering `if (request()->input('order'))`, so how about doing the opposite here?
> 
> ```
> // set a default orderBy clause (will be overridden by DataTable ordering)
> if (!request()->has('order')) {
>     $this->crud->orderBy('updated_at', 'DESC');
> }
> ```

Yeah, that's sort of the main technique used by developers who try this. It doesn't really work for me, or maybe it's just really hard to test since tables are so sticky.

Turning off table persistence in the config seems to help see what's going on a little better, but it would be really helpful if the `Reset` button reset the sort too.

**Comment by sudopeople** [comment]
I get the same behavior when I have `persistentTables=false` in my config, but when it's set to true, the last sort column stays. I'd expect `Reset` to clear the sort, regardless of that setting.

Anyway, as I've worked through this feature request I've started to understand the current functionality better, so I'm very grateful for that, thanks again. 🙏

**Comment by pxpm** [comment]
Hello @joelmellon sorry for the time it took to get back here. 

Usually column `0` it's the model primary column that Backpack automatically adds when developer don't manually specify it.
By default, if you don't apply any order to the table, Backpack will apply the "default order" that is `primaryKey => DESC` so that you get the last created items first. 

You can change the order by applying your custom orders to any other columns, so Backpack will apply your orders first, and on top of that, the primary key order.
You can also add your custom primary key orderBy, to override Backpack defaults.

The orderBy's are applied on database level so they cannot be "model attributes", but must be "table columns".

The reset button does not reset  `query orders`, only resets `table orders/filters`, so if you don't apply any order, like I told you Backpack will apply the "orderBy primary key" in the `query orders`. 

If in you controller you have something like:
```php
public function setupListOperation() 
{
$this->crud->query->where('active', true)->orderBy('id', 'asc');
}
```
This is a `query order`, the reset button will not reset this order.

I hope I made myself clear enough here, so I will be closing this, let me know if I missed something so that I can re-open if needed.

Cheers

**Comment by realtebo** [comment]
@pxpm is this documented? if not, could the team add a 'default sort option' in the section of api doc about sorting?

**Comment by tabacitu** [comment]
I don't think it's properly documented, no. @pxpm could you please create a first draft for docs for this, and tag me to take a second look? 🙏
