### ISSUE TITLE
Which version is current ?

### ISSUE THREAD

**Issue by petyots** [Laravel-Backpack/CRUD#419]
Hello, so i followed the tutorial how to install on Laravel 5.4 and i was thinking that i am gonna use 3.2 Of Crud but i was using 3.1.x. Then i tried to upgrade from 3.1 to 3.2 using this guide https://laravel-backpack.readme.io/v3.0/docs/whats-new-november-2016. Nothing good happened... After that i tried to install it on clean L5.4 using 3.2-dev in composer, this part was OK, Then i tried to publish the configs,langs etc... nothing happened nothing was published. Okay "everything can happen" i tried to copy everything manually -> Elfinder is not working. I said to myself never mind i will make workaround about this. After that i continue and tried to create the News section with translatable models. And guess what... There are no any options about the translations, just plain english that's it. So my question is what we have to do to use 3.2.x with L5.4 and translatable options ? Thank you very much and the project and work is just perfect,awesome etc... This is the most useful Laravel package for me. Keep up the good work.

**Comment by tabacitu** [comment]
Hi @petyots ,

3.2 isn't officially launched yet, I'm currently trying to cram in as many breaking changes as possible, because the next chance we get is in 6 months.

3.1.57 does bring Laravel 5.4 compatibility and is an official release, so you can use that. If you want the multi-language functionality, you can use the ```multilanguage``` branch, I've just updated it with L5.4 compatibility too.

Cheers!
