### ISSUE TITLE
[Bug] error with null relationships

### ISSUE THREAD

**Issue by thdebay** [Laravel-Backpack/CRUD#4217]
# Bug report

### What I did

I have an Invoice model and an InvoiceDetail models defined like so:

```
// Invoice.php

    protected $casts = [
        'invoiceDetails' => 'array',
    ];

    public function invoiceDetails()
    {
        return $this->hasMany(InvoiceDetail::class);
    }
```

```
// InvoiceDetails.php
    public function invoice()
    {
        return $this->belongsTo(Invoice::class);
    }
```

In my InvoiceCrudController I added this field:

```
        CRUD::addField([
            'name' => 'invoiceDetails',
            'label' => __('Products'),
            'type' => 'relationship',
            'subfields' => [
                [
                    'name' => 'product_name',
                    'type' => 'text',
                    'label' => __('Product'),
                    'wrapper' => ['class' => 'form-group col-md-8'],
                ],
                [
                    'name' => 'quantity',
                    'type' => 'number',
                    'label' => __('Quantity'),
                    'attributes' => ['step' => '0.01', 'min' => 1],
                    'wrapper' => ['class' => 'form-group col-md-2'],
                ],
                [
                    'name' => 'price',
                    'type' => 'number',
                    'attributes' => ['step' => '0.01'],
                    'label' => __('Price'),
                    'wrapper' => ['class' => 'form-group col-md-2'],
                ]
            ],
            'tab' => __('Products'),
            'init_rows' => 0,
        ]);
```

### What I expected to happen

I tried to use the new features of the "relationship" field as [described here](https://backpackforlaravel.com/docs/5.x/crud-fields#manage-related-entries-in-the-same-form-create-update-delete)

### What happened

I got this error: 
`foreach() argument must be of type array|object, null given`

### What I've already tried to fix it

Wrap this line into a collect() to handle null values
https://github.com/Laravel-Backpack/CRUD/blob/v5/src/app/Library/CrudPanel/Traits/Update.php#L117

`$relationModels = $relatedModel->{$relationMethod};`

`$relationModels = collect($relatedModel->{$relationMethod});`

### Backpack, Laravel, PHP, DB version

BAckpack 5.0.7, PHP 8.0

**Comment by pxpm** [comment]
Hello @thdebay 

I think I finally found the problem. You are casting you relation `invoiceDetails` to array. I usually keep my relations as collections, if I need them as array I could use `->toArray()`. Any reason you are casting the relation to array ? Or was just because it's a "repeatable" and for the repeatable to work (when it's not a relationship) we cast it to array ?

The line you mentioned does not need to be wrapped in a `collect()` because at that time we know that `$model->$method` is a relation so it returns an empty collection already, I didn't account for casting the relation to array, I think because I never did that. 

@tabacitu casting the relations to array is usual ? Should we support it ? It's not just wrapping that in a `collect()`, from first investigation casting to array the relation also breaks the saving process. Didn't investigate further as I never casted the relations to array, so I better ask opinions! 👍 

Thanks again for the report @thdebay , sorry for the bad experience. If you are not casting your relation to array for any special reason, just remove the casting and everything should work fine. 

Thanks 🙏

**Comment by tabacitu** [comment]
Wheew!! Good find @pxpm , I'm sure this took a lot more time than it looks 😅

That's odd to me too... never saw relations casted to array before... so... 🤷‍♂️ 
Let's wait and see what @thdebay says... why that casting is here in the first place.

**Comment by thdebay** [comment]
Thank you @pxpm and @tabacitu - indeed, the easiest way to solve this is simply to remove the cast. I don't needed anymore, since I will rely entirely on the new subfields feature.

Thanks for your help!
