### ISSUE TITLE
[BUG] Users do not have an associated email address.

### ISSUE THREAD

**Issue by alihamidali** [Laravel-Backpack/CRUD#4224]
Package

        "backpack/crud": "4.1.*",

`php artisan route:list` command gives following error

```
Symfony\Component\HttpKernel\Exception\HttpException

Users do not have an associated email address.

  at vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1132
    1128▕         if ($code == 404) {
    1129▕             throw new NotFoundHttpException($message);
    1130▕         }
    1131▕
  ➜ 1132▕         throw new HttpException($code, $message, null, $headers);
    1133▕     }
    1134▕
    1135▕     /**
    1136▕      * Register a terminating callback with the application.

      +2 vendor frames
  3   [internal]:0
      Backpack\CRUD\app\Http\Controllers\Auth\ResetPasswordController::__construct()

      +12 vendor frames
  16  [internal]:0
      Illuminate\Foundation\Console\RouteListCommand::Illuminate\Foundation\Console\{closure}(Object(Illuminate\Routing\Route))
```

https://github.com/Laravel-Backpack/CRUD/blob/f811634e8c4789fa15026d70592515b8051700ad/src/helpers.php#L86

**Comment by tabacitu** [comment]
@alihamidali I'm pretty sure I know what's going on for you.

Backpack uses Laravel's default `users` table. An it looks like you modified that table, and deleted the `email` column. If so, please follow the steps here to [configure Backpack to use usernames instead of emails for login](https://backpackforlaravel.com/docs/5.x/base-how-to#login-with-username-instead-of-email-1).

Hope it helps. Let us know if it doesn't.
Cheers!

**Comment by alihamidali** [comment]
#4225
