### ISSUE TITLE
IoC for CrudController::__construct()

### ISSUE THREAD

**Issue by halaei** [Laravel-Backpack/CRUD#424]
We have an issue in overriding dependencies of CrudController. Will this be OK to change the constructor in the following way?

```php
    public function __construct()
    {
           ...
              $this->crud = app()->make(CrudPanel::class); // Instead of new CrudPanel()
           ...
    }
```

This give us the flexibility to replace the CrudPanel dependency with our implementation, for faster bugfix and extendability.

**Comment by OwenMelbz** [comment]
Hi,

If you could create a PR with a full explanation into this issue and how this solves it, then tabacitu will be able to review it much faster for consideration :)

I'll close the issue here to keep the place tidy as it's not an actual bug - then the discussion can continue within a PR thread :)

Thanks

**Comment by tabacitu** [comment]
@halaei , sounds like a great idea, yes.
