### ISSUE TITLE
Delete button causes 419 Page expired

### ISSUE THREAD

**Issue by engel-m** [Laravel-Backpack/CRUD#4241]
This is very strange. There seems to be some problem with Csrf token, but I am using the delete button and crud delete operation out of the box, and did not change anything. 

I get the error: There's been an error. Your item might not have been deleted.

Status code 419 for the request, with 'status unknown' / page expired

The update method is working fine for me, so it seems to be limited to just the DELETE method.

EDIT: Just found out this problem only occurs on local server. It might be unrelated to Backpack, will keep searching.

**Comment by engel-m** [comment]
The problem was caused by the use of this route url in the delete button:

`data-route="{{ url($crud->route.'/'.$entry->getKey()) }}"`

I am running browserSync with webpack, and found out that it did work if I refer to 127.0.0.1:8000 directly instead of my localhost browserSync route. 

I made a custom delete button and replaced the above code with:

`data-route="/{{ $crud->route.'/'.$entry->getKey() }}"`

This makes it work as expected.

**Comment by pxpm** [comment]
@engel-m `url()` does some magic you can see it here (specifically the method `to()` that's called by `url()`: s://github.com/laravel/framework/blob/ee2958b68897b00c5662c80757179fe007555521/src/Illuminate/Routing/RouteUrlGenerator.php

At first i don't see a problem using an absolute url in this scenario, but I am not 100% confident about it. 

Why in first place does it throw the error with `url()` helper ? I expect `url()` helper to be used ALOT in backpack, does it throw errors in every place ? 

Could you change your app url in your config to be `http://127.0.0.1` instead of localhost ? Or maybe some configuration on the BrowserSync ? Also it's worth having a look in your `config/session.php` and make sure it's using the proper values.

I am going to close this as I don't think this is a Backpack issue, but feel free to continue the conversation, I am quite curious. 

Thanks,
Pedro
