### ISSUE TITLE
Empty name for subfields not handling properly

### ISSUE THREAD

**Issue by kiddtang** [Laravel-Backpack/CRUD#4250]
# Bug report

### What I did

I was using a select2 to populate the read-only fields in the form in v4.1
To quickly trick the CRUD ignore this nested field, i set the field to be empty `name`.
In v5, it is not properly handled...
```
                'name'  => 'jobs',
                'label' => 'Jobs',
                'type'  => 'relationship',
                'subfields' => [
                    [
                        'name'             => '',
                        'label'            => "Dummy Select",
                        'type'             => 'select2_from_array',
                        'options'          => $this->options,
                        'allows_multiple'  => false,
                        'wrapper'          => ['class' => 'form-group col-md-3 dummy-select2'],
                    ],
```

### What I expected to happen

Understand that it is documented as `name` is a mandatory attribute. 
However, an empty string is not considered as undefined name.
I need the proper way to skip this field. https://backpackforlaravel.com/docs/5.x/upgrade-guide#step-15
Maybe a meaningful Exception should be thrown to tell `name` cannot be empty string?

### What happened

With Empty Name
![image](https://user-images.githubusercontent.com/26017547/156874125-30f2e2e3-9ba6-44f3-88a9-caa68b2d415d.png)

With Name
![image](https://user-images.githubusercontent.com/26017547/156874221-bf900e38-1618-409a-acdf-08d8a130a097.png)

So, it breaks when trying to save

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'jobs[-1' in 'field list'
```

### What I've already tried to fix it

N/A

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.0.16 (cli) (built: Feb 21 2022 14:42:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.2@b91b3b5b39fbbdc763746f5714e08d50a4dd7857

### BACKPACK VERSION:
5.0.9@d995de2026b6fcb1b13b469f371c929c29d1c1cc

**Comment by pxpm** [comment]
Hey @kiddtang 

Would using `disabled` in your field do the trick? It would show up, but it wouldn't get sent with the form? 

You can also use controller or field events to manually remove the field before saving: https://backpackforlaravel.com/docs/5.x/release-notes#define-model-events-directly-on-fields

**Comment by kiddtang** [comment]
@pxpm 
Actually, it is a helper select2 to help users fill some read-only fields.  so, i cannot disable it.
Yeah, I have to remove the helper field manually, in v4.1 just empty name CRUD will just skip it.

**Comment by pxpm** [comment]
@kiddtang I am thinking we should keep the same behaviour just because we can't `build a proper field name from an empty name` as you showed it endup with `[-1[]]` wtv strange name! 

I get that using an empty field name allows to show the field and interact with, and at the same time don't post it because it does not have name. 

I started playing with this, it's not "difficult" to go back to the previous behaviour. I created a sample PR to discuss with @tabacitu if this is something worth, because this would only work inside repeatable (having fields with empty names). 

What I am thinking is why the reason to have a "helper" field to make "other read-only" fields work, from my understanding it should be the other way around, since the "read-only" fields can't be changed by developer, they are some kind of "internal relationship" with the field you are setting up without name.

What I am really wondering is that if you are not using that as some kind of "workaround" for some issues with relationships in 4.1, and we provide a nice way of dealing with that in v5. 

Thanks

**Comment by tabacitu** [comment]
Hey @kiddtang ,

I don't think we should support no-name fields. This is the first I hear about it in 6-7 years. Very nifty what you've been doing but... I don't think we should add code to support this use case, sorry.

While talking to Pedro, we came up with a solution like this one. I recommend you:
- give everything names
- give them a flag, something like `'ignore_on_save' => true`
- do something like the above in your `setupCreateOperation()`, to remove the fields & subfields you don't want

```php
    $this->crud->set('strippedRequest', function($request) {
        // TODO: process the CRUD to remove the subfields that have ignore_on_save

        $request = $request->only($this->getAllFieldNames());

        return $request;
    });
```

Is that reasonable @kiddtang ? @pxpm will come back with actual working code if you want.

Cheers!

**Comment by kiddtang** [comment]
Hi @tabacitu  @pxpm 
Thanks for your guys' comments... 
Maybe my description was confusing you guys... I am afraid we're not in the same picture.

Instead of how to handle my rare scenario...
I am asking to handle the empty `name` field in a better way...
If I delete the `name` attribute totally, i got this
![image](https://user-images.githubusercontent.com/26017547/157163706-ef126dba-7b3c-4b6e-8a9c-70177cec5466.png)

However, if i give `'name' => ' '`, or `'name' => ''` then it gives me
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'jobs[-1' in 'field list'`
Then i was confused that, I never declared such a weird column name.
I was hoping it throws something like `name should not be empty`, instead of  `Column not found` exception.

I am currently, set the name as `'_aux_tax_select2'` then `unset($job['_aux_tax_select2']);` in the request file `prepareForValidation()` function. It works pretty fine and neat.

During the journey of the v5 upgrade, I encounter many exceptions, this one (`Unknown column 'jobs[-1'`) takes me some time to figure out what was happening.

really appreciate you guys hard work!

**Comment by tabacitu** [comment]
> I am asking to handle the empty name field in a better way...

I TOTALLY agree with that. Just talked to Pedro about this yesterday... that we should throw an error with a clear message. If an empty name in a _field_ triggers an error... then an empty name in a _subfield_ should trigger an error too. 

> During the journey of the v5 upgrade, I encounter many exceptions

Please open issues when you find other confusing errors like this. It's something we want from Backpack v5, to be a lot easier to debug. The more clear errors messages we throw, the faster developers can know what to do, instead of searching or scratching their heads.

**Comment by tabacitu** [comment]
I've just reclassified this, because I think we DO need to do something about this - trigger a clear error message for subfields. We'll close this when that's done.

**Comment by kiddtang** [comment]
> I've just reclassified this, because I think we DO need to do something about this - trigger a clear error message for subfields. We'll close this when that's done.

Yes. Please give a clear message when the user tries to define `name=''` instead of a mysterious unknown column not found.
It was working fine in Backpack in v4.1 (automatic skip the empty `name`), so it is very helpful for ppl do the upgrade to Backpack v5.

Thanks @tabacitu

**Comment by pxpm** [comment]
I've sent #4268 to address this. 

Thanks again @kiddtang !

Best,
Pedro
