### ISSUE TITLE
Ordering Select field Items

### ISSUE THREAD

**Issue by charlielangridge** [Laravel-Backpack/CRUD#426]
I've created new field with type 'select2' but the related options are populating in the table order, rather than the crud->orderBy() for the related table. Is there a way to change the ordering of the selectbox items?

         $this->crud->addField([
            'label' => "Status",
            'type' => 'select2',
            'name' => 'status_id', // the db column for the foreign key
            'entity' => 'status', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Status", // foreign key model
        ]);

**Comment by OwenMelbz** [comment]
Hi Charlie,

You could try looking at laravels scoping -> https://laravel.com/docs/5.4/eloquent#global-scopes

This would mean you could apply a global scope, to enforce whenever the `all` method is called, it would enforce ordering, hopefully this gives you what you're after.

-------

As a note - the GitHub is not for support, its for tracking bugs and issues, if you're after support I recommend you follow the publisised guidelines stated https://github.com/Laravel-Backpack/CRUD/blob/master/CONTRIBUTING.md#having-trouble-using-backpack - because of that I will close this issue to keep the area support free, however people will more than likely respond to help you out if you're lucky :) maybe even tabacitu himself!
