### ISSUE TITLE
[Bug] incorrect entry loading on showOperation

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#4276]
# Bug report
When loading model `id 1000` (for example), it will show information for `id 123`. Introduced in `5.0.11`

### What I've already tried to fix it
Downgrading to `5.0.10` fixes the issue.

I have custom logic in one of my CrudControllers, like so:
```
        $this->crud->query
            ->notCancelled()
            ->allowedForDriver($user_id)
            ->distanceSphere('driver_best_journey', $user_latlng, $distance)
            ->orWhereIn('id', $invited_journeys);
```

The `orWhereIn()` clause works fine with `5.0.10`, however in `5.0.11`, it doesn't fetch the correct entry, and shows incorrect information on the show operation/template. If I remove the `orWhereIn` clause from the query, it seems to behave as expected.

I believe this is related to #4259.

**Comment by pxpm** [comment]
Hey @olipayne . Thanks for the report: 🙏 

I belive it worked before exactly because of the error I fixed. 

If your **PANEL** have a **GLOBAL** constrain, it should be respected in all operations. Problem was what you describe, you have a global constrain, but `SjowOperation` was not respecting it. Imagine that you want only to be able to list/view the items that are `active` in your panel, so in the `setup()` you would do: `$this->query->onlyActive()`. It would work for `List`, but for `Show` you could show ANY product no matter if it had the `active` or not. 

I guess the fix is to remove the "global" constrain from the query and use it only in the needed operations if it' not needed in all of them. For multiple operations setup and to avoid code duplication you can use:

```php
// in your setup()

$this->crud->operation(['list', 'update'], function () {
            $this->crud->query->addSpecificConstrainThatShowOperationWillNotHave();
        });
```
Does it make sense @olipayne ?

**Comment by olipayne** [comment]
Hey @pxpm, thank you for the extra-verbose info! Greatly appreciated. The `operation()` function does exactly what I need indeed. I guess I hadn't realised my own hack to work around what you have now fixed properly!

Closing, thanks again.
