### ISSUE TITLE
Multiple file upload delete error

### ISSUE THREAD

**Issue by petyots** [Laravel-Backpack/CRUD#430]
Hello, so i created the form using the guide in the site with the multiple_upload field i created the mutator the cast and everything else what i had to do... So far so good the photos are uploading successfully but after that they can't be deleted this is the error 

~~~~
Array to string conversion (SQL: update `hotels` set `photos` = [], `clear_photos` = 1486718635/6899c8ec146b611add5fd89accb6a374.jpeg, `updated_at` = 2017-02-10 12:01:42 where `id` = 2)
~~~~

I created the clear_photos field in db i casted it also in fillable var. Is this some kind of future for Soft Deletes ?
P.S I was searching everywhere for this field in every function but i did not find anything... Thanks in advance

**Comment by petyots** [comment]
I fixed it it was type in the cast. Anyway what is this for maybe soft deletes ? It will be nice if there is a switch to turn it off. 

P.S How can i contribute to the readme.io because there are some missing parts, for example in the upload_multiple field is not written that you need to create photos  and clear_photos fields as text or json. Also there are another useful function in the cli generator it will be nice if there is some information about that.

**Comment by tabacitu** [comment]
Hi @petyots ,

Thank you for searching first. Glad you worked it out!

Yes, basically CRUD all the "store"/"update" operations for the upload fields happen in the model. That's because this can be SO different from project to project, and from model to model. The [docs give an example](https://laravel-backpack.readme.io/docs/crud-fields#section-upload_multiple) of how you can achieve that - an Accessor and an Observer.

If you want to only delete the file from disk when force deleting, you should be able to modify the observer to check for that. Found this out [from here](https://laracasts.com/discuss/channels/eloquent/determine-if-is-a-soft-delete-in-a-event-handler-laravel):

```diff

    public static function boot()
    {
        static::deleting(function($obj) {
-            if (count((array)$obj->photos)) {
+            if (count((array)$obj->photos) && $obj->forceDeleting === true) {
                foreach ($obj->photos as $file_path) {
                    \Storage::disk('public_folder')->delete($file_path);
                }
            }
        });
    }
```

About the docs - you can find a "Suggest Edit" button in the top-right corner. Anything you edit then will be submitted for review. It would help a lot, thanks.

Actually, you don't need a clear_photos field in the database. That's just used to delete photos upon "updat". If you use $fillable on your model, just don't include it. If you use $guarded on your model, place it in guarded. But you're right, that's unclear and should be in the docs, thank you.

Hope it helps.

Cheers!

**Comment by zschuessler** [comment]
@tabacitu could you add this bit you mentioned in the docs? --

> Actually, you don't need a clear_photos field in the database. That's just used to delete photos upon "updat". If you use $fillable on your model, just don't include it. If you use $guarded on your model, place it in guarded. 

You mentioned it should be in the docs, you may have forgot :wink:. Had to do some sleuthing to find the issue, docs would help others avoid that!

**Comment by tabacitu** [comment]
Done @zschuessler - thank you.
