### ISSUE TITLE
[Bug] Security patch not working

### ISSUE THREAD

**Issue by JoepdeJong** [Laravel-Backpack/CRUD#4301]
# Security patch not working

### What I did

Executing the comments provided by email:
```
composer update backpack/crud
php artisan backpack:fix
```

### What I expected to happen

Composer updating `backpack/crud` and adding a `backpack:fix` command.

### What happened

Composer did not update `backpack/crud` and the `bakpack:fix` command was not available.

Output of `composer update backpack/crud`:
```
- composer update backpack/crud
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```
and
```
- php artisan backpack:fix                                     
Command "backpack:fix" is not defined.  
```

### What I've already tried to fix it

- Running the commands in several laravel environments.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yeah, that is the whole problem :) composer is not updating `backpack/crud`.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.4.28 (cli) (built: Mar 16 2022 09:01:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.63.0@8f3d280f36a427730c8c8fa34316c79eed38781e

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

```

**Comment by pxpm** [comment]
Hello @JoepdeJong 

Thanks for the report, unfortunatelly I think your composer is not updating for some time, since your version is `4.1.30` and current Backpack version is  `4.1.69`. 

Probably you have not properly defined your rule in `composer.json` ? `backpack/crud:"^4.1"` should work for you and get you the latest version. 

I am going to close this as I don't think this is a problem with Backpack. Please re-open if I am wrong. 

Thanks.
