### ISSUE TITLE
SimpleMDE fullscreen / splitscreen doesn't account for toolbars

### ISSUE THREAD

**Issue by samsebastian** [Laravel-Backpack/CRUD#432]
Using the `simplemde` field option. 
When I hit fullscreen or splitscreen on the simplemde editor, the sidebar and top menu overlap it which makes it impossible to see what you are typing or exit fullscreen.

Fixed with adding the below the the `vendor/backpack/base/layout.blade.php` view, but would be good to update the core stylesheet.

```
            <style type="text/css">
                .CodeMirror-fullscreen, .editor-toolbar.fullscreen {
                    z-index: 9999 !important;
                }
            </style>
```

**Comment by tabacitu** [comment]
Hi @samsebastian , 

Thanks for the issue and the fix! Just applied it to the field and it works perfectly. You can run ```composer update``` to get it.

Pro tip: whenever you need to modify something in a field/column/button/other crud view, you can just create a blade file with the same name in your ```resources/views/vendor/backpack/crud/``` folder. So for SimpleMDE field it would have been ```resources/views/vendor/backpack/crud/fields/simplemde.blade.php```. This is an easy way to make custom modifications, if you need them, without modifying general files like ```layout.blade.php```. Backpack loads the views from there if they exist, otherwise it falls back to the ones in the package. Hope it helps in the future.

Cheers!
