### ISSUE TITLE
[Bug] Unable to cast repeatable into fake columns , it cant show the saved data

### ISSUE THREAD

**Issue by SebastianCordiano** [Laravel-Backpack/CRUD#4320]
# Bug report
For the new repeatable i need to cast the columns but if the repeatable is inside a fake column, that is already cast, the repeatable cant retrieve the data and it always empty
### What I did
I have a fake columns in my model with cast as array
In the crud controller i have a repeatable with 
                'fake'     => true, 
    		'store_in' => 'extras',

### What I expected to happen
All the data saved in the repeatable shows up

### What happened
Repeatable is always empty

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.4 (cli) (built: Apr  4 2022 13:30:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.5.1@35be2599c9ac3d58bf1578895c2e85ea4848a0d7

### BACKPACK VERSION:
5.0.11@337163b7e9a0e63413474bd3ee800a198f83c8e9

**Comment by pxpm** [comment]
@SebastianCordiano repeatable is itself a "fake" field. It will store as json inside the column with the name you specify for it. 

So if you want to store the repeatable data inside the extras column in database, just name your repeatable extras and remove the `fake => true` and `store_in` from field definition. 

Altough I would recomend using other column name for the repeatable since `extras` is the assumed name when you just use `fake` and it could cause conflicts with the repeatable data on database. 

Also don't forget that you need to cast the column you use to store the repeatable as array or json in your mode.

I don't think we plan to add any kind of support for `fake => true` in a repeatable field since, like I said, repeatable is itself already a fake field. 

You can read more about repeatable here : https://backpackforlaravel.com/docs/5.x/crud-fields#repeatable-pro

Going to close this, please re-open if you think I am wrong, I am alot of times 🙃 

Thanks

**Comment by SebastianCordiano** [comment]
@pxpm 
Just assume the case for the PageManager:
I create various template for the pages , all the data will be stored inside the extras (fake column) , inside that template i need a repeatable for various reason (ex: slider, listing or just n block all displayed the same but with different data), in that case i was unable to use it there ?

**Comment by tabacitu** [comment]
Hmm so... from what I understand... the difference is:
- `repeatable` without `fake` will replace all the JSON
- `repeatable` with `fake` should just insert that JSON into the `extras` JSON 

Seems like a valid use case... Can you please investigate if it's difficult to support @pxpm ?

**Comment by SebastianCordiano** [comment]
@tabacitu @pxpm 
I think i found a rude solution for that

**What i do:**
In the crud controller i overwrote the store/edit methods , with a function to encode the fields with a custom parameter , called 'encode', and replace the current request, here the code:
`private function encodeFields(){
        $request = $this->crud->getRequest()->request->all();    
        $operation= $this->crud->getCurrentOperation();
        $fields = $this->crud->get($operation.'.fields');
        foreach($fields as $field){
            if(isset($field['encode']) && $field['encode']){
                $request[$field['name']]=json_encode($this->crud->getRequest()->request->all()[$field['name']]);
            }
        }
        $this->crud->getRequest()->request->replace($request);
}
public function store(){
        $this->encodeFields();

	$response = $this->traitStore();
        return $response;
}
`
That allowed the repeatable to retrieve the data and store it without problems

Idk if that helps you , but is a solution for this specif case

**Comment by pxpm** [comment]
Hey @jorgetwgroup

I think this is probably fixed, or partially fixed by this PR https://github.com/Laravel-Backpack/PRO/pull/76

Can you give this a try and report your findings ? Let me know if I can help you with something. 

Cheers

**Comment by pxpm** [comment]
I've just re-tested this, and everything is working as expected now. 

I will be closing this, thanks for the report @SebastianCordiano 

If I am wrong, please re-open, I've been wrong many times before.

Cheers
