### ISSUE TITLE
i want to take title from model using relationship

### ISSUE THREAD

**Issue by Bekshakx** [Laravel-Backpack/CRUD#4340]
ErrorException
Undefined array key "relation_type" (View: C:\OpenServer\domains\altyn-adam-back\vendor\backpack\pro\resources\views\columns\relationship.blade.php)

### What I did
Controller:
  CRUD::column('marital_status')->label('Семейное положение')->type('relationship')->entity('resumes')->attribute('title')->model('App\Models\Resume');

User Model:
public function resumes()
    {
    	return $this->hasMany('App\Models\Resume', 'user_id', 'id');
    }

### What I expected to happen

I want to take marital status through a bunch:

User->resumes->marital_status()
resume in marital_status_id

### What happened

??

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @Bekshakx I guess you are looking for an `HasManyThrough` relation, so User -> `HasMany`  matrial_status `Through` resumes if I get that rigth ?

**Comment by tabacitu** [comment]
@pxpm I've been seeing this `Undefined array key "relation_type"` reported quite a few times. If it's NOT a bug, just devs trying something that's unsupported... then we should definitely throw a custom error message, with more info or steps to debug. To help devs debug it themselves, instead of thinking it's a bug in Backpack. Of course, that's if it's NOT a bug in Backpack 😅

**Comment by tabacitu** [comment]
@Bekshakx what was your problem here, do you remember? We're trying to it figure out, so we can throw better error messages. If so, please let us know and we'll reopen. Thanks!
