### ISSUE TITLE
[Bug] Repeatable field - reordering stops fields from working

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4356]
# Bug report

### What I did

In the demo, inside PetCrudController, I've made the `owners()` field show up/down arrows too, in order for an admin to be able to reorder its owners. So I just added `reorder(true)` on the `owners` field.

### What I expected to happen

- arrows to show
- after you click the arrows, the fields to work

### What happened

- arrows do show
- sometimes... after you click the arrows, the JS fields STOP WORKING

https://user-images.githubusercontent.com/1032474/166426676-8ec15ffa-d0a4-4085-961b-78faaa17fbaf.mp4

### What I've already tried to fix it

Nothing yet... I expect the fields need to be re-initialized or something.

**Comment by gkamaratak** [comment]
Hello Cristian,

I am writing here what else I have noticed.

Select2 , Browse , Datepicker and whatever other field needs initialization does not respond on the moved row. 
As far as I investigated when a row is moved it is cloned and then deleted the original one. Therefore it needs inititalization when created (That's for the elements that needs libraries to work).

Tried textbox works fine. Tried the simple  select and it loses the latest selected value .

**Comment by pxpm** [comment]
Finally found the culprit!! 

It will take a little to fix, but we should be good at the end of the day. 

I will update when I have news later.

**Comment by pxpm** [comment]
Hello, just to let you guys know that the PR to pro is already submitted.

The issue was the fact that when we changed to arrayed names, we also changed the order/how repeatable elements are initialized and cloned on page.
In the "order operation" we were directly cloning the repeatable container visible on page that already had the fields initialized, so when it was removed and re- added in the desired position, the fields that depend on javascript would stop working because they were never re-initialized.

Cheers

**Comment by gkamaratak** [comment]
Looking forward to check it out ! Thanks Pedro !

**Comment by tabacitu** [comment]
Just merged and tagged Pedro's PR - a `composer update backpack/pro` should pull the fix for it, and it should all work smoothly @gkamaratak . Let us know if that's not the case and we'll reopen.

Again - thanks for letting us know about this bug.
Cheers!
