### ISSUE TITLE
[Bug] Class Alias DeveloperProvidedFormRequest breaks parallel testing

### ISSUE THREAD

**Issue by spoyntersmith** [Laravel-Backpack/CRUD#4389]
# Bug report

### What I did

Ran PestPHP tests in parallel that check CRUD controllers validation is working

### What I expected to happen

The tests in parallel should pass as they do in singular

### What happened

`ErrorException: Cannot declare class DeveloperProvidedFormRequest, because the name is already in use in /Users/name/Sites/app-name/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Validation.php:207`

### What I've already tried to fix it

Running tests singularly works. Wrapping the class_alias code in a class_exists check works

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.0.19 (cli) (built: May 12 2022 09:09:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.13.0@87b6cc8bc41d1cf85c7c1401cddde8570a3b95bb

### BACKPACK VERSION:
5.0.18@06ea421e44c353604ba56669e1fd3ac7a18981df
```

**Comment by pxpm** [comment]
Hey @spoyntersmith 

Thanks for the report 🙏 

Ok ... I think I get the issue ... Let me think about the best way to solve it. 

I think we have two options here: 
- first as you described, checking if class already exists (but I am not sure that when using paralellism the class is refering to the same crud as expected)
Imagine crud A and B, crud A validates, and when crud B runs validation we check if class already exists (and it will exist from crud A, not crud B validation). Not 100% sure about this theory but it's possible.

- destroy the class after using it. (probably the best and permanent solution since we don't need it anymore. 

Can you help me to debug if my theory from crud A to crud B holds? What's your outputs when you use `class_exists()` ? OR you are validating the same crud multiple times ? 

Cheers

**Comment by spoyntersmith** [comment]
@pxpm Those were my thoughts but I couldn't get the words out, especially point 1.

I think the more viable solution is point 2.

I'll add a test case and get back to you.

**Comment by spoyntersmith** [comment]
@pxpm I've got a test case set up and can replicate the same issue when using two different Requests.

As expected tests fail when running crud A and crud B in parallel using my original solution. crud B ends up using the validation rules from crud A

**Comment by spoyntersmith** [comment]
@pxpm Would it be possible to do something like

`new DeveloperProvidedFormRequest($formRequest);`

Then in the `DeveloperProvidedFormRequest::class` we handle the rules logic?

**Comment by pxpm** [comment]
Hello @spoyntersmith 

It could be a possible solution, yes ... I've talked with some peers and the suggestions I got lied around doing like you are saying, or creating some king of `FormRequest Factory`. 

I am still not sure if any of the solutions would cover the scenario that we are dealing with here, I think i've tried before getting into this solution and it would not fully fix our issue here, but I cannot fully recall so I need to try to redo it from scratch. 

Problem is, for example, if you have the FormRequest (that you give crud with `$this->crud->setValidation(FormRequest::class)`) and let's say you configure `$stopOnFirstFailure` and a special validator with `public function withValidation(...)` in this request.
Then you add a field, and you say that this field have the rule `min:1`. 

So we have a FormRequest class, and an array of validation rules at this point. 

We want that `min:1` rule to be validated, but also to run the `withValidation`, stop on the first failure and also redirect the user to wherever the developer defined in the request. 

From my understanding those configurations done in the `FormRequest` will not go through `DeveloperProvidedRequest`, we will give it the $formRequest, but will be the same as we have before creating the anonymous class, we still need to add those rules into the request and validate it at once so all the request rules are respected. 

The only problem I am aware with this solution is the fact that we have to create an alias for the $formRequest, because we cannot use `someClass extends $someVariable` otherwise I would just do `DeveloperProvidedRequest extends $formRequest`. 
Also, from my knowledge it's not possible to remove an alias after creating it. :|

Like I said, this solution was either a f*king genius idea, or the most stupid one. Time will tell me!

**Comment by jorguerra** [comment]
I have the same problem. It happened to me handling an entity with two many to many relationships

**Comment by pxpm** [comment]
Hello @spoyntersmith and @jorguerra 

I think I have the answer about using an anonymous class 🤡 

I've created https://github.com/Laravel-Backpack/CRUD/pull/4529 to remove the anonymous class in favor of other solution.

If you can/want give that branch a test and let us know in the PR thread your feedback. It's very appreciate and helpful 🙏 

Going to close this, thanks for the report!

Cheers

**Comment by jorgetwgroup** [comment]
Hello @spoyntersmith and @jorguerra did you have an example of test file to replicate problem from my side.

Thanks.

Cheers.
