### ISSUE TITLE
[Bug] Select2 on `relationship` field (PRO) is squished

### ISSUE THREAD

**Issue by GRardB** [Laravel-Backpack/CRUD#4393]
# Bug report

### What I did

I added a `CRUD::field('users')->type('relationship')` to a field in a `setupCreateOperation()` function.

### What I expected to happen

It would always display like this:

![Edit_organization____FAST_Network_Admin_Panel](https://user-images.githubusercontent.com/748180/169805825-97fe2706-f09b-45d7-8d98-f557b8f57494.png)

### What happened

90% of the time, it displays like this:

![Edit_organization____FAST_Network_Admin_Panel](https://user-images.githubusercontent.com/748180/169805343-7b565189-6b86-421f-8e7e-036fcc42e3b7.png)

### What I've already tried to fix it

Nothing, really. It seems to be caused by some sort of race condition. To "fix" it, I refresh until I see it correctly.

### Is it a bug in the latest version of Backpack?

Yes, upgraded to 5.0.18. `backpack/pro` is 1.0.17.

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 8.1.5 (cli) (built: Apr 21 2022 10:15:06) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v9.11.0@598a8c84d452a66b90a3213b1d67189cc726c728

### BACKPACK VERSION:
5.0.18@06ea421e44c353604ba56669e1fd3ac7a18981df
```

**Comment by tabacitu** [comment]
Damn! Thanks for reporting this @GRardB . I wasn't able to get the same thing though - it shows ok to me. Can you give us a bit of context please? 

- What browser are you using? 
- Is it in a page with a lot of fields? If so, it might take a 1-2 seconds to unsquish, does "time fix it"?
- Can you give us a screenshot/video of it happening with the full form page, maybe that gives us some more hints?
- Any JS errors?

Thanks again. Cheers!

**Comment by GRardB** [comment]
> Damn! Thanks for reporting this @GRardB . I wasn't able to get the same thing though - it shows ok to me. Can you give us a bit of context please?
> 
> * What browser are you using?
> * Is it in a page with a lot of fields? If so, it might take a 1-2 seconds to unsquish, does "time fix it"?
> * Can you give us a screenshot/video of it happening with the full form page, maybe that gives us some more hints?
> * Any JS errors?
> 
> Thanks again. Cheers!

Thanks for the quick Response, @tabacitu.

- Browser: I'm on the latest Chrome on macOS 12.2.1. I tried reproducing in Firefox and Safari, but those seem to work fine. I tried disabling all my Chrome extensions, but that didn't fix the issue.
- Fields: Only two fields in total.
- Time: Waiting doesn't seem to fix it, unfortunately.
- Screenshot: attached below!
- JS Errors: None

<img width="1183" alt="Edit_organization____FAST_Network_Admin_Panel" src="https://user-images.githubusercontent.com/748180/170142314-d9876f23-b2c7-49a7-97a8-85082498b973.png">

**Comment by pxpm** [comment]
@GRardB hi there.

I recall sometime ago we had `style="width:100%"` hardcoded in the select. It was removed because aparently it was not needed ... but maybe it was there to prevent that "race condition" when it happens (it just not happen that ofter, or happen more for some users than others). I've never seen that error myself ... but hey, here we are and you are getting the error.

Can you go into `vendor/backpack/pro/resources/views/fields/relationship/relationship_select.blade.php` and add on the `<select` tag (around line 60) the hardcoded `style="width:100%"` ? I am not sure if you get the error consistently, if you do it should be easy for you to check if the solution works.

I would test this myself but I am like on hundreds of refreshes and can't get the error to appear on my side not even once :| I am also using Chrome but on windows. 

Let me know,
Pedro

**Comment by GRardB** [comment]
> @GRardB hi there.
> 
> I recall sometime ago we had `style="width:100%"` hardcoded in the select. It was removed because aparently it was not needed ... but maybe it was there to prevent that "race condition" when it happens (it just not happen that ofter, or happen more for some users than others). I've never seen that error myself ... but hey, here we are and you are getting the error.
> 
> Can you go into `vendor/backpack/pro/resources/views/fields/relationship/relationship_select.blade.php` and add on the `<select` tag (around line 60) the hardcoded `style="width:100%"` ? I am not sure if you get the error consistently, if you do it should be easy for you to check if the solution works.
> 
> I would test this myself but I am like on hundreds of refreshes and can't get the error to appear on my side not even once :| I am also using Chrome but on windows.
> 
> Let me know, Pedro

Hey @pxpm , that does indeed fix the issue!

I did a little more testing, and I'm seeing that the field isn't always race-conditioning to the same width. After a bunch of refreshing, here are some different sizes that I ended up seeing without the fix applied (same window size and everything):

![Edit_organization____FAST_Network_Admin_Panel-2](https://user-images.githubusercontent.com/748180/170453227-d96ae53f-896a-458c-a40a-aa2e953f8037.png)
![Edit_organization____FAST_Network_Admin_Panel](https://user-images.githubusercontent.com/748180/170453237-cc0c49d5-cd14-4acd-9184-f3d3053e516a.png)
![Edit_organization____FAST_Network_Admin_Panel-4](https://user-images.githubusercontent.com/748180/170453262-67a1fd01-b6ab-49d9-a8f1-61cb2839a467.png)

Not sure if that helps, but I figured it was worth mentioning

**Comment by pxpm** [comment]
Hey @GRardB thanks for quick reply and such good explanation.

I guess it's because at the time of draw it calculates the available space and set the width accordingly. Dunno why size differs and other times it fully works. I think I really don't want to go into that rabbit hole, just find the fix for it and be done with.

I will check the best way to fix it, since I think something like this had been reported for other fields that use the select2 plugin, but we never reached a conclusion. 

Thanks again for report and confirming the solution.

Cheers

**Comment by tabacitu** [comment]
Guys - we just release backpack/pro 1.0.19 which should fix this. We ended up reverting the inline `width:100%` so that it's non-breaking. No need to publish assets or anything else. After you run a `composer update backpack/pro` you should be getting 1.0.19 which has this fixed. Can anyone please confirm?

Thanks and sorry 🙏
Cheers!

**Comment by GRardB** [comment]
I can confirm it's fixed! Thanks for the super quick work on this! And no need to apologize 😁

**Comment by pxpm** [comment]
Thanks @GRardB for the help here!

Cheers 🍻
