### ISSUE TITLE
Broken image using image field on new crud items

### ISSUE THREAD

**Issue by njbarrett** [Laravel-Backpack/CRUD#443]
Everytime I use the image field, when adding a new entry a broken image is displayed.
I feel this is not aesthetically pleasing or intended. See attached.

<img width="141" alt="screen shot 2017-02-10 at 3 14 40 pm" src="https://cloud.githubusercontent.com/assets/241407/22917700/4aea21ee-f2c1-11e6-8916-c3b0b0de98e6.png">

**Comment by usmanhafeez147** [comment]
how are you showing your encrypted image file on user side please tell me

**Comment by Athuli7** [comment]
He's not talking about a stored file. He's talking about when the file doesn't exist. Like when the entry is added for the first time.

**Comment by mpixelz** [comment]
+1
this is because the path on the crud edit screen is wrong.. not only on the first time but also on the edit screen the image shows as broken. the model function to set file path and name works for posting but is not applied here to display where the image is being saved.
i might be wrong.. if someone can show us what we are doing wrong?

**Comment by Athuli7** [comment]
@mpixelz The issue isn't with the crud. It's with the image field view. njbarrett is talking about having a better placeholder when the image isn't available.

**Comment by mpixelz** [comment]
yeah figured it out.. there is no placeholder for the image for the first time..
the second issue i was facing was due to the wrong driver selected in the filesystem.. had to create new driver for public_path();
thanks thou :)

**Comment by lloy0076** [comment]
If this is still an issue that needs fixing, please reopen.
