### ISSUE TITLE
[Repeatable] Show custom balde data 

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#4495]
# Bug report
I want to show a custom blade data in a custom_html field inside a repeatable
### What I did
I creataed an accesor in the model with the repeatable data as json

```
public function getLogisticServicesDataAttribute()
{  
   $logisticServicesData = [
      'name' => $this->name
      'up_services_html' => view('common/logistic_service_order', [
             'date' => $this->date,
     ]),
   ];
    return json_encode($logisticServicesData);
}
```

And in the controller the repeatable
```
$this->crud->addField([
            'name'  => 'logistic_services_data',
            'label' => trans('crud.order.logisticServicesOrder'),
            'type'  => 'repeatable',
            'fields' => [
                 [
                    'name'  => 'name',
                    'type'  => 'text',
                ],
                [
                    'name'  => 'up_services_html',
                    'type'  => 'custom_html',
                ],
            ],
            'new_item_label'  => trans('crud.order.newService'),
            'tab' => trans('crud.service.services'),
            'init_rows' => 0
        ]);
```
### What I expected to happen

I want to show the up_services_html blade in the custom_html field. 'value' field is mandatory, but what i put there?

**Comment by pxpm** [comment]
Hello @aberaldo as per `custom_html` field definition https://backpackforlaravel.com/docs/5.x/crud-fields#custom_html the `value ` should be the content you want to show as a field. for example an `<hr/>` or something like that. 

For more advanced field usage i'd recommend you to create a custom field or use a view field type https://backpackforlaravel.com/docs/5.x/crud-fields#view-1 to load your custom field.

I'd also recommend you to start from a backpack field like template by publishing it: `php artisan backpack:publish crud/fields/text` and then rename it so it does not replace the backpack core `text` field. You will have the backpack field structure and will avoid some errors when building a custom field. If you want a select start from select etc ... 

Let me know,
Pedro

**Comment by pxpm** [comment]
Hey @aberaldo the way I see it, the `view` or `custom_html` fields allow developer to use their own html, but ofcourse if they want their custom field to work with backpack features it must have some Backpack core stuff on it, like the wrapper etc. 
Same principle applies if you want your custom field to be compatible with CRUD JS API depending on your fields inner-workings you might need to apply some solutions (that we already apply on some crud fields, like listening to the enable/disable/change etc events and doing some custom stuff on those fields). 

That's why I'd recomment starting from an already existing Backpack field so you don't mess up setting up the wrapper the `initElementFunction` if it needs some js, pushing to the correct styles/scripts stacks etc. 

I will be closing this as I don't think there is much we can do here, or maybe I am not fully understanding what is the need here, maybe when you come up with something that satisfy your needs, you share it, and I get a better picture of what you want to achieve.

If there is something else I can help with, ping me! 

Cheers

**Comment by aberaldo** [comment]
@pxpm what i need is inside a repeatable, display some value as html not in a text field or some other form field type. I will try those you mentioned before. I will drop you a line if i have some news ;-)
