### ISSUE TITLE
[Bug] disabling ConvertEmptyStringsToNull has side effects on the saving process for M-M relations

### ISSUE THREAD

**Issue by basselhossam** [Laravel-Backpack/CRUD#4527]
# Bug report

### What I did

I have a select2_from_ajax_multiple which represent n-n relationship and this field is optional but when I try to submit the form without filling the field it crashes

### What I expected to happen

the record should be saved and the relation should be empty

### What happened

it crashes `array_values() expects parameter 1 to be array, null given`
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/29305349/179374832-6e9bfd3c-473b-4196-88f6-bb62703cbe7a.png">

### What I've already tried to fix it

after some investigation I found that the issue happens because the form is sending empty string when the field is empty so in [`app/Library/CrudPanel/Traits/Create.php`](https://github.com/Laravel-Backpack/CRUD/blob/v5/src/app/Library/CrudPanel/Traits/Create.php#L122) the null escapes doesn't work I suggest to make it like so `$values = (isset($relationDetails['values'][$relationMethod]) && !empty($relationDetails['values'][$relationMethod])) ? $relationDetails['values'][$relationMethod] : [];` that way wether the value is null or the value is empty it becomes `[]`

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.21 (cli) (built: Sep 30 2021 13:37:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.83.19@4264f2ee12330bdb1be050998f58ba7271236395

### BACKPACK VERSION:
5.1.4@4539c787a2e052d2e2e2c00188c38432dc2a7ea9

**Comment by pxpm** [comment]
Hello @basselhossam I could not reproduce your issue, my `select2_from_ajax_multiple` does not return an empty string. 
Can you confirm that you are not overriding the `select2_from_ajax_multiple` in your project and misses out some update ? 

What's your PRO version ? and what looks like line 20 in your `select2_from_ajax_multiple` ? 

Cheers

**Comment by basselhossam** [comment]
> What's your PRO version ? and what looks like line 20 in your `select2_from_ajax_multiple` ?

```
<input type="hidden" name="{{ $field['name'] }}" value="" @if(in_array('disabled', $field['attributes'] ?? [])) disabled @endif />
```

**Comment by basselhossam** [comment]
> Can you confirm that you are not overriding the `select2_from_ajax_multiple` in your project and misses out some update ?

I'm not overriding `select2_from_ajax_multiple` and I'm on the latest version on backpack and pro

**Comment by basselhossam** [comment]
check the highlighted field this is the value from the `select2_from_ajax_multiple` field
<img width="1790" alt="Screen Shot 2022-07-18 at 12 18 48 PM" src="https://user-images.githubusercontent.com/29305349/179491973-2a1858b6-59f0-42bf-bd0d-43d93d7f1ec8.png">

**Comment by pxpm** [comment]
Ok @basselhossam can you provide me your relations and field definition as I am still not able to reproduce your issue: https://recordit.co/8vJxAds3T2

**Comment by basselhossam** [comment]
@pxpm when I applied this fix on my vendor package it worked https://github.com/Laravel-Backpack/CRUD/pull/4528

**Comment by pxpm** [comment]
Hey @basselhossam I saw that thanks for the PR.
As soons as I can reproduce the issue I can test your PR, but as you can see from the video I sent you, I am still unable to reproduce it

**Comment by basselhossam** [comment]
> As soons as I can reproduce the issue I can test your PR, but as you can see from the video I sent you, I am still unable to reproduce it

I hope the data I shared is sufficient if you need any extra info I'd be happy to assist in anyway possible

**Comment by basselhossam** [comment]
@pxpm any updates regarding this ?

**Comment by pxpm** [comment]
I have it on my TODO list for this week, I will get back to you with news asap @basselhossam

**Comment by pxpm** [comment]
Hello @basselhossam . I tried to reproduce this once again but am still unable.

I still think ConvertEmptyStringsToNull middleware is not running. 

I don't mind adding an extra check, but I am sure it's not in the null coalescing operator (`smt ?? smt_else`) because that's the main purpose of that operator, don't allow null to go by. 

So the only way I can think that you can get null there is if you are sending an empty string (so that empty string is not converted to null), and after the `json_decode` if the string is empty it returns null. 

You can add after `$values = $relationDetails['values'][$relationMethod] ?? [];` a `dd(gettype($values))` and I bet you will get string, while in my tests I am getting array `[]`.

Like I said, adding an aditional check wouldnt hurt anybody so what you think:

```php
$values = $relationDetails['values'][$relationMethod] ?? [];
$values = is_string($values) ? json_decode($values, true) : $values;
$values = $values ?? [];
```

Wouldn't this cover the only case I describe where null can reach the `array_values` function? 

Cheers

**Comment by basselhossam** [comment]
> I still think ConvertEmptyStringsToNull middleware is not running.

actually you are right I just added a `dd` inside it and it didn't run but I don't really remember disabling it and it wasn’t mention in the upgrade guide that I should add it

also I believe it should be optional though

**Comment by basselhossam** [comment]
> You can add after `$values = $relationDetails['values'][$relationMethod] ?? [];` a `dd(gettype($values))` and I bet you will get string, while in my tests I am getting array `[]`.

correct I got "string"

**Comment by basselhossam** [comment]
> Like I said, adding an aditional check wouldnt hurt anybody so what you think:
> 
> ```
> $values = $relationDetails['values'][$relationMethod] ?? [];
> $values = is_string($values) ? json_decode($values, true) : $values;
> $values = $values ?? [];
> ```
> 
> Wouldn't this cover the only case I describe where null can reach the `array_values` function?

Yes I tried this solution and it worked like a charm +1

**Comment by pxpm** [comment]
It's a Laravel middleware, not a Backpack one. We never mentioned it because, well .. we just assume people would be using it as it's a Core piece of Laravel, and in my opinion, a very very usefull one.

But I agree with you, that in some use cases you migth want to remove it. 
The usage of the middleware can/should be optional, I am just not sure if this has impact in other Backpack places since we always developed Backpack using `ConvertEmptyStringsToNull` middleware from Laravel. 

Like I told you, I don't mind adding an aditional check so atleast users don't get ugly errors, and it's empty anyway so it should have no impact in other parts of the code. 

Do you want to update your PR to use this simpler solution ? If you do it, also please add a comment above the line we are adding say something like:
 ```
// disabling ConvertEmptyStringsToNull middleware may return null from json_decode() if an empty string is used.
// we need to make sure no null value can go foward so we reassure that values is not null after json_decode()
```

Cheers

**Comment by basselhossam** [comment]
@pxpm yes I agree with you that this is a very useful Middleware and I always leave it on but unfortunately the system that I'm working on the DB design is a bit weird that some columns are not nullable that's why we disabled it 

Anyways the PR is updated now, thank you for your time and effort regarding this and sorry to discover this just now
