### ISSUE TITLE
[Bug] Problem with version 5.2.0

### ISSUE THREAD

**Issue by helesjunior** [Laravel-Backpack/CRUD#4531]
# Bug report

### What I did

I upgraded from version 5.1.3 to version 5.2.0, and now I get an error on the dashboard page.

### What I expected to happen

Load the page normally as before

### What happened

Returned the error:  "Argument 2 passed to Backpack\CRUD\app\Library\CrudPanel\CrudPanel::getViewNamespacesFromConfigFor() must be an instance of Backpack\CRUD\app\Library\CrudPanel\Traits\mixed or null, string given, called in D:\junior\Documents\Projetos\contratos_v2\vendor\backpack\crud\src\app\Library\CrudPanel\Traits\HasViewNamespaces.php on line 71 (View: D:\junior\Documents\Projetos\contratos_v2\vendor\backpack\crud\src\resources\views\base\inc\widgets.blade.php) "

![image](https://user-images.githubusercontent.com/34820135/179813902-40439363-900f-4731-a2bf-83cc416c15fb.png)

### What I've already tried to fix it

On line 56 of the file: 'vendor\backpack\crud\src\app\Library\CrudPanel\Traits\HasViewNamespaces.php', when I change the second argument from 'mixed' to 'string' the problem is solved.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:48) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.83.20@aa5908e83fccb18b135ca31aa0342cf4bd6909a8

### BACKPACK VERSION:
5.2.0@85229a7258608ed80e1812ee0ddb4bad983e15a1

**Comment by tabacitu** [comment]
Hey @helesjunior ,

That's odd - I just updated [our online demo](https://demo.backpackforlaravel.com/) and didn't get the error. Thanks for reporting this - I'll ask @pxpm to take a look as soon as he wakes up 😀 We'll probably have it fixed by the end of today.

Cheers!

PS. The problem seems to be super-clear: 
- because of Laravel 8, we still support PHP 7.3
- `mixed` was introduced in PHP 8
- so if you use them together... 💣

But... why didn't our tests catch this? That's exactly what they're there for. That's what I wanna know 😀

**Comment by tabacitu** [comment]
Update: I just added more testing combinations in https://github.com/Laravel-Backpack/CRUD/pull/4532 , but I think the scenario above should have been covered by our regular tests anyway (not these new ones).
