### ISSUE TITLE
[Feature] Menu Type field

### ISSUE THREAD

**Issue by petyots** [Laravel-Backpack/CRUD#456]
Hello, guys a made small useful field it's called menu_type and it's used in MenuItem you can choose whatever you want for example tag,article,hotel,destination,category etc... whatever you want. Here is the syntax 

```php
 $this->crud->addField([
            'name' => 'type',
            'label' => 'Type',
            'choose_label' => 'Choose Option',
            'type' => 'menu_type',
            'options' => [
                'page' => 'Page',
                'tag'  => 'Tag',
                'hotel' => 'Hotel',
                'destination' => 'Destination',
                'category' => 'Category'
            ],

            'types' => [

                'page'   => [
                    'model' => 'App\Models\Page',
                    'name' => 'page_id',
                    'attribute' => 'name'
              ],
                'tag'  => [
                    'model'=> 'App\Models\Tag',
                    'name' => 'tag_id',
                    'attribute' => 'name'
                ],
                'hotel' => [
                    'model' => 'App\Models\Hotel',
                    'name'   => 'hotel_id',
                    'attribute' => 'name'
                ],
                'destination' => [
                    'model' => 'App\Models\Destination',
                    'name' => 'destination_id',
                    'attribute' => 'name',
                ],
                'category' => [
                    'model' => 'App\Models\Category',
                    'name' => 'category_id',
                    'attribute' => 'name'
                ]
            ],
        ]);
```

**Comment by tabacitu** [comment]
Hi @petyots ,

Sounds great! How do you store the information in the DB, to know which "entity" the ID corresponds to (whether it's a Tag, Hotel, Destination, Category, etc)? 

Cheers!

**Comment by AbbyJanke** [comment]
Seems similar to what I had suggested just recently? May be mistaken. https://github.com/Laravel-Backpack/MenuCRUD/pull/23

**Comment by lloy0076** [comment]
@AbbyJanke - I noticed you closed your PR?

@tabacitu - is this still useful/relevant?

(I'm on a close issues rampage atm).

**Comment by tabacitu** [comment]
@petyots , @AbbyJanke - any of you guys want to help the community by writing an article on how to do this? It can be wherever you want ([medium](http://medium.com/), your blog, any other blog) and I'd love to link to it from [the backpack blog](https://backpackforlaravel.com/articles) too. I think this is a great way to keep these snippets close right now, so that we can reuse them in our projects, even if we don't include them in the core project.

Cheers!

PS. @lloy0076 I say let's close it, we need a little more room to breathe in _Issues_, so let's only keep _issues_ in _Github Issues_ :-) We do need to provide a helpful solution for everything before we close, though. That's the kind thing to do and I hope it will foster the same kind of attitude from the community. We all _choose_ to work with Backpack, and communicate with each other, so I truly believe each message should be kind :-)
