### ISSUE TITLE
[Feature Request] Callbacks for operations

### ISSUE THREAD

**Issue by lmout82** [Laravel-Backpack/CRUD#4571]
# Feature Request

### What's the feature you think Backpack should have?

Callbacks for operations.

In one of my recent projects, access is controlled by roles/permissions (spatie package). But these global permissions are not enough as a user can only perform an operation on certain models. So calling `hasAccessOrFail()` is not enough.
Although it is possible to filter the models beforehand (list view), nothing prevents the user to manually edit the id in the URL to access another model and gain access to confidential data.

For an show/edit operation for instance, I had to override the `show()` / `edit()` method to access to `$this->data['entry']` to do the check. For the `update()` method, the check can be done with FormRequest. 

Doing this check in the events of the concerned model is not always a good option: for example, it is possible to use the retrieved event to block access to a particular model, but it may be necessary to allow access if the model is a relation of another model.

I have no doubt that there are other situations than mine.

Rather than overwriting everything, it would be better to be able to declare callbacks in a controller. For example: editBefore, editEntryRetrieved, editDataFilled,...

### Have you already implemented a prototype solution, for your own project?

Easily by adding this:
```
if (method_exists($this, ‘editEntryRetrieved’)) {
	$this->editEntryRetrieved();
}
```

### Do you see this as a core feature or an add-on?

Core feature.

**Comment by pxpm** [comment]
Hello @lmout82 
I think the problem with editing constrained entries had been fixed, you should add those constraints in the crud panel query. 

You can create a model scope let's say for example: `scopeForCreator($query) { //add your constraints to the query` and in your crud controller add those constraints in the setup or per operation as needed with `$this->crud->query->addClause()`

It's a work in progress for the show operation, we are working on some improvements in our read operations list/show and using the crud query there too is on the roadmap. 

But it should work for list/update operations that already use the query instead of the model.

**Comment by lmout82** [comment]
Hello @pxpm,

Thanks for the answer.
Query scopes are a very interesting approach and I can't wait to use them everywhere.

Regardless of my real example related to permissions, it is rarely a good idea to have to overwrite a method of a package completely, at least as long as the changes are not important/complex. It would be great to have a mechanism that allows you to customerize the behavior of some Library\CrudPanel\Traits methods, to some extend, without having to pull out the bazooka too easily.

**Comment by tabacitu** [comment]
Hi @lmout82 ,

Thanks for the suggestion. We've considered adding `before` and `after` hooks for Operations - but every time a use case popped up, we found that we had ways around it, that were a bit cleaner. Let's see if that's the case here too.

If what you're concerned with is... single-item operations... then you should be able to create just ONE check, in the `setup()` method. For example:

```php

    /**
     * Configure the CrudPanel object. Apply settings to all operations.
     *
     * @return void
     */
    public function setup()
    {
        CRUD::setModel(\App\Models\User::class);
        CRUD::setRoute(config('backpack.base.route_prefix') . '/user');
        CRUD::setEntityNameStrings('user', 'users');

        if (request('id')) {
            // TODO: if the logged in user shouldn't be able to do this, quit
        }
    }
```

That being said, I agree with you, we _could_ split up Operations into more blocks, so that they're more easily edited, overridden or hooked into. Or trigger Backpack events across the operation process. But to do that, or even talk about that, we'd need to work on specific scenarios, eg. _"I want to do X for Operation Y in a real project, and I can't do that because all code is in one place"_ - doing this without actual use cases in mind could lead us to work on fixing a non-issue, in an inefficient-in-real-world manner, so I'm going to close the issue. **When you stumble into a use case where the code prevents you from doing something elegantly, please open a different issue, and we'll talk about solutions for that specific use case** 🙏

In the meantime, I think my solution above fixes your problem about how to stop all single-item operations, in one place. If it does not, please let us know and we'll reopen.

Thanks, cheers!
