### ISSUE TITLE
[Feature Request] setEntityNameStrings with html, but without in title of page

### ISSUE THREAD

**Issue by Sladous** [Laravel-Backpack/CRUD#4597]
# Feature Request

### What's the feature you think Backpack should have?

blank text in title of page in $this->crud->setEntityNameStrings(.....);
If I use:
$this->crud->setEntityNameStrings(<a href="'https://backpackforlaravel.com/">Backpack is the best.'</a>);
you change title of page to <a href="'https://backpackforlaravel.com/">Backpack is the best.'</a>.
Better would be: "Backpack is the best."
Or create escape parametr?

**Comment by pxpm** [comment]
@Sladous I am sorry but I didn't fully understand what you meant. 

The entity name strings are written by developer, should be simple strings, but if you need something more custom you can manually escape the text with: `e($textToEscape)`. 

I tried with `$this->crud->setEntityNameStrings("mo'nster", "mo'nsters");`

![image](https://user-images.githubusercontent.com/7188159/184340455-27ce6c49-7add-4822-8183-154b7a7a4591.png)

Sorry I can't be of more help, going to close this as I don't think there is any bug here. 

If you think I am wrong, and I am alot of times, please re-open or continue the discussion. 

Feel free to post some screenshoots and/or code example if your english writting skills are not the best, we devs understand each other by code 👍 

Cheers

**Comment by Sladous** [comment]
Your advice goes to the tag
         <div class="container-fluid">
    <h2>
      <span class="text-capitalize">

But I think title in browser:
<head>
    <title><href=......

Potřebuji mít setEntityNameStrings like href. 
That will work, but I would like <title> escaped.

**Comment by pxpm** [comment]
Like the function name says, setEntityName**Strings**. Ofcourse and `<a>` is a string, but that's not the purpose of this function.

you can customize the header file by publishing it with: `php artisan backpack:publish base/inc/head`

make a note that since you are overriding this file you should keep an eye on future Backpack updates if something changes here, because Backpack will use your overriden file and not the file in the package folder.

Cheers
