### ISSUE TITLE
nested grid and field template

### ISSUE THREAD

**Issue by avifatal** [Laravel-Backpack/CRUD#460]
Hi,
1. I have a Customer entity that has many Notes and many Managers.
    when editing a customers I want to display 2 tabs bellow the edit form with grids inside. Note model grid and Manager model grid. is it possible?

2.  Is it possible to have a field template?

```[
                'template' => '<div class="col-lg-6">{0}</div>',
                'name'  => 'email',
                'label' => trans('backpack::permissionmanager.email'),
                'type'  => 'email',
            ],``` 
So I would be able to make the form readable?

Thanks

**Comment by jsiebach** [comment]
1. I think you need to show some code or describe what issue you are having in order to get help.

2. You can use the `prefix` and `suffix` options to create a template, or just create a custom field type by adding your blade file to `views/vendor/backpack/crud/fields`

prefix/suffix example https://laravel-backpack.readme.io/docs/crud-fields#section-number

**Comment by tabacitu** [comment]
Closing old threads. Feel free to continue posting if this still an issue. Cheers!
