### ISSUE TITLE
Defined two n-n relationships (with the same pivot table) , just the second relation saved in DB

### ISSUE THREAD

**Issue by dimaAlj** [Laravel-Backpack/CRUD#4603]
In the Employee model:
```
public function companyEmployees()
    {
        return $this->belongsToMany(Employee::class)->where('employees.employee_subordination', 
            EmployeeSubordination::CompanyEmployee)->withTimestamps();
    }

    public function subcontractormainemployees()
    {
        return $this->belongsToMany(Employee::class)->where('employees.employee_subordination', 
             EmployeeSubordination::SubcontractorMainEmployee)->withTimestamps();
    }
```
In the EmployeeCrudController:
```
['name' => 'subcontractormainemployees',        'label' => trans('site.subcontractors'),    'type'=>'select2_multiple'],
['name' => 'companyemployees',        'label' => trans('site.employees'),   'type'=>'select2_multiple']
```

In this case, companyemployees relationship is not stored

**Comment by pxpm** [comment]
Hello @dimaAlj 

I guess `EmployeeSubordination` is some kind of enum ? Can you check if they are returning the correct results ?

Also from what I see in your code, polymorphic relationships would be a better suite. https://backpackforlaravel.com/docs/5.x/crud-how-to#morphtomany-n-n-polymorphic-relationship

Can you show me the request that is posted when you submit the form ? Does both fields get sent ? 

Cheers

**Comment by dimaAlj** [comment]
Hello @pxpm

**Comment by pxpm** [comment]
Hey @dimaAlj thanks for the clarification. 

Like I said I think you need to be using the Polymorphic relationship because both "relations" belong to the same `pivot table`l, and when the last one is `synced` with the database it will only have the one you have sent last.

This is the process:
- sync companyemployees (delete all "related entries" from the database and leave only the one you sent).
- sync subcontractormainempolyees (delete all "related entries", including the last one you added from the database and leave only the one you sent)

That's how Laravel `sync` works. 

You have two options here:
- Either override the backpack `store()` function and do your saving manually. 
- use the mentioned polymorphic relationships 

I would use the polymorphic relationships as from your issue description they seem the perfect fit.
Any way, all roads lead to Rome, just pick whatever better suits you. 

Going to close this as I don't think there is any Bug here from our side. 

Please re-open if I am wrong, sometimes I am 🙃 

Cheers
