### ISSUE TITLE
Mac Safari 13 javascript console errors block functionality [Bug] 

### ISSUE THREAD

**Issue by CamusMX7** [Laravel-Backpack/CRUD#4608]
# Bug report

### What I did

My client opened the crud forms in Safari 13.1.2 on Mac

### What I expected to happen

Simple calculations in javascript and all fields will work correctly

### What happened

Although in all the browsers of my Windows 10 everything works correctly, in that version of Safari it did not work (On another Mac with safari 15 it works fine) and several Javascript errors appeared in the browser console.

![errores_safari](https://user-images.githubusercontent.com/107073227/185724733-661efad1-10b2-4cc9-b7cf-1241143c3cfb.JPG)
 
In Chrome on that same Mac everything works fine, but my client always uses safari for his teamwork.

### What I've already tried to fix it

nothing

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP: 8.1.2
Laravel: 9.15.0
Backpack: 5.2.2
Backpack/pro: 1.2.1

**Comment by tabacitu** [comment]
Hi @CamusMX7 ,

Thanks for letting us know. Safari 13 - it comes with what version of Mac OS?

Cheers!

**Comment by CamusMX7** [comment]
Hi @tabacitu 

It is macOS High Sierra 10.13.6

My suggestion to the customer is that their workers use Chrome, because apparently they can no longer update Safari. But you know that people who use Mac generally use Safari. Hopefully something can be done about it.

Thanks!

**Comment by CamusMX7** [comment]
Hi @tabacitu @pxpm 
Is there any comment or news about whether this problem will be addressed at some point or if slightly older browsers will definitely not be supported?

I would like to know about it so I can make decisions.

Thanks.

**Comment by pxpm** [comment]
Hey @CamusMX7 me and @tabacitu already discussed this but we found no proper solution yet. 
Unfortunatelly we have bigger issues to work now and can't spend the proper time here to make sure we fully support Safari 13, we suspect that if it's breaking here it could be breaking in other places too and it needs to be properly addressed. 
From what I've read High Sierra is no longer getting updates, and I think Safari 13 is also out of the update cycle. 

It's a multitude of factors that we can't fully control:
- Client can't update OS
- Client don't want to use Chrome


All of them are reasonable, and I fully understand the issue, but we cannot prioritize this in the near future.
If you come up with a solution feel free to send a PR or something that we can have a look, otherwise I don't think we will be working on this for the next weeks, if ever. 

Sorry about that, I will be closing this, let me know if you think I am wrong. 

Cheers

**Comment by CamusMX7** [comment]
@pxpm Thanks for letting me know. I understand that there are many things that cannot be controlled and the decision makes sense to me. But I consider it important to place a visible notice (I don't know if it already exists, but I think I haven't seen it) where it is specified that Backpack is only compatible with the latest browser versions (or specify a time limit or versions), because it is an important limitation depending on the client.

Cheers

**Comment by pxpm** [comment]
Thanks @CamusMX7 , we already added them after you opened this issue!  https://github.com/Laravel-Backpack/docs/pull/369

Thanks for letting us know!

Cheers
