### ISSUE TITLE
[Bug] Can't create an admin user on install if users table already exists

### ISSUE THREAD

**Issue by elenakondrateva** [Laravel-Backpack/CRUD#4648]
# Bug report

### What I did

Followed installation instructions and run `php artisan backpack:install` command.

### What I expected to happen

Command finishes without errors and I would be able to create at least one admin user.

### What happened

It couldn't add an admin user because there's existing `users` table with different from expected structure.

Output is the following:

```
root@5a7e904030ab:/var/www/html# php artisan backpack:install

   STEP 1  Installing Backpack CRUD:

  Publishing configs, views, js and css files ............................................................................ DONE
  Creating users table ................................................................................................... DONE
  Creating CheckIfAdmin middleware ....................................................................................... DONE
  Installing Backpack Generators ......................................................................................... DONE


   STEP 2  Creating an admin:

  │ Quickly jump in your admin panel, using the email & password you choose here.
  │ Currently there are 267 users in the users table.

  Add an admin user? (yes/no) [no]:
 > yes

  Name:
 > elena

  elena's email:
 > [email removed]

  elena's password:
 > 


   ERROR  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "name" of relation "users" does not exist
LINE 1: insert into "users" ("name", "email", "password", "created_a...
                             ^ (SQL: insert into "users" ("name", "email", "password", "created_at", "updated_at") values (elena, [email removed], [password hash removed], 2022-09-06 00:53:56, 2022-09-06 00:53:56))
  │ Skipping creating an admin user.
```

### What I've already tried to fix it

Just skipped adding admin user part. I guess it should ask for alternative table name if `users` already exists. 

### Is it a bug in the latest version of Backpack?

Yes, just installed.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 10 2022 12:23:36) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v8.83.16@6be5abd144faf517879af7298e9d79f06f250f75

### BACKPACK VERSION:
5.3.11@f418447283bc17df616c6030d6585c59b0557bb3

**Comment by pxpm** [comment]
Hello @elenakondrateva thanks for the report.

From my understanding creating the admin uses the model you defined in `config('backpack.base.user_model_fqn')` to get the table, by default   it's `App\Models\User`, and assume that you have a `name, email and password` columns on that table. 

I don't think we should enter that rabbit hole here, I think we should check if the columns we need are in the table and show the option to the user to add an admin, if not present in the table, don't show that option to create a new admin. 

What do you think @tabacitu ? After allowing to change the "table", we need to make configurarable email for people that use username, and maybe remove password if people are not using it ... you know where this is going to lead. 

Let me know what you think.

**Comment by tabacitu** [comment]
Hmm... good catch... Thanks for telling us about it @elenakondrateva .

I agree with you @pxpm , I don't see much we can do here "as a feature", without going into a deep _deep_ rabbit hole. Possible customizations to the `users` table are infinite. We _can_ test we have those columns there... sure. But _should we_? Then what do we do? Do we ask for different things (username instead of email, things like that)? No, I don't think we should do that, either. 

I don't think we should cater as much to non-standard `users` tables, to be honest. We can make this experience better by 
- (a) throwing a nice error message (maybe) 
- (b) changing the docs so it's clear that creating a user from the command-line will only work for standard `users` table
- (c) creating a separate `installation` docs section for those who install it on top of existing projects... where that's more clear

But I don't think this should be worked on as "_a feature_", no.

**Comment by pxpm** [comment]
I've submitted https://github.com/Laravel-Backpack/docs/pull/376 to the docs. 

I think the right path here is :
- add this note to the docs.
- check if user table have `name, email, password` fields, case not we show a warning: `unknown user table structure, backpack is unable to automatically create admin users for you, please manually create them`. Not throwing "a nice error" after user had input everything. 

- alternatively, add the note to the docs, and hide the question completely.

@tabacitu If you think the PR for docs is enough, please close this issue when you merge the docs PR, otherwise let me know what you think about my suggestions above.

Cheers

**Comment by tabacitu** [comment]
I say that's enough for now, with the note in the docs. If more people stumble upon this problem, we'll code a solution. Until then, I think we're good. 

Thanks for submitting this @elenakondrateva ! If anybody else gets here because they had the problem, please speak up, we want to know!

Cheers!

**Comment by Geezter** [comment]
Hello. I have problem installing Backpack too. I don't get this far that it asks about admin user. It gets stuck on creating users table. I already have a fully functional users table and it should make its own user table like admin_users, but I can't find a way to change this. I wouldn't want to change the name of my users table since there would be so much fixing to do. So is there a way to change the users table name which backpack wants to create in the isntallation process? Or is my problem somewhere else?

Thank you in advance. I'm using Laravel 10.

**Comment by tabacitu** [comment]
@Geezter I recommend you follow the [manual installation process](https://backpackforlaravel.com/docs/5.x/crud-how-to#how-to-manually-install-backpack), and only run what commands you need. 

If you already have a `users` table, I recommend you use that one, and the User model you already have (might want to use it in `config/backpack/base.php`). The only thing you'd need is a way to differentiate between which users are Admins and which are not. That could be done with an extra DB column, or a package like https://github.com/spatie/laravel-permission - your choice. Just make sure you change the `app\Middleware\CheckIfAdmin.php` middleware to _actually_ check that the logged in user is an admin. 

You can find more information about how to customize the Auth process in this FAQ - https://backpackforlaravel.com/docs/5.x/base-how-to#authentication-1

Hope it helps!
