### ISSUE TITLE
[Bug] PHP 8.2 deprecation in AddonServiceProvider in BackPack/PRO

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/CRUD#4665]
# Bug report

### What I did

Run my application using BackPack on the RC-version of PHP 8.2.

### What I expected to happen

Everything to work smoothly ;)

### What happened

Everything worked smoothly, but a deprecation error was raised.

### What I've already tried to fix it

Submitted a PR to fix this in the `addon-skeleton` repository that seems to be used as a base for the `pro` repository, see https://github.com/Laravel-Backpack/addon-skeleton/pull/13. I think this might have gone unnoticed. Note that the same fix should be done in the `pro` repository, but I cannot access that.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?  
*Yes*

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:  
*5.3.10 and pro 1.2.7*  
*PHP 8.2rc1*

**Comment by pxpm** [comment]
Thank you @jnoordsij 

I will be honest, I haven't tried PHP 8.2, but I will, sometime soon ! 🙃 

If this is the only thing that we have to update for 8.2, I am very very very happy with it!

I've just tagged and moved your PR to the right project so that we don't forget about it, I will be closing this issue, if you find anything more related to this deprecation we can build the list on that other PR and start from there. 

Thanks again for your contribution @jnoordsij 🙏 

Cheers
