### ISSUE TITLE
[Feature Request] / [Bug] - Allow to set a default sort using a field on a related table

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4683]
# Feature Request

### What's the feature you think Backpack should have?

Situation: 
- jobs table related with customers table where jobs.customer_id => customer.id

In the setupList of JobCrudController we're adding this 

        $this->crud->addColumn([
            'name' => 'company_name',
            'label' => 'Cliente',
            'type' => 'text',
            'orderable'  => true,
            'orderLogic' => function ($query, $column, $columnDirection) {
                // nota bene, dato che l'ordinamento predefinito è su questo campo
                // ho tolto il leftJoin necessario da qui perchè l'ho messo
                // in cima alla setupListOperation come predefinito
                return $query
                    ->leftJoin('customers', 'joborders.customer_id', '=', 'customers.id')
                    ->orderBy('customers.company_name', $columnDirection)
                    ->select('joborders.*')
                ;
            }
        ]);

The sorting works.

But now we CANNOT sort by Id because id column is not unique. 
So we tweaked the id field

        $this->crud->addColumn([
            'name'=> 'id',
            'label' => 'ID',
            'orderable'  => true,
            'orderLogic' => function ($query, $column, $columnDirection) {
                return $query
                    ->orderBy('joborders.id', $columnDirection)
                    ->select('joborders.*')
                    ;
            }
        ]);

And now ... how can we set a default sorting based on customers.name ?

I tried this

        $this->crud->query
               ->orderBy('customers.company_name', 'asc');

but it don't works because there is no join at first loading. So no customers table, so we got a sql error

### Have you already implemented a prototype solution, for your own project?

No, not found a solution. We left our client with a working sort but without the default sorting by customs.customer_name like he asked

### Do you see this as a core feature or an add-on?

core

**Comment by realtebo** [comment]
Temporary workaround:

We published datatablelogic blade

changed

    //aaSorting: [],

into
     aaSorting: [{!! isset($crud->orderColumnPosition) ? "[".$crud->orderColumnPosition.",'asc']" : "" !!}],

Then in the setupList we used

     $this->crud->orderColumnPosition = 3;


were '3' is the index of customers.company_name column

I proposed to add to setters
- setDefaultOrderColumnIndex();

and
- setDefaultOrderColumnDirection();

so to modify 'aaSorting'

**Comment by pxpm** [comment]
Hello @realtebo 

Sorry for the time it took to come back here. It's a complex example and one that's better to address in a "tutorial" perspective. 

So I've setup a similar scenario, I have `Jobs (id, name, customer_id)` and `Customers (id, name)`. 
In JobModel I have the customer relation:
```php
public function customer()
    {
        return $this->belongsTo(Customers::class, 'customer_id');
    }
```

If I understood you correctly, you would like to show the Jobs list, ordered by `customers.name` by default and a secondary order by `job.id` ?  

Let's first get the `queries` straight. 

There are two types of queries in Backpack, first is the **main query** or **crud query**. That's the query that is performed when the table is displayed. The one you configure with `CRUD::addClause()` or `CRUD::addBaseClause()` (if it has any effect on the entry count, not this case). 

The second type is the **table query** or **secondary query** that is applied on top of the **crud query** when you `order/search/filter` the table. 

You could had achieved the desired results by defining the following column in Jobs controller:

```php
    protected function setupListOperation()
    {
        CRUD::addClause(function ($query) {
            return $query
                ->leftJoin('customers', 'customers.id', '=', 'jobs.customer_id')
                ->select(['jobs.*', 'customers.name as customer_name'])
                ->orderBy('customer_name','asc')->orderBy('jobs.id', 'desc');
        });

        CRUD::column('name');
        CRUD::column('customer_name')->orderLogic(function ($query, $column, $columnDirection) {
            return $query->orderBy('customer_name', $columnDirection)->orderBy('jobs.id', 'desc');
        })->orderable(true);
    }
```

![image](https://user-images.githubusercontent.com/7188159/199502701-9109bc5d-dae8-4e80-9dc4-2cece9356ed7.png)

Notice that on purpose I added an additional layer of complexity here by having a `name` column on `jobs` and `customers`. It's something devs easily overlook and then notice they are getting the attribute overwritten in eloquent when not properly aliased (`'customers.name as customer_name'`). (looking myself in the mirror 👀 )

Also another dev note: use the `reset` table button alot when testing this because datatables caches the order etc from table. 

Let me know if I missed your example, I will probably transform this reply in a FAQ section, or a small blog tip. 

Cheers

**Comment by pxpm** [comment]
I am going to close this just because I don't think there is any bug here. 

Maybe we should just make it more clear on the docs how the structure works and the query flow like I explained @realtebo here. 

I'am discussing with @tabacitu how we should do it. 

Cheers

**Comment by realtebo** [comment]
Thanks for tutorial.

Try to do not make it explode having 2 ids to show. 

I've a real situation like this.

**Comment by realtebo** [comment]
A little problem with your solution is that datatable is not showing which column is ordered by default.
