### ISSUE TITLE
find solution to problem of  orderBy with enableAjaxTable

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#471]
I found a solution for problem of order By with enableAjaxTable     (issue #357) ;

for example we have Post Model and we want to sort it in data table by created_at .

first we add "sort" attribute to crud column  :  
```
                               $this->crud->addColumn([
                                    'name' => 'created_at',
                                    'label' => 'created_at',
                                    'type' => 'publish_date',
                                    'sort' => 'desc'
                                ]);
```
next we add this :  

```
@foreach($crud->columns as $key => $column)
    @if(array_key_exists("sort",$column))  
       {!! '"order":'."[[".$key.',"'.$column['sort'].'"]],' !!} @break 
    @endif  
@endforeach

```
to list.blade.php just after    "aaSorting": [] at line 183. 
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/list.blade.php#L183

Ok Its done ! ... 

hope it helped

**Comment by zachweix** [comment]
This is great, but it's a bummer that default Backpack doesn't take care of this (or I guess really the problem is with dataTables)

**Comment by tabacitu** [comment]
Quick update: this has since been fixed. 

Backpack 3.3 comes with all-ajax-tables and reordering out of the box.

Cheers, thanks for reporting this, and the solution @M0H3N .

**Comment by mamarmite** [comment]
I'm facing a kind a like bug in 3.3 and this fix it.
On the first load, the dataTable use the order param, and to make the feature useful I implement the @M0H3N suggestion. 
The only difference is the '$loop->index' instead of the column's name.
```
@foreach($crud->columns as $key => $column)
  @if(array_key_exists("sort", $column))
    {!! '['.$loop->index.',"'.$column['sort'].'"],' !!}
  @endif
@endforeach ],
```
I was trying to implement this by adding `$this->crud->orderBy` or `$this->crud->query->orderBy()`.
In the setup() or in the search(), but the search() function in AjaxTable trait reset all order set from setup to apply the new one set onClick in the view.
