### ISSUE TITLE
[Feature Request] Remove deprecated `\PackageVersions\Versions` call

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/CRUD#4725]
# Feature Request

Replace `\PackageVersions\Versions` with `\Composer\InstalledVersions` in `config/backpack/base.php`.

This does require Composer 2, but I think requiring that now or else on a next major version is quite reasonable, given it has been released more than 2 years ago. This can be made explicit by requiring `"composer-runtime-api": "^2.0"` in `composer.json`.

This also allows removing the deprecated "composer/package-versions-deprecated" dependency.

**Comment by pxpm** [comment]
Totally @jnoordsij it's planned for the next major to remove it, we already decided about it. 

I think we should had done it in v5. We overlooked this, it is what it is. 🤷 

I will be closing this since we already have the PR pending for it here https://github.com/Laravel-Backpack/CRUD/pull/3613, I will just add a note there about `"composer-runtime-api": "^2.0"` in `composer.json` as you mentioned, I think it's a good improvement to explicit require it. 

Thanks for you time and effort 🙏

**Comment by jnoordsij** [comment]
> Totally @jnoordsij it's planned for the next major to remove it, we already decided about it.
> 
> I think we should had done it in v5. We overlooked this, it is what it is. 🤷
> 
> I will be closing this since we already have the PR pending for it here #3613, I will just add a note there about `"composer-runtime-api": "^2.0"` in `composer.json` as you mentioned, I think it's a good improvement to explicit require it.
> 
> Thanks for you time and effort 🙏

Thanks, somehow missed the PR when submitting this. Looks like a perfect solution!
