### ISSUE TITLE
[Bug] extra headers disableResponsiveTable

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/CRUD#4734]
# Bug report

### What I did

Use `$this->crud->disableResponsiveTable(); `

### What I expected to happen

Show all columns with scroll independent of the screen size.

### What happened

When ussing `$this->crud->disableResponsiveTable();`  adds a tag `<thead>` on top and a tag `<tfoot>` on bottom.

Screenshot normal table ResponsiveTable enable
![imagen](https://user-images.githubusercontent.com/20278289/197210537-a234098e-e828-4ff2-ac8d-e91fd73f641d.png)

Screenshot table ResponsiveTable disabled
![imagen](https://user-images.githubusercontent.com/20278289/197210678-0fd7ca8e-662d-4568-a929-e6705b1b6724.png)
![imagen](https://user-images.githubusercontent.com/20278289/197210323-2da4b6b2-9669-40e8-a5f9-3a001c2337fe.png)

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 8.1.5
#### LARAVEL VERSION:
v9.36.4@15ce569fd93124e8e2257c24e3ed85b9ef9951d6
#### BACKPACK VERSION:
5.4.4@6dfaaf36c919be3b2873b66169dbb942df1245d5

**Comment by pxpm** [comment]
Hello @adriallongarriu 

I guess this is an updated application ? I say that because I see on your screenshot that the arrows to order the columns on top of the table also changes when you disable the responsive table, and we fixed that in https://github.com/Laravel-Backpack/CRUD/pull/4490 so probably you should republish backpack assets with `php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag="public" --force` 

If you overrided any files in the `public/packages` folder **make sure you do a backup first** in case anything goes wrong.

As you can see from that PR, there is a pending issue that we are working on about the headers alignment. 

I will be closing this issue, as this particular issue have already been fixed. 

Cheers

**Comment by adriallongarriu** [comment]
Hello @pxpm,

I create a new project and blow last items it seems a bar white in the first column and grey in the follow.
![imagen](https://user-images.githubusercontent.com/20278289/198617250-233af205-9af6-4e5e-95b2-7a401a216c83.png)

I tested and sems to be only on Firefox. On Chrome it show different add and extra space between first and second column.
![imagen](https://user-images.githubusercontent.com/20278289/198650733-d3517328-d73e-40ef-8c58-cbae04c900fa.png)


As it is an option that I do not use much, I leave it as it is for now.
Thank you

**Comment by pxpm** [comment]
@adriallongarriu thanks for getting back here. @promatik is already working on a solution for it. 👍 

Cheers
