### ISSUE TITLE
[Bug] Backpack CRUD preview shows error after composer update.

### ISSUE THREAD

**Issue by Zannatul** [Laravel-Backpack/CRUD#4752]
# Bug report
Backpack CRUD preview shows error after composer update. This is not only one crud preview but also all crud preview.

`array_map(): Argument #2 ($array) must be of type array, null given`

### What I did
I face some problem after my last composer update. I use laravel 9. Before composer update it worked fine but after that it broke. It shows

### What I expected to happen
It should be show preview content.

### What happened
![show error](https://user-images.githubusercontent.com/5654915/198868501-d7d0d15d-1c82-404d-a47c-2616cc76cd3a.png)
![error 2](https://user-images.githubusercontent.com/5654915/198868654-919c6bba-2425-4e12-b9d8-afb82996c0ca.png)

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes, this is still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.3 (cli) (built: Feb 18 2022 20:33:47) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.37.0@0c9675abf6d966e834b2ebeca3319f524e07a330

### BACKPACK VERSION:
5.4.6@39876b312b1ef3d6faebba89a0220a6bed7f870c

**Comment by pxpm** [comment]
Hello @Zannatul thanks for the report 🙏 

I guess you are overriding some files and probably missing some implementation. 

`getViewNamespacesFor` has been deprecated in favor of `ViewNamespaces::getFor`. We aliased it so it was a NON BC, but since the new `show.blade.php` have the updated code https://github.com/Laravel-Backpack/CRUD/blob/39876b312b1ef3d6faebba89a0220a6bed7f870c/src/resources/views/crud/show.blade.php#L64 and in the code you provided you are using the older code (it should work as I said it's aliased here: https://github.com/Laravel-Backpack/CRUD/blob/main/src/app/Library/CrudPanel/Traits/HasViewNamespaces.php ) I guess that you messed up some configuration that lead to that error. 

I am going to close this since I think there is no bug here, but please feel free to continue the discussion providing more info that would help me to track the issue and help you to fix it. 

Cheers

**Comment by Zannatul** [comment]
Hey man, Thanks for your reply. Yah, I solved this by downgrading to  `5.3.6` version. 
Thanks again man.
