### ISSUE TITLE
[Bug] Switch field doesn't support CrudField JS Library

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4766]
# Bug report

### What I did

In our demo, added `switch` to `public/assets/js/monster/field.js` so that we can test it inside [the Field Monster](https://demo.backpackforlaravel.com/admin/field-monster/create).

### What I expected to happen

That the top buttons work, and properly show / hide / disable / enable / require / unrequire / onchange on the `switch` field.

### What happened

They no work.

**Comment by maurohmartinez** [comment]
I tested this and it works locally.
Also, I checked the `js` file in demo project and it doesn't seem to have the `switch` field added.

https://demo.backpackforlaravel.com/assets/js/monster/fields.js
https://github.com/Laravel-Backpack/demo/blob/main/public/assets/js/monster/fields.js

@tabacitu how do we normally edit `fields.js`? My guess is that adding `'switch',` will just do the job.

**Comment by pxpm** [comment]
@maurohmartinez you can submit a PR to demo to include the `switch` field. 
I think it was what @tabacitu did but when clicking the buttons it didn't show/enable/hide etc the field.

If you did the same test and it's working, please submit the PR to the demo to enable the field, otherwise we probably need to fix something. 
In some fields we use events like `CrudField.enable` to do some custom stuff in the fields when they just don't work "out of the box". 

Let me know if there is something I can help you with. 🙏

**Comment by pxpm** [comment]
PR done, tested and ready to merge! 

Closing this! Thanks for raising the issue @tabacitu 🙏
