### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by maxboone** [Laravel-Backpack/CRUD#4772]
# Bug report

### What I did

Generate CRUD Controllers

### What I expected to happen

A happy linter / intelephense not complaining

### What happened

Intelephense complaining about "Non static method 'column' should not be called statically.":

![Screenshot from 2022-11-12 22-59-25](https://user-images.githubusercontent.com/6454510/201496189-fb2f065a-e916-4306-bb02-63d07c1b8256.png)

### What I've already tried to fix it

Call these methods using the `$this->crud` attribute.

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 29 2022 22:29:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.36.2@0bcd350eec1974c9f912f129368587ef7e43722b

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8
```

**Comment by maxboone** [comment]
I see that this is more related to the generation commands, that are hosted (for this instance) in the [Laravel-Backpack/Generators repo](https://github.com/Laravel-Backpack/Generators/blob/main/src/Console/Commands/CrudControllerBackpackCommand.php)

Should I open an issue (and MR) there to replace the `CRUD::` with `$this->crud->`s?

**Comment by pxpm** [comment]
@maxboone I think you need to "help" your IDE to better understand the app ecosystem otherwise it would happen with any Facade you use. 
Since when using `CRUD` we are aliasing it to `CrudPanelFacade` `use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;` and that allow us to call non-static methods statically because missing static calls would the fowarded to the non-static methods. 

As you can see, non-static methods are properly read by IDE when using them statically through the Facade

![image](https://user-images.githubusercontent.com/7188159/201670195-bfe4fc4a-47b7-4c4e-a38b-60937ab6e7fc.png)

Can you make sure you have the properly `use` of the Facade on top of your file ?

I am going to close this as I don't think there is a bug here, atleast in CRUD, please feel free to continue this conversation so that I can help you with. 

Cheers
