### ISSUE TITLE
Class 'Str' not found

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/CRUD#4789]
# Bug report

### What I did

Open users crud

### What happened

Error
Class 'Str' not found (View: \vendor\backpack\crud\src\resources\views\crud\inc\datatables_logic.blade.php)

### What I've already tried to fix it

no

### Is it a bug in the latest version of Backpack?

new version

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.25@b77b908a9426efa41d6286a2ef4c3adbf5398ca1

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

**Comment by pxpm** [comment]
Hey @AlexKomMsk thanks for the report.
That's very odd, that's just Laravel `Str` class that should be available in all Laravel installations.

Can you do: `php artisan tinker` and in the prompt try something like `(string) Str::of('test')->upper()` and check the output ? 

It should be something like this:
![image](https://user-images.githubusercontent.com/7188159/203784053-13758081-f254-4ec7-b35a-b303280c6b24.png)

Cheers

**Comment by AlexKomMsk** [comment]
PHP Error:  Class "Str" not found in D:\laragon\www\storry.rueval()'d code on line 1

**Comment by AlexKomMsk** [comment]
I get:

`PHP Error: Class "Str" not found in D:\laragon\www\storrry.rueval()'d code on line 1`

I use Str in view like this:

`\Illuminate\Support\Str::upper('test')`

Otherwise I will get an error: Class "Str" not found

**Comment by pxpm** [comment]
@AlexKomMsk you shouldn't need to provide the full namespace since `Str` is aliased. 
You can see a list of default aliased classes here: https://github.com/laravel/framework/blob/2641bc172640ec625d84a0e66b0fd6caf112fb2a/src/Illuminate/Support/Facades/Facade.php#L255

If you are still missing them somehow, you can manually add it to your`config/app.php` 
```php
'aliases' => [
        'Arr'       => Illuminate\Support\Arr::class,
        'Str'       => Illuminate\Support\Str::class,
    ],
```
Don't forget to clear config cache after with `php artisan config:clear`
I am going to close this as I don't think there is any Backpack bug here, but rather some misconfiguration on developer side.

Please feel free to continue the discussion if needed and I will try to help you the best I can.

Cheers 🙏
