### ISSUE TITLE
[New Feature] Add native laravel pagination 

### ISSUE THREAD

**Issue by juanem1** [Laravel-Backpack/CRUD#481]
I have a table with 1k rows and I want to use native laravel pagination. 
I don't know if is posible right now? 
Something like:
```
$this->crud->setFromDb()->paginate(15);
```
Pagination docs: https://laravel.com/docs/5.4/pagination
Thanks.

**Comment by tabacitu** [comment]
Hi @juanem1 ,

I think ```$this->crud->enableAjaxTable()``` will help you out. 

Cheers!

**Comment by juanem1** [comment]
Hey, my idea is use the native pagination instead of ajax pagination.

**Comment by tabacitu** [comment]
Ok, reopened it :-)

What would be the benefit of using native pagination instead of ajax pagination?

**Comment by adbmdp** [comment]
Benefit is we don't have all the enableAjaxTable bugs ;-)
https://github.com/Laravel-Backpack/CRUD/issues/411

**Comment by jsiebach** [comment]
@adbmdp this does not avoid the issues occuring with the Ajax table.  When sorting or searching models, any fake columns created would still cause errors, because Laravel couldn't sort or query a column that wasn't in the DB.  You'd still have to load all of the models every time, and in fact I think the existing method of paginating is far better since you can navigate pages without reloading, and Laravel would have to load the models anyway.

This would still be a new feature but I think AJAX would be the preferred method of doing for any use case I can think of.

**Comment by cdarken** [comment]
@jsiebach Can you recommend a simple method of returning to a certain page when editing a record, then? Because I need that in an app I'm building.

**Comment by jsiebach** [comment]
Sure - using the DataTables JS documentation, if you pass along a parameter to the constructor called `displayStart`, the pagination will start there.  So if you want to start with item 100, you could use the URL http://example.dev/admin/model?displayStart=100

Then edit your `list.blade.php` file like so (3 new lines close to the end):

          @if ($crud->ajaxTable())
          "processing": true,
          "serverSide": true,
          "ajax": {
              "url": "{{ url($crud->route.'/search').'?'.Request::getQueryString() }}",
              "type": "POST"
          },
              @if(Request::has('displayStart'))
              "displayStart": <?php echo intval(Request::get('displayStart')) ?>
              @endif
          @endif

**Comment by cdarken** [comment]
Thanks. Now to propagate those pages to the edit view :)

**Comment by lloy0076** [comment]
I believe this issue has run its course.
