### ISSUE TITLE
Roles not showing in Roles Grid and throwing the Error.

### ISSUE THREAD

**Issue by mikdanjey** [Laravel-Backpack/CRUD#4816]
# Bug report

### What happened

Roles not showing in Roles Grid and throwing the Error. Please check the attached screenshot. 

![Screenshot 2022-12-05 181023](https://user-images.githubusercontent.com/17296759/205639565-216701bf-724d-4c37-a62e-536fad56410c.png)

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.42.2@607d7867c93706eae20e28e46679f8a66e2a23ec

### BACKPACK VERSION:
5.4.10@050b288caf2f60c79313f2b0b7d4fefd25177f3f

**Comment by pxpm** [comment]
Hello @mikdanjey thanks for the report. 

We already merged the fix for it, we will tag a new version later this evening with some additional fixes. 

You can check the release draft here: https://github.com/Laravel-Backpack/CRUD/releases/tag/untagged-3a70596c3dc83da70a8f

When that version is tagged, that bug will be fixed, so in a few hours a `composer update backpack/crud` will pull the fix for you. 

Going to close this, wish you all the best 🎅

**Comment by mikdanjey** [comment]
Thanks for fixed this in your side. I understood not released so far.

FYI, I can't see your tag link:
https://github.com/Laravel-Backpack/CRUD/releases/tag/untagged-3a70596c3dc83da70a8f

**Comment by pxpm** [comment]
What you mean you can't see the tag link ? Does the release link I provided don't work for you ? Maybe because it's not released it's only accessible to maintainers? Sorry I didn't know about that. 😞

Here is a screenshot of it: 
![image](https://user-images.githubusercontent.com/7188159/205643389-b1bcb75a-7d18-4911-af14-30dd61b9ad24.png)

It will be released in a few hours, if you subscribe to repository notifications you will be notified when we do it 👍 

Let me know if I can help you with something else, cheers!

**Comment by mikdanjey** [comment]
Great Thanks, Looks fine. I got it this draft version.

Closing this bug :)
