### ISSUE TITLE
[Bug] digitallyHappy 0.4.1 brokes theme

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4831]
# Bug report

### What I did

I need to customize theme, like all the time

Now when I recompile the theme I see something broken, like bad '3 dots' in datable, for example

### What I've already tried to fix it

Manually blocked digitallyHappy/backstrap to version 0.4.0

You can see that in this package, from 0.40 to 0.41 the 'custom' folder is missing

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.8 (cli) (built: Jul  5 2022 23:04:29) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.42.2@607d7867c93706eae20e28e46679f8a66e2a23ec

### BACKPACK VERSION:
5.4.11@ffbadcdb6478822646600b2cd763490caa927155

**Comment by pxpm** [comment]
Hey @realtebo Backpack CRUD has the Backstrap package locked at 0.4.0 too https://github.com/Laravel-Backpack/CRUD/blob/68b067d46fb77004baf06e3b7e5cdd51505ffc6f/package.json#L25

We don't recommend to upgrade at this moment as we are aware of some issues in that repository. We will be probably be deprecating that repository in the next version following this PR https://github.com/Laravel-Backpack/CRUD/pull/4815

Thanks for the report, and sorry for the bad experience. 

I will be closing this and probably submitting a PR to CRUD to effectively lock the version. 

Wish you the best 🎅

**Comment by realtebo** [comment]
why close an issue still valid? "I close because we know and soon we will fix it'" why ?

last week we started 3 new projects, and we have same issue in each project. 

someone could end up here so knowing that is actually 'live' as known problem is better, imho.

**Comment by pxpm** [comment]
Hello @realtebo I closed because I created the PR to fix it (not to fix, just to lock the versions in `packages.json`) so users don't get broken versions. 

It's the way I organize myself, when I create the PR for the issue, I close the issue. Not saying it's the best way, but have been working for me. 

I will re-open per your request until we merge the fix. 

Cheers

**Comment by tabacitu** [comment]
@realtebo unfortunately there is nothing much we can do at this point. 0.4.0 was released and we can't un-release it. We are at 0.5.1 right now, and it's working fine. We haven't pushed any breaking changes between those two versions, only bumped versions. So 0.5.1 should be working ok for you (the latest).

Since 0.4.0 was [released 2 years ago](https://www.npmjs.com/package/@digitallyhappy/backstrap?activeTab=versions), I'm going to close this issue without fixing, sorry. I'm closing Pedro's PR too - https://github.com/Laravel-Backpack/CRUD/pull/4833/files - because installing particular versions... is not a good fix here, it would lock people into old versions.

Sorry for the mess we caused here, and for taking so much time to close this. The good news is... we've created a whole new system in v6, that makes creating themes (even custom ones) sooooo much easier. You'll love it.

Cheers!
