### ISSUE TITLE
[Bug] select2_ajax filter and select2_from_ajax field pagination not working AGAIN

### ISSUE THREAD

**Issue by kartomantas** [Laravel-Backpack/CRUD#4837]
Same bug on as here:

https://github.com/Laravel-Backpack/CRUD/issues/4464

on new backpack version: 5.4.10

It was fixed but now the issue is there again.

**Comment by pxpm** [comment]
Hello @kartomantas . Thanks for the report. 

It's not exactly the same bug, but we should have spotted it while working on that PR. 😞 Sorry for the bad experience. 

I've already submitted the PR to PRO to fix it, should be merged by next Monday in the next release 🤞

The problem was the fact that the filter was parsing the retrieved options in a different way than `select2_from_ajax` or `fetch` fields, in the previous PR only a portion of the issue in the filter file was fixed. 😢 

I think I've now fixed it for good, 😅 

I will leave this open until we merge the PR with the fix. 

Once again, thanks 🙏

**Comment by kartomantas** [comment]
> Hello @kartomantas . Thanks for the report.
> 
> It's not exactly the same bug, but we should have spotted it while working on that PR. 😞 Sorry for the bad experience.
> 
> I've already submitted the PR to PRO to fix it, should be merged by next Monday in the next release 🤞
> 
> The problem was the fact that the filter was parsing the retrieved options in a different way than `select2_from_ajax` or `fetch` fields, in the previous PR only a portion of the issue in the filter file was fixed. 😢
> 
> I think I've now fixed it for good, 😅
> 
> I will leave this open until we merge the PR with the fix.
> 
> Once again, thanks 🙏

Is it already merged?

**Comment by pxpm** [comment]
@kartomantas not merged yet, is pending revirew. It should be merged during this next week. 

I will close this issue when we merge the fix in PRO repository, so you will get notified 👍 

Wish you the best 🎅

**Comment by pxpm** [comment]
The fix had been merged in PRO 1.6.4 released just a few minutes ago. 

It should take a bit for our repositories to pick the change and you will be able to get the fix with a `composer update backpack/pro`

Thanks again for raising the issue 🙏
