### ISSUE TITLE
[Bug] Unable to sort by relationship count in list

### ISSUE THREAD

**Issue by de-raaf-media** [Laravel-Backpack/CRUD#4838]
# Bug report

### What I did

add a relationship count column

```
        CRUD::addColumn([
            "name" => "airports", // name of relationship method in the model
            "type" => "relationship_count",
            "label" => "Airports",
            "orderable" => true,
        ]);
```

### What I expected to happen

If I click on the header relations with highest count will appear on top of the list

### What happened

I am not sure. It is sorting something but not the number of relations. The relationship count does seem to work. "3 items" is shown where a country has indeed three airports.

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.12 (cli) (built: Oct 30 2022 12:55:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.15@bf8fbdd9061611b2c05562fa14f6987cc5145d78

### BACKPACK VERSION:
4.1.69@248e2e034cedcffe01732cdce01fb3d1ecad9ffa

**Comment by pxpm** [comment]
Hey @de-raaf-media thanks for the report. 

To have the order working on that type or column you need to provide a custom `orderLogic`. 

I've submitted an example to the docs too so that other people looking for it can find it. 

In you case, something like this should work:

```
CRUD::addColumn([
            "name" => "airports", // name of relationship method in the model
            "type" => "relationship_count",
            "label" => "Airports",
            "orderable" => true,
            "orderLogic" => function ($query, $column, $columnDirection) {
                $query->orderBy('airports_count', $columnDirection);
            },
        ]);
```
I will be closing this as I don't think there is any bug in Backpack in that regard. 

Once again thanks for the report, it was a great opportunity to improve our docs. 

Wish you the best 🎅

**Comment by de-raaf-media** [comment]
Hi @pxpm, thank you for the example and great to see this is documented now!

**Comment by de-raaf-media** [comment]
This worked for me after I added $this->crud->query->withCount("airports") right before I add the column.
