### ISSUE TITLE
select2_from_ajax and select2_from_ajax_multiple not filling current values

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#491]
I added those field types to a form and i realised that they do not display what is allready saved in the database (i don't know how to do that yet). can anyone fix that?

**Comment by pxpm** [comment]
Your question is toooooo damn vague and difficult to replicate.

Could you please post the code you used to add those fields to the form, and what they are showing instead of what you want?

I think your problem relies on field definition, but without looking at it, it would be dificult to say.

Thanks

**Comment by adbmdp** [comment]
I think i have the same issue: https://github.com/Laravel-Backpack/CRUD/issues/446

**Comment by adbmdp** [comment]
@AurelDragut did you managed to get it work?

**Comment by AurelDragut** [comment]
No, not yet. I have other priorities at the moment, but i will get back to it when i am done with those priorities.

**Comment by Muhammadinaam** [comment]
Please solve this issue

**Comment by tabacitu** [comment]
Hi guys,

Just pushed an update on the ```dev``` branch - I've upgraded all select2 fields to the latest select2.js. That update also fixes this issue, I believe. If you can please test&confirm, that would be great. If not, you'll have access to these modifs next week, when they'll be on the ```master``` branch.

Cheers!
