### ISSUE TITLE
[Bug] Phone Number Getting Cut Off

### ISSUE THREAD

**Issue by zachweix** [Laravel-Backpack/CRUD#4948]
# Bug report

### What I did

Saved a phone number that started with 1800 (specifically (+18005882300)

### What I expected to happen

When I edit, the entire number should show up

### What happened

Only the last 2 digits show up

### What I've already tried to fix it

It's a bug in the library. When I test on the live demo when editing a monster, it shows up there. Notably, this seems to have only happened with 1800 numbers so far

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 5.4.16

**Comment by zachweix** [comment]
I do apologize, I am clearly working on not enough sleep. I realize now what it was asking when you ask what I've already tried. I tried commenting out different lines in the field blade, but it looks to be related to the library itself and that JavaScript is above my tired understanding...

**Comment by tabacitu** [comment]
Hey @zachweix ,

Thanks for letting us know. I can confirm the bug exists for US numbers. Debugging right now. Until this is solved, you can get around it by disabling the geoIP functionality. So please add this config to your field:

```php
CRUD::field('phone')->config(['initialCountry' => false]);
```

I'll be back.
Cheers!

**Comment by zachweix** [comment]
This is still not 100% working. On line 77 we are now always switching to us. If initialCountry is false we shouldn't be trying to set the country. I set the number with another country, but it switched it to USA.

**Comment by tabacitu** [comment]
@zachweix regarding your 1800 numbers problem, turns out... that wasn't caused by GeoIP. So even after the fix above... or even after the "fix to the fix" in https://github.com/Laravel-Backpack/PRO/pull/137... **you'll still have the problem.** 

Turns out you were right in your first evaluation, even if tired 😅 Indeed the JS Library itself has a bug with displaying 1800 numbers. So please bring it up with them, so they fix it upstream. 

Until they fix it, is it possible for you to use `'separateDialCode' => false`? It seems to alleviate the problem in my tests. 

Normal US phone numbers will look good:
<img width="411" alt="CleanShot 2023-03-06 at 13 27 59@2x" src="https://user-images.githubusercontent.com/1032474/223097984-ec489a71-8de4-49f2-936c-341539d2e263.png">

While 1800 phone numbers would look... not as good... but at least readable:
<img width="416" alt="CleanShot 2023-03-06 at 13 27 50@2x" src="https://user-images.githubusercontent.com/1032474/223097921-2f32e7ec-4f6f-40c7-b88c-fdca477b1396.png">
