### ISSUE TITLE
[Bug] Phone Number always gets US country code

### ISSUE THREAD

**Issue by zachweix** [Laravel-Backpack/CRUD#4950]
If you look at https://github.com/Laravel-Backpack/CRUD/issues/4948:

This is still not 100% working. On line 77 we are now always switching to us. If initialCountry is false we shouldn't be trying to set the country. I set the number with another country, but it switched it to USA.

**Comment by GregaUNK** [comment]
Same here. Its fine one creation, but problematic on edit. It does select either your current country or USA... But not the one from DB record.

**Comment by tabacitu** [comment]
Ouch! You're right guys, trying to fix a bug I introduced another one 😅🤦‍♂️ I've just fixed that in a PR (https://github.com/Laravel-Backpack/PRO/pull/137), it's currently waiting for review. I expect it'll be merged in 1-2 days, we'll follow up as soon as it's launched and ready for you guys to use.

Heads-up @zachweix I've replied to https://github.com/Laravel-Backpack/CRUD/issues/4948, please see my suggestion there.

**Comment by CamusMX7** [comment]
I don't know if I should open another issue, but in the documentation: "https://github.com/jackocnr/intl-tel-input" it says: "If you leave initialCountry blank, it will default to the first country in the list. "

`'config' => [
                //'onlyCountries' => ['mx', 'us'],
                'preferredCountries' => ["mx", "us"],
                'initialCountry' => '',
                'separateDialCode' => true,
                'nationalMode' => true,
                'autoHideDialCode' => false,
                'placeholderNumberType' => 'MOBILE',
            ],`

I have tried to put "mx" by default having all the countries available, but I have not been able to achieve it. It seems a bug.
Because it always puts US by default.
@tabacitu should i open an issue?

thanks

**Comment by tabacitu** [comment]
Yes please 🙏
