### ISSUE TITLE
How to add the multilingue to PageManager ?

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#501]
Hello,

I learned how to use the translatables models thanks to the documentation of the site of [site of Backpack](https://laravel-backpack.readme.io/docs/advanced-features#section-translatable-models-and-multi-language-cruds). But to add it to my pages in PageManager, how do I do it? It says that you should edit the template file, but that of PageManager is in Vendor. It's bad ?

thank you very much

**Comment by Jimmylet** [comment]
Hello, do you have a response to me? thank you !

**Comment by AbbyJanke** [comment]
Hi Jimmy,

So editing the files within the `vendor` folder isnt really all that helpful mostly because the vendor files are generally not included when you upload to a website (assuming you are using git to push/pull to your live website). That folder gets ignored via the default `.gitignore` file.

Right now it looks like the PageManager isn't translatable as all the text is hard coded into the specific files within the vendor folder. If you are comfortable with making the changes and submitting a pull request to the [PageManager repo](https://github.com/Laravel-Backpack/PageManager). If not if you can go ahead and send the translations for your preferred language here I can go about doing it when I get a chance and submit one.

**Comment by justijndepover** [comment]
You should have a file `config/backpack/pagemanager.php`. Here you can overwrite which controller / model you want to use.

So if you want to make your `Page` model multilingual change the class that is used by packpack here.

I'm doing the same in my own project and i just copied the code from the `Page` model inside the `vendor` folder and pasted it my new model. Then i made the changes and everything works as expected.

But now i'm struggling with my frontend. When i want to fetch my page based on the given slug I get an sql error. 

This is my setup in my `PageController`

```php
public function index($slug)
{
    $page = Page::findBySlug($slug);
    ...
}
```

**Comment by lloy0076** [comment]
If the discussion still needs to continue, please reopen.

**Comment by tabacitu** [comment]
On this:

Unfortunately Backpack itself won’t create any new packages - I’m afraid we already have more than we have resources to maintain.

I would _love_ to see a ```TranslatablePageManager```, as a fork of ```PageManager```. If someone makes it happen, let me know, I’d love to promote it among Backpack developers. That way people could use ```PageManager``` or ```TranslatablePageManager```, depending on their needs.

**Comment by Dakaa** [comment]
@tabacitu Is Backpack still being developed i.e. Backpack 3? I wish the doc has more examples including how to create your own package.

**Comment by tabacitu** [comment]
@Dakaa yes, of course, 3.5 is our current version, just launched it last week. True - there's no guide in how to create your own package for Backpack... I'll made a note to write one. Until then, you can use [this guide](https://medium.com/@tabacitu/creating-laravel-5-packages-for-dummies-ec6a4ded2e93) which is not Backpack-specific, but for all types of Laravel packages. I know the author - he's a great guy ;-)
