### ISSUE TITLE
[Feature Request] Allow hiding the button texts, so that buttons only show icons

### ISSUE THREAD

**Issue by K-Mazur** [Laravel-Backpack/CRUD#5010]
# Feature Request

### What's the feature you think Backpack should have?

I'm not sure if there's a proper way for doing that (if there is, please let me know). One of my clients wanted to have just icons, instead of icons + copy for the list operation, just in **one** model. I tried to use the modifyButton method like this:

```
$this->crud->modifyButton( 'show', [
    'content' => '<i class="la la-eye"></i>',
] );
$this->crud->modifyButton( 'update', [
    'content' => '<i class="la la-edit"></i>',
] );
$this->crud->modifyButton( 'delete', [
    'content' => '<i class="la la-trash"></i>',
] );
```
but that didn't work as I expected.
The show button was still showing `<i class="la la-eye"></i> {{ trans('backpack::crud.preview') }}` etc.

### Have you already implemented a prototype solution, for your own project?

In my project I've copied the `show.blade.php`, `update.blade.php` and, `delete.blade.php` files to `vendor/backpack/crud/buttons` directory. And then modified those, like for example:

```
<a href="{{ url($crud->route.'/'.$entry->getKey().'/show') }}" class="btn btn-sm btn-link">
    @if($button->content !== 'crud::buttons.show')
        {!! $button->content !!}
    @else
        <i class="la la-eye"></i> {{ trans('backpack::crud.preview') }}
    @endif
</a>
```
instead of:
```
<a href="{{ url($crud->route.'/'.$entry->getKey().'/show') }}" class="btn btn-sm btn-link"><i class="la la-eye"></i> {{ trans('backpack::crud.preview') }}</a>
```
for the show button, etc.

I'm not sure if that's the best way to do that. If there's a better solution, please let me know. Otherwise, I can submit a PR.

### Do you see this as a core feature or an add-on?

core feature

**Comment by pxpm** [comment]
Hello @K-Mazur thanks for raising that question. 

In your case the `modifyButton()` wouldn't work with straight html because the `type` of those buttons retrieve the `$content` from the view file, so to modify it you need to change the view files.

There is no issue in publishing those buttons and changing them accordingly, I would add to rename them too after publishing in your resources folder, that way you would be able to keep the "default backpack buttons", and your "custom buttons". 

So instead of changing the content to be html, you will provide your custom button view by doing in your `setupListOperation`: 

```php
CRUD::modifyButton('show', ['content' => 'crud::buttons.your_custom_button']);
```

I agree this is overkill, and we could/should probably do something to ease that out. 

Either create those properties on the button `showLabel => true`, `icon => 'la la-smt'` so that you can configure "per button" if label is shown or not. 

Or create a global operation setting `lineButtonsWithLabels` or similar that would show/hide the labels from all buttons. Similar to what we did to the action buttons as drop down. 

What do you think @tabacitu ?

Cheers

**Comment by tabacitu** [comment]
I'm sorry guys, I don't agree showing the icon alone is a good idea. I've done that a few times in admin panels, and every time both I and the admins have found it too obscure. Especially for custom operations... the icon isn't necessarily representative of what it will do. So I don't agree with this as a built-in feature, sorry.

The [feature we just launched that compresses buttons into a dropdown](https://backpackforlaravel.com/docs/5.x/crud-operation-list-entries#buttons-1) seems like a much better solution to me.

Again... I don't agree with making this an official feature... That extra conditional would pollute all buttons, all for a feature we do NOT recommend people use. 

Howeveeeeer. I do agree with making it _easier_ for people who need this to do it themselves. And I think there's an easier way to do that... in a clean and non-breaking manner:
- we wrap the button texts in a `<span>`;
- we make sure those `span`s are easy to target... then for a developer to hide all button texts on the list page it's as easy as adding a CSS rule to a file;

Would that work ok for everyone?

**Comment by K-Mazur** [comment]
Hi @tabacitu, sure. The span button (maybe with some class name?) would work and be easy and straightforward enough.

**Comment by pxpm** [comment]
I am cleaning up old issues, I've moved the proposed solution to a PR in #5343 

Let's keep any relevant conversation about this topic over there.

Closing this, thanks for the suggestion @K-Mazur 🙏
