### ISSUE TITLE
[Bug] Error 500 The relationship field does not support MorphTo at the moment on Backpack v5

### ISSUE THREAD

**Issue by guillorrr** [Laravel-Backpack/CRUD#5050]
# Bug report

### What I did

I have a n-1 polymorphic relationship between "SuccessCriteria" and "KeyResult" or "KeyAction". 

```
class SuccessCriteriaCrudController extends CrudController
{

    protected function setupCreateOperation()
    {

        CRUD::field('criterionable')
            ->label('For')
            ->addMorphOption(KeyResult::class, 'Key Result', ['attribute' => 'title'])
            ->addMorphOption(KeyAction::class, 'Key Action', ['attribute' => 'title'])
            ->morphTypeField(['wrapper' => ['class' => 'form-group col-md-4']])
            ->morphIdField(['wrapper' => ['class' => 'form-group col-md-8']]);
    }
}
```

```
class SuccessCriteria extends Model
{
    public function criterionable()
    {
        return $this->morphTo();
    }
}

```
```
class KeyResult extends Model
{
    public function successCriteria()
    {
        return $this->morphMany(SuccessCriteria::class, 'criterionable');
    }
}
```

```
class KeyAction extends Model
{
    public function successCriteria()
    {
        return $this->morphMany(SuccessCriteria::class, 'criterionable');
    }
}
```

### What I expected to happen

I used the field same as pet-shop/comment/create on demo.

### What happened

500
It's not you, it's me.
The relationship field does not support MorphTo at the moment, nobody asked for it yet. If you do, please let us know here - https://github.com/Laravel-Backpack/CRUD/issues

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes, the same. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.5 (cli) (built: Apr 14 2023 04:27:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.52.6@16454f17a2585c4589f721655fc5133270aadf8c

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v4.0.2
backpack/crud: 5.6.0
backpack/devtools: 1.0.31
backpack/editable-columns: 2.1.4
backpack/filemanager: 2.0.1
backpack/generators: 3.3.16
backpack/logmanager: v4.0.10
backpack/permissionmanager: 6.0.16
backpack/pro: 1.2.2
backpack/revise-operation: 1.0.12
backpack/settings: 3.0.16

**Comment by promatik** [comment]
Hi @guillorrr!

One year ago backpack had a huge improvement on relationship field, supporting almost every type of relationship, but `MorphedByMany` relationship was left a side because it was to complex, it required us to create an interface that allows you to select entries from multiple models.

Thank you for letting us know that you stumble on this 👌
The bad news is this feature will probably take some time to be available, do to its complexity. But I'll let @tabacitu decide on that, and maybe the master of the relationship field @pxpm to step in here.

**Comment by pxpm** [comment]
I think you may be using an outdated version of backpack/pro. It seems what you want to achieve is already working in Backpack.

`morphTo` support was added in 1.3 https://github.com/Laravel-Backpack/PRO/releases/tag/1.3.0

Cheers

**Comment by guillorrr** [comment]
Hi @pxpm ! Okay, it's a bit confusing. You are right, I have an old version of Backpack PRO.
But I was using the official documentation and in it, the Repeater field allows you to use polymorphic relationships in v5, which is what I have: [https://backpackforlaravel.com/docs/5.x/crud-fields#relationship-pro](https://backpackforlaravel.com/docs/5.x/crud-fields#relationship-pro) Perhaps it would be necessary to add in those fields, from which version of Backpack PRO they work or accept certain characteristics.
For these and other details, it is that I was sending emails with @tabacitu

Thank you all

**Comment by pxpm** [comment]
Hello @guillorrr 

I don't think  we can be adding the version constrains on every feature in docs. That will get messy really quick.  Unless is something that completely breaks from the past (we will be mentioning `v6` in some places in the next version, to clearly differentiate what is available in v5/v6). 

But as a general rule of thumb there is no need to add minor version bumps in docs. 
But **maybe** for `pro` features there is that need because the software license may have expired and they can't go past the current version they have.

In this case @guillorrr pro license could have expired and he was able to get updates for 1 year up to 1.2. He's now not able to update past 1.2 without buying a new license, so even if it wasn't a major version release (was just 1.3, a minor without BC's)

@karandatwani92 can you take this up ? Please:

- Create a list of the likely most important features we added in PRO, like this one, maps, telephone etc and map them with the released version. 
- Update the docs of those features with the minimum required version. 

Something like: 
![image](https://user-images.githubusercontent.com/7188159/235875942-ae0f25ad-c873-41de-b070-279f5b26075d.png)

Cheers

**Comment by guillorrr** [comment]
It is exactly what you say @pxpm! What's more, I also think it could be an improvement to update the error messages. In my case, before writing this issue, I did the recommended steps and one was to run 'compose update backpack/crud', so if there were new messages that identify these requirements, it would be easier for the developer too.

Obrigado!

**Comment by tabacitu** [comment]
> @karandatwani92 can you take this up? Please:
> - Create a list of the likely most important features we added in PRO, like this one, maps, telephone etc and map them with the released version.
> - Update the docs of those features with the minimum required version.

Excellent idea Pedro! 👏👏👏 I think that's all we need to do at this moment. And I think we only need to do that in v5 docs. Starting with v6, we'll be requiring PRO v2, which has all of them.

**Comment by karandatwani92** [comment]
@pxpm @tabacitu Opps! I missed the notification. Sorry for the delay, I take it from here

**Comment by tabacitu** [comment]
Since we're launching v6 on Friday, that will become the current version. And it will have all these features.

Instead of going back to v5 and seeing WHEN we introduced a feature, and saying that in the docs... let's just make sure we remember this problem, and when we add a new feature mid-version, write that in the feature docs.
