### ISSUE TITLE
[Bug] Two different json fields cannot have the same fake fields inside (fake fields with the same name)

### ISSUE THREAD

**Issue by skpr-repo** [Laravel-Backpack/CRUD#5073]
# Bug report

### What I did

I have a table "orders" with two different json fields, one named "billing_address" and one named "shipping_address".

I want to use them to store informations about user address, with fake fields inside.

Both shipping and billing have fake fields with the same name, like "address", "zip_code", "phone", and so on.

I followed the instructions and added $fakeColumns inside model, then crud fields inside the crud controller.

But since the fields have the same name, the last group of fields (shipping) overwrites the first one (billing).

### What I expected to happen

Since fake fields are inside different json fields, I would expect them to show and work together, even if they have the same name.

### What I've already tried to fix it

Changing the field names and not using the same names works as expected.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes, I just updated everything

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 10 2022 12:22:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.7@675ea868fe36b18c8303e954aac540e6b1caa677

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.0
backpack/devtools: 1.3.5
backpack/editable-columns: 2.1.4
backpack/filemanager: 2.0.1
backpack/generators: 3.3.16
backpack/logmanager: v4.0.10
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.4
backpack/revise-operation: 1.0.12
backpack/settings: 3.0.16

**Comment by skpr-repo** [comment]
Hi!

[
    'name'    => 'street',
    'type'    => 'text',
    'label'   => 'Indirizzo',
    'fake'     => true,
    'store_in' => 'billing_data',
],

and

[
    'name'    => 'street',
    'type'    => 'text',
    'label'   => 'Indirizzo',
    'fake'     => true,
    'store_in' => 'shipping_data',
],

// Inside the Order model, json fields defined as arrays ...
protected $casts = [
    ...,
    'billing_data' => 'array',
    'shipping_data' => 'array',
];

// ... and fake columns
protected $fakeColumns = [
    'billing_data',
    'shipping_data',
];

**Comment by tabacitu** [comment]
Ah... yes, it's like I expected. Unfortunately, this isn't a Backpack bug, as much as it is an HTML problem. When you add a **field** with the name `street`... Backpack will add an **input** with the name `street`. And here's the HTML problem: if you include multiple inputs _with the same name_ in an HTML form... then _only the last input will be sent_. In general, in Backpack and any other form builder... **you can't add multiple fields with the same name**. So you can't add multiple fields with the same name, unfortunately.

But let's find another solution to your problem. You want to have:
- `billing_data.street`
- `shipping_data.street`

The best solution I have for you... is to use [the `repeatable` field](https://backpackforlaravel.com/docs/5.x/crud-fields#repeatable-pro). So you can have:
- `billing_data` as a repeatable field, that includes the subfields `street` etc.
- `shipping_data`  as a repeatable field, that includes the subfields `street` etc.

But there will be a few problems:
1) the admin would be able to add multiple billing_addresses and shipping_addresses - you can fix that by specifying `'max_rows' => 1` on your repeatable fields;
2) the data in the database will be an array of arrays (not a simple array) - you can fix that by catching the data before it gets saved/gotten from the database using Laravel's [accessors and mutators](https://laravel.com/docs/10.x/eloquent-mutators#accessors-and-mutators), in order to turn that multi-level array into a single-level array; or better yet you can use [model events](https://backpackforlaravel.com/docs/5.x/release-notes#use-model-events-inside-crudcontrollers) inside your field, for the same goal; 

So your field definition would look something like this:

```php
[   // repeatable
    'name'  => 'billing_data',
    'label' => 'Billing Data',
    'type'  => 'repeatable',
    'subfields' => [
        [
            'name'    => 'street',
            'type'    => 'text',
            'label'   => 'Street',
            'wrapper' => ['class' => 'form-group col-md-4'],
        ],
        [
            'name'    => 'address',
            'type'    => 'text',
            'label'   => 'Address',
            'wrapper' => ['class' => 'form-group col-md-4'],
        ],
            'name'    => 'zip_code',
            'type'    => 'text',
            'label'   => 'ZIP Code',
            'wrapper' => ['class' => 'form-group col-md-4'],
        ],
    ],
    'init_rows' => 1, // number of empty rows to be initialized, by default 1
    'min_rows' => 1, // minimum rows allowed, when reached the "delete" buttons will be hidden
    'max_rows' => 1, // maximum rows allowed, when reached the "new item" button will be hidden
    'events' => [
        'retrieved' => function ($entry) {
            $entry->billing_data = $entry->billing_data[0];
        },
        'saving' => function ($entry) {
            $entry->billing_data = [json_encode($entry->billing_data, true)];
        },
    ],
]
```

The above is just pseudocode, you might want to tinker with it to match your use case.

Hope it helps.
Cheers!

**Comment by skpr-repo** [comment]
Thank you very much, it's a good workaround.
It would be worth writing it in the docs.
Cheers!
