### ISSUE TITLE
[V6][Bug] Getting error "No hint path defined for [backpack]."

### ISSUE THREAD

**Issue by munjaldevelopment** [Laravel-Backpack/CRUD#5095]
# Bug report

### What I did

Created new CRUD & added 'denyAccess'

### What I expected to happen

403 error display

### What happened

Getting error "No hint path defined for [backpack]."

### What I've already tried to fix it

Search on google & checked Code Stack Trace

### Is it a bug in the latest version of Backpack?

Yes 

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun  7 2022 21:45:53) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies
    with Xdebug v3.1.6, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.13.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v4.0.2
backpack/basset: 0.15.0
backpack/crud: v6.x-dev
backpack/editable-columns: 2.1.4
backpack/filemanager: 2.0.1
backpack/generators: v6.x-dev
backpack/logmanager: v4.0.10
backpack/menucrud: v3.0.1
backpack/newscrud: 4.0.9
backpack/pagemanager: 3.0.12
backpack/permissionmanager: v6.x-dev
backpack/pro: v6.x-dev
backpack/revise-operation: 1.0.12
backpack/settings: 3.0.16
backpack/theme-coreuiv2: dev-main
backpack/theme-coreuiv4: dev-main
backpack/theme-tabler: dev-main

Code sample:

`$is_admin = backpack_user()->hasRole('Super Admin');`
`if($is_admin) {`
`}`
`else`
`{`
   `$this->crud->denyAccess('list');`
`}`

Error Screenshot

![image](https://github.com/Laravel-Backpack/CRUD/assets/14837352/d893bb62-68aa-4562-9668-0ade71644190)

**Comment by munjaldevelopment** [comment]
Hi team, any update?

**Comment by pxpm** [comment]
Hey @munjaldevelopment thanks for the report. 

I will ping @maurohmartinez or @tabacitu here. I think it will be easier for them have a look at this, since they worked on this bit of the views. 

@tabacitu if Mauro and/or you can't and want me to have a look please re-assign me. 

Cheers

**Comment by munjaldevelopment** [comment]
Hi @pxpm , `I think I got this error too sometime, but can't recall when/where.` This error usually appear on 403 or 500 error appear on backpack..

**Comment by tabacitu** [comment]
Hmm... I remember getting this error when I installed `backpack/theme-tabler` without having `backpack/crud` v6 installed. Can't determine anything more without an error stack. @munjaldevelopment if you keep getting this error please use Flare to share the error stack here - works better than screenshot.

**Comment by munjaldevelopment** [comment]
please use Flare to share the error stack here - works better than screenshot.

@tabacitu Can you please tell me where to get Flare.

**Comment by munjaldevelopment** [comment]
Thanks for the clarification, @pxpm 

Here you go:

https://flareapp.io/share/o7ApQJEP#F80

**Comment by pxpm** [comment]
I think I found where the error started, but @tabacitu is the one that probably knows the answer to this https://github.com/Laravel-Backpack/CRUD/commit/6d25299abf10241dd9840ff6a51eaf0ae2134d86

The error is from this line: https://github.com/Laravel-Backpack/CRUD/blob/550df50be3d59c1a4cca75513cd86e82d4445991/src/resources/error_views/layout.blade.php#LL1C1-L1C1
when it tries to get the deleted `backpack::` namespace. 

Also for you @tabacitu in the BackpackServiceProvider change I mentioned, another change you did was hardcoding theme-tabler, are you sure about that change ? 

Do you happen to know how to fix this the error or should I investigate further? 

Cheers

**Comment by tabacitu** [comment]
Todo: quick fix now. Let's 
- [ ] change the namespace in the error layout blade file, from `backpack::` to `backpack.ui::` 
- [ ] add it to the upgrade guide

**Comment by pxpm** [comment]
I don't think we can get way with the "simple" solution me and Cristian talked before. 

So we use two layouts for the errors pages:

1 - `top_left` for logged in users, has sidebar, topbar etc, so that your admin can still navigate the app if he get a 404 on a resource or access denied to some operation. 
2 - `plain` for non-logged user where there is no "admin ui" (sidebar, topbar etc), it's just a little bit prettier error page.

We can't "hardcode" the layout names, because we don't know what layouts the theme has.

So since we know the requirements, **one layout for logged users and one layout for non-logged users**, and we know that for **logged in users we want to use the chosen "theme layout"**, that we can get with `backpack_theme_config('layout')`, we can create the `ui\errors\guest_errors.blade.php` that themes can overwrite for styling. 

So in the end it would load the selected layout for the logged in users errors, and use the `guest_errors.blade.php` for non authenticated, either from theme if present, otherwise the unstyled from ui.

Let me know what you think.

**Comment by tabacitu** [comment]
Todo: let's do a POC with BackpackException - see if it can render itself.

**Comment by tabacitu** [comment]
This is getting fixed in https://github.com/Laravel-Backpack/CRUD/pull/5125 so let's continue the conversation there, if needed.
