### ISSUE TITLE
[Bug] Optional Packages are not installable on V6 

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5107]
#### Backpack Optional Packages are currently not installable on V6 using the guide.
https://backpackforlaravel.com/docs/6.x/install-optionals

**Comment by miquelangeld** [comment]
Hi I had the same problem few days ago because a weird problem with the site [repo.](https://repo.backpackforlaravel.com) which banned my ip address. But now I  be able to install any package with V6. I have a test project with language manager, permissions manager, devtools, pro, and editable columns. Maybe is the same

**Comment by tabacitu** [comment]
During beta, to install any first-party Backpack add-on, please require the v6 branch on that addon. That provides support for Backpack v6. For example:

```bash
composer require backpack/permission-manager:"v6.x-dev"
```
