### ISSUE TITLE
[V6][Feature Request] Need Date filter on Dashboard to filter current stats

### ISSUE THREAD

**Issue by munjaldevelopment** [Laravel-Backpack/CRUD#5124]
# Feature Request

### What's the feature you think Backpack should have?

Need Date filter on Dashboard to filter current stats so that if someone choose date filter, dashboard data get updated.

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Add-on

**Comment by munjaldevelopment** [comment]
Hi Team,

I have started working on this from my own & developed like below:

![image](https://github.com/Laravel-Backpack/CRUD/assets/14837352/1addf4fb-d1b2-42b5-84b9-f850caa89373)

Please share your valuable feedback.

**Comment by pxpm** [comment]
Hey @munjaldevelopment I've needed something similar myself in the past, but I added the "filter" only on the widget card that I needed. 

From what it seems you took a "general" approach, so that when you select a date it is applied to all widgets on page ? 

We need to revamp the widgets a little bit. We plan to do it using Livewire v3 (launching next month 20th). 

It will make the "dynamic" parts easier to write and maintain. 

This looks good, is something we could take into consideration if you want to create a "integrated dashboard". Good job and thanks for sharing. 

Anything that stood out to you as "hacky" to implement or was it straightforward ? 

Cheers

**Comment by munjaldevelopment** [comment]
Hi @pxpm,

I have created new `widget` for filter which looks like:

`Widget::add(['type'        => 'filter', 'name'        => 'admin_filter', 'wrapperClass'=> 'shadow-xs', 'filter_type' => 'admin',
             'filter_content_type' => [
                [
                    'name' => 'date_from_to',
                    'key' => 'date_from_to',
                    'type' => 'date_range',
                    'label' => 'Date range'
                ],
                [
                    'name' => 'valuation_status',
                    'key' => 'valuation_status',
                    'type' => 'select2',
                    'label' => 'Valuation Status',
                    'values' => ['0' => 'New', '1' => 'Draft', '2' => 'Submitted', '3' => 'Evaluated']
                ],
                [
                    'name' => 'vendor_name',
                    'key' => 'vendor_name',
                    'type' => 'select2_vendor',
                    'label' => 'Vendor Name',
                    'values' => \App\Models\Vendor::pluck('vendor_name', 'id')->toArray()
                ]
             ]
         ])->to('before_content')->makeFirst();`

Here is my Filter widget code:

`@php
  $date_from_to = $valuation_status = $vendor_name = $vendor_manager ='';

  if (request()->has('date_from_to')) {
  	$date_from_to = request()->date_from_to;
  }

  if (request()->has('valuation_status')) {
  	$valuation_status = request()->valuation_status;
  }

  if (request()->has('vendor_name')) {
  	$vendor_name = request()->vendor_name;
  }
   if (request()->has('vendor_manager')) {
  	$vendor_manager = request()->vendor_manager;
  }

  $widget['wrapper']['class'] = $widget['wrapper']['class'] ?? $widget['wrapperClass'] ?? 'col-sm-6 col-md-4';
@endphp

@includeWhen(!empty($widget['wrapper']), backpack_view('widgets.inc.wrapper_start'))
	<div class="{{ $widget['class'] ?? 'card' }}">
    	@if($widget['filter_type'] == "admin")
    	<div class="card-body">
    		<nav class="navbar navbar-expand-lg navbar-filters mb-0 py-0 shadow-none">
    			<div class="collapse navbar-collapse" id="bp-filters-navbar">
		    		<ul class="nav navbar-nav">

                        @if(is_array($widget['filter_content_type']))
                            @foreach($widget['filter_content_type'] as $content_type)
                                @if($content_type['type'] == "date_range")
                                    @include('backpack.pro::filters.date_range_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'currentValue' => $date_from_to ])
                                @elseif($content_type['type'] == "select2")
                                    @include('backpack.pro::filters.select2_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'values' => $content_type['values'], 'currentValue' => $valuation_status  ])
                                @elseif($content_type['type'] == "select2_vendor")
                                    @include('backpack.pro::filters.select2_vendor_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'values' => $content_type['values'], 'currentValue' => $vendor_name ])
                                @endif
                            @endforeach
                       @endif
		    		</ul>
		    	</div>
	    	</nav>
    	</div>
        @elseif($widget['filter_type'] == "vendor")
        <div class="card-body">
            <nav class="navbar navbar-expand-lg navbar-filters mb-0 py-0 shadow-none">
                <div class="collapse navbar-collapse" id="bp-filters-navbar">
                    <ul class="nav navbar-nav">

                        @if(is_array($widget['filter_content_type']))
                            @foreach($widget['filter_content_type'] as $content_type)
                                @if($content_type['type'] == "date_range")
                                    @include('backpack.pro::filters.date_range_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'currentValue' => $date_from_to ])
                                @elseif($content_type['type'] == "select2")
                                    @include('backpack.pro::filters.select2_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'values' => $content_type['values'], 'currentValue' => $valuation_status  ])
                                @elseif($content_type['type'] == "select2_vendor")
                                    @include('backpack.pro::filters.select2_vendor_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'values' => $content_type['values'], 'currentValue' => $vendor_name ])
                                @elseif($content_type['type'] == "select2_vendor_manager")
                                    @include('backpack.pro::filters.select2_vendor_manager_dashboard', [ 'name' => $content_type['name'], 'key' => $content_type['key'], 'label' => $content_type['label'], 'values' => $content_type['values'], 'currentValue' => $vendor_manager ])
                                @endif
                            @endforeach
                       @endif
                    </ul>
                </div>
            </nav>
        </div>
    	@endif
  </div>
@includeWhen(!empty($widget['wrapper']), backpack_view('widgets.inc.wrapper_end'))`

Let me know if you need any assistance any explanation on above.

Cheers..

**Comment by munjaldevelopment** [comment]
Hi @pxpm 

Yes, I made it specific as per my requirement. But, yes we can make it generic as per Backpack CRUD operation (We can plan to create filters same like CRUD filters also) so that developer can call like `$this->crud->addDashboardFilter` (just a thought).

Feel free to connect me if you need more lights on this.

Cheers...

**Comment by tabacitu** [comment]
Hey @munjaldevelopment ,

Thanks for the feature request - and the code. Will definitely help someone looking to do the same thing. I was going to suggest the exact same thing - creating a `widget` for it 😉

I don't think this is something Backpack can help with. Dashboards are very _very_ custom things. And you don't only want a way to show the datepicker... you also want the page to respond to it, and all dashboard elements to get recalculated.

And then... what happens if some Dashboard elements DO NOT need to get recalculated? Like if they're "lifetime" indicators? Or "current" indicators"? Or "totals"? They would need to be placed separately so it doesn't look like they get recalculated.

What I'm saying is... we could try to help with this... but we'd do a bad job at it. Dashboards are just too custom for us to be able to help. The most we can do is provide a general widget with a `date_range_picker`. That we can do. But that part isn't the difficult one, all the other wiring is. And we can't help with that, because it's too custom. 

So **I'm going to say "pass" at this one. It would become a Large task, while the time we reduce for the developer is minimal**. We could re-visit this in the future, after we create LiveComponents. That could change the decision.

Cheers!
