### ISSUE TITLE
[Bug] Localization incomplete or not working as expected

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#5205]
# Bug report

### What I did

In the file `config/app.php` I changed 

    'locale' => 'it',

and 

    'fallback_locale' => 'en',

### What I expected to happen

I expected both UI and validation messages where translated into italian

### What happened

UI are translated but all of validation messages are not translated.
In the following images, login button and remember me checkbox are translated.
But validation errors no !

![image](https://github.com/Laravel-Backpack/CRUD/assets/1268699/2bd7cfd9-9ab7-40f4-85d3-8ae3b67841de)

### What I've already tried to fix it

Actually, nothing ...

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.2.8 (cli) (built: Jul  4 2023 15:53:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.15.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.4
backpack/generators: v4.0.0
backpack/pro: 2.0.6
backpack/theme-tabler: 1.0.2
```

**Comment by tabacitu** [comment]
Hi @realtebo ,

Actually the translations strings for validation aren't provided by Backpack. They are provided by Laravel. And the reason they are still in English is because... most likely you don't have a `resources/lang/it/validation.php` file.

There's [a project that specializes in providing all must-have translations for Laravel](https://laravel-lang.com/), one of them is validation. So if your project are in Italian, this package is a must-have for you.

I believe the only thing you need to do is:
```php
composer require --dev laravel-lang/common
php artisan lang:add it
```

After that my validation messages have been translated in Italian:

<img width="1492" alt="CleanShot 2023-07-12 at 15 10 50@2x" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/fd3585d6-8571-47ad-a0f1-7e2e31c3b5d3">

But I recommend you follow their docs https://laravel-lang.com/installation/

Hope it helps.
Cheers!

**Comment by realtebo** [comment]
thanks, Added italian as usual.  I was aware of this but  a lot of coworkers still googles to understand why not :)

I simply suggest now to add a paragraph to explain this in the documentation?
