### ISSUE TITLE
Remember-me option not working after update to version 6 

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/CRUD#5216]
# Bug report

### What I did

After upgrading a project from version 5 to version 6 the **Remember Me** option doesn't  appear to be working at all.

### What I expected to happen

That after checking the **Remember Me** option upon login, a new login would not be required for an extended period (not sure what this period exactly was with version 5).

### What happened

After a few hours (haven't timed this) I need to login again.

### What I've already tried to fix it

Added this `remember `setting to `auth.php` config file as suggested in many places:
```php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
            'remember' => 43800, // Set remember me duration here (minutes)
        ],
    ],
```

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.3 (cli) (built: Feb 14 2023 16:58:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.15.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.0.0
backpack/crud: 6.0.5
backpack/devtools: 2.0.2
backpack/editable-columns: 3.0.1
backpack/filemanager: 3.0.2
backpack/generators: v4.0.0
backpack/logmanager: v5.0.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.7
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.1.3
backpack/theme-coreuiv4: 1.0.3
backpack/theme-tabler: 1.0.4

**Comment by malle-pietje** [comment]
@phpfour thanks for checking. Odd thing is I don't see the remember me cookie being created at all. These are the cookies related to the FQDN:
![image](https://github.com/Laravel-Backpack/CRUD/assets/12016131/77cd9997-0737-4d60-9554-bbd59bfff69a)

I do see the cookie on a 5.X project that is running off the same development server:
![image](https://github.com/Laravel-Backpack/CRUD/assets/12016131/79c5009f-9b54-43c1-af3f-149774caf636)

Could it be I need to rebuild the JS assets?

**Comment by malle-pietje** [comment]
I also checked and the `remember_token` column in the `users` table is being updated every time the user logs out of the app.

**Comment by tabacitu** [comment]
Sorry for the delay @malle-pietje - seem like we dropped the ball on this one. 

I just tested this in our demo and... I can confirm it's happening in our demo. That is because we have an overriden blade file for Tabler Theme's login page. And the login form didn't have the `name` on the remember input. I've added it here https://github.com/Laravel-Backpack/demo/commit/1fe97c2dc2a2d199292afc9e0064b92563ddb892 and now it's all working again:
- the `remember_backpack_xxx` cookie is being added;
- the value of `remember_token` is being set on the `users` db table, for that user;
- after changing the `lifetime` in `config/session.php` to 1min, I can confirm I'm still logged in;

So while I did find a bug... I'm pretty sure it doesn't apply to you... If you're still having this issue, here are a few ideas:

1. Please check that you haven't overriden the login form blade file. If so, make sure you have the `remember` input (with a name).
2. From your [comment here](https://github.com/Laravel-Backpack/CRUD/issues/5216#issuecomment-1642021509)
 I see your cookie in v5 is called `remember_web` not `remember_backpack`. So I assume you're using the `web` guard instead of Backpack's? What other customizations do you have in your login/auth process? The problem might be generated in those customizations.
3. "_Could it be I need to rebuild the JS assets?_" No, I don't think the JS has anything to do with it.
4. "_I also checked and the remember_token column in the users table is being updated every time the user logs out of the app._" yes that's fine. If someone logs out, it's ok for the hash to change.
5. Please try a `composer update`.

I'm afraid there's not much more I can do here... If you're still having this problem, AFAIK it's working in Backpack, so it must be something in your project preventing it from working. Take a look at the above please (especially 1 and 5) 🤷‍♂️

Sorry I can't be of more help.
Cheers!
