### ISSUE TITLE
V6 multilevel menu items

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#5268]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/614

<div type='discussions-op-text'>

<sup>Originally posted by **froid24** August  4, 2023</sup>
Hi guys,

I saw a lot of talk about having multiple levels for the menu in previous versions (where a submenu option can have a submenu of its own). Where can I find an example of how it is done in V6 (Tabler)?

Also, at some point menu options not having any suboptions were automatically hidden. is this not the case anymore? Because that was really nice.

Thank you!</div>

**Comment by pxpm** [comment]
@karandatwani92 investigated and Tabler support multi-level menu, unfortunately our menu components don't.

**Comment by tabacitu** [comment]
I would love to have this too ❤️ Not sure how we can implement it though. And if we do... is it a Tabler feature only or should we add it to ALL themes? Food for thought.

**Comment by tabacitu** [comment]
Thanks for the investigation @karandatwani92 . So then:
- this is NOT a bug fix, this is a feature
- this is NOT a Small (1 day) task, it's most likely become Medium (1 week) or even 2x M
- this is still a SHOULD, I agree

This is a cool feature we could launch this week if @pxpm has the time. Otherwise we can do it next month too. We're not in a rush since Antonio is already working on a feature this month, the activity-log package. 

@pxpm do you agree with the above?

**Comment by tabacitu** [comment]
Happy to say this is DONE thanks to Pedro. You only need to define `nested="true"` on you sub-dropdowns in 6.2+ 😉

https://backpackforlaravel.com/docs/6.x/base-components#menu-dropdown-menu-dropdown-item
