### ISSUE TITLE
[Bug]  It collides with 'HasTranslations' and NodeTrait

### ISSUE THREAD

**Issue by azenot-dev** [Laravel-Backpack/CRUD#5312]
# Bug report

### What I did

I use use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations; and Kalnoy\Nestedset\NodeTrait,

### What I expected to happen

No errors

### What happened

Trait method 'create' will not be applied because it collides with 'HasTranslations'

### What I've already tried to fix it

I don't understand, how to fix it

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

backpack/basset: 1.1.1
backpack/crud: 6.1.11
backpack/generators: v4.0.2
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/theme-tabler: 1.0.11

**Comment by promatik** [comment]
Hi @azenot-dev!

Trait collisions are rare, when it happens usually you can just do;

```php
class Example
{
	use ExampleTrait {
		exampleMethod as traitExampleMethod;
	}
```

And then use `traitExampleMethod` as you wish.

The issue here is that the methods that are colliding, are used internally, not by your code directly.

So both of the packages you are using `SpatieTranslatable\HasTranslations` and `Nestedset\NodeTrait` modify the model create method.

By what I can see here; https://github.com/lazychaser/laravel-nestedset/blob/v6/src/NodeTrait.php#L754C7-L754C7, both methods do a `$model = new static();`.
You can only do it once, so one solution might be to call `createNodeTrait` first, and then call the `update` of `HasTranslations`.

```php
class Example
{
    use HasTranslations, NodeTrait {
        NodeTrait::create insteadof HasTranslations;
        NodeTrait::create as createNodeTrait;
    }

    public static function create(array $attributes = [])
    {
        $entry = self::createNodeTrait($attributes); // This will create from the NodeTrait
        $entry->update($attributes); // this will call HasTranslations update
    }
```

Not tested, but something like this might work 👌

**Comment by promatik** [comment]
Anyway @azenot-dev, there isn't anything we can do on package level to solve this, we can't change the method name, I'll open a discussion to prevent issues like this, but since it's a breaking change, it will only be available to push it at the next major version, it will take some time.

Raised https://github.com/Laravel-Backpack/community-forum/issues/670 for it 👌
