### ISSUE TITLE
[Feature Request] Remote database connection gives error on Backpack Admin

### ISSUE THREAD

**Issue by munjaldevelopment** [Laravel-Backpack/CRUD#5368]
# Feature Request

### What's the feature you think Backpack should have?

?? Remote database connection working with Laravel Backpack

### Have you already implemented a prototype solution, for your own project?

?? Yes, I tried that but it's showing database schema error.

### Do you see this as a core feature or an add-on?

?? add-on.

**Comment by tabacitu** [comment]
Hey @munjaldevelopment ,

Not sure I understand the feature request here. Backpack doesn't do anything special about connection with Databases, local or remote. It just plugs into Eloquent. If you DB connection is properly set up, and your Laravel app works with it... so should Backpack, because it uses the same DB connection. So if you're seeing DB schema errors, it's probably not Backpack who is the problem, but your DB connection setup.

Hope it helps.

**Comment by munjaldevelopment** [comment]
Hi @tabacitu 
I am getting "Schema" error from backpack/setting `SettingsServiceProvider.php` on this line `if (!\App::runningInConsole() && Schema::hasTable(config('backpack.settings.table_name'))) {`

let me know if this helps.
