### ISSUE TITLE
[Feature Request] 'table' layout instead of 'repeatable' inside 'relationship' field

### ISSUE THREAD

**Issue by JoepdeJong** [Laravel-Backpack/CRUD#5374]
# Feature Request

### What's the feature you think Backpack should have?
I am working with a relationship field (Backpack PRO). This field depends on a 'repeatable' field. However, this repeatable field always repeats all the labels of the lines and takes a lot of space (See picture). It would be nice to use the 'table' layout instead. I tried switching to the table layout, but the table layout does not support the subfields in a proper way.
<img width="954" alt="Screenshot 2023-11-19 at 13 25 23" src="https://github.com/Laravel-Backpack/CRUD/assets/7187634/353351a7-3f1b-48c5-b1ac-f3fd2e35dd6f">

Is there a way to use the table layout inside 'relationships', or more in general: to use the table layout for one to many relationships but also allow different subfields like select2?

If its not possible, maybe I can implement it myself. But just checking, before I put a lot of effort in this.

### Have you already implemented a prototype solution, for your own project?
-

**Comment by jorgetwgroup** [comment]
Hello @JoepdeJong 

Thank you for sending us your requirement here, however, we do not have plans for this year to work on this, we have achieved a stable version of Backpack and our focus is now on the themes. Working with relationships in the table field will not be something very simple and we do not have it in our scope for now, however, stay tuned, since every month we launch new functionalities, and perhaps some of them can supply the features you are requesting.

Cheers.
