### ISSUE TITLE
after_scripts not yielded when using form_content (edit, create)

### ISSUE THREAD

**Issue by ockam** [Laravel-Backpack/CRUD#541]
The blade files for create and edit have an `after_scripts` section block that never gets rendered because they both includes `form_content`which also yield the `after_scripts` section...

This make the crud js files useless.

`form_content` should probably push to a stack.

**Comment by tabacitu** [comment]
Hi @ockam ,

You're totally right, thanks for reporting this. Just pushed a fix on the dev branch - https://github.com/Laravel-Backpack/CRUD/commit/10a3872566c4b22b6d2e343b655b3d11c44892ac. It will be available with a ```composer update``` in the next patch release, later this week.

If you're in a hurry, you can create these modified files in your ```vendor/backpack/crud/``` folder, and Backpack will pick them up instead of the ones in the package.

Cheers!
