### ISSUE TITLE
Accessing a model relationship from the CrudController

### ISSUE THREAD

**Issue by baj84** [Laravel-Backpack/CRUD#544]
I have a Study model defined with a relationship:
public function objects() { return $this->hasMany('App\Models\Object'); }

In my StudyCrudController i'm unable to access the objects with:
$this->crud->model->objects

But if I do a $tmp = Study::find($id), then this will work:
$tmp->objects 

How can I make the relationships load automatically?

Thanks

**Comment by tabacitu** [comment]
Hi @baj84 ,

Hmm... You can't do that in ```StudyCrudController::setup()``` but you CAN do it inside methods where you already have an instance of your object, like ```StudyCrudController::edit()```. Try ```$this->crud->entry->objects``` or ```$this->data['entry']->objects```. 

You can't do it not because of Backpack, but because of OOP. You can't access the something's relationships, if you don't know what that something is. In programming terms, your relationships will never be static methods, because you can never call them without having instantiated the object.

Hope it helps. You'll find more help for this on StackOverflow, using the ```laravel``` tag.

Cheers!

**Comment by baj84** [comment]
Thanks for the quick reply 👍
