### ISSUE TITLE
[4.0][Refactoring] CRUD allowAccess setting is misleading

### ISSUE THREAD

**Issue by ockam** [Laravel-Backpack/CRUD#547]
The way I initially understood it (before diving into the code) was that allowAccess would simply set the permission, not add to a default set.

Currently, allowAccess adds the passed permission array to CrudPanel default access ('list', 'create', 'update', 'delete').

So there should be 2 methods: addAccess (with the current behavior) and allowAccess, which would replace default permission.

Or a least, explain the behavior in the doc/boilerplate.

**Comment by lloy0076** [comment]
@tabacitu - maybe make the doc change - I don't know if this needs to stay open though.

**Comment by tabacitu** [comment]
Hi @ockam ,

I think your way of looking at it makes a lot of sense. It's difficult to see the design errors when you're the one that designed it, so thanks a lot for your suggestion. 

Frankly, I think calling it "access" might have been the real source of confusion. You _add_ access, _remove_ access, _allow_ access, but what _is_ "access"? And how is it different from "permissions", if you have those too? I've seen a lot of first-timers get confused by this.

If we are to rework this part, I say we do it right, and rename it entirely (backwards-compatible, of course). What do you guys think about instead of calling it ```access```, calling it ```enabledFeatures``` or something like that? Wouldn't that be easier to comprehend? The benefits I see:
- we already use the notion of "enable" and "disable" features in some places (details_row, reorder, etc);
- everybody knows what enabled/disabled means, so we basically eliminate a notion we don't _need_ (access); 

Here's what I have in mind:
```diff
// ------ ACCESS
-$this->crud->allowAccess('list');
+$this->crud->enable('list');
-$this->crud->allowAccess(['list', 'create', 'delete']);
+$this->crud->enable(['list', 'create', 'delete']);
-$this->crud->denyAccess('list');
+$this->crud->disable('list');
-$this->crud->denyAccess(['list', 'create', 'delete']);
+$this->crud->disable(['list', 'create', 'delete']);

-$this->crud->hasAccess('add'); // returns true/false
+$this->crud->isEnabled('add'); // returns true/false
-$this->crud->hasAccessOrFail('add'); // throws 403 error
+$this->crud->isEnabledOrFail('add'); // throws 403 error
-$this->crud->hasAccessToAll(['create', 'update']); // returns true/false
+$this->crud->areAllEnabled(['create', 'update']); // returns true/false
-$this->crud->hasAccessToAny(['create', 'update']); // returns true/false
+$this->crud->anyAreEnabled(['create', 'update']); // returns true/false
```

We could also use the ```$crud->enabled``` array to store if other smaller features are enabled. They're all _features_, after all. So:

```diff
// ------ REORDER
-$this->crud->enableReorder('label_name', MAX_TREE_LEVEL);
+$this->crud->enable('reorder', MAX_TREE_LEVEL);
+$this->crud->reorder->setLabel('label_name');
+$this->crud->reorder->setMaxDepth(3);

-// NOTE: you also need to do allow access to the right users: $this->crud->allowAccess('reorder');
+// NOTE: you would NOT need to allow access separately

-$this->crud->disableReorder();
+$this->crud->disable('reorder');

-$this->crud->isReorderEnabled(); // return true/false
+$this->crud->isEnabled('reorder'); // return true/false

// ------ DETAILS ROW
-$this->crud->enableDetailsRow();
+$this->crud->enable('details_row');
-// NOTE: you also need to do allow access to the right users: $this->crud->allowAccess('details_row');
+// NOTE: you would NOT need to do allow access separately

// NOTE: you also need to do overwrite the showDetailsRow($id) method in your EntityCrudController to show whatever you'd like in the details row OR overwrite the views/backpack/crud/details_row.blade.php

-$this->crud->disableDetailsRow();
+$this->crud->disable('details_row');


// ------ REVISIONS
// You also need to use \Venturecraft\Revisionable\RevisionableTrait;
// Please check out: https://laravel-backpack.readme.io/docs/crud#revisions
-$this->crud->allowAccess('revisions');
+$this->crud->enable('revisions');

// ------ DATATABLE EXPORT BUTTONS
// Show export to PDF, CSV, XLS and Print buttons on the table view.
// Does not work well with AJAX datatables.
-$this->crud->enableExportButtons();
+$this->crud->enable('export_buttons');
```

Behind the scenes, ```enable('some_text')``` could:
- call the ```enableSomeText()``` method if it exists;
- add ```some_text``` to the ```$enabledFeatures``` property if not;

So that we also keep the posibility for each feature to do extra things upon enabling/disabling them, and keep it OOP.

This single way of enabling/disabling features would also allow us to have one method to enable multiple features. Something like:
```php
$this->crud->enable(['revisions', 'reorder', 'details_row', 'export_buttons']);
$this->crud->disable(['create', 'delete']);
```

What do you think? Would this refactoring solve problems and eliminate the confusion? Or would it just add to it?

Thanks, cheers!

**Comment by tabacitu** [comment]
PS. @ockam nice job on the Razor, all my friends love it ;-)

**Comment by ockam** [comment]
I really like your proposition. Makes more sense to me.

**Comment by tabacitu** [comment]
@Laravel-Backpack/veterans ? What do you guys think? Like/dislike?

**Comment by indra1** [comment]
@tabacitu I don't really mind the current way, but it does sound nice to have it he way you proposed

**Comment by eduardoarandah** [comment]
Yes, easier to read.

Following code would need no explanation:

``` 
$this->crud->enable(['read']);

if($user->hasRole('manager') && $this->someConditionHere()){
    $this->crud->enable(['edit']);
}
```

**Comment by lloy0076** [comment]
This is just confusing but it's not a **bug** and I'm closing it again.

**Comment by tabacitu** [comment]
Opening it so we don't forget :-) I think this would be a good feature for v4.

**Comment by tabacitu** [comment]
**Update:** Since we've added a Settings API in PR #1997 , and cleaned up CrudPanel in #1942 : 
- There are no longer any defaults in Access; Zero access by default, until you use an Operation on a CrudController (```use OperationTrait```); then, that operation will do ```allowAccess()``` for you;
- Access has been moved inside ```CrudPanel::settings``` (instead of ```CrudPanel::access```;
- Access is no longer stored as an array, but as a sub-property of an operation; 

Here's a dump of ```$crud->settings()```:
![Screenshot 2019-09-02 at 11 03 53](https://user-images.githubusercontent.com/1032474/64099477-10015780-cd72-11e9-97a1-0b365359bd89.png)

There is no ```$crud->access``` array any more. Access is stored as a setting for each operation (ex: ```'list.access' => true```).

I think this approach solves the initial confusion:
1) Developers will no longer need to do ```allowAccess('reorder')```; The operation itself will be doing that ([example here](https://github.com/Laravel-Backpack/CRUD/blob/v4/src/app/Http/Controllers/Operations/ReorderOperation.php#L37));
2) Developers would only use ```denyAccess()``` on operations, so ```denyAccess('reorder')``` which I think isn't confusing;

Any further confusion can be solved by better docs. At this point, renaming Access to Enabled would just make it harder to upgrade to v4, I think. Of course, I may be wrong, let me know if you think this is the case, and we can re-open the issue.

Thanks everybody for the ideas & feedback.
Cheers!
