### ISSUE TITLE
[Bug] [Feature] Improve error message when table has not been migrated

### ISSUE THREAD

**Issue by Kasparsu** [Laravel-Backpack/CRUD#5528]
# Bug report

### What I did

Open newly created crud while forgetting to migrate the table it was generated on

### What I expected to happen

Nice error message telling me that hey we did not find table this crud was generated for maybe you forgot to migrate

### What happened

nondescript and super unhelpful stacktrace
![image](https://github.com/Laravel-Backpack/CRUD/assets/3220262/844fa69b-d87b-4bf4-8694-f8e66db324ed)

### What I've already tried to fix it

Migrated the table. 

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
### PHP VERSION:
8.2.4

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, xmlreader, xmlwriter, curl, fileinfo, mbstring, Phar, pdo_mysql, pdo_sqlite

### LARAVEL VERSION:
11.9.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.4
backpack/crud: 6.7.14
backpack/generators: v4.0.5
backpack/theme-tabler: 1.2.10

**Comment by Kasparsu** [comment]
Seems this is a bug after all. Nice Backpack exceptions are giving this nondescript error because laravel 11.x is not happy about how routes are registered by Backpack.

**Comment by Kasparsu** [comment]
And it seems to be that Exceptions not rendering correctly was laravel issue 
https://github.com/laravel/framework/pull/51614

**Comment by pxpm** [comment]
Thanks @Kasparsu for the report and for gathering all the info 🙏 

I started reading your issue report without noticing your further replies and I was thinking to myself that this should be an issue in Laravel, we don't do any magic tricks to the exception, since it's from an "ajax call", the search endpoint, we render it nicely in an iframe, or the error would be hidden in the browser network tab and not visible for the developer.

Nice find about the Laravel issue. 🙏

I will keep this open until Laravel releases the fixed version. 

Thanks again! 🙏

**Comment by Kasparsu** [comment]
[Laravel 11.9.2](https://github.com/laravel/framework/tree/v11.9.2) has been released including the fix mentioned above making this issue solved. Closing
