### ISSUE TITLE
[Bug] Stop checking if the column has all the necessary attributes on construct

### ISSUE THREAD

**Issue by susanu** [Laravel-Backpack/CRUD#5579]
# Bug report

### What happened

Recently i had some issues with the database where queries to database ```information_schema``` were taking around 10 seconds each.
The admin panel was loading super slow because of this and looking at the code i've noticed that the problem is i am configuring my columns using fluent syntax.
So, something like this ```CRUD::column('product');``` would cause the CRUD to call this function ```makeSureColumnHasNeededAttributes``` 3 times and only the first time it actually does something.
Also, if the crud guesses the column to be one type but you on the controller you set it to something else, the configuration for the guessed type will remain.

### Is it a bug in the latest version of Backpack?

Well, this happened in backpack v5 but i'm pretty sure this also happen in v6 because it's the same behavior and code.

I propose to remove the ```makeSureColumnHasNeededAttributes``` calls from the ```CrudColumn``` class and move them somewhere in a new function called ```getColumns()``` and call this function in ```List``` and ```Show``` operations.

NOTE: I think this also applies to fields.

Cheers.

**Comment by pxpm** [comment]
Hey @susanu thanks for the report. 

You are totally right about the 3 calls to `makeSureColumnHasNeededAttributes`, that was due to a poor design decision but easily fixable. Actually I've already submitted the PR for that here: https://github.com/Laravel-Backpack/CRUD/pull/5581

I really doubt that making some function calls that "do nothing" makes any app (considerably) slower, like you said only the first call would do some actual work, the others would just return early because the attribute was already set on the first call. 
From my benchmarks those calls are very very inexpensive, not more than a `if () { }` and rarely noticeable, in 20 fields would be 40 additional calls, but I still couldn't measure any significant impact, much less like you noticed 10s. 
 
I also tested the scenario of `CRUD::column('my_column')->type('my_type')` the type of the column will be what you define and not the backpack defaults. 
![image](https://github.com/user-attachments/assets/920b9416-6044-424c-a9f1-1deaaac57910)

Some stuff have been improved from v5 to v6, so it's possible this was one of the things that were fixed. 

If you want to try the other PR branch to see if it solves your issue, you can change your `composer.json` to:
```diff
- "backpack/crud": "^6.7",
+ "backpack/crud": "dev-avoid-repetitive-calls-when-constructing-the-object as 6.7.99",
```

I will do some more testing and ask someone to give it a test too before merging it. Let me know your results if you happen to give it a try. 

I will close this issue, let's continue the conversation in the PR if needed. 

Cheers
