### ISSUE TITLE
[Bug] - no hint path defined backpack with livewire v3  

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#5599]
# Bug report

### What I did

I've updated on Laravel 10 Livewire 3 and Backpack 6 (was 5 before)

### What I expected to happen

I have no hint path defined laravel when I include full page components with Livewire 3

### What happened

I have this error : I have no hint path defined for backpack

### What I've already tried to fix it

Try to override the theme config

How can I do to fix this error. :
I include full page component like this : 
```
return view('quote::livewire.quote-data-table', [
            'results' => $results, 'countStatuses' => $countStatuses
        ])->extends('backpack::layouts.top_left')->section('content');
```

**Comment by tabacitu** [comment]
Hi @t-prod ,

Here are a few ideas:

1. Are you sure you've followed all steps in the upgrade guide? For example I see [quite a few previous issues](https://github.com/search?q=org%3ALaravel-Backpack+no+hint+path+defined&type=issues) where Pedro replied they should delete the `errors` views directory - could that be your problem too? https://github.com/Laravel-Backpack/FileManager/issues/41#issuecomment-1666853342

2. "_No hint path defined_" is a very general error. Any chance you can provide a link to the error using Ignition/Flare? So that we can look at the error stack?

Cheers!

**Comment by tabacitu** [comment]
Hey @t-prod - I'm going to assume the above will fix your issue too and close the issue - let us know if that's not the case. But I'm pretty sure it's an upgrade step being skipped, so I'll close it. Cheers!
