### ISSUE TITLE
AddField before/after seems to not be working properly

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#567]
Hi,

Tested to add field with the before/after parameters but it seems it's not interpreted correctly - or I did not understood the doc:

![2017-03-22 001322](https://cloud.githubusercontent.com/assets/26375917/24208394/1afcf13a-0f56-11e7-8b44-46658dbd3f43.png)
![2017-03-22 001323](https://cloud.githubusercontent.com/assets/26375917/24208393/1aeac956-0f56-11e7-91cd-e014f25cf636.png)

**Comment by OwenMelbz** [comment]
Quick question, are you using the `setFromDBAuto` thing?

**Comment by MickaelTH** [comment]
@OwenMelbz No, as discussed in the lobby, I tested without $this->crud->setFromDb(); forgot to gave this info int the issue report sorry. That is why it is either a weird behavior or wrong coding from my part.

**Comment by tabacitu** [comment]
Does this PR fix it for you?
https://github.com/Laravel-Backpack/CRUD/pull/472

**Comment by MickaelTH** [comment]
This may be related, bu it is for COLUMN and I reported the issue for FIELDS. This can be the same root cause but I was enable to apply the path to src/PanelTraits/Fields.php as the code is quite different.

**Comment by tabacitu** [comment]
Hi @MickaelTH ,

Fixed! Finally. Turns out it was because of ```setFromDb()``` after all. ```setFromDb()``` used strings as keys for the ```columns``` array, ```addColumn()``` used integers. It's a wonder this hasn't produced more bugs until now.

Anyway, it's now fixed on the ```dev``` branch. After a few more people test it and confirm it's working, we'll merge it to ```master```. If you want to use the fix yourself, please use the ```dev``` branch in your project. If you find anything - say so. If you don't, say so :-)

Cheers!

**Comment by MickaelTH** [comment]
@tabacitu Ok this one can be closed. Thank you again for resolving it!
