### ISSUE TITLE
[Feature] IP field type

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#568]
Hi,

Not really issue but enhancement.

Laravel, at least using 5.4 that I am using now, has option to create column in db in 'ip' format. When using CRUD to edit/add this field no option for the type is available:

https://laravel-backpack.readme.io/docs/crud-fields

This may create some conflict if someone insert wrong format or display a whoops screen because format is incorrect.

**Comment by MarcosBL** [comment]
Could be useful to have one of those; in the meantime I suppose a `text` type and a custom IP validation in the model would do as well

**Comment by MickaelTH** [comment]
Correct, right now using text field + rules validations.

**Comment by OwenMelbz** [comment]
Just to throw it out there, are you talking IPv4 or 6?

**Comment by MickaelTH** [comment]
Well the "ip" type from Laravel is valid for both, otherwise we need to specify type "ipv4" or "ipv6".

https://laravel.com/docs/5.4/validation#rule-ip

I suppose that Backpack should do the same?

**Comment by tabacitu** [comment]
Hi guys,

An "IP" field type would be a nice feature, I agree. The way I see it, it would:
- have a mask
- support both IPv4 and IPv6
- maybe have HTML5 validation on it (regex)
- still need PHP validation (we would instruct developers in the documentation to not forget it)

Considering it's not a must-have feature, I'll close the issue. Anyone who needs this and builds a solution, please submit a PR and I'll merge it, so that we can all use it. It would be nice :-)

Cheers!

PS. I'll leave this thread unlocked in case anybody wants to add to the conversation.
