### ISSUE TITLE
Move initButtons() call to CrudPanel constructor

### ISSUE THREAD

**Issue by victorlap** [Laravel-Backpack/CRUD#627]
The current line is not working for me:

```$this->crud->removeAllButtons();```

The buttons `preview`, `update`, `revisions` and `delete` are still being loaded.

**Comment by victorlap** [comment]
I know why its not working. I have a BaseCrudController of which the individual controllers are extending. When I call setRoute() the buttons are reinitialized. Maybe the initButtons() call can be moved to the constructor? As there is no dependency whatsoever on the route.

**Comment by tabacitu** [comment]
Hi @victorlap ,

Thanks for the report. Just moved it in the constructor on the ```dev``` branch and everything seems to be working fine. I just can't remember why it was there instead of the constructor - makes no sense to me. Anyway, thanks for the fix, it will be available to everyone in the next point update (later this week).

Cheers!
