### ISSUE TITLE
Attribute Casting causes error

### ISSUE THREAD

**Issue by dmrc1143** [Laravel-Backpack/CRUD#66]
Hi, I use eloquent attribute casting and I have
`    protected $casts = [
        'mentions' => 'array',
    ];`

in my model. It causes 

> ErrorException in 90d0d21803ea756d9c9e49ba82191f0eef2d2e2d.php line 97: strip_tags() expects parameter 1 to be string, array given (View: ...\...\vendor\backpack\crud\src\resources\views\list.blade.php)

error when I hit the admin/somecrudpage .If I remove $casts, there is no problem. So, I think Backpack/Crud needs to support eloquent attribute casting.
I will be happy if you help me to makeshift for this issue because I have a project to done. Or I prefer if you commit for solving this problem :)

**Comment by tabacitu** [comment]
Hi @dmrc1143 ,

You're right, Backpack _should_ support attribute casting. And I _think_ the change is as easy as replacing ```$entry->{$column['name']}``` with ```$entry->getOriginal({$column['name']})```.

The change isn't very difficult, but needs to be done in a lot of blade files (all field types, all column types, all button types). 

I'm on it, but it will take a few days to do it all and properly test it. If you're in a rush, you can do it yourself for the few field types you need, until I get to change them all.

Cheers!

**Comment by dmrc1143** [comment]
Thank you for your interest,
I'm goingt to try fix with `$entry->{$column['name']} with $entry->getOriginal({$column['name']})` for blade files that I need and after your fix, I will update project when you have fixed completly. I will be happy if you inform me.

**Comment by tabacitu** [comment]
Great. Will do!

**Comment by tabacitu** [comment]
Hi @dmrc1143 ,

It's done in ```3.0.1.```. The fix was easier than anticipated:
- I created a new column type that I think is perfect for your use case (it's called ```array```, see [the docs](https://laravel-backpack.readme.io/v3.0/docs/crud-columns-types#array));
- I edited the ```date``` and ```datetime``` field types to also support attribute casting;

As far as I can figure it out, we've now covered most attribute castings:
- integer - works;
- real - works;
- float - works;
- double - works;
- string - works;
- boolean - works;
- object - DOES NOT WORK;
- array - works;
- collection - DOES NOT WORK;
- date - works;
- datetime - works;

But I don't think we should support casting to objects or collections - they can be so different that it's difficult create fields or columns for them... I think for those, the developers should build their own column or field types.

**Comment by dmrc1143** [comment]
Thank you for fixing,
i will update it :+1:

**Comment by NenadZivanovic** [comment]
Hi,
I have the same problem but I'm not sure if my settings are correct. I have
one field in migration declared as **text** for article images. I used upload_multiple
input for images.  I inserted this in my model 

`protected $casts = [
      'images' => 'array'
 ];`

Everything works fine, just one part. When I insert new article with images, but when I want
to access that article in table veiw, system is generate error. When I comment $casts part, I can
see table records. Problem is that my database field is text, which table type I must use?

**Comment by tabacitu** [comment]
Hi @NenadZivanovic

If you error only shows up on the table view, it means the problem is with the column type you're using to display that array. What column type are you? If you use a "text" column, naturally it will throw an error, because you're trying to display an array as text. You should use the [array column type](https://laravel-backpack.readme.io/docs/crud-columns-types) or write your own if none fit your needs.

Cheers!

**Comment by NenadZivanovic** [comment]
Hi @tabacitu,

Thank you for fast response. I am using 

`$this->crud->addField([  // Select2
            'label' => "Category",
            'type' => 'select2',
            'name' => 'category_id', // the db column for the foreign key
            'entity' => 'article_category', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Article_category" // foreign key model
         ]);`
in my controller,  and how I can add array column type? In migration or model?

**Comment by tabacitu** [comment]
If you were editing Cars, for example, you'd have a CarCrudController. Right? Well, in your CarCrudController, in the ```__construct()``` or ```setup()``` method you're defining how the CRUD looks and works. Part of that is defining what fields you have and what columns you have.

So that's where you need to poke around - CarCrudController. You can find the link to the array column type in my previous comment. Take a look at [all available functions](https://laravel-backpack.readme.io/docs/crud-full-api) to understand what you can do inside __construct or setup().

Cheers!

**Comment by NenadZivanovic** [comment]
Sorry, in last post I added wrong code. In my controller I have this code in constructor
`$this->crud->addField([   // Upload
            'name' => 'images',
            'label' => 'Photos',
            'type' => 'upload_multiple',
            'upload' => true,
            'disk' => 'uploads' 
        ]);`
and my column type in migration is **text**. How I can add array column type, when I used addField method for that field?

**Comment by NenadZivanovic** [comment]
I founded solution, I realized that i addField addColumn are different methods. Thank you very much!

**Comment by sayankanatov** [comment]
Hello! I have one problem with multiple uploadings, error say strip_tags() expects parameter 1 to be string, array given (View: C:\xampp\htdocs\vendor\backpack\crud\src\resources\views\columns\text.blade.php) Pliz help me< thank u
