### ISSUE TITLE
Using SweetAlert2 instead of system alert/confirm/prompt

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/CRUD#665]
Currently eg. confirmation of deleting an Item via delete button in the table opens the system confirm popup which is not very beautiful and not customisable to your CI.

By replacing all alert, confirm and prompt calls with [SweetAlert2](https://limonte.github.io/sweetalert2/) one can easily style the alerts via css.

Is there anything to consider why this should or can not be done?

If not I would create a pull request.

**Comment by AbbyJanke** [comment]
Mentioning #668 pull request for posterity sakes.

I do think this is a neat idea but I feel like it would cause too many breaks for people currently. What if we found a way to toss in a config option so users can choose between the two and include it in the base? Since most of the alert stuff is located in `base/views/inc/alerts` we could easily use the same file add an if statement of what config is set?

thoughts?

**Comment by OliverZiegler** [comment]
As mentioned in #668 I'm not aware of any breaks. 
@AbbyJanke Could you post an example for a break?

In the PR the alert stuff currently managed with PNotify is not touched at all.
I just replaced the default API javascript popups as I don't like them.

**Comment by tabacitu** [comment]
Hi @OliverZiegler ,

I think what @AbbyJanke is referring to as "breaking change" is that the default Backpack\Base installation procedure so far has been to publish all blade files. That will soon change - you only _really_ need to publish ```sidebar.blade.php``` and ```menu.blade.php``` - that's the only thing most people change anyway. 

But A LOT of them also change ```layout.blade.php```, which would suffer changes when including sweetalerts. And we consider that a breaking change - when we push an update, but the people can't get it without republishing the assets, which would effectively overwrite any changes they've done to their blade files. It's a little bit trickier than it looks to make a smooth transition...

**Comment by bloggervista** [comment]
@tabacitu Will it be merged for future release?

**Comment by tabacitu** [comment]
@bloggervista I wouldn't count on it. 

This is pretty much a matter of opinion, so I think the best way to go forward would be to make it easier to customize (uniform API for alerts) rather than adopting this library. Ideally, whoever wants a different system would just need to replace a JS/blade file, and they'd be using a different one. This is a breaking change, though, so we need to time it right - we only release breaking changes a few days/weeks after Laravel does, so I'd say in about a month.

**Comment by tabacitu** [comment]
That being said, this is definitely not high-prio :-) We use the [Moscow prioritisation technique](https://en.wikipedia.org/wiki/MoSCoW_method), and I'd say this is a "could have", so quite a few things to do before this.

**Comment by tabacitu** [comment]
Hi guys. I've given this a lot of thought and it doesn't seem like a good idea to merge this right now. 

The priority right now is to get Backpack to a STABLE and TESTABLE state, where very very few issues show up any more. It's been hell battling with all issues and PRs, and this is definitely not sustainable. SweetAlert is a nice feature, but I'm afraid it will just bring more problems, it's not a priority right now and it's easily implemented by pasting a few files, so whoever wants it can install it.

I'm sorry about this, I hope you understand. This will help us all move faster, add features faster and use Backpack more happily. Let's leave the PR open, though, would gladly merge it after we get to the stable state.

Cheers!
