### ISSUE TITLE
LaravelCollective/html

### ISSUE THREAD

**Issue by MDEvo** [Laravel-Backpack/CRUD#691]
Can you update the LaravelCollective/html to 5.4 branch since 5.0 was close. 

This update related to getToken() deprecated in laravel 5.4. 

Thank you.

**Comment by victorlap** [comment]
Maybe we can remove the `laravelcollective/html` package altogether, because it looks like it is used only for a few simple `Form::open` and `Form::close` tags in the package? 

See:
https://github.com/Laravel-Backpack/CRUD/blob/b5e8f929310d86d831b43310ca68eea2e1d254d0/src/resources/views/create.blade.php#L26
https://github.com/Laravel-Backpack/CRUD/blob/b5e8f929310d86d831b43310ca68eea2e1d254d0/src/resources/views/edit.blade.php#L26
https://github.com/Laravel-Backpack/CRUD/blob/b5e8f929310d86d831b43310ca68eea2e1d254d0/src/resources/views/inc/revision_timeline.blade.php#L29

**Comment by tabacitu** [comment]
Totally agree - if that's the only place we use it, let's replace those calls and drop it.

![giphy](https://user-images.githubusercontent.com/1032474/28325566-d0eeb5ae-6be6-11e7-9d94-71767b13f8a0.gif)

**Comment by tabacitu** [comment]
Updated the package, still open to removing it entirely, but since there's a separate issue for that (https://github.com/Laravel-Backpack/CRUD/issues/910), let's close this one.

Cheers!
