### ISSUE TITLE
UX: Persistent "let me add another item"

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#73]
In the create form, when a user chooses to "let me add another item" at the end of the form, don't only redirect him to the create form, also make sure this time the "let me add another item" radio is checked, because most of the time that's what he'll want.

This can be done in two ways:
1) a cookie (which would also affect other create forms);
2) a GET parameter;

I tend to think option no 2 is better.

This enhancement, combined with #72 and #71  will greatly improve the create form usability.

**Comment by OwenMelbz** [comment]
Have added a WIP version of this.

Im using the session rather than a query string for the time being, as I couldnt think of a scenario where sharing the data across forms would realistically happen unless they were to perfectly submit both forms perfectly.

What issues can you see with using the session?

https://github.com/Laravel-Backpack/CRUD/pull/145

**Comment by tabacitu** [comment]
Yeah, you're right. Session might be better. No issues.

Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu just going to close this as the discussion has furthered https://github.com/Laravel-Backpack/CRUD/pull/145 we can always reopen if you want :)
