### ISSUE TITLE
elFinder Themes

### ISSUE THREAD

**Issue by AndresOchoaS** [Laravel-Backpack/CRUD#732]
Hello everyone

I would like to suggest a feature:

Could you add some friendlier theme to elFinder? The current is not pleasing to the eye.

I suggest Moono Theme: https://github.com/lokothodida/elfinder-theme-moono

![image](https://user-images.githubusercontent.com/18619074/26857658-b9d1a6e4-4af1-11e7-9591-b9c84a59223b.png)

**Comment by tabacitu** [comment]
Hi @AndresOchoaS ,

Sure, we'll consider this. I believe the current theme was chosen at the time because moono, though simpler, has an inconsistency between the standard view, right-click menu and popups. Don't know if that's still the case.

I'll leave the issue open and let anyone +1 or express comments here, to show support for switching the default theme.

Until then, you can definitely change the theme used in your projects, as instructed in the link you posted.

Cheers!

**Comment by tabacitu** [comment]
Let's close this issue, as it's not a priority and not a lot of people have expressed the need. Cheers!
