### ISSUE TITLE
Elfinder + Crud

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/CRUD#733]
@tabacitu 

Is there any reason why the `elfinder` package happens to live in `laravel-Backpack/CRUD` vs `laravel-Backpack/elfinder` or something similar? 

One commenter has noticed the theme is a little not to their liking (see https://github.com/Laravel-Backpack/CRUD/issues/732). Although I tend to take a POV that theme changes are aesthetic, I know that theme changes in production systems - even simply providing a different colour scheme - can be jarring and/or unexpected.

I wonder if we should shunt `elfinder` out of CRUD or if there's a reason for it being part of it?

**Comment by tabacitu** [comment]
@lloy0076 ,

As far as I remember, elFinder is used only by the ```browse``` field type, but it was included in the main CRUD package because:
- its installation involves quite a few steps, and I wanted to bundle those steps along with the steps necessary for CRUD;
- we need to overwrite the views the standard laravel-elfinder package comes with (you'll notice that in the CRUD installation process we do 
``` 
php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="elfinder" #publish custom elFinder views
```

I hope this is what you asked for? Not sure, sorry.

**Comment by lloy0076** [comment]
Ok :)
