### ISSUE TITLE
Blocked mixed content in video field type

### ISSUE THREAD

**Issue by ablunier** [Laravel-Backpack/CRUD#735]
In a website with HTTPS if you insert a vimeo video in a video type field it fails because the Ajax request is getting a Blocked Mixed Content error. This happens because the request to vimeo's API is done via HTTP instead of HTTPS.

**Comment by ablunier** [comment]
By the way, I will send a PR with the solution when I get a break to do it.

**Comment by tabacitu** [comment]
Hi @ablunier ,

Just merged your PR onto ```dev```, thanks for it. It will be available on the stable branch later this week, after more people test it out. 

If you want to be one of the guys using the ```dev``` branch too, just make sure your composer.json uses ```dev-dev``` for Backpack\CRUD, instead of the specific version, then run ```composer install```. Having more people using the dev branch during development helps us build a better product and catch bugs before we launch them on the master branch. All the cool kids are doing it :-)

Cheers!
