### ISSUE TITLE
orderFields not working

### ISSUE THREAD

**Issue by cerelli** [Laravel-Backpack/CRUD#798]
I want to order the fileds in form, but orderFields not work.

`        // ------ CRUD FIELDS
        $this->crud->orderFields(['name', 'parent_id', 'lft'], 'update/create/both');`

In the form parent_id remaining the first field.
Why?

**Comment by lloy0076** [comment]
What do you mean by "it doesn't work"?

**Comment by cerelli** [comment]
if i use:
$this->crud->orderFields(['name', 'parent_id', 'lft'], 'update/create/both');
in form i have this order:
parent_id
lft
name.

**Comment by tabacitu** [comment]
@cerelli thanks for reporting this. Unit tests (currently being developed) should confirm this. @tumf87  have you stumbled upon this so far?

**Comment by tumf87** [comment]
Hi @tabacitu, yes. Sort makes use of those ambiguous methods from the CrudPanel that need a bit of refactoring.

**Comment by tumf87** [comment]
Hi,
I've made a PR for this but I just now realized that in the initial comment, @cerelli calls the method like this:

`$this->crud->orderFields(['name', 'parent_id', 'lft'], 'update/create/both');`

While this works, because the method will automatically order fields on both the create and update form in case the second parameter is neither 'create' or 'update', the correct call should have been:

`$this->crud->orderFields(['name', 'parent_id', 'lft'], 'both');`

or even simpler:

`$this->crud->orderFields(['name', 'parent_id', 'lft']);`

I think the phpDoc should be specify this more clearly.

**Comment by tabacitu** [comment]
Yeah... the way this has worked so far is that if you specify anything other than ```create``` or ```update``` it will actually be ```both```. And I bet a lot of people have just left ```update/create/both``` in their code (programmer lazyiness FTW!). So IMO ```update/create/both``` should get interpreted into ```both```.

Does your PR do this @tumf87 ?

**Comment by tumf87** [comment]
It does, , although [I argue](https://github.com/Laravel-Backpack/CRUD/issues/985) that it shouldn't. I did not change that part for backwards compatibility.
