### ISSUE TITLE
Keep filter label dynamic

### ISSUE THREAD

**Issue by inquisitive-stha** [Laravel-Backpack/CRUD#846]
Is there any way, to display name of different hospitals, instead of static label Hospital as in the following figure.
I want to display the name of selected hospital in the filter instead of filter name Hospital.
Or, is there any way to display the name of selected filter in next place close to title or anywhere.
![temp_hh](https://user-images.githubusercontent.com/16288854/29249425-3f18fd6a-804f-11e7-92b4-5124ee10154f.png)

**Comment by lloy0076** [comment]
I haven't seen such an option from within backpack - it might be possible if one checks data tables itself.

**Comment by tabacitu** [comment]
Hi @inquisitive-stha , there's no way right now, unless you modify the filter yourself (it's just a blade file so it's just like creating a new field). This can't be implemented in the core, however, because people might have a bunch of filters, like a an entire screen's worth. If then the user chooses 5 entries and they all show up, it might look very bad, span on two rows... bleah.

Anyway. Hope it helps. Cheers!
