### ISSUE TITLE
Reorder Feature Issue

### ISSUE THREAD

**Issue by BinaryBlock** [Laravel-Backpack/CRUD#85]
Hey... so I was pleasantly surprised that you implemented a reorder feature. I would suggest adding it to the documentation somewhere and really **spell it out** for newbies. I looked at the `/MenuCRUD` package to see how I turn it on and an example: https://github.com/Laravel-Backpack/MenuCRUD/blob/master/src/app/Http/Controllers/Admin/MenuItemCrudController.php#L22 *and* I found your note in `/CRUD` about the MUST HAVE columns to make it work: https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php#L181

In any case, THANK YOU!
I did hit one snag. Everything flowed well, but the fact that I have a different `id` for my Model. Example: `Challenge.challenge_id` is my primary key. So... when I turned everything on... it only listed 1 item. I changed the following line of code and **everything** appeared for me:
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/reorder.blade.php#L76
```PHP
$all_entries = collect($entries->all())->sortBy('lft')->keyBy('id');
```
**to**
```PHP
$all_entries = collect($entries->all())->sortBy('lft')->keyBy($crud->getModel()->getKeyName());
```

I think this might be a good code solution. **What do you think?**

**Comment by tabacitu** [comment]
Yup, you're right, thank you. Must have missed that during the ```->primaryKey()``` refactoring. Fixed in 3.0.12.

Yes, the reorder functionality is pretty hidden. I consider this to be the next priority - overhauling the documentation. But it's more difficult than I expected to have all features explained in a short, clear way, which is easy to understand for new users and easy to find for existing ones. And on top of that, stick to the limitations readme.io imposes, because switching providers wouldn't make sense at this point. It's... a challenge :-) But I'll find a way, I'm sure :-)

Thanks, cheers!
