### ISSUE TITLE
Create multiple entries with one "save_and_*"

### ISSUE THREAD

**Issue by marleybobby** [Laravel-Backpack/CRUD#867]
I have a model `Tag`. So I added all parts with CRUD to create and edit an single item. Now I want to be able to create multiple tags at once. Is this possible? If not why not? 
I would have to create my own controller in this case?
I thought about sth. like an button which adds the fields via Javascript. How would you handle the serverside part in this case? Am I right that you have to check in `storeCrud` method if its an array or not?

I know I could set the button to `save_and_new` but you would have to click save after each element. With a huge amount of tags that wouldn't be nice.

**Comment by lloy0076** [comment]
@marleybobby - it's not implemented because there's only so much the small number can do.

Your suggestion regarding JavaScript is a good suggestion and one could, I should suppose, iterate over a set of input values, creating entries so long as the entries passed validtion.

I'd be happy to help if you wanted to put up a `gist` or even a PR (but a generic PR might be a lot of work).

**Comment by tabacitu** [comment]
Hi guys. Yes, bulk adding is not supported right now. However you should be able to quickly add tags by clicking the "save and new" button once, then using the keyboard only. Also note pressing Ctrl+S (Cmd+S on a mac) submits the current form:

https://cl.ly/383V2g2o1k2G

Hope it helps.

Cheers!
