### ISSUE TITLE
CRUD Fields with tab on CREATE not on UPDATE

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#870]
Hey,

Weird issue here I think.

When addField with parameters 'tab' => 'My Tab' AND with view only 'create'
![2017-08-18 001967](https://user-images.githubusercontent.com/26375917/29445360-7edd54fe-8410-11e7-93a8-7bd9e7daef78.png)
If you try to addField without parameters 'tab' for view UPDATE, then Backpack CRUD is not showing is as it seems it assumes it should be in a tab:
![2017-08-18 001968](https://user-images.githubusercontent.com/26375917/29445396-bbdd4936-8410-11e7-83f4-2ac76221e3b8.png)
Result: nothing
![2017-08-18 001966](https://user-images.githubusercontent.com/26375917/29445399-c0691994-8410-11e7-9936-7e732dd10b86.png)
HTML code added tab for reason I ignore:
![2017-08-18 001965](https://user-images.githubusercontent.com/26375917/29445400-c3042086-8410-11e7-918a-1444e7b2666a.png)

**Comment by lloy0076** [comment]
That's odd but it seems that once one has a mention of *any* tabs, then everything needs a `tab` parameter/key.

Would you consider this a:

* bug?
* gotcha?
* something else?

I think it's more of a _gotcha_ myself.

**Comment by MickaelTH** [comment]
@lloy0076 Well yes if one has 'tab' then all should have too, if not they will be added in the last TAB. Which also create another weird behavior that you currently cannot mix TAB with other type. (Ex have an input for title at the top of the page and below few tabs).

I think this is a bug because CREATE and UPDATE fields can be set/ should be set separately. Or now if I have TABS in CREATE then it forces me to use TABS in UPDATE.

**Comment by lloy0076** [comment]
@tabacitu - what do you think? It's somewhat broken - and I agree with @MickaelTH - but I think:

1. In the meantime we might look at the documentation and at least make it obvious that if you have tabs then EVERYTHING needs a tab; and
2. Fix as suggested so that the vraious fields can (or should) be able to be set separtely.

**Comment by tumf87** [comment]
Hi,

I agree as well that a user should be able to set-up tabs differently on create and update.

What I'm not feeling so confident about is having tabs **plus** fields outside of the tabs. That just seems a little bit too much and for cases like the example above with an input for a title at the top of the page, I would usually just go with a 'General' tab or equivalent.

I am not familiar with all the use cases though, so I would really appreciate more input on this.

@tabacitu, any views on this?

**Comment by tumf87** [comment]
If we decide to go with tabs only, a form can then either have tabs or not, like the current behavior. This should then become a crud panel configuration. 

I see the crud panel API like this:

`setFieldTabs(array $tabNames, $form = 'both')`

`getFieldTabs($form)` // either 'create' or 'update'

`clearFieldTabs($form = 'both')`

All fields from a certain form that contain a valid tab name go in the specific tab, otherwise go in a generic tab at the end.
If the crud panel field tabs array is empty, there should be no tabs regardless of fields having the 'tab' property.

**Comment by tabacitu** [comment]
Hi guys,

I wish I saw this sooner. I merged a PR on the ```upgrade``` branch this week which introduced a feature - **not specifying a tab will now place that field _before_ the tabs**:
<img width="1440" alt="screen shot 2017-09-30 at 11 13 08" src="https://user-images.githubusercontent.com/1032474/31044059-64081d9e-a5d0-11e7-910a-09aa9bf3bfd3.png">

I now think this is a more intuitive behaviour. When you don't specify a tab, you'd expect it not to be in a tab... Wouldn't you agree?

--

About adding fields in a certain tab on only create or only update, I think @MickaelTH 's syntax is spot-on. I would have expected that to work, so I'd say this is a bug.

@tumf87 I think adding public ```setFieldTabs()```, ```getFieldTabs()```, ```clearFieldTabs()``` would just make it more difficult to understand how to use tabs. I'm ok with them as private, if we need them to make it work, but not public methods, since I don't believe they're actually needed. I think @MickaelTH 's syntax is pretty darn intuitive - if you'd like separate fields on separate tabs, just add them twice, specifying a different tab each time.
![29445396-bbdd4936-8410-11e7-83f4-2ac76221e3b8](https://user-images.githubusercontent.com/1032474/31044104-6e7d520c-a5d1-11e7-8c65-d202d7ddaf82.png)

My opinion on this:
- we keep the option to have fields above the tabs, which is already merged in ```upgrade```
- we "make it work" with @MickaelTH 's syntax

Do you guys agree/disagree?

**Comment by tumf87** [comment]
@tabacitu, agreed. Like I said, those methods would have only worked in case we decided to go with tabs only, not fields + tabs.

**Comment by lloy0076** [comment]
Please re-open if more discussion is needed.

**Comment by tswonke** [comment]
This seems to be broken...?
In a project I defined tabs for `update`, but don't want them in `create`. I get this error then:

![bildschirmfoto 2018-11-19 um 00 13 29](https://user-images.githubusercontent.com/6401044/48679407-20a06280-eb90-11e8-8e59-2c4e0688e198.png)

**Comment by tabacitu** [comment]
Thank you @tswonke - you’re right, there was a bug when the tabs were only defined for update, or create. Fixed in 
https://github.com/Laravel-Backpack/CRUD/commit/6de4545dc44d8f7afa852678dcf89db24d2d3e98 and tagged. A ```composer update``` should fix it for you.

Cheers!
