### ISSUE TITLE
Request to change name of a file to avoid file ban

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#875]
Hey,

Users may have filter to blacklist files with bad name. I found that this one here may be a huge problem:

![2017-08-21 001975](https://user-images.githubusercontent.com/26375917/29505186-dedee178-866e-11e7-88cb-f7554eed2bb0.png)

**Comment by DelightedD0D** [comment]
"Users may have filter to blacklist files with bad name". Can you give us some more context here? 
What users? Your end users, your developers? How does that blacklist work exactly? 

Honestly, such a "blacklist" mechanism seems like it would be awfully problematic. It wouldn't be unreasonable to have a file like `dt-ass.min.css`  ("down time assessment") or similar. I'm skeptical that something that attempts to block such files would be very workable. Please elaborate.

**Comment by lloy0076** [comment]
It's a legitimate word:

- http://www.todayifoundout.com/index.php/2012/04/how-dick-came-to-be-short-for-richard/
- https://www.merriam-webster.com/dictionary/dick

Please reopen this with a PR changing any file names that might cause offence.

**Comment by MickaelTH** [comment]
Yes legitimate word but it was blocked by Content Advisor in IE.

**Comment by niladam** [comment]
@MickaelTH who in the world uses IE anymore in 2017 ?:) -- sorry, i'm just a jackass -- but i had to ask this..

**Comment by tabacitu** [comment]
Haha. Sorry, @MickaelTH, I'm sure the guys were just messing around. Yup, I know the D. It's actually because Backpack's father was called Dick. Now that I recall, that was pretty fun, we used to have this kind of discussions all day :-) [```git pull dick```, ```git push dick```, ```Dude shut up learn how to use Dick```]. But yes, I changed the name because it was NSFW.

I'm wondering if we're actually using that stylesheet anymore. It's probably just to apply the AdminLTE style to the select2 and if so, I'm totally onboard with renaming this to something more appropriate. The only uncomfortable thing is that it would be a breaking change... people need to republish their assets for it to work...
