### ISSUE TITLE
Included pnotify version is really old

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/CRUD#885]
It looks like this is related to #884  and could be sorted pretty easily, but again -- i wonder if there's any reason why the included versions are so old.

The included version of `pnofity` (again, as per `public/vendor/backpack/pnotify` is **3.0.0** (released on 21st December 2015) while the latest version is **3.2.1** released 1st of August 2017. The previous version (3.2.1, stable) was released on 24th of April 2017.

**Comment by lloy0076** [comment]
Simply because they still work and AFAICT there's no known bugs in the older version.

As in the other one, feel free to update and see what happens (if anything).

**Comment by tabacitu** [comment]
Hi @niladam ,

As @lloy0076 said - no reason, really. Just difficult to always be up-to-date with JS dependencies, since we don't use a dependency manager for JS right now.

I see you already have a good history of contributing to open-source projects. **Would you like to create a PR to fix this?**

---

PS. Haha @lloy0076 - I see you almost snapped there :-)) I totally understand - maintaining OSS is definitely more difficult than I expected, too. I sometimes read a issue, get frustrated, and just don't reply. But we'll learn to do this better in time, I guess. 

It sometimes helps to remind yourself that _**we all want the same thing - making this software we use better**_. Sure, for me and you this might seem like a minor issue compared to what we know is urgent/important. It's already working and little benefit will come from upgrading. But **if it's a pain point for him, it means we should probably take it into consideration**. Especially so if he's willing to fix it. I say let's encourage people to pitch in for small issues like this:
- we're definitely past the point where we can handle everything with a small team, so we _need_ the help;
- a lot of people are happy to contribute with small PRs, since they get a bump in their github stats, they're listed as a contributor and they get to interact with a community of like-minded people; 

So it's win-win. Just my 2 cents.

**Comment by niladam** [comment]
@tabacitu alright -- i'll attempt to have a look at it. Sadly, i'm in the middle of a pretty big project that's gotten me burned-out. But i will look into this too probably sometimes next week :)

**Comment by lloy0076** [comment]
@tabacitu - no I hadn't snapped, that was simply a poorly chosen set of words.

What I meant was more like "feel free to update the version of the dependency to a higher level and see if something breaks" _not_ make a PR and see if anything happens with the PR!

**Comment by lloy0076** [comment]
AFAICT nothing is actually broken with the notifications :)

Feel free to reopen if there is.
