### ISSUE TITLE
Problems with many-to-many relation fields.

### ISSUE THREAD

**Issue by Ole-Gi** [Laravel-Backpack/CRUD#90]
Hi folks, I have encountered problem while creating/updating entity with many-to-many relation.
I have a field configured like this:

```
$this->crud->addField([
            'label' => trans('backend/crud_entities.users.field_labels.albums'),
            'type' => 'select2_multiple',
            'name' => 'genres',
            'entity' => 'genres',
            'attribute' => 'name',
            'model' => Genre::class,
            'pivot' => true
        ]);
```
Class has relation:
```
public function genres()
    {
        return $this->belongsToMany(Genre::class, 'albums')->withTimestamps();
    }
```
But when I'm trying to create/update User entity I get the error 

> ErrorException in helpers.php line 747:
> preg_replace(): Parameter mismatch, pattern is a string while replacement is an array
> in helpers.php line 747
> at HandleExceptions->handleError('2', 'preg_replace(): Parameter mismatch, pattern is a string while replacement is an array', '/home/vagrant/projects/shootster/environment/vendor/laravel/framework/src/Illuminate/Support/helpers.php', '747', array('search' => '\?', 'replace' => array('$2y$10$xMtJxgDEjkraJ9bbND5HUucibU0SgDqUsYv8tIuAEm/GrpPnmXotC', '2016-08-22 11:56:18', array('1', '3'), '2'), 'subject' => 'update `users` set `password` = y$xMtJxgDEjkraJ9bbND5HUucibU0SgDqUsYv8tIuAEm/GrpPnmXotC, `updated_at` = 2016-08-22 11:56:18, `genres` = ? where `id` = ?', 'value' => array('1', '3')))
> at preg_replace('/\?/', array('1', '3'), 'update `users` set `password` = y$xMtJxgDEjkraJ9bbND5HUucibU0SgDqUsYv8tIuAEm/GrpPnmXotC, `updated_at` = 2016-08-22 11:56:18, `genres` = ? where `id` = ?', '1') in helpers.php line 747

I think a problem is because it tries to save fields for many-to-many relation and falls on the array.
I found solution: to add filtration in trait Create - to unset all relational fields before 
```
public function create($data)
    {
        $values_to_store = $this->compactFakeFields($data, 'create');
        $item = $this->model->create(someFilterFunctionHereToUnsetRelationFileds($values_to_store));

        // if there are any relationships available, also sync those
        $this->syncPivot($item, $data);

        return $item;
    }
```

Maybe I'm doing something wrong and there is an error in field configuration.
Please help.

Regards, Oleh.

**Comment by tabacitu** [comment]
Hi Oleh,

Can you also try declaring the field with:
```php
            'model' => 'App\Models\Genre',
```
instead of
```php
            'model' => Genre::class,
```
and tell me if it fixes your issue? 

(assuming your Genre model is in a Models folder, otherwise just ```App\Genre```)

Cheers!

**Comment by Ole-Gi** [comment]
Thanks for so fast reaction!
But this fix doesn't help.

**Comment by tabacitu** [comment]
Hmm... I just tried it on fresh installation and it works for me, throws no errors. So it's most likely an implementation problem or a very very niche issue.

From the error you gave me it seems like the relationship might not be properly defined. Eloquent tries to save the multiple genre ids in the albums table, which I bet is wrong.

1) Are you sure your connection table isn't something like ```album_genre``` rather than just ```albums```?

2) How about if you use the [default Laravel syntax](https://laravel.com/docs/5.2/eloquent-relationships#many-to-many) for the relationship?
```php
public function genres()
    {
        return $this->belongsToMany('App\Models\Genres', 'albums')->withTimestamps();
    }
```
(most likely not the issue, but worth the shot)

3) Can you [create an album manually](https://laravel.com/docs/5.2/eloquent#inserting-and-updating-models), in a different controller (including attaching genres)? Because if that doesn't work, it's definitely the way the relationship has been defined, and not Backpack.

Cheers!

**Comment by tabacitu** [comment]
Hi @Ole-Gi ,

Are you still having this issue or have you abandoned?

Thanks, cheers!

**Comment by tabacitu** [comment]
P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
