### ISSUE TITLE
Unable to add new record in crud create page not found Error 404

### ISSUE THREAD

**Issue by Hemantkumawat** [Laravel-Backpack/CRUD#920]
I have created custom crud view of records is properly working but when I want to add new records Getting error page not found error 404 please help me for this issue.

**Comment by Hemantkumawat** [comment]
only view page is working and create, delete, update is not working getting the page not found the error.

**Comment by lloy0076** [comment]
This is hard to diagnose without more information (such as example[s] of what you've tried / are doing) or even just a link to which documentation (if any) you are following.

I'd also recommen asking on https://stackoverflow.com/search?q=laravel+backpack as well.

**Comment by tabacitu** [comment]
Hi @Hemantkumawat ,

As @lloy0076 says, pretty difficult to diagnose without more information. Please include your Crud controller, model and route if your think this is a bug in the software. But since I've just tested it and it works, it seems like it's misconfiguration, so I'll close the issue - [a better place to ask for support is stackoverflow](http://stackoverflow.com/questions/tagged/backpack-for-laravel).

I'll take a stab at it, however :-) I bet your route isn't set correctly in your CrudController (it doesn't match the route you setup in your routes file). Was I right? :-)
```
        $this->crud->setRoute('admin/your-entity');
```
This can sometimes happen with crud panels you generate, when the entity name has spaces and such.

Cheers!

**Comment by Hemantkumawat** [comment]
Thank you, sir, something was missing in the controller so  I  solve this issue.
