### ISSUE TITLE
can't add button

### ISSUE THREAD

**Issue by seedgabo** [Laravel-Backpack/CRUD#93]
View [viewname] not found when trying to list the table

**Comment by tabacitu** [comment]
Hi @seedgabo ,

What button are you trying to add? Can you please paste the code you're using?

Cheers!

**Comment by tabacitu** [comment]
Sorry, you're totally right. It didn't work - the views were not prefixed by the path specified in the documentation.

Now they are, it's fixed in 3.0.17. A ```composer update``` should fix it for you. Thanks an cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by seedgabo** [comment]
This is perfect. Now it's working again, thanks
