### ISSUE TITLE
Field type 'image' uses url() to assemble src

### ISSUE THREAD

**Issue by gta4kv** [Laravel-Backpack/CRUD#937]
Hi,

I've been exploring why my validation rule 'required' does not work for image, and in image.blade.php found this line:

```php
<img id="mainImage" src="{{ url(isset($field['prefix']) ? $field['prefix'] : '') . (old($field['name']) ? old($field['name']) : (isset($field['value']) ? $field['value'] : (isset($field['default']) ? $field['default'] : '') ))) }}">
```

I believe url function is redundant here and url should be assembled somewhere in mutator.

Using `url()` here causes `src` by default to have APP_URL, which leads us to situation when field is never empty.

**Comment by lloy0076** [comment]
Wouldn't that have to be a URL of some sort for `src` to work properly though?

**Comment by gta4kv** [comment]
@lloy0076 
Hey, as I suggested it is possible to assemble url in mutator.

By default src just has APP_URL value. It is incorrect, because if you submit form without image, it'd consider as non-empty and will try process the image, but there is no image, just a text.
Also it uses base64, means there is never a URL.

**Comment by lloy0076** [comment]
So it's more of a bug but the fix might also require an update (or at least re-examination) of the docs?

**Comment by wtime** [comment]
About that I have reported an issue #868 with the image field.

**Comment by lloy0076** [comment]
#868 isn't related to this AFAICT.

Coming to think of this, this is more a breaking chanage and a feature request.

@gta4kv Does this still affect you?

**Comment by tabacitu** [comment]
@gta4kv the ```image``` field has suffered a lot of changes in the meantime. Added ```prefix``` and ```disk``` options, and a better handling of this situation. While it still uses ```url()``` to assemble the path, it should do so only if there's a value. Unfortunately we can't get rid of ```url()``` because it would break a lot of people's apps, who already use the field as-is and don't have a mutator to get the image.

Please let me know if you still have this problem after a ```composer update``` and we'll reopen the issue. Cheers!
