### ISSUE TITLE
Iconpicker update.

### ISSUE THREAD

**Issue by cerelli** [Laravel-Backpack/CRUD#961]
I do not find some icons.
How do I update my iconpicker?

**Comment by lloy0076** [comment]
This might best be asked on [Stack Overflow](https://stackoverflow.com/search?q=laravel+backpack) .

However I'm not even sure what you mean by "not find some icons" and/or what steps you've taken in order to have encountered the issue and if there are any logs/errors that you might share to be able to help.

Please feel free to provide the information here (but re-open the issue so we can see it), or on SO so that we can help out more.
